[[cards]]
kanji = '兄'
kana = 'あに'
english = "(one's own) older brother (kenjougo)"
level = 'n5'
tags = ['common', 'family', 'humble', 'kenjougo', 'people']
frequency_scores = { anime = 505, leeds = 3647, novels = 766, wikipedia = 1069 }

[[cards]]
kanji = '姉'
kana = 'あね'
english = "(one's own) older sister (kenjougo)"
level = 'n5'
tags = ['common', 'family', 'humble', 'kenjougo', 'people']
frequency_scores = { anime = 320, leeds = 3837, novels = 644, wikipedia = 2890 }

[[cards]]
kanji = '妹'
kana = 'いもうと'
english = "(one's own) younger sister (kenjougo)"
level = 'n5'
tags = ['common', 'family', 'humble', 'kenjougo', 'people']
frequency_scores = { anime = 493, leeds = 3065, novels = 775, wikipedia = 2289 }

[[cards]]
kanji = 'お母さん'
kana = 'おかあさん'
english = 'mother (sonkeigo)'
level = 'n5'
tags = ['common', 'family', 'honorific', 'respectful', 'sonkeigo']
frequency_scores = { anime = 347, leeds = 2549, novels = 2088 }

[[cards]]
kanji = '奥さん'
kana = 'おくさん'
english = 'wife (sonkeigo)'
level = 'n5'
tags = ['common', 'family', 'honorific', 'respectful', 'sonkeigo']
frequency_scores = { anime = 2135, leeds = 3555, novels = 2371 }

[[cards]]
kanji = '伯父'
kana = 'おじ'
english = 'uncle'
source = 'wiki-n5'
level = 'n5'
tags = ['common', 'family', 'noun', 'people']
frequency_scores = { anime = 8036, leeds = 13123, wikipedia = 3155 }

[[cards]]
kanji = 'お祖父さん'
kana = 'おじいさん'
english = 'grandfather; male senior citizen (sonkeigo)'
level = 'n5'
tags = ['common', 'family', 'honorific', 'respectful', 'sonkeigo']
frequency_scores = { anime = 6182, leeds = 9861 }

[[cards]]
kanji = '伯父さん'
kana = 'おじさん'
english = 'uncle; old man (sonkeigo)'
level = 'n5'
tags = ['common', 'family', 'honorific', 'respectful', 'sonkeigo']
frequency_scores = { anime = 1921, leeds = 3858 }

[[cards]]
kanji = '夫'
kana = 'おっと'
english = 'husband'
source = 'wiktionary'
level = 'n4'
tags = ['generated', 'tsv']
frequency_scores = { anime = 3816, leeds = 1321, novels = 1189, wikipedia = 893 }

[[cards]]
kanji = 'お父さん'
kana = 'おとうさん'
english = 'father (sonkeigo)'
level = 'n5'
tags = ['common', 'family', 'honorific', 'respectful', 'sonkeigo']
frequency_scores = { anime = 470, leeds = 3497, novels = 1938 }

[[cards]]
kanji = '弟'
kana = 'おとうと'
english = "(one's own) little brother (kenjougo)"
level = 'n5'
tags = ['common', 'family', 'humble', 'kenjougo', 'people']
frequency_scores = { anime = 1063, leeds = 3372, novels = 1378, wikipedia = 953 }

[[cards]]
kanji = 'お兄さん'
kana = 'おにいさん'
english = 'older brother (sonkeigo)'
level = 'n5'
tags = ['common', 'family', 'honorific', 'respectful', 'sonkeigo']

[[cards]]
kanji = 'お姉さん'
kana = 'おねえさん'
english = 'older sister (sonkeigo)'
level = 'n5'
tags = ['common', 'family', 'honorific', 'respectful', 'sonkeigo']

[[cards]]
kanji = 'お祖母さん'
kana = 'おばあさん'
english = 'grandmother (sonkeigo)'
level = 'n5'
tags = ['common', 'family', 'honorific', 'respectful', 'sonkeigo']
frequency_scores = { anime = 38578, leeds = 9363 }

[[cards]]
kanji = '伯母さん'
kana = 'おばさん'
english = 'aunt (sonkeigo)'
level = 'n5'
tags = ['common', 'family', 'honorific', 'respectful', 'sonkeigo']
frequency_scores = { anime = 3230, leeds = 5802 }

[[cards]]
kanji = '親'
kana = 'おや'
english = 'mother OR father (singular); parent'
source = 'wanikani; movies'
level = 'n4'
explain = 'https://hinative.com/ja/questions/1301745'
tags = ['common', 'family', 'noun', 'people']
frequency_scores = { anime = 952, leeds = 923, novels = 1264, wikipedia = 1018 }

[[cards]]
kanji = '家内'
kana = 'かない'
english = '(my) wife (polite humble)'
source = 'n4-wikipedia'
level = 'n4'
explain = 'https://japanese.stackexchange.com/a/14787'
tags = ['common', 'family', 'noun', 'people']
frequency_scores = { anime = 16157, leeds = 9088 }

[[cards]]
kanji = '兄弟'
kana = 'きょうだい'
english = 'siblings'
level = 'n5'
tags = []
frequency_scores = { anime = 1913, leeds = 3214, novels = 2991, wikipedia = 1150 }

[[cards]]
kanji = '主婦'
kana = 'しゅふ'
english = 'housewife'
source = 'try! n4'
level = 'n3'
tags = ['common', 'family', 'noun', 'people']
frequency_scores = { anime = 9304, leeds = 3550, wikipedia = 8909 }

[[cards]]
kanji = '祖父'
kana = 'そふ'
english = "(one's own) grandfather; old man"
level = 'n5'
tags = ['common', 'family', 'humble', 'kenjougo', 'people']
frequency_scores = { anime = 5178, leeds = 6964, wikipedia = 2943 }

[[cards]]
kanji = '祖母'
kana = 'そぼ'
english = "(one's own) grandmother"
level = 'n4'
tags = ['common', 'family', 'humble', 'kenjougo', 'people']
frequency_scores = { anime = 7708, leeds = 6476, wikipedia = 6842 }

[[cards]]
kanji = '父'
kana = 'ちち'
english = "(one's own) father (kenjougo)"
level = 'n5'
tags = ['common', 'family', 'humble', 'kenjougo', 'people']
frequency_scores = { anime = 843, leeds = 1370, novels = 453, wikipedia = 332 }

[[cards]]
kanji = '妻'
kana = 'つま'
english = "(one's own) wife"
source = 'jlptstudy'
level = 'n4'
tags = ['common', 'family', 'humble', 'kenjougo', 'people']
frequency_scores = { anime = 2245, leeds = 1353, novels = 1033, wikipedia = 684 }

[[cards]]
kanji = '母'
kana = 'はは'
english = "(one's own) mother (kenjougo)"
level = 'n5'
tags = ['common', 'family', 'humble', 'kenjougo', 'people']
frequency_scores = { anime = 818, leeds = 1104, novels = 501, wikipedia = 639 }

[[cards]]
kanji = '息子'
kana = 'むすこ'
english = 'son'
level = 'n4'
tags = ['common', 'family', 'noun', 'people']
frequency_scores = { anime = 1011, leeds = 1343, novels = 1523, wikipedia = 896 }

[[cards]]
kanji = '娘'
kana = 'むすめ'
english = 'daughter'
level = 'n4'
tags = ['common', 'family', 'noun', 'people']
frequency_scores = { anime = 369, leeds = 1007, novels = 301, wikipedia = 574 }

[[cards]]
kanji = '両親'
kana = 'りょうしん'
english = 'parents; both parents'
level = 'n5'
tags = ['common', 'family', 'noun', 'people']
frequency_scores = { anime = 1868, leeds = 2403, novels = 1629, wikipedia = 2747 }

