[[cards]]
kanji = '相手'
kana = 'あいて'
english = 'partner; opponent (sports)'
level = 'n3'
tags = ['common', 'noun', 'people']
highest_frequency = 173
highest_frequency_source = 'Anime'

[[cards]]
kanji = '赤ちゃん'
kana = 'あかちゃん'
english = 'baby'
level = 'n4'
tags = ['common', 'noun', 'people']
highest_frequency = 3651
highest_frequency_source = 'Leeds'

[[cards]]
kanji = '赤ん坊'
kana = 'あかんぼう'
english = 'infant'
level = 'n4'
source = 'jlptstudy.net'
tags = ['common', 'noun', 'people']
highest_frequency = 4599
highest_frequency_source = 'Anime'

[[cards]]
kanji = '貴方'
kana = 'あなた'
english = 'you (equal or lower status); dear (wife to husband)'
level = 'n5'
tags = ['common', 'people', 'pronouns']
highest_frequency = 1022
highest_frequency_source = 'Anime'

[[cards]]
kanji = '王'
kana = 'おう'
english = 'king; monarch; sovereign'
source = 'wanikani'
level = 'n3'
tags = ['common', 'noun']
highest_frequency = 194
highest_frequency_source = 'Wikipedia'

[[cards]]
kanji = '王様'
kana = 'おうさま'
english = 'king (sonkeigo)'
source = 'wanikani'
level = 'n3'
tags = ['common', 'noun']
highest_frequency = 1902
highest_frequency_source = 'Anime'

[[cards]]
kanji = '大勢'
kana = 'おおぜい'
english = 'crowd of people'
level = 'n5'
tags = []
highest_frequency = 2531
highest_frequency_source = 'Anime'

[[cards]]
kanji = '男'
kana = 'おとこ'
english = 'man; male'
level = 'n5'
tags = []
highest_frequency = 86
highest_frequency_source = 'Novels'

[[cards]]
kanji = '男の子'
kana = 'おとこのこ'
english = 'boy'
level = 'n5'
tags = []
highest_frequency = 1558
highest_frequency_source = 'Anime'

[[cards]]
kanji = '大人'
kana = 'おとな'
english = 'adult'
level = 'n5'
tags = []
highest_frequency = 596
highest_frequency_source = 'Anime'

[[cards]]
kanji = 'お巡りさん'
kana = 'おまわりさん'
english = 'police officer (friendly term)'
level = 'n5'
tags = []
highest_frequency = 18423
highest_frequency_source = 'Anime'

[[cards]]
kanji = '女'
kana = 'おんな'
english = 'woman; female'
level = 'n5'
tags = []
highest_frequency = 110
highest_frequency_source = 'Novels'

[[cards]]
kanji = '女の子'
kana = 'おんなのこ'
english = 'girl'
level = 'n5'
tags = []
highest_frequency = 374
highest_frequency_source = 'Anime'

[[cards]]
kanji = '海賊'
kana = 'かいぞく'
english = 'pirate'
source = 'anime'
tags = ['anime', 'common', 'noun', 'people']
highest_frequency = 925
highest_frequency_source = 'Anime'

[[cards]]
kanji = '家族'
kana = 'かぞく'
english = 'family'
level = 'n5'
tags = []
highest_frequency = 580
highest_frequency_source = 'Anime'

[[cards]]
kanji = '方'
kana = 'かた'
english = 'person (sonkeigo); method or way of'
level = 'n5'
tags = []
highest_frequency = 88
highest_frequency_source = 'Anime'

[[cards]]
kanji = '金持ち'
kana = 'かねもち'
english = 'rich person'
tags = ['common', 'noun', 'people']
level = 'n4'
highest_frequency = 3937
highest_frequency_source = 'Leeds'

[[cards]]
kanji = '看護師'
kana = 'かんごし'
english = 'hospital nurse'
level = 'n4'
tags = ['common']

[[cards]]
kanji = '外国人'
kana = 'がいこくじん'
english = 'foreigner'
level = 'n5'
tags = ['common', 'noun']

[[cards]]
kanji = '外人'
kana = 'がいじん'
english = 'foreigner (less polite)'
tags = ['common', 'noun']
highest_frequency = 7719
highest_frequency_source = 'Leeds'

[[cards]]
kanji = '学者'
kana = 'がくしゃ'
english = 'scholar'
source = 'wanikani'
level = 'n3'
tags = ['common', 'no-adjective', 'noun', 'people']
highest_frequency = 674
highest_frequency_source = 'Wikipedia'

[[cards]]
kanji = '警官'
kana = 'けいかん'
english = 'police'
level = 'n5'
tags = []
highest_frequency = 2475
highest_frequency_source = 'Novels'

[[cards]]
kanji = '子'
kana = 'こ'
english = 'child'
source = 'irasshai'
level = 'n4'
tags = ['age', 'common', 'noun', 'noun-suffix', 'people', 'young']
highest_frequency = 70
highest_frequency_source = 'Anime'

[[cards]]
kanji = '子供'
kana = 'こども'
english = 'child'
level = 'n5'
tags = ['common', 'noun', 'people']
highest_frequency = 263
highest_frequency_source = 'Novels'

[[cards]]
kanji = '市民'
kana = 'しみん'
english = 'citizen; city inhabitant'
source = 'n4-vocab'
level = 'n4'
tags = ['common', 'noun', 'people']
highest_frequency = 973
highest_frequency_source = 'Wikipedia'

[[cards]]
kanji = '社長'
kana = 'しゃちょう'
english = 'company president; manager; director'
level = 'n4'
source = 'wanikani'
tags = ['common', 'noun']
highest_frequency = 914
highest_frequency_source = 'Leeds'

[[cards]]
kanji = '自分'
kana = 'じぶん'
english = 'myself; oneself'
level = 'n5'
tags = []
highest_frequency = 57
highest_frequency_source = 'Novels'

[[cards]]
kanji = '住民'
kana = 'じゅうみん'
english = 'resident'
source = 'wanikani'
level = 'n3'
tags = ['common', 'noun', 'people']
highest_frequency = 938
highest_frequency_source = 'Wikipedia'

[[cards]]
kanji = '女王'
kana = 'じょおう'
english = 'queen'
source = 'wanikani'
level = 'n3'
tags = ['common', 'noun']
highest_frequency = 1777
highest_frequency_source = 'Novels'

[[cards]]
kanji = '助手'
kana = 'じょしゅ'
english = 'assistant'
source = 'wanikani'
level = 'n3'
tags = ['common', 'noun', 'people']
highest_frequency = 3940
highest_frequency_source = 'Wikipedia'

[[cards]]
kanji = '人口'
kana = 'じんこう'
english = 'population'
level = 'n4'
source = 'wanikani'
tags = ['common', 'noun']
highest_frequency = 282
highest_frequency_source = 'Wikipedia'

[[cards]]
kanji = '声優'
kana = 'せいゆう'
english = 'actor; performer'
tags = ['noun', 'people', 'uncommon']
highest_frequency = 1493
highest_frequency_source = 'Wikipedia'

[[cards]]
kanji = '選手'
kana = 'せんしゅ'
english = 'athelete; player (sports)'
level = 'n3'
source = 'wanikani'
tags = ['common', 'noun', 'sports']
highest_frequency = 78
highest_frequency_source = 'Wikipedia'

[[cards]]
kanji = '大統領'
kana = 'だいとうりょう'
english = 'president (of a nation or company)'
source = 'stay in japan'
level = 'n3'
tags = ['common', 'company', 'noun', 'people', 'politics', 'work']
highest_frequency = 530
highest_frequency_source = 'Wikipedia'

[[cards]]
kanji = '町民'
kana = 'ちょうみん'
english = 'townspeople'
source = 'wanikani'
tags = ['common', 'people', 'town']
highest_frequency = 12512
highest_frequency_source = 'Leeds'

[[cards]]
kanji = '天才'
kana = 'てんさい'
english = 'genius'
level = 'n1'
source = 'wanikani'
tags = ['common', 'noun']
highest_frequency = 1373
highest_frequency_source = 'Anime'

[[cards]]
kanji = 'とこや'
kana = 'とこや'
english = 'barber'
source = 'wiktionary'
level = 'n4'
tags = ['common', 'noun', 'person']

[[cards]]
kanji = '年寄り'
kana = 'としより'
english = 'elderly person'
source = 'sekai-wa-fushigi-2'
level = 'n3'
tags = ['common', 'no-adjective', 'noun']
highest_frequency = 5774
highest_frequency_source = 'Anime'

[[cards]]
kanji = '友達'
kana = 'ともだち'
english = 'friend (spoken form)'
level = 'n5'
explain = 'https://hinative.com/en-US/questions/696835'
tags = []
highest_frequency = 235
highest_frequency_source = 'Anime'

[[cards]]
kanji = '泥棒'
kana = 'どろぼう'
english = 'thief'
level = 'n4'
tags = ['common', 'noun', 'suru-verb']
highest_frequency = 2626
highest_frequency_source = 'Anime'

[[cards]]
kanji = '仲間'
kana = 'なかま'
english = 'companion'
source = 'wanikani'
level = 'n3'
tags = ['common', 'noun', 'people']
highest_frequency = 291
highest_frequency_source = 'Anime'

[[cards]]
kanji = '～人'
kana = '～にん'
english = 'counter for people'
level = 'n5'
tags = []

[[cards]]
kanji = '人間'
kana = 'にんげん'
english = 'human being; mankind'
level = 'n3'
tags = ['anime', 'common', 'noun', 'people']
highest_frequency = 105
highest_frequency_source = 'Anime'

[[cards]]
kanji = '俳優'
kana = 'はいゆう'
english = 'actor; performer'
level = 'n3'
tags = ['common', 'no-adjective', 'noun', 'people']
highest_frequency = 860
highest_frequency_source = 'Wikipedia'

[[cards]]
kanji = '白人'
kana = 'はくじん'
english = 'white person; Caucasian'
source = 'wanikani'
tags = ['common', 'no-adjective']
highest_frequency = 3511
highest_frequency_source = 'Wikipedia'

[[cards]]
kanji = '馬鹿'
kana = 'ばか'
english = 'idiot'
source = 'i have always known this'
level = 'n3'
tags = ['common', 'na-adjective', 'noun']
highest_frequency = 694
highest_frequency_source = 'Anime'

[[cards]]
kanji = '髭'
kana = 'ひげ'
english = 'mustache'
source = 'irasshai'
level = 'n4'
tags = ['body', 'common', 'facial-hair', 'noun', 'people', 'style']
highest_frequency = 6735
highest_frequency_source = 'Wikipedia'

[[cards]]
kanji = '人'
kana = 'ひと'
english = 'man; person'
level = 'n5'
tags = []
highest_frequency = 22
highest_frequency_source = 'Anime'

[[cards]]
kanji = '人々'
kana = 'ひとびと'
english = 'people; each person'
source = 'wanikani'
tags = ['common', 'no-adjective', 'noun', 'people']
highest_frequency = 526
highest_frequency_source = 'Leeds'

[[cards]]
kanji = '一人'
kana = 'ひとり'
english = 'one person'
level = 'n5'
tags = []
highest_frequency = 344
highest_frequency_source = 'Novels'

[[cards]]
kanji = '二人'
kana = 'ふたり'
english = 'two people'
level = 'n5'
tags = []
highest_frequency = 714
highest_frequency_source = 'Novels'

[[cards]]
kanji = '星'
kana = 'ほし'
english = 'star'
level = 'n4'
tags = ['common', 'noun', 'space']
highest_frequency = 263
highest_frequency_source = 'Anime'

[[cards]]
kanji = '皆さん'
kana = 'みなさん'
english = 'everyone (sonkeigo)'
level = 'n5'
tags = ['common', 'honorific', 'noun', 'respectful', 'sonkeigo']
highest_frequency = 460
highest_frequency_source = 'Anime'

[[cards]]
kanji = '皆'
kana = 'みんな'
english = 'everyone'
level = 'n5'
tags = []
highest_frequency = 232
highest_frequency_source = 'Anime'

[[cards]]
kanji = '役人'
kana = 'やくにん'
english = 'government official'
level = 'n2'
tags = ['common', 'government']
highest_frequency = 4421
highest_frequency_source = 'Anime'

[[cards]]
kanji = '奴ら'
kana = 'やつら'
english = 'they; those guys'
source = 'wanikani'
tags = ['common', 'people', 'pronoun']
highest_frequency = 545
highest_frequency_source = 'Anime'

[[cards]]
kanji = '友人'
kana = 'ゆうじん'
english = 'friend (written form)'
level = 'n3'
source = 'wanikani'
explain = 'https://hinative.com/en-US/questions/696835'
tags = ['common', 'noun', 'people']
highest_frequency = 870
highest_frequency_source = 'Leeds'

[[cards]]
kanji = '幼児'
kana = 'ようじ'
english = 'toddler'
level = 'n2'
source = 'jisho.org'
tags = ['common', 'noun', 'people']
highest_frequency = 4568
highest_frequency_source = 'Leeds'

[[cards]]
kanji = '若い'
kana = 'わかい'
english = 'young; youthful'
level = 'n5'
tags = []
highest_frequency = 386
highest_frequency_source = 'Novels'

[[cards]]
kanji = '私'
kana = 'わたくし'
english = 'I; me (more formal)'
level = 'n5'
tags = []
highest_frequency = 17
highest_frequency_source = 'Anime'

[[cards]]
kanji = '私'
kana = 'わたし'
english = 'I; me'
level = 'n5'
tags = []
highest_frequency = 17
highest_frequency_source = 'Anime'

[[cards]]
kanji = 'アナウンサー'
kana = 'アナウンサー'
english = 'announcer'
level = 'n4'
tags = ['common', 'gairaigo', 'noun', 'people']
highest_frequency = 1436
highest_frequency_source = 'Wikipedia'

