[[cards]]
kanji = '相手'
kana = 'あいて'
english = 'partner; opponent (sports)'
level = 'n3'
tags = ['common', 'noun', 'people']
frequency_scores = { anime = 173, leeds = 469, novels = 234, wikipedia = 845 }

[[cards]]
kanji = '赤ちゃん'
kana = 'あかちゃん'
english = 'baby'
level = 'n4'
tags = ['common', 'noun', 'people']
frequency_scores = { anime = 3675, leeds = 3651 }

[[cards]]
kanji = '赤ん坊'
kana = 'あかんぼう'
english = 'infant'
level = 'n4'
source = 'jlptstudy.net'
tags = ['common', 'noun', 'people']
frequency_scores = { anime = 4599, leeds = 9738 }

[[cards]]
kanji = '貴方'
kana = 'あなた'
english = 'you (equal or lower status); dear (wife to husband)'
level = 'n5'
tags = ['common', 'people', 'pronouns']
frequency_scores = { anime = 1022, leeds = 4636, novels = 1686, wikipedia = 3647 }

[[cards]]
kanji = '王'
kana = 'おう'
english = 'king; monarch; sovereign'
source = 'wanikani'
level = 'n3'
tags = ['common', 'noun']
frequency_scores = { anime = 234, leeds = 1759, novels = 343, wikipedia = 194 }

[[cards]]
kanji = '王様'
kana = 'おうさま'
english = 'king (sonkeigo)'
source = 'wanikani'
level = 'n3'
tags = ['common', 'noun']
frequency_scores = { anime = 1902, leeds = 6426 }

[[cards]]
kanji = '大勢'
kana = 'おおぜい'
english = 'crowd of people'
level = 'n5'
tags = []
frequency_scores = { anime = 2531, leeds = 3907, novels = 2691, wikipedia = 8495 }

[[cards]]
kanji = '男'
kana = 'おとこ'
english = 'man; male'
level = 'n5'
tags = []
frequency_scores = { anime = 124, leeds = 447, novels = 86, wikipedia = 585 }

[[cards]]
kanji = '男の子'
kana = 'おとこのこ'
english = 'boy'
level = 'n5'
tags = []
frequency_scores = { anime = 1558, leeds = 3810, novels = 2708 }

[[cards]]
kanji = '大人'
kana = 'おとな'
english = 'adult'
level = 'n5'
tags = []
frequency_scores = { anime = 596, leeds = 1231, novels = 1367, wikipedia = 3742 }

[[cards]]
kanji = 'お巡りさん'
kana = 'おまわりさん'
english = 'police officer (friendly term)'
level = 'n5'
tags = []
frequency_scores = { anime = 18423 }

[[cards]]
kanji = '女'
kana = 'おんな'
english = 'woman; female'
level = 'n5'
tags = []
frequency_scores = { anime = 169, leeds = 740, novels = 110, wikipedia = 857 }

[[cards]]
kanji = '女の子'
kana = 'おんなのこ'
english = 'girl'
level = 'n5'
tags = []
frequency_scores = { anime = 374, leeds = 1678, novels = 814, wikipedia = 6781 }

[[cards]]
kanji = '海賊'
kana = 'かいぞく'
english = 'pirate'
source = 'anime'
tags = ['anime', 'common', 'noun', 'people']
frequency_scores = { anime = 925, leeds = 11093, wikipedia = 4712 }

[[cards]]
kanji = '家族'
kana = 'かぞく'
english = 'family'
level = 'n5'
tags = []
frequency_scores = { anime = 580, leeds = 599, novels = 1467, wikipedia = 981 }

[[cards]]
kanji = '方'
kana = 'かた'
english = 'person (sonkeigo); method or way of'
level = 'n5'
tags = []
frequency_scores = { anime = 88, leeds = 116, novels = 108, wikipedia = 800 }

[[cards]]
kanji = '金持ち'
kana = 'かねもち'
english = 'rich person'
tags = ['common', 'noun', 'people']
level = 'n4'
frequency_scores = { anime = 5006, leeds = 3937 }

[[cards]]
kanji = '看護師'
kana = 'かんごし'
english = 'hospital nurse'
level = 'n4'
tags = ['common']

[[cards]]
kanji = '外国人'
kana = 'がいこくじん'
english = 'foreigner'
level = 'n5'
tags = ['common', 'noun']

[[cards]]
kanji = '外人'
kana = 'がいじん'
english = 'foreigner (less polite)'
tags = ['common', 'noun']
frequency_scores = { anime = 14098, leeds = 7719 }

[[cards]]
kanji = '学者'
kana = 'がくしゃ'
english = 'scholar'
source = 'wanikani'
level = 'n3'
tags = ['common', 'no-adjective', 'noun', 'people']
frequency_scores = { anime = 8082, leeds = 2170, wikipedia = 674 }

[[cards]]
kanji = '警官'
kana = 'けいかん'
english = 'police'
level = 'n5'
tags = []
frequency_scores = { anime = 4620, leeds = 5513, novels = 2475, wikipedia = 8024 }

[[cards]]
kanji = '子'
kana = 'こ'
english = 'child'
source = 'irasshai'
level = 'n4'
tags = ['age', 'common', 'noun', 'noun-suffix', 'people', 'young']
frequency_scores = { anime = 70, leeds = 508, novels = 184, wikipedia = 157 }

[[cards]]
kanji = '子供'
kana = 'こども'
english = 'child'
level = 'n5'
tags = ['common', 'noun', 'people']
frequency_scores = { anime = 264, leeds = 320, novels = 263, wikipedia = 565 }

[[cards]]
kanji = '市民'
kana = 'しみん'
english = 'citizen; city inhabitant'
source = 'n4-vocab'
level = 'n4'
tags = ['common', 'noun', 'people']
frequency_scores = { anime = 2570, leeds = 1069, novels = 2809, wikipedia = 973 }

[[cards]]
kanji = '社長'
kana = 'しゃちょう'
english = 'company president; manager; director'
level = 'n4'
source = 'wanikani'
tags = ['common', 'noun']
frequency_scores = { anime = 2501, leeds = 914, wikipedia = 968 }

[[cards]]
kanji = '自分'
kana = 'じぶん'
english = 'myself; oneself'
level = 'n5'
tags = []
frequency_scores = { anime = 68, leeds = 112, novels = 57, wikipedia = 455 }

[[cards]]
kanji = '住民'
kana = 'じゅうみん'
english = 'resident'
source = 'wanikani'
level = 'n3'
tags = ['common', 'noun', 'people']
frequency_scores = { anime = 4612, leeds = 1334, wikipedia = 938 }

[[cards]]
kanji = '女王'
kana = 'じょおう'
english = 'queen'
source = 'wanikani'
level = 'n3'
tags = ['common', 'noun']
frequency_scores = { anime = 2017, leeds = 6055, novels = 1777, wikipedia = 2958 }

[[cards]]
kanji = '助手'
kana = 'じょしゅ'
english = 'assistant'
source = 'wanikani'
level = 'n3'
tags = ['common', 'noun', 'people']
frequency_scores = { anime = 4997, leeds = 7007, wikipedia = 3940 }

[[cards]]
kanji = '人口'
kana = 'じんこう'
english = 'population'
level = 'n4'
source = 'wanikani'
tags = ['common', 'noun']
frequency_scores = { anime = 6136, leeds = 1507, wikipedia = 282 }

[[cards]]
kanji = '声優'
kana = 'せいゆう'
english = 'actor; performer'
tags = ['noun', 'people', 'uncommon']
frequency_scores = { anime = 5538, leeds = 9095, wikipedia = 1493 }

[[cards]]
kanji = '選手'
kana = 'せんしゅ'
english = 'athelete; player (sports)'
level = 'n3'
source = 'wanikani'
tags = ['common', 'noun', 'sports']
frequency_scores = { anime = 742, leeds = 559, wikipedia = 78 }

[[cards]]
kanji = '大統領'
kana = 'だいとうりょう'
english = 'president (of a nation or company)'
source = 'stay in japan'
level = 'n3'
tags = ['common', 'company', 'noun', 'people', 'politics', 'work']
frequency_scores = { anime = 10604, leeds = 1434, wikipedia = 530 }

[[cards]]
kanji = '町民'
kana = 'ちょうみん'
english = 'townspeople'
source = 'wanikani'
tags = ['common', 'people', 'town']
frequency_scores = { anime = 25459, leeds = 12512 }

[[cards]]
kanji = '天才'
kana = 'てんさい'
english = 'genius'
level = 'n1'
source = 'wanikani'
tags = ['common', 'noun']
frequency_scores = { anime = 1373, leeds = 4307, wikipedia = 6371 }

[[cards]]
kanji = 'とこや'
kana = 'とこや'
english = 'barber'
source = 'wiktionary'
level = 'n4'
tags = ['common', 'noun', 'person']

[[cards]]
kanji = '年寄り'
kana = 'としより'
english = 'elderly person'
source = 'sekai-wa-fushigi-2'
level = 'n3'
tags = ['common', 'no-adjective', 'noun']
frequency_scores = { anime = 5774, leeds = 6192, wikipedia = 6779 }

[[cards]]
kanji = '友達'
kana = 'ともだち'
english = 'friend (spoken form)'
level = 'n5'
explain = 'https://hinative.com/en-US/questions/696835'
tags = []
frequency_scores = { anime = 235, leeds = 1074, novels = 1400, wikipedia = 6434 }

[[cards]]
kanji = '泥棒'
kana = 'どろぼう'
english = 'thief'
level = 'n4'
tags = ['common', 'noun', 'suru-verb']
frequency_scores = { anime = 2626, leeds = 7679 }

[[cards]]
kanji = '仲間'
kana = 'なかま'
english = 'companion'
source = 'wanikani'
level = 'n3'
tags = ['common', 'noun', 'people']
frequency_scores = { anime = 291, leeds = 1450, novels = 730, wikipedia = 2071 }

[[cards]]
kanji = '～人'
kana = '～にん'
english = 'counter for people'
level = 'n5'
tags = []

[[cards]]
kanji = '人間'
kana = 'にんげん'
english = 'human being; mankind'
level = 'n3'
tags = ['anime', 'common', 'noun', 'people']
frequency_scores = { anime = 105, leeds = 246, novels = 159, wikipedia = 599 }

[[cards]]
kanji = '俳優'
kana = 'はいゆう'
english = 'actor; performer'
level = 'n3'
tags = ['common', 'no-adjective', 'noun', 'people']
frequency_scores = { anime = 12212, leeds = 4031, wikipedia = 860 }

[[cards]]
kanji = '白人'
kana = 'はくじん'
english = 'white person; Caucasian'
source = 'wanikani'
tags = ['common', 'no-adjective']
frequency_scores = { anime = 27563, leeds = 5987, wikipedia = 3511 }

[[cards]]
kanji = '馬鹿'
kana = 'ばか'
english = 'idiot'
source = 'i have always known this'
level = 'n3'
tags = ['common', 'na-adjective', 'noun']
frequency_scores = { anime = 694, leeds = 3020, novels = 1044, wikipedia = 5993 }

[[cards]]
kanji = '髭'
kana = 'ひげ'
english = 'mustache'
source = 'irasshai'
level = 'n4'
tags = ['body', 'common', 'facial-hair', 'noun', 'people', 'style']
frequency_scores = { anime = 10006, wikipedia = 6735 }

[[cards]]
kanji = '人'
kana = 'ひと'
english = 'man; person'
level = 'n5'
tags = []
frequency_scores = { anime = 22, leeds = 45, novels = 33, wikipedia = 35 }

[[cards]]
kanji = '人々'
kana = 'ひとびと'
english = 'people; each person'
source = 'wanikani'
tags = ['common', 'no-adjective', 'noun', 'people']
frequency_scores = { anime = 1481, leeds = 526, novels = 551, wikipedia = 862 }

[[cards]]
kanji = '一人'
kana = 'ひとり'
english = 'one person'
level = 'n5'
tags = []
frequency_scores = { anime = 41614, leeds = 1665, novels = 344 }

[[cards]]
kanji = '二人'
kana = 'ふたり'
english = 'two people'
level = 'n5'
tags = []
frequency_scores = { anime = 4978, leeds = 4297, novels = 714 }

[[cards]]
kanji = '星'
kana = 'ほし'
english = 'star'
level = 'n4'
tags = ['common', 'noun', 'space']
frequency_scores = { anime = 263, leeds = 1705, novels = 767, wikipedia = 605 }

[[cards]]
kanji = '皆さん'
kana = 'みなさん'
english = 'everyone (sonkeigo)'
level = 'n5'
tags = ['common', 'honorific', 'noun', 'respectful', 'sonkeigo']
frequency_scores = { anime = 460, leeds = 735 }

[[cards]]
kanji = '皆'
kana = 'みんな'
english = 'everyone'
level = 'n5'
tags = []
frequency_scores = { anime = 232, leeds = 1489, novels = 967, wikipedia = 2169 }

[[cards]]
kanji = '役人'
kana = 'やくにん'
english = 'government official'
level = 'n2'
tags = ['common', 'government']
frequency_scores = { anime = 4421, leeds = 6088, wikipedia = 7261 }

[[cards]]
kanji = '奴ら'
kana = 'やつら'
english = 'they; those guys'
source = 'wanikani'
tags = ['common', 'people', 'pronoun']
frequency_scores = { anime = 545, leeds = 10488 }

[[cards]]
kanji = '友人'
kana = 'ゆうじん'
english = 'friend (written form)'
level = 'n3'
source = 'wanikani'
explain = 'https://hinative.com/en-US/questions/696835'
tags = ['common', 'noun', 'people']
frequency_scores = { anime = 2168, leeds = 870, novels = 1603, wikipedia = 2127 }

[[cards]]
kanji = '幼児'
kana = 'ようじ'
english = 'toddler'
level = 'n2'
source = 'jisho.org'
tags = ['common', 'noun', 'people']
frequency_scores = { anime = 16297, leeds = 4568, wikipedia = 7129 }

[[cards]]
kanji = '若い'
kana = 'わかい'
english = 'young; youthful'
level = 'n5'
tags = []
frequency_scores = { anime = 854, leeds = 891, novels = 386, wikipedia = 1526 }

[[cards]]
kanji = '私'
kana = 'わたくし'
english = 'I; me (more formal)'
level = 'n5'
tags = []
frequency_scores = { anime = 17, leeds = 58, novels = 62, wikipedia = 1076 }

[[cards]]
kanji = '私'
kana = 'わたし'
english = 'I; me'
level = 'n5'
tags = []
frequency_scores = { anime = 17, leeds = 58, novels = 62, wikipedia = 1076 }

[[cards]]
kanji = 'アナウンサー'
kana = 'アナウンサー'
english = 'announcer'
level = 'n4'
tags = ['common', 'gairaigo', 'noun', 'people']
frequency_scores = { anime = 4234, leeds = 8778, wikipedia = 1436 }

