[[cards]]
kanji = '足'
kana = 'あし'
english = 'foot; leg'
level = 'n5'
tags = ['body', 'common']
frequency_scores = { anime = 434, leeds = 861, novels = 248, wikipedia = 1249 }

[[cards]]
kanji = '足首'
kana = 'あしくび'
english = 'ankle'
source = 'wanikani/jisho'
tags = ['body', 'common', 'noun']
frequency_scores = { anime = 25656, leeds = 13818 }

[[cards]]
kanji = '頭'
kana = 'あたま'
english = 'head'
level = 'n5'
tags = ['anatomy', 'body', 'common']
frequency_scores = { anime = 267, leeds = 506, novels = 144, wikipedia = 593 }

[[cards]]
kanji = '腕'
kana = 'うで'
english = 'arm'
level = 'n4'
tags = ['anatomy', 'body', 'common', 'noun']
frequency_scores = { anime = 584, leeds = 2557, novels = 295, wikipedia = 2952 }

[[cards]]
kanji = '腕'
kana = 'うで'
english = 'arm'
level = 'n4'
tags = ['body', 'noun']
frequency_scores = { anime = 584, leeds = 2557, novels = 295, wikipedia = 2952 }

[[cards]]
kanji = 'お腹'
kana = 'おなか'
english = 'stomach'
level = 'n5'
tags = ['body']
frequency_scores = { anime = 1689, leeds = 3666 }

[[cards]]
kanji = '顔'
kana = 'かお'
english = 'face'
level = 'n5'
tags = ['body']
frequency_scores = { anime = 180, leeds = 558, novels = 71, wikipedia = 1878 }

[[cards]]
kanji = '踵'
kana = 'かかと'
english = 'heel'
level = 'n1'
tags = ['body', 'common']
frequency_scores = { anime = 30051 }

[[cards]]
kanji = '体'
kana = 'からだ'
english = 'body'
level = 'n5'
tags = ['body']
frequency_scores = { anime = 167, leeds = 494, novels = 219, wikipedia = 165 }

[[cards]]
kanji = '皮'
kana = 'かわ'
english = 'skin; hide'
source = 'wanikani'
level = 'n3'
tags = ['common', 'noun']
frequency_scores = { anime = 3799, leeds = 4042, novels = 2385, wikipedia = 4341 }

[[cards]]
kanji = '筋肉'
kana = 'きんにく'
english = 'muscle'
level = 'n3'
source = 'manga'
tags = ['common']
frequency_scores = { anime = 3051, leeds = 3885, wikipedia = 6311 }

[[cards]]
kanji = '口'
kana = 'くち'
english = 'mouth; opening'
level = 'n5'
tags = ['body', 'common', 'noun']
frequency_scores = { anime = 371, leeds = 907, novels = 136, wikipedia = 679 }

[[cards]]
kanji = '首'
kana = 'くび'
english = 'neck'
level = 'n4'
tags = ['body', 'common']
frequency_scores = { anime = 785, leeds = 2232, novels = 247, wikipedia = 1584 }

[[cards]]
kanji = '血'
kana = 'ち'
english = 'blood'
source = 'wanikani; anime'
level = 'n4'
tags = ['body', 'common', 'health', 'noun']
frequency_scores = { anime = 405, leeds = 2236, novels = 409, wikipedia = 2321 }

[[cards]]
kanji = '手'
kana = 'て'
english = 'hand; arm'
level = 'n5'
tags = ['body']
frequency_scores = { anime = 89, leeds = 281, novels = 76, wikipedia = 306 }

[[cards]]
kanji = '手首'
kana = 'てくび'
english = 'wrist'
source = 'wanikani/jisho'
level = 'n2'
tags = ['body', 'common', 'noun']
frequency_scores = { anime = 10399, leeds = 10379, novels = 2113 }

[[cards]]
kanji = '涙'
kana = 'なみだ'
english = 'tear(s)'
level = 'n3'
tags = ['body', 'common']
frequency_scores = { anime = 861, leeds = 1843, novels = 705, wikipedia = 5232 }

[[cards]]
kanji = '鼻'
kana = 'はな'
english = 'nose'
level = 'n5'
tags = []
frequency_scores = { anime = 1851, leeds = 3656, novels = 743, wikipedia = 5022 }

[[cards]]
kanji = '膝'
kana = 'ひざ'
english = 'knee'
source = 'wanikani'
level = 'n3'
tags = ['body', 'common', 'leg', 'noun']
frequency_scores = { anime = 4414, leeds = 5434, novels = 679, wikipedia = 4528 }

[[cards]]
kanji = '肘'
kana = 'ひじ'
english = 'elbow'
source = 'jisho'
level = 'n2'
tags = ['arm', 'body', 'common', 'noun']
frequency_scores = { anime = 10206, leeds = 12103, wikipedia = 6306 }

[[cards]]
kanji = '額'
kana = 'ひたい'
english = 'forehead'
level = 'n3'
source = 'wanikani'
tags = ['body', 'common', 'noun']
frequency_scores = { anime = 3398, leeds = 1100, novels = 1111, wikipedia = 1990 }

[[cards]]
kanji = '瞳'
kana = 'ひとみ'
english = 'pupil (eye)'
source = 'frequency-list'
level = 'n2'
tags = ['body', 'common', 'eye', 'no-adjective', 'noun']
frequency_scores = { anime = 1395, leeds = 6156, novels = 752, wikipedia = 5781 }

[[cards]]
kanji = '骨'
kana = 'ほね'
english = 'bone'
level = 'n3'
tags = ['body', 'common']
frequency_scores = { anime = 2278, leeds = 3275, novels = 1353, wikipedia = 2129 }

[[cards]]
kanji = '眉毛'
kana = 'まゆげ'
english = 'eyebrow'
source = 'wanikani'
tags = ['common', 'no-adjective', 'noun']
frequency_scores = { anime = 7640 }

[[cards]]
kanji = '耳'
kana = 'みみ'
english = 'ear'
level = 'n5'
tags = ['body', 'common', 'noun']
frequency_scores = { anime = 1030, leeds = 1461, novels = 364, wikipedia = 3147 }

[[cards]]
kanji = '目'
kana = 'め'
english = 'eye; eyeball'
level = 'n5'
tags = []
frequency_scores = { anime = 87, leeds = 189, novels = 80, wikipedia = 1178 }

[[cards]]
kanji = '目玉'
kana = 'めだま'
english = 'eyeball'
source = 'wanikani'
tags = ['body', 'common']
frequency_scores = { anime = 9642, leeds = 8988 }

[[cards]]
kanji = '指'
kana = 'ゆび'
english = 'finger; toe'
level = 'n4'
tags = ['body', 'common']
frequency_scores = { anime = 1276, leeds = 2632, novels = 285, wikipedia = 4001 }

[[cards]]
kanji = '指先'
kana = 'ゆびさき'
english = 'fingertip'
source = 'wanikani'
tags = ['body', 'common']
frequency_scores = { anime = 5183, leeds = 11703, novels = 1711 }

