[[cards]]
kanji = '足'
kana = 'あし'
english = 'foot; leg'
level = 'n5'
tags = ['body', 'common']
highest_frequency = 248
highest_frequency_source = 'Novel 3k'

[[cards]]
kanji = '足首'
kana = 'あしくび'
english = 'ankle'
source = 'wanikani/jisho'
tags = ['body', 'common', 'noun']
highest_frequency = 13818
highest_frequency_source = 'Leeds 15k'

[[cards]]
kanji = '頭'
kana = 'あたま'
english = 'head'
level = 'n5'
tags = ['anatomy', 'body', 'common']
highest_frequency = 144
highest_frequency_source = 'Novel 3k'

[[cards]]
kanji = '腕'
kana = 'うで'
english = 'arm'
level = 'n4'
tags = ['body', 'noun']
highest_frequency = 295
highest_frequency_source = 'Novel 3k'

[[cards]]
kanji = 'お腹'
kana = 'おなか'
english = 'stomach'
level = 'n5'
tags = ['body']
highest_frequency = 1689
highest_frequency_source = 'Anime 45k'

[[cards]]
kanji = '顔'
kana = 'かお'
english = 'face'
level = 'n5'
tags = ['body']
highest_frequency = 71
highest_frequency_source = 'Novel 3k'

[[cards]]
kanji = '踵'
kana = 'かかと'
english = 'heel'
level = 'n1'
tags = ['body', 'common']
highest_frequency = 30051
highest_frequency_source = 'Anime 45k'

[[cards]]
kanji = '体'
kana = 'からだ'
english = 'body'
level = 'n5'
tags = ['body']
highest_frequency = 165
highest_frequency_source = 'Wikipedia 10k'

[[cards]]
kanji = '皮'
kana = 'かわ'
english = 'skin; hide'
source = 'wanikani'
level = 'n3'
tags = ['common', 'noun']
highest_frequency = 2385
highest_frequency_source = 'Novel 3k'

[[cards]]
kanji = '筋肉'
kana = 'きんにく'
english = 'muscle'
level = 'n3'
source = 'manga'
tags = ['common']
highest_frequency = 3051
highest_frequency_source = 'Anime 45k'

[[cards]]
kanji = '口'
kana = 'くち'
english = 'mouth; opening'
level = 'n5'
tags = ['body', 'common', 'noun']
highest_frequency = 136
highest_frequency_source = 'Novel 3k'

[[cards]]
kanji = '首'
kana = 'くび'
english = 'neck'
level = 'n4'
tags = ['body', 'common']
highest_frequency = 247
highest_frequency_source = 'Novel 3k'

[[cards]]
kanji = '血'
kana = 'ち'
english = 'blood'
source = 'wanikani; anime'
level = 'n4'
tags = ['body', 'common', 'health', 'noun']
highest_frequency = 405
highest_frequency_source = 'Anime 45k'

[[cards]]
kanji = '手'
kana = 'て'
english = 'hand; arm'
level = 'n5'
tags = ['body']
highest_frequency = 76
highest_frequency_source = 'Novel 3k'

[[cards]]
kanji = '手首'
kana = 'てくび'
english = 'wrist'
source = 'wanikani/jisho'
level = 'n2'
tags = ['body', 'common', 'noun']
highest_frequency = 2113
highest_frequency_source = 'Novel 3k'

[[cards]]
kanji = '涙'
kana = 'なみだ'
english = 'tear(s)'
level = 'n3'
tags = ['body', 'common']
highest_frequency = 705
highest_frequency_source = 'Novel 3k'

[[cards]]
kanji = '鼻'
kana = 'はな'
english = 'nose'
level = 'n5'
tags = []
highest_frequency = 743
highest_frequency_source = 'Novel 3k'

[[cards]]
kanji = '膝'
kana = 'ひざ'
english = 'knee'
source = 'wanikani'
level = 'n3'
tags = ['body', 'common', 'leg', 'noun']
highest_frequency = 679
highest_frequency_source = 'Novel 3k'

[[cards]]
kanji = '肘'
kana = 'ひじ'
english = 'elbow'
source = 'jisho'
level = 'n2'
tags = ['arm', 'body', 'common', 'noun']
highest_frequency = 6306
highest_frequency_source = 'Wikipedia 10k'

[[cards]]
kanji = '額'
kana = 'ひたい'
english = 'forehead'
level = 'n3'
source = 'wanikani'
tags = ['body', 'common', 'noun']
highest_frequency = 1100
highest_frequency_source = 'Leeds 15k'

[[cards]]
kanji = '瞳'
kana = 'ひとみ'
english = 'pupil (eye)'
source = 'frequency-list'
level = 'n2'
tags = ['body', 'common', 'eye', 'no-adjective', 'noun']
highest_frequency = 752
highest_frequency_source = 'Novel 3k'

[[cards]]
kanji = '骨'
kana = 'ほね'
english = 'bone'
level = 'n3'
tags = ['body', 'common']
highest_frequency = 1353
highest_frequency_source = 'Novel 3k'

[[cards]]
kanji = '眉毛'
kana = 'まゆげ'
english = 'eyebrow'
source = 'wanikani'
tags = ['common', 'no-adjective', 'noun']
highest_frequency = 7640
highest_frequency_source = 'Anime 45k'

[[cards]]
kanji = '耳'
kana = 'みみ'
english = 'ear'
level = 'n5'
tags = ['body', 'common', 'noun']
highest_frequency = 364
highest_frequency_source = 'Novel 3k'

[[cards]]
kanji = '目'
kana = 'め'
english = 'eye; eyeball'
level = 'n5'
tags = []
highest_frequency = 80
highest_frequency_source = 'Novel 3k'

[[cards]]
kanji = '目玉'
kana = 'めだま'
english = 'eyeball'
source = 'wanikani'
tags = ['body', 'common']
highest_frequency = 8988
highest_frequency_source = 'Leeds 15k'

[[cards]]
kanji = '指'
kana = 'ゆび'
english = 'finger; toe'
level = 'n4'
tags = ['body', 'common']
highest_frequency = 285
highest_frequency_source = 'Novel 3k'

