[[cards]]
kanji = '欠伸'
kana = 'あくび'
english = 'yawn'
level = 'n2'
source = 'wanikani'
tags = ['common']
highest_frequency = 32716
highest_frequency_source = 'Anime'

[[cards]]
kanji = '息'
kana = 'いき'
english = 'breath; breathing'
level = 'n3'
tags = ['biology', 'common', 'noun']
highest_frequency = 354
highest_frequency_source = 'Novels'

[[cards]]
kanji = '痛い'
kana = 'いたい'
english = 'painful ; sore'
level = 'n5'
tags = ['common', 'i-adjectives']
highest_frequency = 305
highest_frequency_source = 'Anime'

[[cards]]
kanji = '運動'
kana = 'うんどう'
english = 'exercise'
level = 'n3'
tags = ['activity', 'common', 'health', 'noun', 'suru-verb']
highest_frequency = 402
highest_frequency_source = 'Wikipedia'

[[cards]]
kanji = '風邪'
kana = 'かぜ'
english = 'cold; illness'
level = 'n5'
tags = []
highest_frequency = 1477
highest_frequency_source = 'Anime'

[[cards]]
kanji = '渇き'
kana = 'かわき'
english = 'thirst'
tags = ['common', 'noun']
highest_frequency = 13433
highest_frequency_source = 'Anime'

[[cards]]
kanji = '怪我'
kana = 'けが'
english = 'injury'
level = 'n3'
source = 'wanikani'
tags = ['common', 'noun', 'suru-verb']
highest_frequency = 1718
highest_frequency_source = 'Anime'

[[cards]]
kanji = '元気'
kana = 'げんき'
english = 'lively; healthy'
level = 'n5'
tags = []
highest_frequency = 440
highest_frequency_source = 'Anime'

[[cards]]
kanji = '声'
kana = 'こえ'
english = 'voice'
level = 'n5'
tags = []
highest_frequency = 78
highest_frequency_source = 'Novels'

[[cards]]
kanji = '丈夫'
kana = 'じょうぶ'
english = 'healthy; strong; solid; robust'
level = 'n5'
tags = []
highest_frequency = 6059
highest_frequency_source = 'Anime'

[[cards]]
kanji = '背'
kana = 'せい'
english = 'height'
level = 'n5'
tags = []
highest_frequency = 642
highest_frequency_source = 'Novels'

[[cards]]
kanji = '背中'
kana = 'せなか'
english = 'back (of body)'
level = 'n4'
source = 'https://www.japanesepod101.com/japanese-word-lists/'
tags = ['body', 'common']
highest_frequency = 512
highest_frequency_source = 'Novels'

[[cards]]
kanji = '煙草'
kana = 'たばこ'
english = 'tabacco; cigarettes'
level = 'n5'
tags = []
highest_frequency = 1847
highest_frequency_source = 'Novels'

[[cards]]
kanji = '歯'
kana = 'は'
english = 'tooth'
level = 'n5'
tags = []
highest_frequency = 1318
highest_frequency_source = 'Novels'

[[cards]]
kanji = '灰皿'
kana = 'はいざら'
english = 'ashtray'
level = 'n5'
tags = []
highest_frequency = 26550
highest_frequency_source = 'Anime'

[[cards]]
kanji = '病気'
kana = 'びょうき'
english = 'sickness; illness; disease'
level = 'n5'
tags = []
highest_frequency = 1650
highest_frequency_source = 'Leeds'

[[cards]]
kanji = '太い'
kana = 'ふとい'
english = 'fat; thick'
level = 'n5'
tags = ['common', 'i-adjective']
highest_frequency = 1459
highest_frequency_source = 'Novels'

[[cards]]
kanji = '細い'
kana = 'ほそい'
english = 'thin; slender'
level = 'n5'
tags = []
highest_frequency = 981
highest_frequency_source = 'Novels'

[[cards]]
kanji = '眼鏡'
kana = 'めがね'
english = 'eyeglasses'
level = 'n5'
tags = []
highest_frequency = 2571
highest_frequency_source = 'Novels'

