[[cards]]
kanji = '欠伸'
kana = 'あくび'
english = 'yawn'
level = 'n2'
source = 'wanikani'
tags = ['common']
frequency_scores = { anime = 32716 }

[[cards]]
kanji = '息'
kana = 'いき'
english = 'breath; breathing'
level = 'n3'
tags = ['biology', 'common', 'noun']
frequency_scores = { anime = 973, leeds = 3361, novels = 354, wikipedia = 7173 }

[[cards]]
kanji = '痛い'
kana = 'いたい'
english = 'painful ; sore'
level = 'n5'
tags = ['common', 'i-adjectives']
frequency_scores = { anime = 305, leeds = 1883, novels = 862 }

[[cards]]
kanji = '運動'
kana = 'うんどう'
english = 'exercise'
level = 'n3'
tags = ['activity', 'common', 'health', 'noun', 'suru-verb']
frequency_scores = { anime = 1857, leeds = 790, novels = 1531, wikipedia = 402 }

[[cards]]
kanji = '風邪'
kana = 'かぜ'
english = 'cold; illness'
level = 'n5'
tags = []
frequency_scores = { anime = 1477, leeds = 3103 }

[[cards]]
kanji = '渇き'
kana = 'かわき'
english = 'thirst'
tags = ['common', 'noun']
frequency_scores = { anime = 13433 }

[[cards]]
kanji = '怪我'
kana = 'けが'
english = 'injury'
level = 'n3'
source = 'wanikani'
tags = ['common', 'noun', 'suru-verb']
frequency_scores = { anime = 1718, leeds = 4812, novels = 2085, wikipedia = 3297 }

[[cards]]
kanji = '元気'
kana = 'げんき'
english = 'lively; healthy'
level = 'n5'
tags = []
frequency_scores = { anime = 440, leeds = 1373, novels = 1263, wikipedia = 6329 }

[[cards]]
kanji = '声'
kana = 'こえ'
english = 'voice'
level = 'n5'
tags = []
frequency_scores = { anime = 237, leeds = 472, novels = 78, wikipedia = 935 }

[[cards]]
kanji = '丈夫'
kana = 'じょうぶ'
english = 'healthy; strong; solid; robust'
level = 'n5'
tags = []
frequency_scores = { anime = 6059, leeds = 10434 }

[[cards]]
kanji = '背'
kana = 'せい'
english = 'height'
level = 'n5'
tags = []
frequency_scores = { anime = 2716, leeds = 4364, novels = 642, wikipedia = 3554 }

[[cards]]
kanji = '背中'
kana = 'せなか'
english = 'back (of body)'
level = 'n4'
source = 'https://www.japanesepod101.com/japanese-word-lists/'
tags = ['body', 'common']
frequency_scores = { anime = 1442, leeds = 4037, novels = 512, wikipedia = 6854 }

[[cards]]
kanji = '煙草'
kana = 'たばこ'
english = 'tabacco; cigarettes'
level = 'n5'
tags = []
frequency_scores = { anime = 6652, leeds = 7346, novels = 1847, wikipedia = 3920 }

[[cards]]
kanji = '歯'
kana = 'は'
english = 'tooth'
level = 'n5'
tags = []
frequency_scores = { anime = 3083, leeds = 3192, novels = 1318, wikipedia = 3429 }

[[cards]]
kanji = '灰皿'
kana = 'はいざら'
english = 'ashtray'
level = 'n5'
tags = []
frequency_scores = { anime = 26550 }

[[cards]]
kanji = '病気'
kana = 'びょうき'
english = 'sickness; illness; disease'
level = 'n5'
tags = []
frequency_scores = { anime = 2271, leeds = 1650, novels = 1837, wikipedia = 3005 }

[[cards]]
kanji = '太い'
kana = 'ふとい'
english = 'fat; thick'
level = 'n5'
tags = ['common', 'i-adjective']
frequency_scores = { anime = 2344, leeds = 5439, novels = 1459, wikipedia = 6169 }

[[cards]]
kanji = '細い'
kana = 'ほそい'
english = 'thin; slender'
level = 'n5'
tags = []
frequency_scores = { anime = 4089, leeds = 4567, novels = 981, wikipedia = 5556 }

[[cards]]
kanji = '眼鏡'
kana = 'めがね'
english = 'eyeglasses'
level = 'n5'
tags = []
frequency_scores = { anime = 3320, leeds = 7420, novels = 2571, wikipedia = 7441 }

