[[cards]]
kanji = '医者'
kana = 'いしゃ'
english = 'doctor'
level = 'n5'
tags = ['common', 'people']
highest_frequency = 1957
highest_frequency_source = 'Novel 3k'

[[cards]]
kanji = '看護師'
kana = 'かんごし'
english = 'nurse'
level = 'n4'
source = 'https://www.japanesepod101.com/japanese-word-lists/'
tags = ['common', 'noun', 'people', 'profession']

[[cards]]
kanji = '薬'
kana = 'くすり'
english = 'medicine'
level = 'n5'
tags = ['common', 'noun']
highest_frequency = 1403
highest_frequency_source = 'Anime 45k'

[[cards]]
kanji = '入院'
kana = 'にゅういん'
english = 'hospitalization'
source = 'wanikani'
level = 'n4'
tags = ['common', 'noun', 'suru-verb']
highest_frequency = 2927
highest_frequency_source = 'Leeds 15k'

[[cards]]
kanji = '病院'
kana = 'びょういん'
english = 'hospital'
level = 'n5'
tags = []
highest_frequency = 799
highest_frequency_source = 'Wikipedia 10k'

