- ある [存在]		u-v-i	to be
- ある [所有]		u-v-i	to have
- いく/ゆく	行く	u-v	to go
- いる	居る	u-v	(hum) to be (animate), to exist
- いる	要る	u-v	to need
- おきる	起きる	ru-v	to get up, to rise
- おす	押す	u-v,vt	to push, to press
- おぼえる	覚える	ru-v	to remember, to memorize
- おりる	降りる	ru-v	to alight (eg from bus), to get off
- おわる	終る	u-v	to finish, to close
- かえる	帰る	u-v	to go home, to return
- かかる		u-v,vi	to take (eg time, money)
- かける		ru-v	to put on (eg glasses)
- かける		ru-v	to dial/call (eg phone)
- かぶる		u-v	to wear, to put on (head)
- かりる	借りる	ru-v	to borrow, to have a loan
- きえる	消える	ru-v	to go out, to vanish
- きく	聞く	u-v	to hear, to listen, to ask
- きる	切る	suf,u-v	to cut, to chop
- きる	着る	ru-v	to wear, to put on (from shoulders down)
- くる	来る	vk	to come
- こまる	困る	u-v	to be worried, to be bothered
- さく	咲く	u-v	to bloom
- さす	差す	u-v	to raise (stretch out) hands, to raise (eg umbrella)
- しまる	閉まる	u-v,vi	to close, to be closed
- しめる	閉める	ru-v,vt	to close, to shut
- しめる	締める	ru-v	to tie, to fasten
- すう	吸う	u-v	to smoke, to breathe in, to suck
- スリッパ		n	slippers
- する		vs-i	to do, to try
- たのむ	頼む	u-v	to request, to ask
- つかれる	疲れる	ru-v	to get tired, to tire
- つく	着く	u-v	to arrive at, to reach
- つくる	作る	u-v	to make, to create
- つける		ru-v,vt	to turn on (eg a light)
- つとめる	勤める	ru-v	to serve, to work (for)
- できる		ru-v	to be able to
- とる	取る	u-v	to take
- とる	撮る	u-v	to take (a photo)
- なく	鳴く	u-v	to sing (bird), to make sound (animal)
- ならう	習う	u-v	to learn
- ならぶ	並ぶ	u-v,vi	to line up, to stand in a line
- ならべる	並べる	ru-v,vt	to line up, to set up
- ぬぐ	脱ぐ	u-v	to take off clothes
- ねる	寝る	ru-v	to go to bed, to sleep
- のる	乗る	u-v	to get on, to ride in, to board
- はいる	入る	u-v	to enter, to contain, to hold
- はる	貼る	u-v	to stick, to paste
- はれる	晴れる	ru-v	to be sunny
- ひく	弾く	u-v	to play (piano, guitar)
- ふく	吹く	u-v	to blow (wind, etc)
- ふる	降る	u-v	to precipitate, to fall (e.g. rain)
- みがく	磨く	u-v	to brush (teeth)
- もつ	持つ	u-v	(1) to hold, to carry, (2) to possess
- よぶ	呼ぶ	u-v	to call out, to invite
- わすれる	忘れる	ru-v	to forget
- わたす	渡す	u-v	to pass over, to hand over
- わたる	渡る	u-v	to cross over, to go across
