Grammar
-------
Need to work on grammar cards

- v + つもり; plan to ~

Misc
----
- 傷つく - ( きずつく) - to be wounded; to get hurt feelings
- https://en.wikiversity.org/wiki/Japanese_numbers


--------

- katsudou
- koteki
- daitai
- mukousei
- gotou
- bunseki
- bakayaro
- todokeru
- oren
- tashikani
- sou kamoshironai
- sonzai
- yogoku
- banashigoto
- massaka
- betobeto
- massakenai (pathetic)
  - massakinai, massakinari, nsassakinai
- otoshita (drop)
- se (fault)
- majide?
- hougen
- tatakai
- tairyoku
- sakusen
- kakue (weapon?)


