[[cards]]
kanji = '明るい'
kana = 'あかるい'
english = 'bright; well-lit'
source = 'irasshai'
level = 'n5'
tags = ['common', 'i-adjective']
highest_frequency = 1005
highest_frequency_source = 'Novels'

[[cards]]
kanji = '明るい'
kana = 'あかるい'
english = 'light; bright; well-lit; cheerful'
level = 'n5'
tags = ['appearance', 'common', 'i-adjective', 'mood']
highest_frequency = 1005
highest_frequency_source = 'Novels'

[[cards]]
kanji = '新しい'
kana = 'あたらしい'
english = 'new'
level = 'n5'
tags = ['common', 'i-adjectives']
highest_frequency = 357
highest_frequency_source = 'Leeds'

[[cards]]
kanji = '熱い'
kana = 'あつい'
english = 'hot (thing); passionate'
level = 'n5'
tags = ['common', 'i-adjectives', 'temperature']
highest_frequency = 879
highest_frequency_source = 'Novels'

[[cards]]
kanji = '危ない'
kana = 'あぶない'
english = 'dangerous; watch out!'
level = 'n5'
tags = ['common', 'expressions', 'i-adjectives']
highest_frequency = 628
highest_frequency_source = 'Anime'

[[cards]]
kanji = '怪しい'
kana = 'あやしい'
english = 'sketchy; suspicious; ominous; dangerous'
level = 'n2'
source = 'wanikani'
tags = ['common', 'i-adjective']
highest_frequency = 1860
highest_frequency_source = 'Anime'

[[cards]]
kanji = '忙しい'
kana = 'いそがしい'
english = 'busy; hectic'
level = 'n5'
tags = ['common', 'i-adjectives']
highest_frequency = 1072
highest_frequency_source = 'Anime'

[[cards]]
kanji = '色々'
kana = 'いろいろ'
english = 'various'
level = 'n5'
tags = ['adverb', 'na-adjective', 'no-adjective', 'noun']
highest_frequency = 731
highest_frequency_source = 'Novels'

[[cards]]
kanji = '煩い'
kana = 'うるさい'
english = 'loud; annoying'
level = 'n5'
tags = ['i-adjective']
highest_frequency = 2309
highest_frequency_source = 'Novels'

[[cards]]
kanji = '多い'
kana = 'おおい'
english = 'many'
level = 'n5'
tags = ['common', 'i-adjectives']
highest_frequency = 77
highest_frequency_source = 'Wikipedia'

[[cards]]
kanji = '大きい'
kana = 'おおきい'
english = 'big'
level = 'n5'
tags = ['common', 'i-adjectives']
highest_frequency = 249
highest_frequency_source = 'Wikipedia'

[[cards]]
kanji = '遅い'
kana = 'おそい'
english = 'slow ; late'
level = 'n5'
tags = ['common', 'i-adjectives']
highest_frequency = 401
highest_frequency_source = 'Anime'

[[cards]]
kanji = '重い'
kana = 'おもい'
english = 'heavy'
level = 'n5'
tags = ['common', 'i-adjective']
highest_frequency = 794
highest_frequency_source = 'Novels'

[[cards]]
kanji = '面白い'
kana = 'おもしろい'
english = 'interesting; amusing'
level = 'n5'
tags = ['common', 'i-adjectives']
highest_frequency = 423
highest_frequency_source = 'Anime'

[[cards]]
kanji = '軽い'
kana = 'かるい'
english = 'light (weight); non-serious'
level = 'n5'
tags = ['common', 'i-adjectives']
highest_frequency = 568
highest_frequency_source = 'Novels'

[[cards]]
kanji = '可愛い'
kana = 'かわいい'
english = 'cute; adorable'
level = 'n5'
tags = ['common', 'i-adjectives']
highest_frequency = 554
highest_frequency_source = 'Anime'

[[cards]]
kanji = '簡単'
kana = 'かんたん'
english = 'simple; easy; uncomplicated'
level = 'n4'
tags = ['common', 'na-adjective', 'noun']
highest_frequency = 464
highest_frequency_source = 'Anime'

[[cards]]
kanji = '汚い'
kana = 'きたない'
english = 'dirty; messy'
level = 'n5'
tags = ['common', 'i-adjectives']
highest_frequency = 1844
highest_frequency_source = 'Anime'

[[cards]]
kanji = '厳しい'
kana = 'きびしい'
english = 'strict, unsparing'
source = 'irasshai'
level = 'n4'
tags = ['common', 'i-adjective']
highest_frequency = 1193
highest_frequency_source = 'Leeds'

[[cards]]
kanji = '綺麗'
kana = 'きれい'
english = 'pretty; clean; tidy'
level = 'n5'
tags = ['common', 'na-adjective']
highest_frequency = 1107
highest_frequency_source = 'Anime'

[[cards]]
kanji = '臭い'
kana = 'くさい'
english = 'stinky; smelly'
level = 'n3'
tags = ['common', 'i-adjectives']
highest_frequency = 1788
highest_frequency_source = 'Anime'

[[cards]]
kanji = '四角い'
kana = 'しかくい'
english = 'square; rectangular'
level = 'n2'
tags = ['common', 'i-adjective']
highest_frequency = 17855
highest_frequency_source = 'Anime'

[[cards]]
kanji = '静か'
kana = 'しずか'
english = 'quiet; peaceful'
level = 'n5'
tags = ['common', 'na-adjectives']
highest_frequency = 607
highest_frequency_source = 'Novels'

[[cards]]
kanji = '上手'
kana = 'じょうず'
english = 'skillful'
level = 'n5'
tags = ['common', 'na-adjective', 'noun']
highest_frequency = 1682
highest_frequency_source = 'Anime'

[[cards]]
kanji = '清々しい'
kana = 'すがすがしい'
english = 'refreshing; brisk'
level = 'n1'
source = 'sekai-wa-fushigi-2'
tags = ['common', 'i-adjectives']
highest_frequency = 17840
highest_frequency_source = 'Anime'

[[cards]]
kanji = '少ない'
kana = 'すくない'
english = 'few; scarce'
level = 'n5'
tags = ['common', 'i-adjective']
highest_frequency = 504
highest_frequency_source = 'Wikipedia'

[[cards]]
kanji = '狭い'
kana = 'せまい'
english = 'narrow; confined; cramped'
level = 'n5'
tags = ['common', 'i-adjectives']
highest_frequency = 1375
highest_frequency_source = 'Novels'

[[cards]]
kanji = '大切'
kana = 'たいせつ'
english = 'important; necessary'
level = 'n5'
tags = ['common', 'na-adjective', 'noun']
highest_frequency = 507
highest_frequency_source = 'Anime'

[[cards]]
kanji = '高い'
kana = 'たかい'
english = 'tall; high; expensive'
level = 'n5'
tags = ['common', 'i-adjective']
highest_frequency = 172
highest_frequency_source = 'Wikipedia'

[[cards]]
kanji = '正しい'
kana = 'ただしい'
english = 'correct; right'
level = 'n4'
tags = ['common', 'i-adjective']
highest_frequency = 1002
highest_frequency_source = 'Leeds'

[[cards]]
kanji = '大丈夫'
kana = 'だいじょうぶ'
english = 'safe; alright; OK; no thanks'
level = 'n5'
tags = ['adverb', 'common', 'na-adjective']
highest_frequency = 74
highest_frequency_source = 'Anime'

[[cards]]
kanji = '大好き'
kana = 'だいすき'
english = 'lovable; like very much'
level = 'n5'
tags = ['common', 'na-adjective']
highest_frequency = 724
highest_frequency_source = 'Anime'

[[cards]]
kanji = '小さい'
kana = 'ちいさい'
english = 'small; little'
level = 'n5'
tags = ['common', 'i-adjectives']
highest_frequency = 470
highest_frequency_source = 'Novels'

[[cards]]
kanji = '近い'
kana = 'ちかい'
english = 'near; close by'
level = 'n5'
tags = ['common', 'i-adjectives']
highest_frequency = 616
highest_frequency_source = 'Novels'

[[cards]]
kanji = '詰らない'
kana = 'つまらない'
english = 'dull; uninteresting; boring; insignificant'
level = 'n5'
tags = ['common', 'i-adjectives']
highest_frequency = 2989
highest_frequency_source = 'Anime'

[[cards]]
kanji = '強い'
kana = 'つよい'
english = 'strong; powerful'
level = 'n5'
tags = ['common', 'i-adjectives']
highest_frequency = 152
highest_frequency_source = 'Anime'

[[cards]]
kanji = '丁寧'
kana = 'ていねい'
english = 'polite; courteous; conscientious'
level = 'n4'
tags = ['common', 'na-adjective', 'noun']
highest_frequency = 3183
highest_frequency_source = 'Leeds'

[[cards]]
kanji = '遠い'
kana = 'とおい'
english = 'far; distant'
level = 'n5'
tags = ['common', 'i-adjectives']
highest_frequency = 620
highest_frequency_source = 'Anime'

[[cards]]
kanji = '長い'
kana = 'ながい'
english = 'long (distance)'
level = 'n5'
tags = ['common', 'i-adjectives']
highest_frequency = 284
highest_frequency_source = 'Novels'

[[cards]]
kanji = '苦い'
kana = 'にがい'
english = 'bitter-tasting'
source = 'wanikani'
level = 'n4'
tags = ['common', 'flavor', 'food', 'i-adjective', 'sense']
highest_frequency = 4185
highest_frequency_source = 'Anime'

[[cards]]
kanji = '賑やか'
kana = 'にぎやか'
english = 'bustling; busy; lively'
level = 'n5'
tags = ['common', 'na-adjective']
highest_frequency = 6815
highest_frequency_source = 'Anime'

[[cards]]
kanji = '人気'
kana = 'にんき'
english = 'popular'
source = 'sekai-wa-fushigi-2'
level = 'n3'
tags = ['common', 'na-adjective', 'no-adjective', 'noun']
highest_frequency = 587
highest_frequency_source = 'Wikipedia'

[[cards]]
kanji = '温い'
kana = 'ぬるい'
english = 'lukewarm'
level = 'n5'
tags = ['common', 'i-adjective']
highest_frequency = 17159
highest_frequency_source = 'Anime'

[[cards]]
kanji = '眠い'
kana = 'ねむい'
english = 'sleepy'
source = 'irasshai'
level = 'n4'
tags = ['common', 'feelings', 'i-adjectives', 'sleep', 'tired']
highest_frequency = 2216
highest_frequency_source = 'Anime'

[[cards]]
kanji = '早い'
kana = 'はやい'
english = 'quick; fast; early (in the day)'
level = 'n5'
tags = ['common', 'i-adjective']
highest_frequency = 102
highest_frequency_source = 'Anime'

[[cards]]
kanji = '馬鹿らしい'
kana = 'ばからしい'
english = 'absurd'
source = 'jisho'
level = 'n2'
tags = ['common', 'i-adjective']
highest_frequency = 36010
highest_frequency_source = 'Anime'

[[cards]]
kanji = '低い'
kana = 'ひくい'
english = 'short (height); low (rank, value)'
level = 'n5'
tags = ['common', 'i-adjectives']
highest_frequency = 751
highest_frequency_source = 'Novels'

[[cards]]
kanji = '広い'
kana = 'ひろい'
english = 'wide; vast; spacious'
level = 'n5'
tags = ['common', 'i-adjectives']
highest_frequency = 703
highest_frequency_source = 'Wikipedia'

[[cards]]
kanji = '古い'
kana = 'ふるい'
english = 'old (things not people); aged; ancient'
level = 'n5'
tags = ['common', 'i-adjectives']
highest_frequency = 1175
highest_frequency_source = 'Novels'

[[cards]]
kanji = '下手'
kana = 'へた'
english = 'unskilled; unskillful'
level = 'n5'
tags = ['common', 'na-adjective', 'noun']
highest_frequency = 1773
highest_frequency_source = 'Anime'

[[cards]]
kanji = '便利'
kana = 'べんり'
english = 'convenient; handy; useful'
level = 'n5'
tags = ['common', 'na-adjective']
highest_frequency = 1798
highest_frequency_source = 'Leeds'

[[cards]]
kanji = '欲しい'
kana = 'ほしい'
english = 'desired; want; wished for; need'
level = 'n5'
tags = ['common', 'i-adjective']
highest_frequency = 343
highest_frequency_source = 'Anime'

[[cards]]
kanji = '丸い'
kana = 'まるい'
english = 'round; circular'
level = 'n5'
tags = ['common', 'i-adjective']
highest_frequency = 1608
highest_frequency_source = 'Novels'

[[cards]]
kanji = '短い'
kana = 'みじかい'
english = 'short (length or distance, not height)'
level = 'n5'
tags = ['common', 'i-adjective']
highest_frequency = 1094
highest_frequency_source = 'Novels'

[[cards]]
kanji = '醜い'
kana = 'みにくい'
english = 'ugly; unattractive'
level = 'n2'
source = 'https://www.japanesepod101.com/japanese-word-lists/'
tags = ['common', 'i-adjectives']
highest_frequency = 3583
highest_frequency_source = 'Anime'

[[cards]]
disabled = true
kanji = '盛りだくさん'
kana = 'もりだくさん'
english = 'varied; all sorts; many'
source = 'sekai-wa-fushigi-2'
tags = ['na-adjective', 'no-adjective', 'noun', 'uncommon']
highest_frequency = 11984
highest_frequency_source = 'Leeds'

[[cards]]
kanji = '易しい'
kana = 'やさしい'
english = 'easy; simple'
level = 'n5'
tags = ['common', 'i-adjective']
highest_frequency = 2187
highest_frequency_source = 'Novels'

[[cards]]
kanji = '安い'
kana = 'やすい'
english = 'cheap; inexpensive'
level = 'n5'
tags = ['common', 'i-adjective']
highest_frequency = 1025
highest_frequency_source = 'Leeds'

[[cards]]
kanji = '有名'
kana = 'ゆうめい'
english = 'famous'
level = 'n5'
tags = ['common', 'na-adjective']
highest_frequency = 667
highest_frequency_source = 'Wikipedia'

[[cards]]
kanji = '弱い'
kana = 'よわい'
english = 'weak; frail'
level = 'n5'
tags = ['common', 'i-adjective']
highest_frequency = 613
highest_frequency_source = 'Anime'

[[cards]]
kanji = '立派'
kana = 'りっぱ'
english = 'splendid; fine; handsome'
level = 'n5'
tags = ['common', 'na-adjective']
highest_frequency = 1234
highest_frequency_source = 'Anime'

[[cards]]
kanji = '悪い'
kana = 'わるい'
english = 'bad; poor; inferior; evil'
level = 'n5'
tags = ['common', 'i-adjective']
highest_frequency = 94
highest_frequency_source = 'Anime'

