[[cards]]
kanji = '明るい'
kana = 'あかるい'
english = 'bright; well-lit'
source = 'irasshai'
level = 'n5'
tags = ['common', 'i-adjective']
frequency_scores = { anime = 2574, leeds = 1980, novels = 1005, wikipedia = 3602 }

[[cards]]
kanji = '明るい'
kana = 'あかるい'
english = 'light; bright; well-lit; cheerful'
level = 'n5'
tags = ['appearance', 'common', 'i-adjective', 'mood']
frequency_scores = { anime = 2574, leeds = 1980, novels = 1005, wikipedia = 3602 }

[[cards]]
kanji = '新しい'
kana = 'あたらしい'
english = 'new'
level = 'n5'
tags = ['common', 'i-adjectives']
frequency_scores = { anime = 496, leeds = 357, novels = 701, wikipedia = 629 }

[[cards]]
kanji = '熱い'
kana = 'あつい'
english = 'hot (thing); passionate'
level = 'n5'
tags = ['common', 'i-adjectives', 'temperature']
frequency_scores = { anime = 1269, leeds = 2406, novels = 879, wikipedia = 9287 }

[[cards]]
kanji = '危ない'
kana = 'あぶない'
english = 'dangerous; watch out!'
level = 'n5'
tags = ['common', 'expressions', 'i-adjectives']
frequency_scores = { anime = 628, leeds = 4753, novels = 2891 }

[[cards]]
kanji = '怪しい'
kana = 'あやしい'
english = 'sketchy; suspicious; ominous; dangerous'
level = 'n2'
source = 'wanikani'
tags = ['common', 'i-adjective']
frequency_scores = { anime = 1860, leeds = 4743, novels = 2762 }

[[cards]]
kanji = '忙しい'
kana = 'いそがしい'
english = 'busy; hectic'
level = 'n5'
tags = ['common', 'i-adjectives']
frequency_scores = { anime = 1072, leeds = 1790, novels = 2838 }

[[cards]]
kanji = '色々'
kana = 'いろいろ'
english = 'various'
level = 'n5'
tags = ['adverb', 'na-adjective', 'no-adjective', 'noun']
frequency_scores = { anime = 883, leeds = 1179, novels = 731, wikipedia = 5604 }

[[cards]]
kanji = '煩い'
kana = 'うるさい'
english = 'loud; annoying'
level = 'n5'
tags = ['i-adjective']
frequency_scores = { anime = 10110, leeds = 5333, novels = 2309 }

[[cards]]
kanji = '多い'
kana = 'おおい'
english = 'many'
level = 'n5'
tags = ['common', 'i-adjectives']
frequency_scores = { anime = 450, leeds = 190, novels = 491, wikipedia = 77 }

[[cards]]
kanji = '大きい'
kana = 'おおきい'
english = 'big'
level = 'n5'
tags = ['common', 'i-adjectives']
frequency_scores = { anime = 438, leeds = 324, novels = 251, wikipedia = 249 }

[[cards]]
kanji = '可笑しい'
kana = 'おかしい'
english = 'funny; strange; weird; suspicious'
source = 'wiktionary'
level = 'n4'
tags = ['common', 'i-adjective']
frequency_scores = { anime = 6849, leeds = 13718, novels = 897 }

[[cards]]
kanji = '遅い'
kana = 'おそい'
english = 'slow ; late'
level = 'n5'
tags = ['common', 'i-adjectives']
frequency_scores = { anime = 401, leeds = 1480, novels = 1081, wikipedia = 3177 }

[[cards]]
kanji = '重い'
kana = 'おもい'
english = 'heavy'
level = 'n5'
tags = ['common', 'i-adjective']
frequency_scores = { anime = 1000, leeds = 1573, novels = 794, wikipedia = 3086 }

[[cards]]
kanji = '面白い'
kana = 'おもしろい'
english = 'interesting; amusing'
level = 'n5'
tags = ['common', 'i-adjectives']
frequency_scores = { anime = 423, leeds = 580, novels = 1161, wikipedia = 6886 }

[[cards]]
kanji = '軽い'
kana = 'かるい'
english = 'light (weight); non-serious'
level = 'n5'
tags = ['common', 'i-adjectives']
frequency_scores = { anime = 1363, leeds = 1725, novels = 568, wikipedia = 4744 }

[[cards]]
kanji = '可愛い'
kana = 'かわいい'
english = 'cute; adorable'
level = 'n5'
tags = ['common', 'i-adjectives']
frequency_scores = { anime = 554, leeds = 2737, novels = 2069 }

[[cards]]
kanji = '簡単'
kana = 'かんたん'
english = 'simple; easy; uncomplicated'
level = 'n4'
tags = ['common', 'na-adjective', 'noun']
frequency_scores = { anime = 464, leeds = 579, novels = 884, wikipedia = 3094 }

[[cards]]
kanji = '汚い'
kana = 'きたない'
english = 'dirty; messy'
level = 'n5'
tags = ['common', 'i-adjectives']
frequency_scores = { anime = 1844, leeds = 5914, novels = 2557 }

[[cards]]
kanji = '厳しい'
kana = 'きびしい'
english = 'strict, unsparing'
source = 'irasshai'
level = 'n4'
tags = ['common', 'i-adjective']
frequency_scores = { anime = 1507, leeds = 1193, novels = 2941, wikipedia = 2213 }

[[cards]]
kanji = '綺麗'
kana = 'きれい'
english = 'pretty; clean; tidy'
level = 'n5'
tags = ['common', 'na-adjective']
frequency_scores = { anime = 1107, leeds = 2756, novels = 2029, wikipedia = 9041 }

[[cards]]
kanji = '臭い'
kana = 'くさい'
english = 'stinky; smelly'
level = 'n3'
tags = ['common', 'i-adjectives']
frequency_scores = { anime = 1788, leeds = 4275, novels = 2887 }

[[cards]]
kanji = '四角い'
kana = 'しかくい'
english = 'square; rectangular'
level = 'n2'
tags = ['common', 'i-adjective']
frequency_scores = { anime = 17855 }

[[cards]]
kanji = '静か'
kana = 'しずか'
english = 'quiet; peaceful'
level = 'n5'
tags = ['common', 'na-adjectives']
frequency_scores = { anime = 922, leeds = 2382, novels = 607, wikipedia = 7273 }

[[cards]]
kanji = '上手'
kana = 'じょうず'
english = 'skillful'
level = 'n5'
tags = ['common', 'na-adjective', 'noun']
frequency_scores = { anime = 1682, leeds = 3101 }

[[cards]]
kanji = '清々しい'
kana = 'すがすがしい'
english = 'refreshing; brisk'
level = 'n1'
source = 'sekai-wa-fushigi-2'
tags = ['common', 'i-adjectives']
frequency_scores = { anime = 17840 }

[[cards]]
kanji = '少ない'
kana = 'すくない'
english = 'few; scarce'
level = 'n5'
tags = ['common', 'i-adjective']
frequency_scores = { anime = 1513, leeds = 520, novels = 1249, wikipedia = 504 }

[[cards]]
kanji = '狭い'
kana = 'せまい'
english = 'narrow; confined; cramped'
level = 'n5'
tags = ['common', 'i-adjectives']
frequency_scores = { anime = 2432, leeds = 2402, novels = 1375, wikipedia = 3168 }

[[cards]]
kanji = '大切'
kana = 'たいせつ'
english = 'important; necessary'
level = 'n5'
tags = ['common', 'na-adjective', 'noun']
frequency_scores = { anime = 507, leeds = 756, novels = 1614, wikipedia = 7201 }

[[cards]]
kanji = '高い'
kana = 'たかい'
english = 'tall; high; expensive'
level = 'n5'
tags = ['common', 'i-adjective']
frequency_scores = { anime = 325, leeds = 267, novels = 330, wikipedia = 172 }

[[cards]]
kanji = '正しい'
kana = 'ただしい'
english = 'correct; right'
level = 'n4'
tags = ['common', 'i-adjective']
frequency_scores = { anime = 1095, leeds = 1002, novels = 1280, wikipedia = 3330 }

[[cards]]
kanji = '大丈夫'
kana = 'だいじょうぶ'
english = 'safe; alright; OK; no thanks'
level = 'n5'
tags = ['adverb', 'common', 'na-adjective']
frequency_scores = { anime = 74, leeds = 1623, novels = 664 }

[[cards]]
kanji = '大好き'
kana = 'だいすき'
english = 'lovable; like very much'
level = 'n5'
tags = ['common', 'na-adjective']
frequency_scores = { anime = 724, leeds = 1584, wikipedia = 9407 }

[[cards]]
kanji = '小さい'
kana = 'ちいさい'
english = 'small; little'
level = 'n5'
tags = ['common', 'i-adjectives']
frequency_scores = { anime = 771, leeds = 1037, novels = 470, wikipedia = 1425 }

[[cards]]
kanji = '近い'
kana = 'ちかい'
english = 'near; close by'
level = 'n5'
tags = ['common', 'i-adjectives']
frequency_scores = { anime = 757, leeds = 847, novels = 616, wikipedia = 757 }

[[cards]]
kanji = '詰らない'
kana = 'つまらない'
english = 'dull; uninteresting; boring; insignificant'
level = 'n5'
tags = ['common', 'i-adjectives']
frequency_scores = { anime = 2989, leeds = 4691 }

[[cards]]
kanji = '強い'
kana = 'つよい'
english = 'strong; powerful'
level = 'n5'
tags = ['common', 'i-adjectives']
frequency_scores = { anime = 152, leeds = 360, novels = 316, wikipedia = 408 }

[[cards]]
kanji = '丁寧'
kana = 'ていねい'
english = 'polite; courteous; conscientious'
level = 'n4'
tags = ['common', 'na-adjective', 'noun']
frequency_scores = { anime = 4310, leeds = 3183 }

[[cards]]
kanji = '遠い'
kana = 'とおい'
english = 'far; distant'
level = 'n5'
tags = ['common', 'i-adjectives']
frequency_scores = { anime = 620, leeds = 1778, novels = 632, wikipedia = 4701 }

[[cards]]
kanji = '長い'
kana = 'ながい'
english = 'long (distance)'
level = 'n5'
tags = ['common', 'i-adjectives']
frequency_scores = { anime = 490, leeds = 519, novels = 284, wikipedia = 437 }

[[cards]]
kanji = '苦い'
kana = 'にがい'
english = 'bitter-tasting'
source = 'wanikani'
level = 'n4'
tags = ['common', 'flavor', 'food', 'i-adjective', 'sense']
frequency_scores = { anime = 4185, leeds = 10763 }

[[cards]]
kanji = '賑やか'
kana = 'にぎやか'
english = 'bustling; busy; lively'
level = 'n5'
tags = ['common', 'na-adjective']
frequency_scores = { anime = 6815, leeds = 12655 }

[[cards]]
kanji = '人気'
kana = 'にんき'
english = 'popular'
source = 'sekai-wa-fushigi-2'
level = 'n3'
tags = ['common', 'na-adjective', 'no-adjective', 'noun']
frequency_scores = { anime = 1349, leeds = 805, wikipedia = 587 }

[[cards]]
kanji = '温い'
kana = 'ぬるい'
english = 'lukewarm'
level = 'n5'
tags = ['common', 'i-adjective']
frequency_scores = { anime = 17159 }

[[cards]]
kanji = '眠い'
kana = 'ねむい'
english = 'sleepy'
source = 'irasshai'
level = 'n4'
tags = ['common', 'feelings', 'i-adjectives', 'sleep', 'tired']
frequency_scores = { anime = 2216, leeds = 4845 }

[[cards]]
kanji = '早い'
kana = 'はやい'
english = 'quick; fast; early (in the day)'
level = 'n5'
tags = ['common', 'i-adjective']
frequency_scores = { anime = 102, leeds = 541, novels = 283, wikipedia = 1912 }

[[cards]]
kanji = '馬鹿らしい'
kana = 'ばからしい'
english = 'absurd'
source = 'jisho'
level = 'n2'
tags = ['common', 'i-adjective']
frequency_scores = { anime = 36010 }

[[cards]]
kanji = '低い'
kana = 'ひくい'
english = 'short (height); low (rank, value)'
level = 'n5'
tags = ['common', 'i-adjectives']
frequency_scores = { anime = 2139, leeds = 1098, novels = 751, wikipedia = 972 }

[[cards]]
kanji = '広い'
kana = 'ひろい'
english = 'wide; vast; spacious'
level = 'n5'
tags = ['common', 'i-adjectives']
frequency_scores = { anime = 1706, leeds = 1146, novels = 939, wikipedia = 703 }

[[cards]]
kanji = '深い'
kana = 'ふかい'
english = 'deep'
source = 'wanikani; wiktionary'
level = 'n4'
tags = ['adjective', 'common', 'i-adjective', 'water']
frequency_scores = { anime = 691, leeds = 919, novels = 437, wikipedia = 1267 }

[[cards]]
kanji = '古い'
kana = 'ふるい'
english = 'old (things not people); aged; ancient'
level = 'n5'
tags = ['common', 'i-adjectives']
frequency_scores = { anime = 1695, leeds = 1362, novels = 1175, wikipedia = 1229 }

[[cards]]
kanji = '下手'
kana = 'へた'
english = 'unskilled; unskillful'
level = 'n5'
tags = ['common', 'na-adjective', 'noun']
frequency_scores = { anime = 1773, leeds = 4170 }

[[cards]]
kanji = '変'
kana = 'へん'
english = 'strange; odd; suspicious'
source = 'irasshai; anime; anime-freq'
level = 'n4'
tags = ['common', 'na-adjective', 'noun']
frequency_scores = { anime = 301, leeds = 1811, novels = 899, wikipedia = 3807 }

[[cards]]
kanji = '便利'
kana = 'べんり'
english = 'convenient; handy; useful'
level = 'n5'
tags = ['common', 'na-adjective']
frequency_scores = { anime = 3153, leeds = 1798, wikipedia = 8237 }

[[cards]]
kanji = '欲しい'
kana = 'ほしい'
english = 'desired; want; wished for; need'
level = 'n5'
tags = ['common', 'i-adjective']
frequency_scores = { anime = 343, leeds = 639, novels = 952, wikipedia = 3663 }

[[cards]]
kanji = '丸い'
kana = 'まるい'
english = 'round; circular'
level = 'n5'
tags = ['common', 'i-adjective']
frequency_scores = { anime = 4528, leeds = 6037, novels = 1608, wikipedia = 6163 }

[[cards]]
kanji = '短い'
kana = 'みじかい'
english = 'short (length or distance, not height)'
level = 'n5'
tags = ['common', 'i-adjective']
frequency_scores = { anime = 2175, leeds = 1820, novels = 1094, wikipedia = 1599 }

[[cards]]
kanji = '醜い'
kana = 'みにくい'
english = 'ugly; unattractive'
level = 'n2'
source = 'https://www.japanesepod101.com/japanese-word-lists/'
tags = ['common', 'i-adjectives']
frequency_scores = { anime = 3583, leeds = 9604 }

[[cards]]
disabled = true
kanji = '盛りだくさん'
kana = 'もりだくさん'
english = 'varied; all sorts; many'
source = 'sekai-wa-fushigi-2'
tags = ['na-adjective', 'no-adjective', 'noun', 'uncommon']
frequency_scores = { anime = 30749, leeds = 11984 }

[[cards]]
kanji = '優しい'
kana = 'やさしい'
english = 'tender; gentle; affectionate'
source = 'anime'
level = 'n4'
explain = 'different than 易しい (easy,plain,simple)'
tags = ['common', 'i-adjective']
frequency_scores = { anime = 429, leeds = 2083, novels = 1439, wikipedia = 6274 }

[[cards]]
kanji = '易しい'
kana = 'やさしい'
english = 'easy; simple'
level = 'n5'
tags = ['common', 'i-adjective']
frequency_scores = { anime = 28519, leeds = 3676, novels = 2187 }

[[cards]]
kanji = '安い'
kana = 'やすい'
english = 'cheap; inexpensive'
level = 'n5'
tags = ['common', 'i-adjective']
frequency_scores = { anime = 2040, leeds = 1025, novels = 1717, wikipedia = 5391 }

[[cards]]
kanji = '有名'
kana = 'ゆうめい'
english = 'famous'
level = 'n5'
tags = ['common', 'na-adjective']
frequency_scores = { anime = 1998, leeds = 1150, novels = 2976, wikipedia = 667 }

[[cards]]
kanji = '弱い'
kana = 'よわい'
english = 'weak; frail'
level = 'n5'
tags = ['common', 'i-adjective']
frequency_scores = { anime = 613, leeds = 1783, novels = 1834, wikipedia = 3406 }

[[cards]]
kanji = '立派'
kana = 'りっぱ'
english = 'splendid; fine; handsome'
level = 'n5'
tags = ['common', 'na-adjective']
frequency_scores = { anime = 1234, leeds = 3090, novels = 1632 }

[[cards]]
kanji = '悪い'
kana = 'わるい'
english = 'bad; poor; inferior; evil'
level = 'n5'
tags = ['common', 'i-adjective']
frequency_scores = { anime = 94, leeds = 370, novels = 235, wikipedia = 1997 }

