[[cards]]
disabled = true
kanji = '何時しか'
kana = 'いつしか'
english = 'unnoticed; unawares'
source = 'manga'
tags = ['adverb', 'uncommon']
frequency_scores = { anime = 36309, leeds = 12106 }

[[cards]]
kanji = '何時でも'
kana = 'いつでも'
english = 'always; whenever'
level = 'n3'
explain = 'http://yesjapan.com/YJ6/question/742/when-do-you-use-soshite-and-sorekara'
tags = ['adverb', 'common']

[[cards]]
kanji = '必ず'
kana = 'かならず'
english = 'always; without exception; without fail'
source = 'nihongo-charenji-n4-kotoba; bonobono-anime'
level = 'n4'
tags = ['adverb', 'common']
frequency_scores = { anime = 439, leeds = 1082, novels = 1352, wikipedia = 3357 }

[[cards]]
kanji = '少し'
kana = 'すこし'
english = 'small quantity; little; few'
level = 'n5'
tags = ['adverb', 'common', 'noun']
frequency_scores = { anime = 193, leeds = 329, novels = 196, wikipedia = 2957 }

[[cards]]
kanji = '全て'
kana = 'すべて'
english = 'everything; completely'
level = 'n3'
tags = ['adverb', 'anime', 'common', 'no-adjective', 'noun']
frequency_scores = { anime = 242, leeds = 691, novels = 1793, wikipedia = 187 }

[[cards]]
kanji = 'たっぷり'
kana = 'たっぷり'
english = 'full; ample'
source = 'food-package'
level = 'n3'
tags = ['adverb', 'common', 'na-adjective', 'no-adjective', 'noun']
frequency_scores = { anime = 2810, leeds = 3713, novels = 2092 }

[[cards]]
kanji = '例えば'
kana = 'たとえば'
english = 'for example'
level = 'n4'
tags = ['adverb', 'common']
frequency_scores = { leeds = 572, novels = 2117, wikipedia = 618 }

[[cards]]
kanji = '多分'
kana = 'たぶん'
english = 'perhaps; probably'
level = 'n5'
tags = ['adverb', 'common']
frequency_scores = { anime = 838, leeds = 1774, novels = 1826 }

[[cards]]
kanji = '段々'
kana = 'だんだん'
english = 'gradually; little by little'
level = 'n5'
tags = ['adverb', 'common']
frequency_scores = { anime = 15419, leeds = 14725, novels = 2517 }

[[cards]]
kanji = '丁度'
kana = 'ちょうど'
english = 'exactly; right'
level = 'n5'
tags = ['adverb', 'common']
frequency_scores = { anime = 7811, leeds = 6444, novels = 908, wikipedia = 5566 }

[[cards]]
kanji = '一寸'
kana = 'ちょっと'
english = 'a little; somewhat; excuse me!'
level = 'n5'
tags = ['adverb', 'common']
frequency_scores = { anime = 16954, leeds = 253, novels = 225 }

[[cards]]
kanji = '特に'
kana = 'とくに'
english = 'particularly; especially'
source = 'nihongo-charenji-n4-kotoba; anime; db super'
level = 'n4'
tags = ['adverb', 'common']
frequency_scores = { anime = 798, leeds = 362, novels = 1354, wikipedia = 242 }

[[cards]]
kanji = '初めて'
kana = 'はじめて'
english = 'for the first time'
level = 'n5'
tags = ['adverb', 'common', 'no-adjective']
frequency_scores = { anime = 293, leeds = 601, novels = 584, wikipedia = 396 }

[[cards]]
kanji = '早く'
kana = 'はやく'
english = 'early; soon'
tags = ['adverb', 'common']
frequency_scores = { anime = 22940, leeds = 8851 }

[[cards]]
kanji = '久しく'
kana = 'ひさしく'
english = 'for a long time'
tags = ['adverb', 'uncommon']

[[cards]]
kanji = '吃驚'
kana = 'びっくり'
english = 'to be surprised; to be amazed; to get startled'
level = 'n3'
tags = ['adverb', 'common', 'suru-verb']
frequency_scores = { anime = 34472, leeds = 2304, novels = 1972 }

[[cards]]
kanji = '殆ど'
kana = 'ほとんど'
english = 'mostly; most (of); almost'
level = 'n4'
source = 'nihongo-charenji-n4-kotoba'
tags = ['adverbial-noun', 'common', 'temporal-noun']
frequency_scores = { anime = 7222, leeds = 3161, novels = 476 }

[[cards]]
kanji = '先ず'
kana = 'まず'
english = 'first of all'
level = 'n3'
source = 'wanikani'
tags = ['adverb', 'common']
frequency_scores = { anime = 8024, leeds = 6822, novels = 653, wikipedia = 1807 }

[[cards]]
kanji = '未だ'
kana = 'まだ'
english = 'not yet; still; besides'
level = 'n5'
tags = ['adverb', 'common']
frequency_scores = { anime = 6761, leeds = 5734, novels = 150, wikipedia = 1381 }

[[cards]]
kanji = '真っ直ぐ'
kana = 'まっすぐ'
english = 'straight ahead; direct'
level = 'n5'
tags = ['adverb', 'common', 'na-adjective', 'noun']
frequency_scores = { anime = 6109, leeds = 12790, novels = 1844 }

[[cards]]
kanji = 'もう'
kana = 'もう'
english = 'already; again'
level = 'n5'
tags = ['adverb', 'common']
frequency_scores = { anime = 36, leeds = 210, novels = 92, wikipedia = 1279 }

[[cards]]
kanji = 'もっと'
kana = 'もっと'
english = 'more; longer; further'
level = 'n5'
tags = ['adverb', 'common']
frequency_scores = { anime = 160, leeds = 433, novels = 338, wikipedia = 4916 }

[[cards]]
kanji = 'ゆっくり'
kana = 'ゆっくり'
english = 'slowly; at ease'
level = 'n5'
tags = ['adverb', 'common', 'noun', 'suru-verb']
frequency_scores = { anime = 909, leeds = 1846, novels = 456, wikipedia = 8825 }

[[cards]]
kanji = '良く'
kana = 'よく'
english = 'well; skillfully; frequently'
level = 'n5'
tags = ['adverb', 'common']
frequency_scores = { anime = 26311, leeds = 630, novels = 336 }

