[[cards]]
disabled = true
kanji = '何時しか'
kana = 'いつしか'
english = 'unnoticed; unawares'
source = 'manga'
tags = ['adverb', 'uncommon']
highest_frequency = 12106
highest_frequency_source = 'Leeds 15k'

[[cards]]
kanji = '何時でも'
kana = 'いつでも'
english = 'always; whenever'
level = 'n3'
explain = 'http://yesjapan.com/YJ6/question/742/when-do-you-use-soshite-and-sorekara'
tags = ['adverb', 'common']

[[cards]]
kanji = '必ず'
kana = 'かならず'
english = 'always; without exception; without fail'
source = 'nihongo-charenji-n4-kotoba; bonobono-anime'
level = 'n4'
tags = ['adverb', 'common']
highest_frequency = 439
highest_frequency_source = 'Anime 45k'

[[cards]]
kanji = '少し'
kana = 'すこし'
english = 'small quantity; little; few'
level = 'n5'
tags = ['adverb', 'common', 'noun']
highest_frequency = 193
highest_frequency_source = 'Anime 45k'

[[cards]]
kanji = '全て'
kana = 'すべて'
english = 'everything; completely'
level = 'n3'
tags = ['adverb', 'anime', 'common', 'no-adjective', 'noun']
highest_frequency = 187
highest_frequency_source = 'Wikipedia 10k'

[[cards]]
kanji = 'たっぷり'
kana = 'たっぷり'
english = 'full; ample'
source = 'food-package'
level = 'n3'
tags = ['adverb', 'common', 'na-adjective', 'no-adjective', 'noun']
highest_frequency = 2092
highest_frequency_source = 'Novel 3k'

[[cards]]
kanji = '例えば'
kana = 'たとえば'
english = 'for example'
level = 'n4'
tags = ['adverb', 'common']
highest_frequency = 572
highest_frequency_source = 'Leeds 15k'

[[cards]]
kanji = '多分'
kana = 'たぶん'
english = 'perhaps; probably'
level = 'n5'
tags = ['adverb', 'common']
highest_frequency = 838
highest_frequency_source = 'Anime 45k'

[[cards]]
kanji = '段々'
kana = 'だんだん'
english = 'gradually; little by little'
level = 'n5'
tags = ['adverb', 'common']
highest_frequency = 2517
highest_frequency_source = 'Novel 3k'

[[cards]]
kanji = '丁度'
kana = 'ちょうど'
english = 'exactly; right'
level = 'n5'
tags = ['adverb', 'common']
highest_frequency = 908
highest_frequency_source = 'Novel 3k'

[[cards]]
kanji = '一寸'
kana = 'ちょっと'
english = 'a little; somewhat; excuse me!'
level = 'n5'
tags = ['adverb', 'common']
highest_frequency = 225
highest_frequency_source = 'Novel 3k'

[[cards]]
kanji = '特に'
kana = 'とくに'
english = 'particularly; especially'
source = 'nihongo-charenji-n4-kotoba; anime; db super'
level = 'n4'
tags = ['adverb', 'common']
highest_frequency = 242
highest_frequency_source = 'Wikipedia 10k'

[[cards]]
kanji = '初めて'
kana = 'はじめて'
english = 'for the first time'
level = 'n5'
tags = ['adverb', 'common', 'no-adjective']
highest_frequency = 293
highest_frequency_source = 'Anime 45k'

[[cards]]
kanji = '早く'
kana = 'はやく'
english = 'early; soon'
tags = ['adverb', 'common']
highest_frequency = 8851
highest_frequency_source = 'Leeds 15k'

[[cards]]
kanji = '久しく'
kana = 'ひさしく'
english = 'for a long time'
tags = ['adverb', 'uncommon']

[[cards]]
kanji = '吃驚'
kana = 'びっくり'
english = 'to be surprised; to be amazed; to get startled'
level = 'n3'
tags = ['adverb', 'common', 'suru-verb']
highest_frequency = 1972
highest_frequency_source = 'Novel 3k'

[[cards]]
kanji = '殆ど'
kana = 'ほとんど'
english = 'mostly; most (of); almost'
level = 'n4'
source = 'nihongo-charenji-n4-kotoba'
tags = ['adverbial-noun', 'common', 'temporal-noun']
highest_frequency = 476
highest_frequency_source = 'Novel 3k'

[[cards]]
kanji = '先ず'
kana = 'まず'
english = 'first of all'
level = 'n3'
source = 'wanikani'
tags = ['adverb', 'common']
highest_frequency = 653
highest_frequency_source = 'Novel 3k'

[[cards]]
kanji = '未だ'
kana = 'まだ'
english = 'not yet; still; besides'
level = 'n5'
tags = ['adverb', 'common']
highest_frequency = 150
highest_frequency_source = 'Novel 3k'

[[cards]]
kanji = '真っ直ぐ'
kana = 'まっすぐ'
english = 'straight ahead; direct'
level = 'n5'
tags = ['adverb', 'common', 'na-adjective', 'noun']
highest_frequency = 1844
highest_frequency_source = 'Novel 3k'

[[cards]]
kanji = 'もう'
kana = 'もう'
english = 'already; again'
level = 'n5'
tags = ['adverb', 'common']
highest_frequency = 36
highest_frequency_source = 'Anime 45k'

[[cards]]
kanji = 'もっと'
kana = 'もっと'
english = 'more; longer; further'
level = 'n5'
tags = ['adverb', 'common']
highest_frequency = 160
highest_frequency_source = 'Anime 45k'

[[cards]]
kanji = 'ゆっくり'
kana = 'ゆっくり'
english = 'slowly; at ease'
level = 'n5'
tags = ['adverb', 'common', 'noun', 'suru-verb']
highest_frequency = 456
highest_frequency_source = 'Novel 3k'

[[cards]]
kanji = '良く'
kana = 'よく'
english = 'well; skillfully; frequently'
level = 'n5'
tags = ['adverb', 'common']
highest_frequency = 336
highest_frequency_source = 'Novel 3k'

