[[cards]]
kanji = '余り'
kana = 'あまり'
english = 'not very; not much'
level = 'n5'
tags = ['adverb', 'common', 'na-adjective', 'no-adjective']
frequency_scores = { anime = 11593, leeds = 3368, novels = 489, wikipedia = 990 }

[[cards]]
kanji = '凄く'
kana = 'すごく'
english = 'awfully; immensely'
explain = 'http://nihonshock.com/2009/11/stop-saying-totemo/'
tags = ['adverb', 'uncommon']

[[cards]]
kanji = '随分'
kana = 'ずいぶん'
english = 'extremely; surprisingly'
source = 'wanikani; anime'
level = 'n3'
tags = ['adverb', 'adverb-taking-to-particle', 'common']
frequency_scores = { anime = 1233, leeds = 3602, novels = 1289 }

[[cards]]
kanji = '大変'
kana = 'たいへん'
english = 'very; terrible'
level = 'n5'
tags = ['adverb', 'common', 'na-adjective', 'noun']
frequency_scores = { anime = 337, leeds = 498, novels = 1179, wikipedia = 4119 }

[[cards]]
kanji = '迚も'
kana = 'とても'
english = 'very ; exceedingly'
level = 'n5'
explain = 'http://nihonshock.com/2009/11/stop-saying-totemo/'
tags = ['adverb', 'common']
frequency_scores = { anime = 518, leeds = 394, novels = 541, wikipedia = 5246 }

[[cards]]
kanji = '非常に'
kana = 'ひじょうに'
english = 'extremely; exceedingly'
level = 'n4'
explain = 'http://nihonshock.com/2009/11/stop-saying-totemo/'
tags = ['adverb', 'common']

[[cards]]
kanji = '酷く'
kana = 'ひどく'
english = 'terribly; awfully; very much'
tags = ['adverb', 'common']
frequency_scores = { anime = 16515 }

