[[cards]]
kanji = '余り'
kana = 'あまり'
english = 'not very; not much'
level = 'n5'
tags = ['adverb', 'common', 'na-adjective', 'no-adjective']
highest_frequency = 489
highest_frequency_source = 'Novels'

[[cards]]
kanji = '凄く'
kana = 'すごく'
english = 'awfully; immensely'
explain = 'http://nihonshock.com/2009/11/stop-saying-totemo/'
tags = ['adverb', 'uncommon']

[[cards]]
kanji = '随分'
kana = 'ずいぶん'
english = 'extremely; surprisingly'
source = 'wanikani; anime'
level = 'n3'
tags = ['adverb', 'adverb-taking-to-particle', 'common']
highest_frequency = 1233
highest_frequency_source = 'Anime'

[[cards]]
kanji = '大変'
kana = 'たいへん'
english = 'very; terrible'
level = 'n5'
tags = ['adverb', 'common', 'na-adjective', 'noun']
highest_frequency = 337
highest_frequency_source = 'Anime'

[[cards]]
kanji = '迚も'
kana = 'とても'
english = 'very ; exceedingly'
level = 'n5'
explain = 'http://nihonshock.com/2009/11/stop-saying-totemo/'
tags = ['adverb', 'common']
highest_frequency = 394
highest_frequency_source = 'Leeds'

[[cards]]
kanji = '非常に'
kana = 'ひじょうに'
english = 'extremely; exceedingly'
level = 'n4'
explain = 'http://nihonshock.com/2009/11/stop-saying-totemo/'
tags = ['adverb', 'common']

[[cards]]
kanji = '酷く'
kana = 'ひどく'
english = 'terribly; awfully; very much'
tags = ['adverb', 'common']
highest_frequency = 16515
highest_frequency_source = 'Anime'

