[[cards]]
kanji = '椅子'
kana = 'いす'
english = 'chair; stool'
level = 'n5'
tags = ['common', 'furniture', 'home']

[[cards]]
kanji = '家具'
kana = 'かぐ'
english = 'furniture'
level = 'n3'
tags = ['common', 'furniture']

[[cards]]
kanji = '寝台'
kana = 'しんだい'
english = 'bed; couch'
level = 'n2'
tags = ['common', 'furniture']

[[cards]]
kanji = '箪笥'
kana = 'たんす'
english = 'dresser; chest'
level = 'n2'
tags = ['common', 'furniture']

[[cards]]
kanji = '本棚'
kana = 'ほんだな'
english = 'bookcase'
level = 'n5'
tags = ['books', 'common', 'furniture', 'noun', 'reading']

[[cards]]
kanji = 'テーブル'
kana = 'テーブル'
english = 'table'
level = 'n5'
tags = ['common', 'gairaigo', 'no-adjective', 'noun']

[[cards]]
kanji = 'ベッド'
kana = 'ベッド'
english = 'bed'
level = 'n5'
tags = ['bedroom', 'common', 'gairaigo', 'noun']

