[[cards]]
kanji = '椅子'
kana = 'いす'
english = 'chair; stool'
level = 'n5'
tags = ['common', 'furniture', 'home']
frequency_scores = { anime = 5691, leeds = 3850, novels = 817, wikipedia = 3999 }

[[cards]]
kanji = '家具'
kana = 'かぐ'
english = 'furniture'
level = 'n3'
tags = ['common', 'furniture']
frequency_scores = { anime = 17418, leeds = 3867, novels = 925, wikipedia = 7130 }

[[cards]]
kanji = '寝台'
kana = 'しんだい'
english = 'bed; couch'
level = 'n2'
tags = ['common', 'furniture']
frequency_scores = { anime = 33291, wikipedia = 7267 }

[[cards]]
kanji = '箪笥'
kana = 'たんす'
english = 'dresser; chest'
level = 'n2'
tags = ['common', 'furniture']
frequency_scores = { anime = 20971 }

[[cards]]
kanji = '本棚'
kana = 'ほんだな'
english = 'bookcase'
level = 'n5'
tags = ['books', 'common', 'furniture', 'noun', 'reading']
frequency_scores = { anime = 12480, leeds = 8427 }

[[cards]]
kanji = 'ソファ'
kana = 'ソファ'
english = 'sofa'
level = 'n3'
tags = ['common', 'furniture', 'gairaigo', 'noun']
frequency_scores = { anime = 23107, leeds = 12082 }

[[cards]]
kanji = 'テーブル'
kana = 'テーブル'
english = 'table'
level = 'n5'
tags = ['common', 'gairaigo', 'no-adjective', 'noun']
frequency_scores = { anime = 6189, leeds = 2366, novels = 787, wikipedia = 4481 }

[[cards]]
kanji = 'ベッド'
kana = 'ベッド'
english = 'bed'
level = 'n5'
tags = ['bedroom', 'common', 'gairaigo', 'noun']
frequency_scores = { anime = 3554, leeds = 2907, novels = 686, wikipedia = 9160 }

