[[cards]]
kanji = '椅子'
kana = 'いす'
english = 'chair; stool'
level = 'n5'
tags = ['common', 'furniture', 'home']
highest_frequency = 817
highest_frequency_source = 'Novel 3k'

[[cards]]
kanji = '家具'
kana = 'かぐ'
english = 'furniture'
level = 'n3'
tags = ['common', 'furniture']
highest_frequency = 925
highest_frequency_source = 'Novel 3k'

[[cards]]
kanji = '寝台'
kana = 'しんだい'
english = 'bed; couch'
level = 'n2'
tags = ['common', 'furniture']
highest_frequency = 7267
highest_frequency_source = 'Wikipedia 10k'

[[cards]]
kanji = '箪笥'
kana = 'たんす'
english = 'dresser; chest'
level = 'n2'
tags = ['common', 'furniture']
highest_frequency = 20971
highest_frequency_source = 'Anime 45k'

[[cards]]
kanji = '本棚'
kana = 'ほんだな'
english = 'bookcase'
level = 'n5'
tags = ['books', 'common', 'furniture', 'noun', 'reading']
highest_frequency = 8427
highest_frequency_source = 'Leeds 15k'

[[cards]]
kanji = 'ソファ'
kana = 'ソファ'
english = 'sofa'
level = 'n3'
tags = ['common', 'furniture', 'gairaigo', 'noun']
highest_frequency = 12082
highest_frequency_source = 'Leeds 15k'

[[cards]]
kanji = 'テーブル'
kana = 'テーブル'
english = 'table'
level = 'n5'
tags = ['common', 'gairaigo', 'no-adjective', 'noun']
highest_frequency = 787
highest_frequency_source = 'Novel 3k'

[[cards]]
kanji = 'ベッド'
kana = 'ベッド'
english = 'bed'
level = 'n5'
tags = ['bedroom', 'common', 'gairaigo', 'noun']
highest_frequency = 686
highest_frequency_source = 'Novel 3k'

