[[cards]]
kanji = '家'
kana = 'いえ'
english = 'house; family; household'
level = 'n5'
tags = ['common', 'family', 'home', 'places']
frequency_scores = { anime = 174, leeds = 200, novels = 127, wikipedia = 772 }

[[cards]]
kanji = '家'
kana = 'うち'
english = "house; home (one's own)"
level = 'n5'
tags = []
frequency_scores = { anime = 174, leeds = 200, novels = 127, wikipedia = 772 }

[[cards]]
kanji = '鏡'
kana = 'かがみ'
english = 'mirror'
level = 'n4'
tags = ['common', 'home', 'noun', 'restroom']
frequency_scores = { anime = 2462, leeds = 3437, novels = 1453, wikipedia = 1854 }

[[cards]]
kanji = '家庭'
kana = 'かてい'
english = 'home; household'
level = 'n5'
tags = []
frequency_scores = { anime = 2954, leeds = 1052, wikipedia = 1546 }

[[cards]]
kanji = '花瓶'
kana = 'かびん'
english = '(flower) vase'
level = 'n5'
tags = []
frequency_scores = { anime = 15569 }

[[cards]]
kanji = '塵'
kana = 'ごみ'
english = 'trash; garbage'
level = 'n3'
tags = ['common', 'noun']
frequency_scores = { anime = 11525, leeds = 6277, wikipedia = 8778 }

[[cards]]
kanji = '石鹸'
kana = 'せっけん'
english = 'soap'
level = 'n5'
tags = []
frequency_scores = { anime = 13707, leeds = 11535 }

[[cards]]
kanji = '掃除'
kana = 'そうじ'
english = 'cleaning; sweeping'
level = 'n5'
tags = []
frequency_scores = { anime = 1135, leeds = 2818, novels = 2642 }

[[cards]]
kanji = '畳'
kana = 'たたみ'
english = 'a type of Japanese mat; straw floor coverings'
level = 'n4'
tags = ['common', 'noun']
frequency_scores = { anime = 10845, leeds = 6670, novels = 1809 }

[[cards]]
kanji = '電球'
kana = 'でんきゅう'
english = 'light bulb'
level = 'n2'
tags = ['common']
frequency_scores = { anime = 16917, leeds = 12721 }

[[cards]]
kanji = '村'
kana = 'むら'
english = 'village'
level = 'n5'
tags = []
frequency_scores = { anime = 602, leeds = 1281, novels = 448, wikipedia = 272 }

[[cards]]
kanji = '冷房'
kana = 'れいぼう'
english = 'air conditioning'
level = 'n4'
source = 'jlptstudy.net'
tags = ['common', 'noun', 'suru-verb']
frequency_scores = { anime = 13737, leeds = 10805, wikipedia = 5005 }

[[cards]]
kanji = 'アパート'
kana = 'アパート'
english = 'apartment'
level = 'n5'
tags = ['buildings', 'common', 'gairaigo', 'home', 'places']
frequency_scores = { anime = 5770, leeds = 3886, wikipedia = 7343 }

[[cards]]
kanji = 'ゴミ箱'
kana = 'ゴミばこ'
english = 'trash can'
source = 'irasshai'
tags = ['common']
frequency_scores = { anime = 12341, leeds = 11741 }

[[cards]]
kanji = 'シャワー'
kana = 'シャワー'
english = 'shower'
level = 'n5'
tags = []
frequency_scores = { anime = 4169, leeds = 5873 }

[[cards]]
kanji = 'シーツ'
kana = 'シーツ'
english = 'sheet; bed sheet'
level = 'n2'
tags = ['common', 'noun']
frequency_scores = { anime = 13957, leeds = 14766 }

[[cards]]
kanji = 'ストーブ'
kana = 'ストーブ'
english = 'room heater; stove'
level = 'n5'
tags = []
frequency_scores = { anime = 16670, leeds = 11787 }

[[cards]]
kanji = 'テレビ'
kana = 'テレビ'
english = 'TV'
level = 'n5'
tags = []
frequency_scores = { anime = 1126, leeds = 555, novels = 1946, wikipedia = 102 }

[[cards]]
kanji = 'トイレ'
kana = 'トイレ'
english = 'toilet; restroom'
level = 'n5'
tags = []
frequency_scores = { anime = 1345, leeds = 2526, novels = 2456, wikipedia = 4311 }

[[cards]]
kanji = 'ドア'
kana = 'ドア'
english = 'Western-style door'
level = 'n5'
tags = []
frequency_scores = { anime = 865, leeds = 1280, novels = 463, wikipedia = 2215 }

[[cards]]
kanji = 'プール'
kana = 'プール'
english = 'pool'
level = 'n5'
tags = []
frequency_scores = { anime = 2199, leeds = 4019, wikipedia = 4727 }

