[[cards]]
kanji = '家'
kana = 'いえ'
english = 'house; family; household'
level = 'n5'
tags = ['common', 'family', 'home', 'places']

[[cards]]
kanji = '家'
kana = 'うち'
english = "house; home (one's own)"
level = 'n5'
tags = []

[[cards]]
kanji = '鏡'
kana = 'かがみ'
english = 'mirror'
level = 'n4'
tags = ['common', 'home', 'noun', 'restroom']

[[cards]]
kanji = '家庭'
kana = 'かてい'
english = 'home; household'
level = 'n5'
tags = []

[[cards]]
kanji = '花瓶'
kana = 'かびん'
english = '(flower) vase'
level = 'n5'
tags = []

[[cards]]
kanji = '塵'
kana = 'ごみ'
english = 'trash; garbage'
level = 'n3'
tags = ['common', 'noun']

[[cards]]
kanji = '石鹸'
kana = 'せっけん'
english = 'soap'
level = 'n5'
tags = []

[[cards]]
kanji = '掃除'
kana = 'そうじ'
english = 'cleaning; sweeping'
level = 'n5'
tags = []

[[cards]]
kanji = '電球'
kana = 'でんきゅう'
english = 'light bulb'
level = 'n2'
tags = ['common']

[[cards]]
kanji = '村'
kana = 'むら'
english = 'village'
level = 'n5'
tags = []

[[cards]]
kanji = '冷房'
kana = 'れいぼう'
english = 'air conditioning'
level = 'n4'
source = 'jlptstudy.net'
tags = ['common', 'noun', 'suru-verb']

[[cards]]
kanji = 'アパート'
kana = 'アパート'
english = 'apartment'
level = 'n5'
tags = ['buildings', 'common', 'gairaigo', 'home', 'places']

[[cards]]
kanji = 'ゴミ箱'
kana = 'ゴミばこ'
english = 'trash can'
source = 'irasshai'
tags = ['common']

[[cards]]
kanji = 'シャワー'
kana = 'シャワー'
english = 'shower'
level = 'n5'
tags = []

[[cards]]
kanji = 'シーツ'
kana = 'シーツ'
english = 'sheet; bed sheet'
level = 'n2'
tags = ['common', 'noun']

[[cards]]
kanji = 'ストーブ'
kana = 'ストーブ'
english = 'room heater; stove'
level = 'n5'
tags = []

[[cards]]
kanji = 'テレビ'
kana = 'テレビ'
english = 'TV'
level = 'n5'
tags = []

[[cards]]
kanji = 'トイレ'
kana = 'トイレ'
english = 'toilet; restroom'
level = 'n5'
tags = []

[[cards]]
kanji = 'ドア'
kana = 'ドア'
english = 'Western-style door'
level = 'n5'
tags = []

[[cards]]
kanji = 'プール'
kana = 'プール'
english = 'pool'
level = 'n5'
tags = []

