[[cards]]
kanji = '嘴'
kana = 'くちばし'
english = 'beak; bill'
source = 'jisho'
level = 'n1'
tags = ['birds', 'common', 'noun']
frequency_scores = { anime = 26989 }

[[cards]]
kanji = '翼'
kana = 'つばさ'
english = 'wing'
source = 'manga'
level = 'n3'
tags = ['birds', 'common', 'noun']
frequency_scores = { anime = 1961, leeds = 6211, novels = 1089, wikipedia = 1889 }

