[[cards]]
kanji = '嘴'
kana = 'くちばし'
english = 'beak; bill'
source = 'jisho'
level = 'n1'
tags = ['birds', 'common', 'noun']
highest_frequency = 26989
highest_frequency_source = 'Anime'

[[cards]]
kanji = '翼'
kana = 'つばさ'
english = 'wing'
source = 'manga'
level = 'n3'
tags = ['birds', 'common', 'noun']
highest_frequency = 1089
highest_frequency_source = 'Novels'

