[[cards]]
kanji = '海老'
kana = 'えび'
english = 'shrimp; lobster'
tags = ['common', 'noun']
frequency_scores = { anime = 19219, leeds = 12508, wikipedia = 5900 }

[[cards]]
kanji = '蛙'
kana = 'かえる'
english = 'frog'
level = 'n5'
tags = ['common', 'noun']
frequency_scores = { anime = 10866, leeds = 9205, novels = 1405, wikipedia = 9602 }

[[cards]]
kanji = '蟹'
kana = 'かに'
english = 'crab'
tags = ['common', 'noun']
frequency_scores = { anime = 11836, leeds = 12760, wikipedia = 8226 }

[[cards]]
kanji = '狸'
kana = 'たぬき'
english = 'tanuki (raccoon dog)'
tags = ['common']
frequency_scores = { anime = 5191 }

[[cards]]
kanji = '動物'
kana = 'どうぶつ'
english = 'animal'
level = 'n5'
tags = []
frequency_scores = { anime = 1272, leeds = 1398, novels = 2062, wikipedia = 790 }

[[cards]]
kanji = '～匹'
kana = '～ひき'
english = 'counter for small animals'
level = 'n5'
tags = []

[[cards]]
kanji = 'ペット'
kana = 'ペット'
english = 'pet'
level = 'n5'
tags = []
frequency_scores = { anime = 3512, leeds = 3721, wikipedia = 5786 }

