[[cards]]
kanji = '海老'
kana = 'えび'
english = 'shrimp; lobster'
tags = ['common', 'noun']
highest_frequency = 5900
highest_frequency_source = 'Wikipedia'

[[cards]]
kanji = '蛙'
kana = 'かえる'
english = 'frog'
level = 'n5'
tags = ['common', 'noun']
highest_frequency = 1405
highest_frequency_source = 'Novels'

[[cards]]
kanji = '蟹'
kana = 'かに'
english = 'crab'
tags = ['common', 'noun']
highest_frequency = 8226
highest_frequency_source = 'Wikipedia'

[[cards]]
kanji = '狸'
kana = 'たぬき'
english = 'tanuki (raccoon dog)'
tags = ['common']
highest_frequency = 5191
highest_frequency_source = 'Anime'

[[cards]]
kanji = '動物'
kana = 'どうぶつ'
english = 'animal'
level = 'n5'
tags = []
highest_frequency = 790
highest_frequency_source = 'Wikipedia'

[[cards]]
kanji = '～匹'
kana = '～ひき'
english = 'counter for small animals'
level = 'n5'
tags = []

[[cards]]
kanji = 'ペット'
kana = 'ペット'
english = 'pet'
level = 'n5'
tags = []
highest_frequency = 3512
highest_frequency_source = 'Anime'

