[[cards]]
kanji = '烏'
kana = 'からす'
english = 'raven; crow'
tags = ['common', 'noun']
frequency_scores = { anime = 949, wikipedia = 5234 }

[[cards]]
kanji = '鳥'
kana = 'とり'
english = 'bird'
level = 'n5'
tags = []
frequency_scores = { anime = 1662, leeds = 2011, novels = 1315, wikipedia = 1788 }

[[cards]]
kanji = '白鳥'
kana = 'はくちょう'
english = 'swan'
source = 'wanikani'
level = 'n4'
tags = ['animal', 'common', 'voice']
frequency_scores = { anime = 3341, leeds = 12809, wikipedia = 7021 }

