[[cards]]
kanji = '烏'
kana = 'からす'
english = 'raven; crow'
tags = ['common', 'noun']
highest_frequency = 949
highest_frequency_source = 'Anime'

[[cards]]
kanji = '鳥'
kana = 'とり'
english = 'bird'
level = 'n5'
tags = []
highest_frequency = 1315
highest_frequency_source = 'Novels'

[[cards]]
kanji = '白鳥'
kana = 'はくちょう'
english = 'swan'
source = 'wanikani'
level = 'n4'
tags = ['animal', 'common', 'voice']
highest_frequency = 3341
highest_frequency_source = 'Anime'

