[[cards]]
kanji = '烏'
kana = 'からす'
english = 'raven; crow'
tags = ['common', 'noun']

[[cards]]
kanji = '鳥'
kana = 'とり'
english = 'bird'
level = 'n5'
tags = []

[[cards]]
kanji = '白鳥'
kana = 'はくちょう'
english = 'swan'
source = 'wanikani'
level = 'n4'
tags = ['animal', 'common', 'voice']

