[[cards]]
kanji = '金魚'
kana = 'きんぎょ'
english = 'goldfish'
level = 'n2'
tags = ['common', 'noun']
highest_frequency = 5544
highest_frequency_source = 'Anime 45k'

[[cards]]
kanji = '鮫'
kana = 'さめ'
english = 'shark'
source = 'wanikani'
tags = ['animals', 'common', 'fish']
highest_frequency = 9922
highest_frequency_source = 'Wikipedia 10k'

[[cards]]
kanji = '鮪'
kana = 'まぐろ'
english = 'tuna'
source = 'sekai-wa-fushigi-2'
tags = ['common', 'fish']
highest_frequency = 33869
highest_frequency_source = 'Anime 45k'

