[[cards]]
kanji = '金魚'
kana = 'きんぎょ'
english = 'goldfish'
level = 'n2'
tags = ['common', 'noun']
frequency_scores = { anime = 5544, leeds = 12892 }

[[cards]]
kanji = '鮫'
kana = 'さめ'
english = 'shark'
source = 'wanikani'
tags = ['animals', 'common', 'fish']
frequency_scores = { anime = 10007, wikipedia = 9922 }

[[cards]]
kanji = '鮪'
kana = 'まぐろ'
english = 'tuna'
source = 'sekai-wa-fushigi-2'
tags = ['common', 'fish']
frequency_scores = { anime = 33869 }

