[[cards]]
kanji = '蟻'
kana = 'あり'
english = 'ant'
tags = ['common', 'insect', 'noun']
frequency_scores = { anime = 12401, leeds = 3761, wikipedia = 5382 }

[[cards]]
kanji = '蜘蛛'
kana = 'くも'
english = 'spider'
tags = ['animals', 'common', 'insects', 'noun']
frequency_scores = { anime = 5775, wikipedia = 7372 }

[[cards]]
kanji = '蜚蠊'
kana = 'ごきぶり'
english = 'cockroach'
tags = ['common', 'insect', 'noun']

[[cards]]
kanji = '蝶'
kana = 'ちょう'
english = 'butterfly'
level = 'n1'
tags = ['animals', 'common', 'noun']
frequency_scores = { anime = 2191, leeds = 9389, novels = 900, wikipedia = 5528 }

[[cards]]
kanji = '蜻蛉'
kana = 'とんぼ'
english = 'dragonfly'
source = 'japan-trip'
tags = ['animals', 'common', 'noun']
frequency_scores = { anime = 24130 }

[[cards]]
kanji = '蜂'
kana = 'はち'
english = 'bee; wasp; hornet'
tags = ['animals', 'common', 'insects', 'noun']
frequency_scores = { anime = 8081, leeds = 12956, wikipedia = 4347 }

[[cards]]
kanji = '蛍'
kana = 'ほたる'
english = 'firefly'
tags = ['common', 'insect', 'noun']
frequency_scores = { anime = 2150 }

[[cards]]
kanji = '蚯蚓'
kana = 'みみず'
english = 'earthworm'
tags = ['insect', 'noun', 'uncommon']
frequency_scores = { anime = 27866 }

[[cards]]
kanji = '虫'
kana = 'むし'
english = 'insect'
level = 'n4'
tags = ['animals', 'common', 'noun']
frequency_scores = { anime = 1262, leeds = 3963, novels = 1898, wikipedia = 3121 }

