[[cards]]
kanji = '蟻'
kana = 'あり'
english = 'ant'
tags = ['common', 'insect', 'noun']
highest_frequency = 3761
highest_frequency_source = 'Leeds 15k'

[[cards]]
kanji = '蜘蛛'
kana = 'くも'
english = 'spider'
tags = ['animals', 'common', 'insects', 'noun']
highest_frequency = 5775
highest_frequency_source = 'Anime 45k'

[[cards]]
kanji = '蜚蠊'
kana = 'ごきぶり'
english = 'cockroach'
tags = ['common', 'insect', 'noun']

[[cards]]
kanji = '蝶'
kana = 'ちょう'
english = 'butterfly'
level = 'n1'
tags = ['animals', 'common', 'noun']
highest_frequency = 900
highest_frequency_source = 'Novel 3k'

[[cards]]
kanji = '蜻蛉'
kana = 'とんぼ'
english = 'dragonfly'
source = 'japan-trip'
tags = ['animals', 'common', 'noun']
highest_frequency = 24130
highest_frequency_source = 'Anime 45k'

[[cards]]
kanji = '蜂'
kana = 'はち'
english = 'bee; wasp; hornet'
tags = ['animals', 'common', 'insects', 'noun']
highest_frequency = 4347
highest_frequency_source = 'Wikipedia 10k'

[[cards]]
kanji = '蛍'
kana = 'ほたる'
english = 'firefly'
tags = ['common', 'insect', 'noun']
highest_frequency = 2150
highest_frequency_source = 'Anime 45k'

[[cards]]
kanji = '蚯蚓'
kana = 'みみず'
english = 'earthworm'
tags = ['insect', 'noun', 'uncommon']
highest_frequency = 27866
highest_frequency_source = 'Anime 45k'

[[cards]]
kanji = '虫'
kana = 'むし'
english = 'insect'
level = 'n4'
tags = ['animals', 'common', 'noun']
highest_frequency = 1262
highest_frequency_source = 'Anime 45k'

