[[cards]]
kanji = '犬'
kana = 'いぬ'
english = 'dog'
level = 'n5'
tags = ['common', 'mammal']
highest_frequency = 566
highest_frequency_source = 'Anime'

[[cards]]
kanji = '牛'
kana = 'うし'
english = 'cow'
level = 'n3'
tags = ['common', 'noun']
highest_frequency = 2170
highest_frequency_source = 'Wikipedia'

[[cards]]
kanji = '馬'
kana = 'うま'
english = 'horse'
source = 'irasshai'
level = 'n3'
tags = ['animal', 'common', 'domesticated', 'mammal', 'noun']
highest_frequency = 286
highest_frequency_source = 'Wikipedia'

[[cards]]
kanji = '狼'
kana = 'おおかみ'
english = 'wolf'
tags = ['common', 'noun']
highest_frequency = 1968
highest_frequency_source = 'Anime'

[[cards]]
kanji = '狐'
kana = 'きつね'
english = 'fox'
tags = ['common', 'noun']
highest_frequency = 2063
highest_frequency_source = 'Anime'

[[cards]]
kanji = '屈狸'
kana = 'くずり'
english = 'wolverine'
source = 'bonobono-anime'
tags = ['animal', 'mammal', 'noun', 'uncommon']

[[cards]]
kanji = '熊'
kana = 'くま'
english = 'bear'
tags = ['common', 'noun']
highest_frequency = 2833
highest_frequency_source = 'Wikipedia'

[[cards]]
kanji = '子犬'
kana = 'こいぬ'
english = 'puppy'
tags = ['common', 'noun']
highest_frequency = 10402
highest_frequency_source = 'Anime'

[[cards]]
kanji = '子牛'
kana = 'こうし'
english = 'calf'
level = 'n2'
tags = ['common', 'noun']

[[cards]]
kanji = '子猫'
kana = 'こねこ'
english = 'kitten'
tags = ['common', 'noun']
highest_frequency = 6293
highest_frequency_source = 'Anime'

[[cards]]
kanji = '猿'
kana = 'さる'
english = 'monkey'
level = 'n3'
tags = ['common', 'mammal', 'noun']
highest_frequency = 1278
highest_frequency_source = 'Novels'

[[cards]]
kanji = '鹿'
kana = 'しか'
english = 'deer'
tags = ['common', 'noun']
highest_frequency = 206
highest_frequency_source = 'Novels'

[[cards]]
kanji = '獅子'
kana = 'しし'
english = 'lion'
tags = ['common', 'mammal', 'noun']
highest_frequency = 6788
highest_frequency_source = 'Wikipedia'

[[cards]]
kanji = '象'
kana = 'ぞう'
english = 'elephant'
level = 'n3'
tags = ['common', 'mammal', 'noun']
highest_frequency = 1713
highest_frequency_source = 'Novels'

[[cards]]
kanji = '虎'
kana = 'とら'
english = 'tiger'
level = 'n3'
tags = ['animal', 'common', 'noun']
highest_frequency = 2301
highest_frequency_source = 'Novels'

[[cards]]
kanji = '猫'
kana = 'ねこ'
english = 'cat'
level = 'n5'
tags = []
highest_frequency = 574
highest_frequency_source = 'Anime'

[[cards]]
kanji = '羊'
kana = 'ひつじ'
english = 'sheep'
source = 'wanikani'
tags = ['animal', 'common', 'noun']
highest_frequency = 3609
highest_frequency_source = 'Anime'

[[cards]]
kanji = '豚'
kana = 'ぶた'
english = 'pig'
tags = ['animals', 'common', 'noun']
highest_frequency = 1924
highest_frequency_source = 'Anime'

[[cards]]
kanji = 'パンダ'
kana = 'パンダ'
english = 'panda'
source = 'anime-freq'
tags = ['animal', 'common', 'mammal', 'noun']
highest_frequency = 577
highest_frequency_source = 'Anime'

