[[cards]]
kanji = '犬'
kana = 'いぬ'
english = 'dog'
level = 'n5'
tags = ['common', 'mammal']
frequency_scores = { anime = 566, leeds = 1214, novels = 892, wikipedia = 1772 }

[[cards]]
kanji = '牛'
kana = 'うし'
english = 'cow'
level = 'n3'
tags = ['common', 'noun']
frequency_scores = { anime = 3218, leeds = 2459, novels = 2819, wikipedia = 2170 }

[[cards]]
kanji = '馬'
kana = 'うま'
english = 'horse'
source = 'irasshai'
level = 'n3'
tags = ['animal', 'common', 'domesticated', 'mammal', 'noun']
frequency_scores = { anime = 1029, leeds = 1656, novels = 517, wikipedia = 286 }

[[cards]]
kanji = '狼'
kana = 'おおかみ'
english = 'wolf'
tags = ['common', 'noun']
frequency_scores = { anime = 1968, leeds = 7678, novels = 2716, wikipedia = 5400 }

[[cards]]
kanji = '狐'
kana = 'きつね'
english = 'fox'
tags = ['common', 'noun']
frequency_scores = { anime = 2063, leeds = 13915, wikipedia = 7735 }

[[cards]]
kanji = '屈狸'
kana = 'くずり'
english = 'wolverine'
source = 'bonobono-anime'
tags = ['animal', 'mammal', 'noun', 'uncommon']

[[cards]]
kanji = '熊'
kana = 'くま'
english = 'bear'
tags = ['common', 'noun']
frequency_scores = { anime = 4068, leeds = 6819, novels = 2860, wikipedia = 2833 }

[[cards]]
kanji = '子犬'
kana = 'こいぬ'
english = 'puppy'
tags = ['common', 'noun']
frequency_scores = { anime = 10402, leeds = 13510 }

[[cards]]
kanji = '子牛'
kana = 'こうし'
english = 'calf'
level = 'n2'
tags = ['common', 'noun']

[[cards]]
kanji = '子猫'
kana = 'こねこ'
english = 'kitten'
tags = ['common', 'noun']
frequency_scores = { anime = 6293 }

[[cards]]
kanji = '猿'
kana = 'さる'
english = 'monkey'
level = 'n3'
tags = ['common', 'mammal', 'noun']
frequency_scores = { anime = 2106, leeds = 6391, novels = 1278, wikipedia = 3464 }

[[cards]]
kanji = '鹿'
kana = 'しか'
english = 'deer'
tags = ['common', 'noun']
frequency_scores = { anime = 3594, leeds = 7448, novels = 206, wikipedia = 3337 }

[[cards]]
kanji = '獅子'
kana = 'しし'
english = 'lion'
tags = ['common', 'mammal', 'noun']
frequency_scores = { anime = 8174, leeds = 13380, wikipedia = 6788 }

[[cards]]
kanji = '象'
kana = 'ぞう'
english = 'elephant'
level = 'n3'
tags = ['common', 'mammal', 'noun']
frequency_scores = { anime = 11332, leeds = 8709, novels = 1713, wikipedia = 4389 }

[[cards]]
kanji = '虎'
kana = 'とら'
english = 'tiger'
level = 'n3'
tags = ['animal', 'common', 'noun']
frequency_scores = { anime = 3418, leeds = 7306, novels = 2301, wikipedia = 2411 }

[[cards]]
kanji = '猫'
kana = 'ねこ'
english = 'cat'
level = 'n5'
tags = []
frequency_scores = { anime = 574, leeds = 1618, novels = 1100, wikipedia = 2461 }

[[cards]]
kanji = '鼠'
kana = 'ねずみ'
english = 'mouse; rat'
source = 'lessons; wiktionary'
level = 'n3'
tags = ['animal', 'common', 'mammal', 'noun']
frequency_scores = { anime = 9132, leeds = 13756, wikipedia = 5811 }

[[cards]]
kanji = '羊'
kana = 'ひつじ'
english = 'sheep'
source = 'wanikani'
tags = ['animal', 'common', 'noun']
frequency_scores = { anime = 3609, leeds = 5637, wikipedia = 6172 }

[[cards]]
kanji = '豚'
kana = 'ぶた'
english = 'pig'
tags = ['animals', 'common', 'noun']
frequency_scores = { anime = 1924, leeds = 4401, wikipedia = 5600 }

[[cards]]
kanji = 'パンダ'
kana = 'パンダ'
english = 'panda'
source = 'anime-freq'
tags = ['animal', 'common', 'mammal', 'noun']
frequency_scores = { anime = 577, leeds = 12204 }

