[[cards]]
kanji = '犬'
kana = 'いぬ'
english = 'dog'
level = 'n5'
tags = ['common', 'mammal']

[[cards]]
kanji = '牛'
kana = 'うし'
english = 'cow'
level = 'n3'
tags = ['common', 'noun']

[[cards]]
kanji = '狼'
kana = 'おおかみ'
english = 'wolf'
tags = ['common', 'noun']

[[cards]]
kanji = '狐'
kana = 'きつね'
english = 'fox'
tags = ['common', 'noun']

[[cards]]
kanji = '屈狸'
kana = 'くずり'
english = 'wolverine'
source = 'bonobono-anime'
tags = ['animal', 'mammal', 'noun', 'uncommon']

[[cards]]
kanji = '熊'
kana = 'くま'
english = 'bear'
tags = ['common', 'noun']

[[cards]]
kanji = '子犬'
kana = 'こいぬ'
english = 'puppy'
tags = ['common', 'noun']

[[cards]]
kanji = '子牛'
kana = 'こうし'
english = 'calf'
level = 'n2'
tags = ['common', 'noun']

[[cards]]
kanji = '子猫'
kana = 'こねこ'
english = 'kitten'
tags = ['common', 'noun']

[[cards]]
kanji = '猿'
kana = 'さる'
english = 'monkey'
level = 'n3'
tags = ['common', 'mammal', 'noun']

[[cards]]
kanji = '鹿'
kana = 'しか'
english = 'deer'
tags = ['common', 'noun']

[[cards]]
kanji = '獅子'
kana = 'しし'
english = 'lion'
tags = ['common', 'mammal', 'noun']

[[cards]]
kanji = '象'
kana = 'ぞう'
english = 'elephant'
level = 'n3'
tags = ['common', 'mammal', 'noun']

[[cards]]
kanji = '虎'
kana = 'とら'
english = 'tiger; drunkard (colloquial)'
level = 'n3'
tags = ['animal', 'common', 'noun']

[[cards]]
kanji = '猫'
kana = 'ねこ'
english = 'cat'
level = 'n5'
tags = []

[[cards]]
kanji = '羊'
kana = 'ひつじ'
english = 'sheep'
source = 'wanikani'
tags = ['animal', 'common', 'noun']

[[cards]]
kanji = '豚'
kana = 'ぶた'
english = 'pig'
tags = ['animals', 'common', 'noun']

