[[cards]]
kanji = '亀'
kana = 'かめ'
english = 'turtle; tortoise'
tags = ['common', 'noun']
frequency_scores = { anime = 3569, leeds = 6887, novels = 2685, wikipedia = 2508 }

[[cards]]
kanji = '蛇'
kana = 'へび'
english = 'snake'
tags = ['animal', 'common', 'noun', 'reptile']
frequency_scores = { anime = 3645, leeds = 8506, novels = 2439, wikipedia = 4690 }

[[cards]]
kanji = '鰐'
kana = 'わに'
english = 'crocodile; alligator'
source = 'wanikani'
tags = ['animals', 'noun', 'uncommon']
frequency_scores = { anime = 13304 }

