[[cards]]
kanji = '亀'
kana = 'かめ'
english = 'turtle; tortoise'
tags = ['common', 'noun']

[[cards]]
kanji = '蛇'
kana = 'へび'
english = 'snake'
tags = ['animal', 'common', 'noun', 'reptile']

[[cards]]
kanji = '鰐'
kana = 'わに'
english = 'crocodile; alligator'
source = 'wanikani'
tags = ['animals', 'noun', 'uncommon']

