[[cards]]
kanji = '亀'
kana = 'かめ'
english = 'turtle; tortoise'
tags = ['common', 'noun']
highest_frequency = 2508
highest_frequency_source = 'Wikipedia 10k'

[[cards]]
kanji = '蛇'
kana = 'へび'
english = 'snake'
tags = ['animal', 'common', 'noun', 'reptile']
highest_frequency = 2439
highest_frequency_source = 'Novel 3k'

[[cards]]
kanji = '鰐'
kana = 'わに'
english = 'crocodile; alligator'
source = 'wanikani'
tags = ['animals', 'noun', 'uncommon']
highest_frequency = 13304
highest_frequency_source = 'Anime 45k'

