[[cards]]
kanji = '打つ'
kana = 'うつ'
english = 'to hit ~; to strike ~'
english-conjugated = { base = 'hit', plural = 'hits', continuous = 'hitting', past = 'had hit' }
verb-type = 'godan-tsu'
transitive = true
source = 'wanikani'
level = 'n4'
tags = ['common']
frequency_scores = { anime = 635, leeds = 1476, novels = 648, wikipedia = 1368 }

[[cards]]
kanji = '決める'
kana = 'きめる'
english = 'to decide ~'
english-conjugated = { plural = 'decides', base = 'decide', continuous = 'decides', past = 'decided' }
verb-type = 'ichidan'
transitive = true
source = 'wanikani'
level = 'n4'
tags = ['common']
frequency_scores = { anime = 278, leeds = 679, novels = 992, wikipedia = 897 }

[[cards]]
kanji = '指す'
kana = 'さす'
english = 'to point'
english-conjugated = { base = 'point', past = 'pointed', plural = 'points', continuous = 'pointing' }
verb-type = 'godan-su'
transitive = true
source = 'wanikani'
level = 'n3'
tags = ['common']
frequency_scores = { anime = 4981, leeds = 3331, novels = 1358, wikipedia = 808 }

[[cards]]
kanji = '近づく'
kana = 'ちかづく'
english = 'to get close to; to approach'
english-conjugated = { base = 'get close', past = 'got close', plural = 'gets close', continuous = 'getting close' }
verb-type = 'godan-ku'
transitive = false
source = 'wanikani'
level = 'n1'
tags = ['common']
frequency_scores = { anime = 898, leeds = 2320, novels = 570 }

[[cards]]
kanji = '投げる'
kana = 'なげる'
english = 'to throw ~'
english-conjugated = { base = 'throw', plural = 'throws', continuous = 'throwing', past = 'threw' }
verb-type = 'ichidan'
transitive = true
source = 'wanikani'
level = 'n4'
tags = ['common']
frequency_scores = { anime = 1663, leeds = 3202, novels = 1360, wikipedia = 2099 }

[[cards]]
kanji = '並べる'
kana = 'ならべる'
english = 'to line up ~; to enumerate ~'
english-conjugated = { plural = 'lines up', base = 'line up', continuous = 'lining up', past = 'lined up' }
verb-type = 'ichidan'
transitive = true
source = 'n4-list'
level = 'n5'
tags = ['common']
frequency_scores = { anime = 3649, leeds = 3390, novels = 2168, wikipedia = 4599 }

[[cards]]
kanji = '逃げる'
kana = 'にげる'
english = 'to escape; to run away'
english-conjugated = { base = 'escape', past = 'escaped', plural = 'escapes', continuous = 'escaping' }
verb-type = 'ichidan'
transitive = false
source = 'wanikani'
level = 'n4'
tags = ['common']
frequency_scores = { anime = 179, leeds = 2539, novels = 533, wikipedia = 2442 }

