[[cards]]
kanji = '打つ'
kana = 'うつ'
english = 'to hit ~; to strike ~'
english-conjugated = { base = 'hit', plural = 'hits', continuous = 'hitting', past = 'had hit' }
verb-type = 'godan-tsu'
transitive = true
source = 'wanikani'
level = 'n4'
tags = ['common']

[[cards]]
kanji = '決める'
kana = 'きめる'
english = 'to decide ~'
english-conjugated = { plural = 'decides', base = 'decide', continuous = 'decides', past = 'decided' }
verb-type = 'ichidan'
transitive = true
source = 'wanikani'
level = 'n4'
tags = ['common']

[[cards]]
kanji = '近づく'
kana = 'ちかづく'
english = 'to get close to; to approach'
english-conjugated = { base = 'get close', past = 'got close', plural = 'gets close', continuous = 'getting close' }
verb-type = 'godan-ku'
transitive = false
source = 'wanikani'
level = 'n1'
tags = ['common']

[[cards]]
kanji = '投げる'
kana = 'なげる'
english = 'to throw ~'
english-conjugated = { base = 'throw', plural = 'throws', continuous = 'throwing', past = 'threw' }
verb-type = 'ichidan'
transitive = true
source = 'wanikani'
level = 'n4'
tags = ['common']

[[cards]]
kanji = '逃げる'
kana = 'にげる'
english = 'to escape; to run away'
english-conjugated = { base = 'escape', past = 'escaped', plural = 'escapes', continuous = 'escaping' }
verb-type = 'ichidan'
transitive = false
source = 'wanikani'
level = 'n4'
tags = ['common']

