[[cards]]
kanji = '打つ'
kana = 'うつ'
english = 'to hit ~; to strike ~'
english-conjugated = { base = 'hit', plural = 'hits', continuous = 'hitting', past = 'had hit' }
verb-type = 'godan-tsu'
transitive = true
source = 'wanikani'
level = 'n4'
tags = ['common']
highest_frequency = 635
highest_frequency_source = 'Anime 45k'

[[cards]]
kanji = '決める'
kana = 'きめる'
english = 'to decide ~'
english-conjugated = { plural = 'decides', base = 'decide', continuous = 'decides', past = 'decided' }
verb-type = 'ichidan'
transitive = true
source = 'wanikani'
level = 'n4'
tags = ['common']
highest_frequency = 278
highest_frequency_source = 'Anime 45k'

[[cards]]
kanji = '指す'
kana = 'さす'
english = 'to point'
english-conjugated = { base = 'point', past = 'pointed', plural = 'points', continuous = 'pointing' }
verb-type = 'godan-su'
transitive = true
source = 'wanikani'
level = 'n3'
tags = ['common']
highest_frequency = 808
highest_frequency_source = 'Wikipedia 10k'

[[cards]]
kanji = '近づく'
kana = 'ちかづく'
english = 'to get close to; to approach'
english-conjugated = { base = 'get close', past = 'got close', plural = 'gets close', continuous = 'getting close' }
verb-type = 'godan-ku'
transitive = false
source = 'wanikani'
level = 'n1'
tags = ['common']
highest_frequency = 570
highest_frequency_source = 'Novel 3k'

[[cards]]
kanji = '投げる'
kana = 'なげる'
english = 'to throw ~'
english-conjugated = { base = 'throw', plural = 'throws', continuous = 'throwing', past = 'threw' }
verb-type = 'ichidan'
transitive = true
source = 'wanikani'
level = 'n4'
tags = ['common']
highest_frequency = 1360
highest_frequency_source = 'Novel 3k'

[[cards]]
kanji = '並べる'
kana = 'ならべる'
english = 'to line up ~; to enumerate ~'
english-conjugated = { plural = 'lines up', base = 'line up', continuous = 'lining up', past = 'lined up' }
verb-type = 'ichidan'
transitive = true
source = 'n4-list'
level = 'n5'
tags = ['common']
highest_frequency = 2168
highest_frequency_source = 'Novel 3k'

[[cards]]
kanji = '逃げる'
kana = 'にげる'
english = 'to escape; to run away'
english-conjugated = { base = 'escape', past = 'escaped', plural = 'escapes', continuous = 'escaping' }
verb-type = 'ichidan'
transitive = false
source = 'wanikani'
level = 'n4'
tags = ['common']
highest_frequency = 179
highest_frequency_source = 'Anime 45k'

