[[cards]]
kanji = '怒る'
kana = 'おこる'
english = 'to get angry'
english-conjugated = { base = 'get angry', past = 'got angry', plural = 'gets angry', continuous = 'getting angry' }
verb-type = 'godan-ru'
transitive = false
level = 'n4'
tags = ['common']
highest_frequency = 381
highest_frequency_source = 'Anime 45k'

[[cards]]
kanji = '泣く'
kana = 'なく'
english = 'to cry'
english-conjugated = { base = 'cry', past = 'cried', plural = 'cries', continuous = 'crying' }
level = 'n4'
verb-type = 'godan-ku'
transitive = false
tags = ['common']
highest_frequency = 326
highest_frequency_source = 'Anime 45k'

[[cards]]
kanji = '悩む'
kana = 'なやむ'
english = 'to be worried'
english-conjugated = { continuous = 'being worried', past = 'was worried', plural = 'are worried', base = 'be worried' }
verb-type = 'godan-mu'
transitive = false
source = 'bonobono-anime'
level = 'n3'
tags = ['common']
highest_frequency = 1640
highest_frequency_source = 'Anime 45k'

[[cards]]
kanji = '喜ぶ'
kana = 'よろこぶ'
english = 'to be delighted'
english-conjugated = { base = 'be delighted', past = 'been delighted', plural = 'are delighted', continuous = 'being delighted' }
verb-type = 'godan-bu'
transitive = false
level = 'n4'
source = 'jlptstudy.net'
tags = ['common']
highest_frequency = 721
highest_frequency_source = 'Anime 45k'

