[[cards]]
kanji = '見える'
kana = 'みえる'
english = 'to be able to see'
english-conjugated = { base = 'be able to see', past = 'was able to see', plural = 'are able to see', continuous = 'being able to see' }
verb-type = 'ichidan'
transitive = false
level = 'n4'
tags = ['common']
highest_frequency = 123
highest_frequency_source = 'Novel 3k'

[[cards]]
kanji = '見せる'
kana = 'みせる'
english = 'to show ~'
english-conjugated = { base = 'show', past = 'showed', plural = 'shows', continuous = 'showing' }
verb-type = 'ichidan'
transitive = true
level = 'n5'
tags = ['common']
highest_frequency = 252
highest_frequency_source = 'Anime 45k'

[[cards]]
kanji = '見る'
kana = 'みる'
english = 'to see ~'
english-conjugated = { base = 'see', past = 'saw', plural = 'sees', continuous = 'seeing' }
verb-type = 'ichidan'
transitive = true
level = 'n5'
tags = ['common']
highest_frequency = 41
highest_frequency_source = 'Anime 45k'

[[cards]]
kanji = '読む'
kana = 'よむ'
english = 'to read'
english-conjugated = { base = 'read', past = 'read', plural = 'reads', continuous = 'reading' }
verb-type = 'godan-mu'
transitive = false
level = 'n5'
tags = ['common']
highest_frequency = 214
highest_frequency_source = 'Leeds 15k'

