[[cards]]
kanji = '見える'
kana = 'みえる'
english = 'to be able to see'
english-conjugated = { base = 'be able to see', past = 'was able to see', plural = 'are able to see', continuous = 'being able to see' }
verb-type = 'ichidan'
transitive = false
level = 'n4'
tags = ['common']
frequency_scores = { anime = 150, leeds = 346, novels = 123, wikipedia = 1191 }

[[cards]]
kanji = '見せる'
kana = 'みせる'
english = 'to show ~'
english-conjugated = { base = 'show', past = 'showed', plural = 'shows', continuous = 'showing' }
verb-type = 'ichidan'
transitive = true
level = 'n5'
tags = ['common']
frequency_scores = { anime = 252, leeds = 892, novels = 289, wikipedia = 880 }

[[cards]]
kanji = '見付ける'
kana = 'みつける'
english = 'to find ~; to discover ~'
english-conjugated = { past = 'found', base = 'find', continuous = 'finding', plural = 'finds' }
verb-type = 'ichidan'
transitive = true
source = 'wanikani; anime; wiktionary'
level = 'n4'
tags = ['common']
frequency_scores = { anime = 17727, leeds = 9413, wikipedia = 3656 }

[[cards]]
kanji = '見る'
kana = 'みる'
english = 'to see ~'
english-conjugated = { base = 'see', past = 'saw', plural = 'sees', continuous = 'seeing' }
verb-type = 'ichidan'
transitive = true
level = 'n5'
tags = ['common']
frequency_scores = { anime = 41, leeds = 98, novels = 45, wikipedia = 101 }

[[cards]]
kanji = '読む'
kana = 'よむ'
english = 'to read'
english-conjugated = { base = 'read', past = 'read', plural = 'reads', continuous = 'reading' }
verb-type = 'godan-mu'
transitive = false
level = 'n5'
tags = ['common']
frequency_scores = { anime = 452, leeds = 214, novels = 601, wikipedia = 967 }

