[[cards]]
kanji = '見える'
kana = 'みえる'
english = 'can see'
english-conjugated = { base = 'can see', past = 'could see', plural = 'can see', continous = 'can see' }
verb-type = 'ichidan'
transitive = false
level = 'n4'
tags = ['common']

[[cards]]
kanji = '見せる'
kana = 'みせる'
english = 'to show ~'
english-conjugated = { base = 'show', past = 'showed', plural = 'shows', continous = 'showing' }
verb-type = 'ichidan'
transitive = true
level = 'n5'
tags = ['common']

[[cards]]
kanji = '見る'
kana = 'みる'
english = 'to see ~'
english-conjugated = { base = 'see', past = 'saw', plural = 'sees', continous = 'seeing' }
verb-type = 'ichidan'
transitive = true
level = 'n5'
tags = ['common']

[[cards]]
kanji = '読む'
kana = 'よむ'
english = 'to read'
english-conjugated = { base = 'read', past = 'read', plural = 'reads', continous = 'reading' }
verb-type = 'godan-mu'
transitive = false
level = 'n5'
tags = ['common']

