[[cards]]
kanji = '思う'
kana = 'おもう'
english = 'to think ~'
english-conjugated = { base = 'think', plural = 'thinks', past = 'thought', continuous = 'thinking' }
verb-type = 'godan-u'
transitive = true
source = 'irasshai'
level = 'n4'
tags = ['common']

[[cards]]
kanji = '知る'
kana = 'しる'
english = 'to know ~; to be aware of ~'
english-conjugated = { plural = 'knows', base = 'know', past = 'knew', continuous = 'knowing' }
verb-type = 'godan-ru'
transitive = true
source = 'n5-study'
level = 'n5'
tags = ['common']

[[cards]]
kanji = '信じる'
kana = 'しんじる'
english = 'to believe in ~'
english-conjugated = { base = 'believe in', past = 'believed in', plural = 'believes in', continuous = 'believing in' }
verb-type = 'ichidan'
transitive = true
source = 'wanikani; anime'
level = 'n3'
tags = ['common']

[[cards]]
kanji = '分かる'
kana = 'わかる'
english = 'to understand'
english-conjugated = { base = 'understand', past = 'understood', plural = 'understands', continous = 'understanding' }
verb-type = 'godan-ru'
transitive = false
level = 'n5'
tags = ['common']

