[[cards]]
kanji = '言う'
kana = 'いう'
english = 'to say (quoting); to call something (its name)'
english-conjugated = { base = 'say', past = 'said', plural = 'says', continuous = 'saying' }
verb-type = 'godan-u'
transitive = false
level = 'n5'
explain = 'https://kawakawalearningstudio.com/all/use-said-japanese/'
tags = ['common']
highest_frequency = 24
highest_frequency_source = 'Anime 45k'

[[cards]]
kanji = '歌う'
kana = 'うたう'
english = 'to sing'
english-conjugated = { base = 'sing', past = 'sang', plural = 'sings', continuous = 'singing' }
verb-type = 'godan-u'
transitive = false
level = 'n5'
tags = ['common', 'transitive-and-intransitive']
highest_frequency = 713
highest_frequency_source = 'Anime 45k'

[[cards]]
kanji = '噛む'
kana = 'かむ'
english = 'to bite ~; to chew ~'
english-conjugated = { base = 'bite', plural = 'bites', past = 'bit', continuous = 'biting' }
verb-type = 'godan-mu'
transitive = true
source = 'n4vocab'
level = 'n4'
tags = ['common']
highest_frequency = 2616
highest_frequency_source = 'Novel 3k'

[[cards]]
kanji = '答える'
kana = 'こたえる'
english = 'to answer'
english-conjugated = { base = 'answer', past = 'answered', plural = 'answers', continuous = 'answering' }
verb-type = 'ichidan'
transitive = false
level = 'n5'
tags = ['common']
highest_frequency = 274
highest_frequency_source = 'Novel 3k'

[[cards]]
kanji = '喋る'
kana = 'しゃべる'
english = 'to talk (chat); to chat; to chatter'
english-conjugated = { base = 'chat', past = 'chatted', plural = 'chats', continuous = 'chatting' }
level = 'n3'
verb-type = 'godan-ru'
transitive = false
explain = 'https://kawakawalearningstudio.com/all/use-said-japanese/'
tags = ['common']
highest_frequency = 1577
highest_frequency_source = 'Anime 45k'

[[cards]]
kanji = '食べる'
kana = 'たべる'
english = 'to eat ~'
english-conjugated = { continuous = 'eating', base = 'eat', plural = 'eats', past = 'ate' }
verb-type = 'ichidan'
transitive = true
source = 'irasshai'
level = 'n5'
tags = ['common']
highest_frequency = 123
highest_frequency_source = 'Anime 45k'

[[cards]]
kanji = '飲む'
kana = 'のむ'
english = 'to drink ~; to swallow ~'
english-conjugated = { base = 'drink', past = 'drank', plural = 'drinks', continuous = 'drinking' }
verb-type = 'godan-mu'
transitive = true
level = 'n5'
tags = ['common']
highest_frequency = 397
highest_frequency_source = 'Anime 45k'

[[cards]]
kanji = '話す'
kana = 'はなす'
english = 'to speak ~; to talk ~'
english-conjugated = { base = 'speak', past = 'spoke', plural = 'speaks', continuous = 'speaking' }
verb-type = 'godan-su'
transitive = true
level = 'n5'
tags = ['common']
highest_frequency = 249
highest_frequency_source = 'Anime 45k'

[[cards]]
kanji = '笑う'
kana = 'わらう'
english = 'to laugh'
english-conjugated = { base = 'laugh', past = 'laughed', continuous = 'laughing', plural = 'laughs' }
verb-type = 'godan-u'
transitive = false
source = 'jlpt-study'
level = 'n4'
tags = ['common']
highest_frequency = 203
highest_frequency_source = 'Novel 3k'

