[[cards]]
kanji = '言う'
kana = 'いう'
english = 'to say (quoting); to call something (its name)'
english-conjugated = { base = 'say', past = 'said', plural = 'says', continuous = 'saying' }
verb-type = 'godan-u'
transitive = false
level = 'n5'
explain = 'https://kawakawalearningstudio.com/all/use-said-japanese/'
tags = ['common']
frequency_scores = { anime = 24, leeds = 72, novels = 37, wikipedia = 31 }

[[cards]]
kanji = '歌う'
kana = 'うたう'
english = 'to sing'
english-conjugated = { base = 'sing', past = 'sang', plural = 'sings', continuous = 'singing' }
verb-type = 'godan-u'
transitive = false
level = 'n5'
tags = ['common', 'transitive-and-intransitive']
frequency_scores = { anime = 713, leeds = 1551, novels = 2818, wikipedia = 1124 }

[[cards]]
kanji = '噛む'
kana = 'かむ'
english = 'to bite ~; to chew ~'
english-conjugated = { base = 'bite', plural = 'bites', past = 'bit', continuous = 'biting' }
verb-type = 'godan-mu'
transitive = true
source = 'n4vocab'
level = 'n4'
tags = ['common']
frequency_scores = { anime = 3159, leeds = 6924, novels = 2616, wikipedia = 5142 }

[[cards]]
kanji = '答える'
kana = 'こたえる'
english = 'to answer'
english-conjugated = { base = 'answer', past = 'answered', plural = 'answers', continuous = 'answering' }
verb-type = 'ichidan'
transitive = false
level = 'n5'
tags = ['common']
frequency_scores = { anime = 936, leeds = 1084, novels = 274, wikipedia = 2947 }

[[cards]]
kanji = '喋る'
kana = 'しゃべる'
english = 'to talk (chat); to chat; to chatter'
english-conjugated = { base = 'chat', past = 'chatted', plural = 'chats', continuous = 'chatting' }
level = 'n3'
verb-type = 'godan-ru'
transitive = false
explain = 'https://kawakawalearningstudio.com/all/use-said-japanese/'
tags = ['common']
frequency_scores = { anime = 1577, leeds = 5205, novels = 2807, wikipedia = 8415 }

[[cards]]
kanji = '食べる'
kana = 'たべる'
english = 'to eat ~'
english-conjugated = { continuous = 'eating', base = 'eat', plural = 'eats', past = 'ate' }
verb-type = 'ichidan'
transitive = true
source = 'irasshai'
level = 'n5'
tags = ['common']
frequency_scores = { anime = 123, leeds = 339, novels = 602, wikipedia = 2085 }

[[cards]]
kanji = '飲む'
kana = 'のむ'
english = 'to drink ~; to swallow ~'
english-conjugated = { base = 'drink', past = 'drank', plural = 'drinks', continuous = 'drinking' }
verb-type = 'godan-mu'
transitive = true
level = 'n5'
tags = ['common']
frequency_scores = { anime = 397, leeds = 628, novels = 531, wikipedia = 3120 }

[[cards]]
kanji = '話す'
kana = 'はなす'
english = 'to speak ~; to talk ~'
english-conjugated = { base = 'speak', past = 'spoke', plural = 'speaks', continuous = 'speaking' }
verb-type = 'godan-su'
transitive = true
level = 'n5'
tags = ['common']
frequency_scores = { anime = 249, leeds = 604, novels = 384, wikipedia = 1908 }

[[cards]]
kanji = '笑う'
kana = 'わらう'
english = 'to laugh'
english-conjugated = { base = 'laugh', past = 'laughed', continuous = 'laughing', plural = 'laughs' }
verb-type = 'godan-u'
transitive = false
source = 'jlpt-study'
level = 'n4'
tags = ['common']
frequency_scores = { anime = 385, leeds = 1408, novels = 203, wikipedia = 2092 }

