[[cards]]
kanji = '通う'
kana = 'かよう'
english = 'to commute'
english-conjugated = { past = 'commuted', base = 'commute', continuous = 'commuting', plural = 'commutes' }
verb-type = 'godan-u'
transitive = false
source = 'wanikani; wiktionary'
level = 'n4'
tags = ['common']
frequency_scores = { anime = 2241, leeds = 3971, wikipedia = 1443 }

