# present-indicative (+): walk, will walk
# present-indicative (-): don't walk, won't walk
# presumptive (+): will probably walk
# presumptive (-): probably won't walk
# volitional : let's walk
# imperative (+): walk!
# imperative (-): don't walk!
# past-indicative (+): walked, have walked
# past-indicative (-): didn't walk, haven't walked
# past-presumptive (+): probably walked
# past-presumptive (-): probably didn't walk
# present-progressive (+): walking
# present-progressive (-): not walking
# past-progressive (+): was walking
# past-progressive (-): wasn't walking
# privisional (+): if one walks
# privisional (-): if one doesn't walk
# potential (+): can walk
# potential (-): can't walk
#masu-stem-kanji = 歩くき
#masu-stem-kana = あるき
#te-form-kanji = 歩いて
#te-form-kana = あるいて

[[verbs]]
english = { base = "walk", past = "walked", plural = "walks", continuous = "walking" }
kanji = "歩く"
kana = "あるく"
group = "godan-ku"
transitive = false
level = "n5"

[[verbs]]
english = { base = "answer", past = "answered", plural = "answers", continous = "answering" }
kanji = "答える"
kana = "こたえる"
group = "ichidan"
transitive = false
level = "n5"

[[verbs]]
english = { base = "climb", past = "climbed", plural = "climbs", continous = "climbing" }
kanji = "上る"
kana = "のぼる"
group = "godan-ru"
transitive = false
level = "n5"

[[verbs]]
english = { base = "run", past = "ran", plural = "runs", continous = "running" }
kanji = "走る"
kana = "はしる"
group = "godan-ru"
transitive = false
level = "n5"

[[verbs]]
english = { base = "play", past = "played", plural = "plays", continous = "playing" }
kanji = "遊ぶ"
kana = "あそぶ"
group = "godan-bu"
transitive = false
level = "n5"

[[verbs]]
english = { base = "swim", past = "swam", plural = "swims", continous = "swimming" }
kanji = "泳ぐ"
kana = "およぐ"
group = "godan-gu"
transitive = false
level = "n5"

[[verbs]]
english = { base = "read", past = "read", plural = "reads", continous = "reading" }
kanji = "読む"
kana = "よむ"
group = "godan-mu"
transitive = true
level = "n5"

[[verbs]]
english = { base = "search", past = "searched", plural = "searches", continous = "searching" }
kanji = "探す"
kana = "さがす"
group = "godan-su"
transitive = true
level = "n4"

[[verbs]]
english = { base = "use", past = "used", plural = "uses", continous = "using" }
kanji = "使う"
kana = "つかう"
group = "godan-u"
transitive = true
level = "n5"

[[verbs]]
english = { base = "shoot", past = "shot", plural = "shoots", continous = "shooting" }
kanji = "撃つ"
kana = "うつ"
group = "godan-tsu"
transitive = true
level = "n3"

