# present-indicative (+): walk, will walk
# present-indicative (-): don't walk, won't walk
# presumptive (+): will probably walk
# presumptive (-): probably won't walk
# volitional : let's walk
# imperative (+): walk!
# imperative (-): don't walk!
# past-indicative (+): walked, have walked
# past-indicative (-): didn't walk, haven't walked
# past-presumptive (+): probably walked
# past-presumptive (-): probably didn't walk
# present-progressive (+): walking
# present-progressive (-): not walking
# past-progressive (+): was walking
# past-progressive (-): wasn't walking
# privisional (+): if one walks
# privisional (-): if one doesn't walk
# potential (+): can walk
# potential (-): can't walk
#masu-stem-kanji = 歩くき
#masu-stem-kana = あるき
#te-form-kanji = 歩いて
#te-form-kana = あるいて

