[[cards]]
kanji = 'お茶'
kana = 'おちゃ'
english = 'tea (usu. green)'
level = 'n5'
tags = []
frequency_scores = { anime = 1167, leeds = 2878, novels = 1833 }

[[cards]]
kanji = '牛乳'
kana = 'ぎゅうにゅう'
english = "(cow's) milk"
level = 'n5'
tags = []
frequency_scores = { anime = 3260, leeds = 5306, wikipedia = 9486 }

[[cards]]
kanji = '紅茶'
kana = 'こうちゃ'
english = 'black tea'
level = 'n5'
tags = []
frequency_scores = { anime = 6128, leeds = 6610 }

[[cards]]
kanji = '飲み物'
kana = 'のみもの'
english = 'drink; beverage'
level = 'n5'
tags = []
frequency_scores = { anime = 3591, leeds = 6818 }

[[cards]]
kanji = '～杯'
kana = '～はい'
english = 'counter for cupfuls'
level = 'n5'
tags = []

[[cards]]
kanji = '水'
kana = 'みず'
english = 'water'
level = 'n5'
tags = []
frequency_scores = { anime = 462, leeds = 437, novels = 287, wikipedia = 294 }

[[cards]]
kanji = '湯'
kana = 'ゆ'
english = 'hot water'
source = 'wiktionary'
level = 'n4'
tags = ['common', 'drinks', 'noun']
frequency_scores = { anime = 4735, leeds = 5090, novels = 2593, wikipedia = 2576 }

[[cards]]
kanji = 'アルコール'
kana = 'アルコール'
english = 'alcohol'
level = 'n4'
source = 'jlptstudy.net'
tags = ['common', 'gairaigo', 'no-adjective', 'noun']
frequency_scores = { anime = 14623, leeds = 4908, wikipedia = 4212 }

[[cards]]
kanji = 'コップ'
kana = 'コップ'
english = 'cup'
level = 'n5'
tags = []
frequency_scores = { anime = 10676, leeds = 9323 }

[[cards]]
kanji = '珈琲'
kana = 'コーヒー'
english = 'coffee'
level = 'n5'
tags = []
frequency_scores = { anime = 27231, leeds = 12732, novels = 2286, wikipedia = 5181 }

[[cards]]
kanji = 'ビール'
kana = 'ビール'
english = 'beer'
level = 'n3'
tags = ['common', 'drink', 'gairaigo', 'noun']
frequency_scores = { anime = 6285, leeds = 2231, wikipedia = 4648 }

[[cards]]
kanji = 'ワイン'
kana = 'ワイン'
english = 'wine'
level = 'n3'
tags = ['common', 'drink', 'gairaigo', 'noun']
frequency_scores = { anime = 8556, leeds = 2223, wikipedia = 3421 }

