[[cards]]
kanji = 'お皿'
kana = 'おさら'
english = 'plate'
level = 'n5'
tags = ['common', 'noun']

[[cards]]
kanji = 'お弁当'
kana = 'おべんとう'
english = 'Japanese boxed lunch'
level = 'n5'
tags = []

[[cards]]
kanji = '皿'
kana = 'さら'
english = 'plate'
level = 'n3'
tags = ['common', 'noun']
highest_frequency = 2564
highest_frequency_source = 'Novels'

[[cards]]
kanji = '茶碗'
kana = 'ちゃわん'
english = 'rice bowl; tea cup'
level = 'n5'
tags = []
highest_frequency = 23485
highest_frequency_source = 'Anime'

[[cards]]
kanji = '箸'
kana = 'はし'
english = 'chopsticks'
level = 'n5'
tags = []
highest_frequency = 1305
highest_frequency_source = 'Leeds'

[[cards]]
kanji = 'スプーン'
kana = 'スプーン'
english = 'spoon'
level = 'n5'
tags = []
highest_frequency = 10400
highest_frequency_source = 'Leeds'

[[cards]]
kanji = 'ナイフ'
kana = 'ナイフ'
english = 'knife'
level = 'n5'
tags = []
highest_frequency = 1562
highest_frequency_source = 'Novels'

[[cards]]
kanji = 'フォーク'
kana = 'フォーク'
english = 'fork'
level = 'n5'
tags = []
highest_frequency = 4159
highest_frequency_source = 'Wikipedia'

