[[cards]]
kanji = '朝ご飯'
kana = 'あさごはん'
english = 'breakfast'
level = 'n5'
tags = ['common', 'food']

[[cards]]
kanji = '喫茶店'
kana = 'きっさてん'
english = 'coffee shop'
level = 'n5'
tags = []
frequency_scores = { anime = 4559, leeds = 6882 }

[[cards]]
kanji = '胡椒'
kana = 'こしょう'
english = 'pepper'
level = 'n2'
tags = ['common', 'food', 'noun']
frequency_scores = { anime = 19577 }

[[cards]]
kanji = 'ご飯'
kana = 'ごはん'
english = 'cooked rice; meal'
level = 'n5'
tags = []
frequency_scores = { anime = 816, leeds = 2712 }

[[cards]]
kanji = '塩'
kana = 'しお'
english = 'salt'
level = 'n5'
tags = []
frequency_scores = { anime = 2873, leeds = 3197, wikipedia = 1721 }

[[cards]]
kanji = '生姜'
kana = 'しょうが'
english = 'ginger'
tags = ['common', 'food', 'noun']
frequency_scores = { anime = 18252, leeds = 4987 }

[[cards]]
kanji = '食堂'
kana = 'しょくどう'
english = 'cafeteria; dining hall'
level = 'n5'
tags = []
frequency_scores = { anime = 5238, leeds = 5046, novels = 2968, wikipedia = 6474 }

[[cards]]
kanji = '食品'
kana = 'しょくひん'
english = 'foodstuffs; food products'
level = 'n3'
source = 'nihongo-charenji-n4-kotoba'
tags = ['common', 'noun']
frequency_scores = { anime = 13128, leeds = 1995, wikipedia = 2066 }

[[cards]]
kanji = '食料品'
kana = 'しょくりょうひん'
english = 'groceries'
source = 'wiktionary'
level = 'n4'
tags = ['common', 'food', 'noun', 'shopping']

[[cards]]
kanji = '蕎麦'
kana = 'そば'
english = 'buckwheat; buckwheat noodles'
level = 'n2'
tags = ['common', 'food']
frequency_scores = { anime = 12451, leeds = 6989, novels = 698 }

[[cards]]
kanji = '堆肥'
kana = 'たいひ'
english = 'compost'
tags = ['common', 'kitchen', 'noun']

[[cards]]
kanji = '食べ物'
kana = 'たべもの'
english = 'food'
level = 'n5'
tags = []
frequency_scores = { anime = 2710, leeds = 3011 }

[[cards]]
kanji = '台所'
kana = 'だいどころ'
english = 'kitchen'
level = 'n5'
tags = []
frequency_scores = { anime = 10217, leeds = 6905, novels = 2463 }

[[cards]]
kanji = '冷たい'
kana = 'つめたい'
english = 'cold (to the touch); coldhearted'
level = 'n5'
tags = []
frequency_scores = { anime = 1469, leeds = 3526, novels = 882 }

[[cards]]
kanji = '生'
kana = 'なま'
english = 'raw; uncooked; fresh'
source = 'sekai-wa-fushigi-2'
level = 'n3'
tags = ['common', 'na-adjective', 'no-adjective', 'noun', 'prefix']
frequency_scores = { anime = 626, leeds = 817, novels = 1000, wikipedia = 189 }

[[cards]]
kanji = '晩御飯'
kana = 'ばんごはん'
english = 'dinner'
level = 'n5'
tags = []

[[cards]]
kanji = '昼御飯'
kana = 'ひるごはん'
english = 'lunch'
source = 'wiktionary'
level = 'n5'
tags = ['food', 'noun', 'uncommon']

[[cards]]
kanji = '昼ご飯'
kana = 'ひるはん'
english = 'lunch'
level = 'n5'
tags = []

[[cards]]
kanji = '八百屋'
kana = 'やおや'
english = 'greengrocer'
level = 'n5'
tags = []
frequency_scores = { anime = 23473 }

[[cards]]
kanji = '夕飯'
kana = 'ゆうはん'
english = 'evening meal (5-7pmish)'
level = 'n5'
tags = []
frequency_scores = { anime = 4265, leeds = 9721 }

[[cards]]
kanji = '料理'
kana = 'りょうり'
english = 'cooking; cuisine'
level = 'n5'
tags = []
frequency_scores = { anime = 508, leeds = 836, novels = 1666, wikipedia = 1462 }

[[cards]]
kanji = '冷蔵庫'
kana = 'れいぞうこ'
english = 'refrigerator'
level = 'n5'
tags = []
frequency_scores = { anime = 4726, leeds = 5381 }

[[cards]]
kanji = 'カップ'
kana = 'カップ'
english = 'cup'
level = 'n5'
tags = []
frequency_scores = { anime = 5011, leeds = 3554, novels = 2336, wikipedia = 1727 }

[[cards]]
kanji = 'カレー'
kana = 'カレー'
english = 'curry'
level = 'n5'
tags = []
frequency_scores = { anime = 1340, leeds = 3195, wikipedia = 7105 }

[[cards]]
kanji = 'スパイス'
kana = 'スパイス'
english = 'spice'
tags = ['common', 'noun', 'suru-verb']
frequency_scores = { anime = 4992, leeds = 12003 }

[[cards]]
kanji = 'バター'
kana = 'バター'
english = 'butter'
level = 'n5'
tags = []
frequency_scores = { anime = 10181, leeds = 8699 }

[[cards]]
kanji = 'パン'
kana = 'パン'
english = 'bread'
level = 'n5'
tags = []
frequency_scores = { anime = 915, leeds = 1830, novels = 1909, wikipedia = 2993 }

[[cards]]
kanji = 'レストラン'
kana = 'レストラン'
english = 'restaurant'
level = 'n5'
tags = []
frequency_scores = { anime = 6864, leeds = 2178, wikipedia = 3660 }

