[[cards]]
kanji = '牛肉'
kana = 'ぎゅうにく'
english = 'beef'
level = 'n5'
tags = []
highest_frequency = 5755
highest_frequency_source = 'Leeds'

[[cards]]
kanji = '魚'
kana = 'さかな'
english = 'fish'
level = 'n5'
tags = []
highest_frequency = 1381
highest_frequency_source = 'Anime'

[[cards]]
kanji = '卵'
kana = 'たまご'
english = 'egg'
level = 'n5'
tags = []
highest_frequency = 1761
highest_frequency_source = 'Anime'

[[cards]]
kanji = '鳥肉'
kana = 'とりにく'
english = 'chicken meat; bird meat'
level = 'n5'
tags = []

[[cards]]
kanji = '肉'
kana = 'にく'
english = 'meat'
level = 'n5'
tags = []
highest_frequency = 395
highest_frequency_source = 'Novels'

[[cards]]
kanji = '豚肉'
kana = 'ぶたにく'
english = 'pork'
level = 'n5'
tags = []
highest_frequency = 10890
highest_frequency_source = 'Leeds'

