[[cards]]
kanji = '牛肉'
kana = 'ぎゅうにく'
english = 'beef'
level = 'n5'
tags = []
frequency_scores = { anime = 11050, leeds = 5755 }

[[cards]]
kanji = '魚'
kana = 'さかな'
english = 'fish'
level = 'n5'
tags = []
frequency_scores = { anime = 1381, leeds = 1972, novels = 1727, wikipedia = 2019 }

[[cards]]
kanji = '卵'
kana = 'たまご'
english = 'egg'
level = 'n5'
tags = []
frequency_scores = { anime = 1761, leeds = 3339, wikipedia = 2621 }

[[cards]]
kanji = '鳥肉'
kana = 'とりにく'
english = 'chicken meat; bird meat'
level = 'n5'
tags = []

[[cards]]
kanji = '肉'
kana = 'にく'
english = 'meat'
level = 'n5'
tags = []
frequency_scores = { anime = 660, leeds = 2061, novels = 395, wikipedia = 3203 }

[[cards]]
kanji = '豚肉'
kana = 'ぶたにく'
english = 'pork'
level = 'n5'
tags = []
frequency_scores = { anime = 15661, leeds = 10890 }

