[[cards]]
kanji = '飴'
kana = 'あめ'
english = 'hard candy; toffee'
level = 'n5'
tags = ['common', 'food']
frequency_scores = { anime = 5808, leeds = 13115 }

[[cards]]
kanji = 'お菓子'
kana = 'おかし'
english = 'candy; confections'
level = 'n5'
tags = []
frequency_scores = { anime = 1743, leeds = 4366 }

[[cards]]
kanji = '砂糖'
kana = 'さとう'
english = 'sugar'
level = 'n5'
tags = []
frequency_scores = { anime = 5141, leeds = 5487, wikipedia = 5155 }

[[cards]]
kanji = 'チョコ'
kana = 'チョコ'
english = 'chocolate (shortened)'
tags = ['candy', 'common', 'noun', 'sweets']
frequency_scores = { anime = 1524, leeds = 5339 }

[[cards]]
kanji = 'チョコレート'
kana = 'チョコレート'
english = 'chocolate'
tags = ['candy', 'common', 'noun', 'sweets']
frequency_scores = { anime = 6232, leeds = 4698, wikipedia = 8840 }

