[[cards]]
kanji = '飴'
kana = 'あめ'
english = 'hard candy; toffee'
level = 'n5'
tags = ['common', 'food']
highest_frequency = 5808
highest_frequency_source = 'Anime 45k'

[[cards]]
kanji = 'お菓子'
kana = 'おかし'
english = 'candy; confections'
level = 'n5'
tags = []
highest_frequency = 1743
highest_frequency_source = 'Anime 45k'

[[cards]]
kanji = '砂糖'
kana = 'さとう'
english = 'sugar'
level = 'n5'
tags = []
highest_frequency = 5141
highest_frequency_source = 'Anime 45k'

[[cards]]
kanji = 'チョコ'
kana = 'チョコ'
english = 'chocolate (shortened)'
tags = ['candy', 'common', 'noun', 'sweets']
highest_frequency = 1524
highest_frequency_source = 'Anime 45k'

[[cards]]
kanji = 'チョコレート'
kana = 'チョコレート'
english = 'chocolate'
tags = ['candy', 'common', 'noun', 'sweets']
highest_frequency = 4698
highest_frequency_source = 'Leeds 15k'

