[[cards]]
kanji = '飴'
kana = 'あめ'
english = 'hard candy; toffee'
level = 'n5'
tags = ['common', 'food']

[[cards]]
kanji = 'お菓子'
kana = 'おかし'
english = 'candy; confections'
level = 'n5'
tags = []

[[cards]]
kanji = '砂糖'
kana = 'さとう'
english = 'sugar'
level = 'n5'
tags = []

[[cards]]
kanji = 'チョコ'
kana = 'チョコ'
english = 'chocolate (shortened)'
tags = ['candy', 'common', 'noun', 'sweets']

[[cards]]
kanji = 'チョコレート'
kana = 'チョコレート'
english = 'chocolate'
tags = ['candy', 'common', 'noun', 'sweets']

