[[cards]]
kanji = '味'
kana = 'あじ'
english = 'flavor; taste'
level = 'n4'
source = 'jlptstudy.net'
tags = ['common', 'noun']

[[cards]]
kanji = '甘い'
kana = 'あまい'
english = 'sweet-tasting'
level = 'n5'
tags = ['common', 'food', 'i-adjectives']

[[cards]]
kanji = '薄い'
kana = 'うすい'
english = 'thin; weak (eg. taste)'
level = 'n5'
tags = ['common', 'i-adjective']

[[cards]]
kanji = '美味しい'
kana = 'おいしい'
english = 'delicious'
level = 'n5'
tags = ['common', 'i-adjective']

[[cards]]
kanji = '辛い'
kana = 'からい'
english = 'spicy; hot; salty'
level = 'n5'
tags = ['common', 'i-adjectives']

[[cards]]
kanji = '酸っぱい'
kana = 'すっぱい'
english = 'sour; acid'
source = 'jisho'
level = 'n2'
tags = ['common', 'food', 'i-adjective', 'taste']

[[cards]]
kanji = '苦い'
kana = 'にがい'
english = 'bitter'
source = 'wanikani'
level = 'n4'
tags = ['common', 'food', 'i-adjective', 'taste']

[[cards]]
kanji = '不味い'
kana = 'まずい'
english = 'unappetising; unpleasant taste'
level = 'n5'
tags = ['common', 'food', 'i-adjective', 'taste']

