[[cards]]
kanji = '味'
kana = 'あじ'
english = 'flavor; taste'
level = 'n4'
source = 'jlptstudy.net'
tags = ['common', 'noun']
frequency_scores = { anime = 703, leeds = 1205, novels = 1488, wikipedia = 3331 }

[[cards]]
kanji = '甘い'
kana = 'あまい'
english = 'sweet-tasting'
level = 'n5'
tags = ['common', 'food', 'i-adjectives']
frequency_scores = { anime = 504, leeds = 1951, novels = 1252, wikipedia = 6637 }

[[cards]]
kanji = '薄い'
kana = 'うすい'
english = 'thin; weak (eg. taste)'
level = 'n5'
tags = ['common', 'i-adjective']
frequency_scores = { anime = 2809, leeds = 2790, novels = 1420, wikipedia = 3603 }

[[cards]]
kanji = '美味しい'
kana = 'おいしい'
english = 'delicious'
level = 'n5'
tags = ['common', 'i-adjective']
frequency_scores = { anime = 1007, leeds = 1634, novels = 2591 }

[[cards]]
kanji = '辛い'
kana = 'からい'
english = 'spicy; hot; salty'
level = 'n5'
tags = ['common', 'i-adjectives']
frequency_scores = { anime = 1319, leeds = 2415, wikipedia = 7626 }

[[cards]]
kanji = '酸っぱい'
kana = 'すっぱい'
english = 'sour; acid'
source = 'jisho'
level = 'n2'
tags = ['common', 'food', 'i-adjective', 'taste']
frequency_scores = { anime = 10741 }

[[cards]]
kanji = '苦い'
kana = 'にがい'
english = 'bitter'
source = 'wanikani'
level = 'n4'
tags = ['common', 'food', 'i-adjective', 'taste']
frequency_scores = { anime = 4185, leeds = 10763 }

[[cards]]
kanji = '不味い'
kana = 'まずい'
english = 'unappetising; unpleasant taste'
level = 'n5'
tags = ['common', 'food', 'i-adjective', 'taste']
frequency_scores = { anime = 7118, leeds = 4489, novels = 2220 }

