[[cards]]
kanji = '味'
kana = 'あじ'
english = 'flavor; taste'
level = 'n4'
source = 'jlptstudy.net'
tags = ['common', 'noun']
highest_frequency = 703
highest_frequency_source = 'Anime'

[[cards]]
kanji = '甘い'
kana = 'あまい'
english = 'sweet-tasting'
level = 'n5'
tags = ['common', 'food', 'i-adjectives']
highest_frequency = 504
highest_frequency_source = 'Anime'

[[cards]]
kanji = '薄い'
kana = 'うすい'
english = 'thin; weak (eg. taste)'
level = 'n5'
tags = ['common', 'i-adjective']
highest_frequency = 1420
highest_frequency_source = 'Novels'

[[cards]]
kanji = '美味しい'
kana = 'おいしい'
english = 'delicious'
level = 'n5'
tags = ['common', 'i-adjective']
highest_frequency = 1007
highest_frequency_source = 'Anime'

[[cards]]
kanji = '辛い'
kana = 'からい'
english = 'spicy; hot; salty'
level = 'n5'
tags = ['common', 'i-adjectives']
highest_frequency = 1319
highest_frequency_source = 'Anime'

[[cards]]
kanji = '酸っぱい'
kana = 'すっぱい'
english = 'sour; acid'
source = 'jisho'
level = 'n2'
tags = ['common', 'food', 'i-adjective', 'taste']
highest_frequency = 10741
highest_frequency_source = 'Anime'

[[cards]]
kanji = '苦い'
kana = 'にがい'
english = 'bitter'
source = 'wanikani'
level = 'n4'
tags = ['common', 'food', 'i-adjective', 'taste']
highest_frequency = 4185
highest_frequency_source = 'Anime'

[[cards]]
kanji = '不味い'
kana = 'まずい'
english = 'unappetising; unpleasant taste'
level = 'n5'
tags = ['common', 'food', 'i-adjective', 'taste']
highest_frequency = 2220
highest_frequency_source = 'Novels'

