[[cards]]
kanji = 'じゃが芋'
kana = 'じゃがいも'
english = 'potato'
tags = ['common', 'food', 'healthy', 'noun', 'vegetable']
frequency_scores = { anime = 38995 }

[[cards]]
kanji = '玉ねぎ'
kana = 'たまねぎ'
english = 'onion'
source = 'wanikani'
tags = ['common', 'food', 'noun', 'vegetable']
frequency_scores = { anime = 13106 }

[[cards]]
kanji = '茄子'
kana = 'なす'
english = 'eggplant'
source = 'wanikani'
tags = ['common', 'food', 'noun', 'vegetable']
frequency_scores = { anime = 29259, leeds = 1360, novels = 1277 }

[[cards]]
kanji = '人参'
kana = 'にんじん'
english = 'carrot'
tags = ['common', 'food', 'healthy', 'noun', 'vegetable']
frequency_scores = { anime = 15776, leeds = 14442 }

[[cards]]
kanji = '野菜'
kana = 'やさい'
english = 'vegetable'
level = 'n5'
tags = ['common', 'food', 'no-adjective', 'noun', 'vegetable']
frequency_scores = { anime = 2871, leeds = 2086, wikipedia = 5815 }

