[[cards]]
kanji = 'じゃが芋'
kana = 'じゃがいも'
english = 'potato'
tags = ['common', 'food', 'healthy', 'noun', 'vegetable']
highest_frequency = 38995
highest_frequency_source = 'Anime 45k'

[[cards]]
kanji = '玉ねぎ'
kana = 'たまねぎ'
english = 'onion'
source = 'wanikani'
tags = ['common', 'food', 'noun', 'vegetable']
highest_frequency = 13106
highest_frequency_source = 'Anime 45k'

[[cards]]
kanji = '茄子'
kana = 'なす'
english = 'eggplant'
source = 'wanikani'
tags = ['common', 'food', 'noun', 'vegetable']
highest_frequency = 1277
highest_frequency_source = 'Novel 3k'

[[cards]]
kanji = '人参'
kana = 'にんじん'
english = 'carrot'
tags = ['common', 'food', 'healthy', 'noun', 'vegetable']
highest_frequency = 14442
highest_frequency_source = 'Leeds 15k'

[[cards]]
kanji = '野菜'
kana = 'やさい'
english = 'vegetable'
level = 'n5'
tags = ['common', 'food', 'no-adjective', 'noun', 'vegetable']
highest_frequency = 2086
highest_frequency_source = 'Leeds 15k'

