[[cards]]
type = 'grammar'
kanji = 'だい'
kana = 'だい'
question = '〜{}？'
english = 'grammar: familiar language, marks wh-question (what, where, who)'
source = 'grammar-dict-basic'
tags = ['common', 'particle']
frequency_scores = { anime = 858, leeds = 4945, novels = 589 }

[[cards]]
type = 'grammar'
kanji = '許り'
kana = 'ばかり'
question = 'noun+{}'
english = 'grammar: only (noun) (todo: this is used for many constructions)'
source = 'grammar-dict-basic'
tags = ['common', 'particle']
frequency_scores = { leeds = 479, novels = 194, wikipedia = 2187 }

