[[cards]]
kanji = '余り'
kana = 'あまり'
english = 'not very; not much'
level = 'n5'
tags = ['common', 'no-adjective', 'na-adjective', 'adverb']

[[cards]]
disabled = true
kanji = '何時しか'
kana = 'いつしか'
english = 'unnoticed; unawares'
source = 'manga'
tags = ['uncommon', 'adverb']

[[cards]]
kanji = '少し'
kana = 'すこし'
english = 'small quantity; little; few'
level = 'n5'
tags = ['common', 'adverb', 'noun']

[[cards]]
kanji = '大変'
kana = 'たいへん'
english = 'very; terrible'
level = 'n5'
tags = ['common', 'adverb', 'na-adjective', 'noun']

[[cards]]
kanji = '多分'
kana = 'たぶん'
english = 'perhaps; probably'
level = 'n5'
tags = ['common', 'adverb']

[[cards]]
kanji = '段々'
kana = 'だんだん'
english = 'gradually; little by little'
level = 'n5'
tags = ['common', 'adverb']

[[cards]]
kanji = '丁度'
kana = 'ちょうど'
english = 'exactly; right'
level = 'n5'
tags = ['common', 'adverb']

[[cards]]
kanji = '一寸'
kana = 'ちょっと'
english = 'a little; somewhat; excuse me!'
level = 'n5'
tags = ['common', 'adverb']

[[cards]]
kanji = '迚も'
kana = 'とても'
english = 'very ; exceedingly'
level = 'n5'
tags = ['common', 'adverb']

[[cards]]
kanji = '初めて'
kana = 'はじめて'
english = 'for the first time'
level = 'n5'
tags = ['common', 'adverb', 'no-adjective']

[[cards]]
kanji = '早く'
kana = 'はやく'
english = 'early; soon'
tags = ['common', 'adverb']

[[cards]]
kanji = '吃驚'
kana = 'びっくり'
english = 'to be surprised; to be amazed; to get startled'
level = 'n3'
tags = ['common', 'suru-verb', 'adverb']

[[cards]]
kanji = '未だ'
kana = 'まだ'
english = 'not yet; still; besides'
level = 'n5'
tags = ['common', 'adverb']

[[cards]]
kanji = '真っ直ぐ'
kana = 'まっすぐ'
english = 'straight ahead; direct'
level = 'n5'
tags = ['common', 'na-adjective', 'adverb', 'noun']

[[cards]]
kanji = 'もう'
kana = 'もう'
english = 'already; again'
level = 'n5'
tags = ['common', 'adverb']

[[cards]]
kanji = 'もっと'
kana = 'もっと'
english = 'more; longer; further'
level = 'n5'
tags = ['common', 'adverb']

[[cards]]
kanji = 'ゆっくり'
kana = 'ゆっくり'
english = 'slowly; at ease'
level = 'n5'
tags = ['common', 'adverb', 'noun', 'suru-verb']

[[cards]]
kanji = '良く'
kana = 'よく'
english = 'well; skillfully; frequently'
level = 'n5'
tags = ['common', 'adverb']

