[[cards]]
kanji = '余り'
kana = 'あまり'
english = 'not very; not much'
level = 'n5'
tags = ['adverb', 'common', 'na-adjective', 'no-adjective']

[[cards]]
disabled = true
kanji = '何時しか'
kana = 'いつしか'
english = 'unnoticed; unawares'
source = 'manga'
tags = ['adverb', 'uncommon']

[[cards]]
kanji = '何時でも'
kana = 'いつでも'
english = 'always; whenever'
level = 'n3'
explain = 'http://yesjapan.com/YJ6/question/742/when-do-you-use-soshite-and-sorekara'
tags = ['adverb', 'common']

[[cards]]
kanji = '必ず'
kana = 'かならず'
english = 'be sure to; always/necessarily; without fail'
source = 'nihongo-charenji-n4-kotoba'
level = 'n4'
tags = ['adverb', 'common']

[[cards]]
kanji = '少し'
kana = 'すこし'
english = 'small quantity; little; few'
level = 'n5'
tags = ['adverb', 'common', 'noun']

[[cards]]
kanji = '全て'
kana = 'すべて'
english = 'completely'
level = 'n3'
tags = ['adverb', 'anime', 'common', 'no-adjective', 'noun']

[[cards]]
kanji = '大変'
kana = 'たいへん'
english = 'very; terrible'
level = 'n5'
tags = ['adverb', 'common', 'na-adjective', 'noun']

[[cards]]
kanji = 'たっぷり'
kana = 'たっぷり'
english = 'full; ample'
source = 'food-package'
level = 'n3'
tags = ['adverb', 'common', 'na-adjective', 'no-adjective', 'noun']

[[cards]]
kanji = '例えば'
kana = 'たとえば'
english = 'for example'
level = 'n4'
tags = ['adverb', 'common']

[[cards]]
kanji = '多分'
kana = 'たぶん'
english = 'perhaps; probably'
level = 'n5'
tags = ['adverb', 'common']

[[cards]]
kanji = '段々'
kana = 'だんだん'
english = 'gradually; little by little'
level = 'n5'
tags = ['adverb', 'common']

[[cards]]
kanji = '丁度'
kana = 'ちょうど'
english = 'exactly; right'
level = 'n5'
tags = ['adverb', 'common']

[[cards]]
kanji = '一寸'
kana = 'ちょっと'
english = 'a little; somewhat; excuse me!'
level = 'n5'
tags = ['adverb', 'common']

[[cards]]
kanji = '特に'
kana = 'とくに'
english = 'particularly; especially'
source = 'nihongo-charenji-n4-kotoba'
level = 'n4'
tags = ['adverb', 'common']

[[cards]]
kanji = '迚も'
kana = 'とても'
english = 'very ; exceedingly'
level = 'n5'
tags = ['adverb', 'common']

[[cards]]
kanji = '初めて'
kana = 'はじめて'
english = 'for the first time'
level = 'n5'
tags = ['adverb', 'common', 'no-adjective']

[[cards]]
kanji = '早く'
kana = 'はやく'
english = 'early; soon'
tags = ['adverb', 'common']

[[cards]]
kanji = '久しく'
kana = 'ひさしく'
english = 'for a long time'
tags = ['adverb', 'uncommon']

[[cards]]
kanji = '吃驚'
kana = 'びっくり'
english = 'to be surprised; to be amazed; to get startled'
level = 'n3'
tags = ['adverb', 'common', 'suru-verb']

[[cards]]
kanji = 'ふんわり'
kana = 'ふんわり'
english = 'gently; fluffily'
source = 'food-package'
tags = ['common', 'onomatopoeia']

[[cards]]
kanji = '殆ど'
kana = 'ほとんど'
english = 'mostly; most (of); almost'
level = 'n4'
source = 'nihongo-charenji-n4-kotoba'
tags = ['adverbial-noun', 'common', 'temporal-noun']

[[cards]]
kanji = '先ず'
kana = 'まず'
english = 'first of all'
level = 'n3'
source = 'wanikani'
tags = ['adverb', 'common']

[[cards]]
kanji = '未だ'
kana = 'まだ'
english = 'not yet; still; besides'
level = 'n5'
tags = ['adverb', 'common']

[[cards]]
kanji = '真っ直ぐ'
kana = 'まっすぐ'
english = 'straight ahead; direct'
level = 'n5'
tags = ['adverb', 'common', 'na-adjective', 'noun']

[[cards]]
kanji = 'もう'
kana = 'もう'
english = 'already; again'
level = 'n5'
tags = ['adverb', 'common']

[[cards]]
kanji = 'もっと'
kana = 'もっと'
english = 'more; longer; further'
level = 'n5'
tags = ['adverb', 'common']

[[cards]]
kanji = 'ゆっくり'
kana = 'ゆっくり'
english = 'slowly; at ease'
level = 'n5'
tags = ['adverb', 'common', 'noun', 'suru-verb']

[[cards]]
kanji = '良く'
kana = 'よく'
english = 'well; skillfully; frequently'
level = 'n5'
tags = ['adverb', 'common']

