[[cards]]
kanji = '蟻'
kana = 'あり'
english = 'ant'
tags = ['common', 'insect', 'noun']

[[cards]]
kanji = '犬'
kana = 'いぬ'
english = 'dog'
level = 'n5'
make_kanji_card = true
tags = ['common', 'mammal']

[[cards]]
kanji = '牛'
kana = 'うし'
english = 'cow'
make_kanji_card = true
level = 'n3'
tags = ['common', 'noun']

[[cards]]
kanji = '海老'
kana = 'えび'
english = 'shrimp; lobster'
tags = ['common', 'noun']

[[cards]]
kanji = '狼'
kana = 'おおかみ'
english = 'wolf'
tags = ['common', 'noun']

[[cards]]
kanji = '蛙'
kana = 'かえる'
english = 'frog'
level = 'n5'
tags = ['common', 'noun']

[[cards]]
kanji = '蟹'
kana = 'かに'
english = 'crab'
tags = ['common', 'noun']

[[cards]]
kanji = '亀'
kana = 'かめ'
english = 'turtle; tortoise'
make_kanji_card = true
tags = ['common', 'noun']

[[cards]]
kanji = '烏'
kana = 'からす'
english = 'raven; crow'
tags = ['common', 'noun']

[[cards]]
kanji = '狐'
kana = 'きつね'
english = 'fox'
tags = ['common', 'noun']

[[cards]]
kanji = '金魚'
kana = 'きんぎょ'
english = 'goldfish'
level = 'n2'
tags = ['common', 'noun']

[[cards]]
kanji = '熊'
kana = 'くま'
english = 'bear'
tags = ['common', 'noun']

[[cards]]
kanji = '蜘蛛'
kana = 'くも'
english = 'spider'
tags = ['animals', 'common', 'insects', 'noun']

[[cards]]
kanji = '子犬'
kana = 'こいぬ'
english = 'puppy'
make_kanji_card = true
tags = ['common', 'noun']

[[cards]]
kanji = '子牛'
kana = 'こうし'
english = 'calf'
level = 'n2'
make_kanji_card = true
tags = ['common', 'noun']

[[cards]]
kanji = '子猫'
kana = 'こねこ'
english = 'kitten'
make_kanji_card = true
tags = ['common', 'noun']

[[cards]]
kanji = '蜚蠊'
kana = 'ごきぶり'
english = 'cockroach'
tags = ['common', 'insect', 'noun']

[[cards]]
kanji = '猿'
kana = 'さる'
english = 'monkey'
level = 'n3'
tags = ['common', 'mammal', 'noun']

[[cards]]
kanji = '獅子'
kana = 'しし'
english = 'lion'
tags = ['common', 'mammal', 'noun']

[[cards]]
kanji = '象'
kana = 'ぞう'
english = 'elephant'
level = 'n3'
tags = ['common', 'mammal', 'noun']

[[cards]]
kanji = '鳥'
kana = 'とり'
english = 'bird'
level = 'n5'
tags = []

[[cards]]
kanji = '蜻蛉'
kana = 'とんぼ'
english = 'dragonfly'
source = 'japan-trip'
tags = ['animals', 'common', 'noun']

[[cards]]
kanji = '動物'
kana = 'どうぶつ'
english = 'animal'
level = 'n5'
tags = []

[[cards]]
kanji = '猫'
kana = 'ねこ'
english = 'cat'
level = 'n5'
tags = []

[[cards]]
kanji = '蜂'
kana = 'はち'
english = 'bee; wasp; hornet'
tags = ['animals', 'common', 'insects', 'noun']

[[cards]]
kanji = '～匹'
kana = '～ひき'
english = 'counter for small animals'
level = 'n5'
tags = []

[[cards]]
kanji = '豚'
kana = 'ぶた'
english = 'pig'
tags = ['animals', 'common', 'noun']

[[cards]]
kanji = '鮪'
kana = 'まぐろ'
english = 'tuna'
source = 'sekai-wa-fushigi-2'
tags = ['common', 'fish']

[[cards]]
kanji = '蚯蚓'
kana = 'みみず'
english = 'earthworm'
tags = ['insect', 'noun', 'uncommon']

[[cards]]
kanji = '虫'
kana = 'むし'
english = 'insect'
level = 'n4'
tags = ['animals', 'common', 'noun']

[[cards]]
kanji = 'ペット'
kana = 'ペット'
english = 'pet'
level = 'n5'
tags = []

