[[cards]]
kanji = '火星'
kana = 'かせい'
english = 'Mars (planet)'
level = 'n1'
source = 'wanikani'
tags = ['common', 'no-adjective', 'noun', 'space']
frequency_scores = { anime = 4287, leeds = 7410, wikipedia = 5868 }

[[cards]]
kanji = '金星'
kana = 'きんせい'
english = 'Venus (planet)'
source = 'wanikani'
tags = ['common', 'noun', 'planet', 'space']
frequency_scores = { anime = 16594, leeds = 14137, wikipedia = 8294 }

[[cards]]
kanji = '水星'
kana = 'すいせい'
english = 'Mercury (planet)'
source = 'wanikani'
tags = ['noun', 'planet', 'space', 'uncommon']

[[cards]]
kanji = '月'
kana = 'つき'
english = 'moon'
level = 'n3'
tags = ['common', 'space']
frequency_scores = { anime = 430, leeds = 77, novels = 646, wikipedia = 21 }

[[cards]]
kanji = '土星'
kana = 'どせい'
english = 'Saturn (planet)'
source = 'wanikani'
tags = ['common', 'noun', 'planet', 'space']

