[[cards]]
kanji = '上着'
kana = 'うわぎ'
english = 'coat'
level = 'n5'
tags = []
highest_frequency = 8853
highest_frequency_source = 'Anime'

[[cards]]
kanji = '鞄'
kana = 'かばん'
english = 'bag; briefcase; basket'
level = 'n5'
tags = []
highest_frequency = 2374
highest_frequency_source = 'Novels'

[[cards]]
kanji = '着物'
kana = 'きもの'
english = 'clothing; ALSO traditional clothing type'
source = 'wiki-n4'
level = 'n4'
tags = ['clothing', 'common', 'noun']
highest_frequency = 2240
highest_frequency_source = 'Novels'

[[cards]]
kanji = '靴'
kana = 'くつ'
english = 'shoes'
level = 'n5'
tags = []
highest_frequency = 1110
highest_frequency_source = 'Leeds'

[[cards]]
kanji = '靴下'
kana = 'くつした'
english = 'socks'
level = 'n5'
tags = []
highest_frequency = 11045
highest_frequency_source = 'Leeds'

[[cards]]
kanji = '財布'
kana = 'さいふ'
english = 'wallet'
level = 'n5'
tags = []
highest_frequency = 4229
highest_frequency_source = 'Anime'

[[cards]]
kanji = '背広'
kana = 'せびろ'
english = 'business suit'
level = 'n5'
tags = []
highest_frequency = 43112
highest_frequency_source = 'Anime'

[[cards]]
kanji = '洗濯'
kana = 'せんたく'
english = 'laundry; washing'
level = 'n5'
tags = []
highest_frequency = 3454
highest_frequency_source = 'Anime'

[[cards]]
kanji = '服'
kana = 'ふく'
english = 'clothes (esp. Western)'
level = 'n5'
tags = []
highest_frequency = 557
highest_frequency_source = 'Anime'

[[cards]]
kanji = '帽子'
kana = 'ぼうし'
english = 'hat'
level = 'n5'
tags = []
highest_frequency = 2217
highest_frequency_source = 'Novels'

[[cards]]
kanji = '指輪'
kana = 'ゆびわ'
english = 'ring (for finger)'
source = 'irasshai'
level = 'n4'
tags = ['attire', 'clothing', 'common', 'noun']
highest_frequency = 3918
highest_frequency_source = 'Anime'

[[cards]]
kanji = '洋服'
kana = 'ようふく'
english = 'Western-style clothes'
level = 'n5'
tags = []
highest_frequency = 6718
highest_frequency_source = 'Leeds'

[[cards]]
kanji = 'シャツ'
kana = 'シャツ'
english = 'shirt'
level = 'n5'
tags = []
highest_frequency = 2280
highest_frequency_source = 'Novels'

[[cards]]
kanji = 'スカート'
kana = 'スカート'
english = 'skirt'
level = 'n5'
tags = []
highest_frequency = 1600
highest_frequency_source = 'Novels'

[[cards]]
kanji = 'スリッパ'
kana = 'スリッパ'
english = 'slippers'
level = 'n5'
tags = []
highest_frequency = 16824
highest_frequency_source = 'Anime'

[[cards]]
kanji = 'ズボン'
kana = 'ズボン'
english = 'pants (from French)'
level = 'n5'
tags = []
highest_frequency = 2478
highest_frequency_source = 'Novels'

[[cards]]
kanji = 'セーター'
kana = 'セーター'
english = 'sweater'
level = 'n5'
tags = []
highest_frequency = 12776
highest_frequency_source = 'Leeds'

[[cards]]
kanji = 'ネクタイ'
kana = 'ネクタイ'
english = 'necktie'
level = 'n5'
tags = []
highest_frequency = 9284
highest_frequency_source = 'Leeds'

[[cards]]
kanji = 'ハンカチ'
kana = 'ハンカチ'
english = 'handkerchief'
level = 'n5'
tags = []
highest_frequency = 8824
highest_frequency_source = 'Anime'

[[cards]]
kanji = 'ボタン'
kana = 'ボタン'
english = 'button'
level = 'n5'
tags = []
highest_frequency = 2464
highest_frequency_source = 'Leeds'

[[cards]]
kanji = 'ポケット'
kana = 'ポケット'
english = 'pocket'
level = 'n5'
tags = []
highest_frequency = 1454
highest_frequency_source = 'Novels'

[[cards]]
kanji = 'ワイシャツ'
kana = 'ワイシャツ'
english = 'business shirt (lit. white shirt)'
level = 'n5'
tags = []
highest_frequency = 23882
highest_frequency_source = 'Anime'

