[[cards]]
kanji = '上着'
kana = 'うわぎ'
english = 'coat'
level = 'n5'
tags = []
frequency_scores = { anime = 8853, leeds = 11932 }

[[cards]]
kanji = '鞄'
kana = 'かばん'
english = 'bag; briefcase; basket'
level = 'n5'
tags = []
frequency_scores = { anime = 6364, leeds = 12301, novels = 2374 }

[[cards]]
kanji = '絹'
kana = 'きぬ'
english = 'silk'
source = 'wiktionary'
level = 'n4'
tags = ['common', 'material', 'noun']
frequency_scores = { anime = 19048, leeds = 14271, wikipedia = 7627 }

[[cards]]
kanji = '着物'
kana = 'きもの'
english = 'clothing; ALSO traditional clothing type'
source = 'wiki-n4'
level = 'n4'
tags = ['clothing', 'common', 'noun']
frequency_scores = { anime = 4637, leeds = 6941, novels = 2240 }

[[cards]]
kanji = '靴'
kana = 'くつ'
english = 'shoes'
level = 'n5'
tags = []
frequency_scores = { anime = 3681, leeds = 1110, novels = 1771, wikipedia = 5760 }

[[cards]]
kanji = '靴下'
kana = 'くつした'
english = 'socks'
level = 'n5'
tags = []
frequency_scores = { anime = 12426, leeds = 11045 }

[[cards]]
kanji = '財布'
kana = 'さいふ'
english = 'wallet'
level = 'n5'
tags = []
frequency_scores = { anime = 4229, leeds = 5666 }

[[cards]]
kanji = '下着'
kana = 'したぎ'
english = 'underwear'
source = 'wiktionary'
level = 'n4'
tags = ['clothing', 'common', 'noun']
frequency_scores = { anime = 3284, leeds = 8440, novels = 2427 }

[[cards]]
kanji = '背広'
kana = 'せびろ'
english = 'business suit'
level = 'n5'
tags = []
frequency_scores = { anime = 43112 }

[[cards]]
kanji = '洗濯'
kana = 'せんたく'
english = 'laundry; washing'
level = 'n5'
tags = []
frequency_scores = { anime = 3454, leeds = 3570 }

[[cards]]
kanji = '服'
kana = 'ふく'
english = 'clothes (esp. Western)'
level = 'n5'
tags = []
frequency_scores = { anime = 557, leeds = 2276, novels = 628, wikipedia = 2633 }

[[cards]]
kanji = '帽子'
kana = 'ぼうし'
english = 'hat'
level = 'n5'
tags = []
frequency_scores = { anime = 4241, leeds = 5577, novels = 2217, wikipedia = 7662 }

[[cards]]
kanji = '木綿'
kana = 'もめん'
english = 'cotton (material)'
source = 'n4-wikipedia'
level = 'n4'
tags = ['clothing', 'common', 'fabric', 'material', 'noun']
frequency_scores = { anime = 9838 }

[[cards]]
kanji = '指輪'
kana = 'ゆびわ'
english = 'ring (for finger)'
source = 'irasshai'
level = 'n4'
tags = ['attire', 'clothing', 'common', 'noun']
frequency_scores = { anime = 3918, leeds = 7969, wikipedia = 9960 }

[[cards]]
kanji = '洋服'
kana = 'ようふく'
english = 'Western-style clothes'
level = 'n5'
tags = []
frequency_scores = { anime = 10879, leeds = 6718 }

[[cards]]
kanji = 'シャツ'
kana = 'シャツ'
english = 'shirt'
level = 'n5'
tags = []
frequency_scores = { anime = 7359, leeds = 5601, novels = 2280, wikipedia = 6916 }

[[cards]]
kanji = 'スカート'
kana = 'スカート'
english = 'skirt'
level = 'n5'
tags = []
frequency_scores = { anime = 4370, leeds = 7455, novels = 1600, wikipedia = 8927 }

[[cards]]
kanji = 'スリッパ'
kana = 'スリッパ'
english = 'slippers'
level = 'n5'
tags = []
frequency_scores = { anime = 16824 }

[[cards]]
kanji = 'ズボン'
kana = 'ズボン'
english = 'pants (from French)'
level = 'n5'
tags = []
frequency_scores = { anime = 9373, leeds = 8349, novels = 2478 }

[[cards]]
kanji = 'セーター'
kana = 'セーター'
english = 'sweater'
level = 'n5'
tags = []
frequency_scores = { anime = 34781, leeds = 12776 }

[[cards]]
kanji = 'ネクタイ'
kana = 'ネクタイ'
english = 'necktie'
level = 'n5'
tags = []
frequency_scores = { anime = 12782, leeds = 9284 }

[[cards]]
kanji = 'ハンカチ'
kana = 'ハンカチ'
english = 'handkerchief'
level = 'n5'
tags = []
frequency_scores = { anime = 8824, leeds = 13821 }

[[cards]]
kanji = 'ボタン'
kana = 'ボタン'
english = 'button'
level = 'n5'
tags = []
frequency_scores = { anime = 3803, leeds = 2464, novels = 2627, wikipedia = 2812 }

[[cards]]
kanji = 'ポケット'
kana = 'ポケット'
english = 'pocket'
level = 'n5'
tags = []
frequency_scores = { anime = 5027, leeds = 5168, novels = 1454, wikipedia = 7161 }

[[cards]]
kanji = 'ワイシャツ'
kana = 'ワイシャツ'
english = 'business shirt (lit. white shirt)'
level = 'n5'
tags = []
frequency_scores = { anime = 23882 }

