[[cards]]
kanji = '青'
kana = 'あお'
english = 'blue'
level = 'n5'
tags = ['color', 'common', 'no-adjective', 'noun']
highest_frequency = 1279
highest_frequency_source = 'Novel 3k'

[[cards]]
kanji = '青い'
kana = 'あおい'
english = 'blue'
level = 'n5'
tags = ['color', 'common', 'i-adjective']
highest_frequency = 1098
highest_frequency_source = 'Novel 3k'

[[cards]]
kanji = '赤'
kana = 'あか'
english = 'red'
level = 'n5'
tags = ['color', 'common', 'no-adjective', 'noun']
highest_frequency = 925
highest_frequency_source = 'Wikipedia 10k'

[[cards]]
kanji = '赤い'
kana = 'あかい'
english = 'red'
level = 'n5'
tags = ['color', 'common', 'i-adjective']
highest_frequency = 586
highest_frequency_source = 'Novel 3k'

[[cards]]
kanji = '色'
kana = 'いろ'
english = 'color'
level = 'n5'
tags = []
highest_frequency = 310
highest_frequency_source = 'Novel 3k'

[[cards]]
kanji = '黄色'
kana = 'きいろ'
english = 'yellow'
level = 'n5'
tags = ['common', 'na-adjective', 'noun']
highest_frequency = 4120
highest_frequency_source = 'Wikipedia 10k'

[[cards]]
kanji = '黄色い'
kana = 'きいろい'
english = 'yellow'
level = 'n5'
tags = ['common', 'i-adjectives']
highest_frequency = 7289
highest_frequency_source = 'Leeds 15k'

[[cards]]
kanji = '黒'
kana = 'くろ'
english = 'black'
level = 'n5'
tags = []
highest_frequency = 604
highest_frequency_source = 'Novel 3k'

[[cards]]
kanji = '黒い'
kana = 'くろい'
english = 'black'
level = 'n5'
tags = ['common', 'i-adjectives']
highest_frequency = 439
highest_frequency_source = 'Novel 3k'

[[cards]]
kanji = '白'
kana = 'しろ'
english = 'white'
level = 'n5'
tags = []
highest_frequency = 494
highest_frequency_source = 'Anime 45k'

[[cards]]
kanji = '白い'
kana = 'しろい'
english = 'white'
level = 'n5'
tags = ['common', 'i-adjective']
highest_frequency = 293
highest_frequency_source = 'Novel 3k'

[[cards]]
kanji = '橙色'
kana = 'だいだいいろ'
english = 'orange (color of the fruit)'
tags = ['common', 'no-adjective', 'noun']

[[cards]]
kanji = '茶色'
kana = 'ちゃいろ'
english = 'brown'
level = 'n5'
tags = []
highest_frequency = 10627
highest_frequency_source = 'Leeds 15k'

[[cards]]
kanji = '灰色'
kana = 'はいいろ'
english = 'gray; ashen'
level = 'n2'
tags = ['color', 'common', 'no-adjective', 'noun']
highest_frequency = 2200
highest_frequency_source = 'Novel 3k'

[[cards]]
kanji = '緑'
kana = 'みどり'
english = 'green'
level = 'n5'
tags = ['common', 'no-adjective', 'noun']
highest_frequency = 989
highest_frequency_source = 'Anime 45k'

[[cards]]
kanji = '紫'
kana = 'むらさき'
english = 'purple'
source = 'irasshai'
level = 'n2'
tags = ['colors', 'common', 'noun']
highest_frequency = 4143
highest_frequency_source = 'Wikipedia 10k'

[[cards]]
kanji = 'ピンク'
kana = 'ピンク'
english = 'pink'
level = 'n2'
tags = ['color', 'common', 'gairaigo', 'no-adjective', 'noun']
highest_frequency = 2853
highest_frequency_source = 'Novel 3k'

