[[cards]]
kanji = '青'
kana = 'あお'
english = 'blue'
level = 'n5'
tags = ['color', 'common', 'no-adjective', 'noun']
frequency_scores = { anime = 1391, leeds = 2851, novels = 1279, wikipedia = 1325 }

[[cards]]
kanji = '青い'
kana = 'あおい'
english = 'blue'
level = 'n5'
tags = ['color', 'common', 'i-adjective']
frequency_scores = { anime = 2450, leeds = 3762, novels = 1098, wikipedia = 4295 }

[[cards]]
kanji = '赤'
kana = 'あか'
english = 'red'
level = 'n5'
tags = ['color', 'common', 'no-adjective', 'noun']
frequency_scores = { anime = 1009, leeds = 2106, novels = 1051, wikipedia = 925 }

[[cards]]
kanji = '赤い'
kana = 'あかい'
english = 'red'
level = 'n5'
tags = ['color', 'common', 'i-adjective']
frequency_scores = { anime = 1215, leeds = 2795, novels = 586, wikipedia = 2915 }

[[cards]]
kanji = '色'
kana = 'いろ'
english = 'color'
level = 'n5'
tags = []
frequency_scores = { anime = 767, leeds = 772, novels = 310, wikipedia = 454 }

[[cards]]
kanji = '黄色'
kana = 'きいろ'
english = 'yellow'
level = 'n5'
tags = ['common', 'na-adjective', 'noun']
frequency_scores = { anime = 7085, leeds = 6093, wikipedia = 4120 }

[[cards]]
kanji = '黄色い'
kana = 'きいろい'
english = 'yellow'
level = 'n5'
tags = ['common', 'i-adjectives']
frequency_scores = { anime = 9685, leeds = 7289, wikipedia = 9358 }

[[cards]]
kanji = '黒'
kana = 'くろ'
english = 'black'
level = 'n5'
tags = []
frequency_scores = { anime = 718, leeds = 2022, novels = 604, wikipedia = 952 }

[[cards]]
kanji = '黒い'
kana = 'くろい'
english = 'black'
level = 'n5'
tags = ['common', 'i-adjectives']
frequency_scores = { anime = 1774, leeds = 3318, novels = 439, wikipedia = 3244 }

[[cards]]
kanji = '白'
kana = 'しろ'
english = 'white'
level = 'n5'
tags = []
frequency_scores = { anime = 494, leeds = 1964, novels = 838, wikipedia = 903 }

[[cards]]
kanji = '白い'
kana = 'しろい'
english = 'white'
level = 'n5'
tags = ['common', 'i-adjective']
frequency_scores = { anime = 1688, leeds = 2088, novels = 293, wikipedia = 2895 }

[[cards]]
kanji = '橙色'
kana = 'だいだいいろ'
english = 'orange (color of the fruit)'
tags = ['common', 'no-adjective', 'noun']

[[cards]]
kanji = '茶色'
kana = 'ちゃいろ'
english = 'brown'
level = 'n5'
tags = []
frequency_scores = { anime = 18992, leeds = 10627 }

[[cards]]
kanji = '灰色'
kana = 'はいいろ'
english = 'gray; ashen'
level = 'n2'
tags = ['color', 'common', 'no-adjective', 'noun']
frequency_scores = { anime = 10148, leeds = 10853, novels = 2200, wikipedia = 6855 }

[[cards]]
kanji = '緑'
kana = 'みどり'
english = 'green'
level = 'n5'
tags = ['common', 'no-adjective', 'noun']
frequency_scores = { anime = 989, leeds = 2715, novels = 1838, wikipedia = 1991 }

[[cards]]
kanji = '紫'
kana = 'むらさき'
english = 'purple'
source = 'irasshai'
level = 'n2'
tags = ['colors', 'common', 'noun']
frequency_scores = { anime = 4551, leeds = 6507, wikipedia = 4143 }

[[cards]]
kanji = 'ピンク'
kana = 'ピンク'
english = 'pink'
level = 'n2'
tags = ['color', 'common', 'gairaigo', 'no-adjective', 'noun']
frequency_scores = { anime = 7852, leeds = 4892, novels = 2853, wikipedia = 5073 }

