[[cards]]
kanji = 'かどうか'
kana = 'かどうか'
english = "whether or not (eg. I do't know whether or not I can come.)"
source = 'wanikani'
tags = ['common']

[[cards]]
kanji = 'が'
kana = 'が'
english = 'and, but (links two clauses)'
explain = 'https://kawakawalearningstudio.com/all/how-to-use-linking-words-and-phrases-to-connect-your-sentences/'
tags = ['common', 'conjunction']

[[cards]]
kanji = 'けど'
kana = 'けど'
english = 'however (links two clauses); however... (soft open ending)'
level = 'n4'
explain = 'https://kawakawalearningstudio.com/all/how-to-use-linking-words-and-phrases-to-connect-your-sentences/'
tags = ['common', 'conjunction', 'particle']

[[cards]]
kanji = '然し'
kana = 'しかし'
english = 'however (start of sentence; formal/storytelling)'
level = 'n5'
explain = 'https://kawakawalearningstudio.com/all/how-to-use-linking-words-and-phrases-to-connect-your-sentences/'
tags = ['common', 'conjunction']

[[cards]]
kanji = '然も'
kana = 'しかも'
english = 'furthermore'
level = 'n3'
explain = 'https://kawakawalearningstudio.com/all/how-to-use-linking-words-and-phrases-to-connect-your-sentences/'
tags = ['common', 'conjunction']

[[cards]]
kanji = 'じゃあ'
kana = 'じゃあ'
english = 'well then...'
level = 'n5'
tags = ['common', 'conjunction']

[[cards]]
kanji = 'すると'
kana = 'すると'
english = 'just then'
source = 'kachikachiyama'
level = 'n4'
tags = ['common', 'conjunction']

[[cards]]
kanji = '然うして'
kana = 'そうして'
english = 'and then (does not imply chronological order)'
level = 'n5'
explain = 'http://yesjapan.com/YJ6/question/742/when-do-you-use-soshite-and-sorekara'
tags = ['common', 'conjunction']

[[cards]]
kanji = 'そして'
kana = 'そして'
english = 'and'
source = 'irasshai'
level = 'n5'
tags = ['common', 'conjunction', 'grammar']

[[cards]]
kanji = '其れに'
kana = 'それに'
english = 'moreover'
level = 'n4'
explain = 'https://kawakawalearningstudio.com/all/how-to-use-linking-words-and-phrases-to-connect-your-sentences/'
tags = ['common', 'conjunction']

[[cards]]
kanji = '為に'
kana = 'ために'
english = 'for the sake of; on behalf of'
tags = ['common', 'conjunction']

[[cards]]
kanji = 'だって'
kana = 'だって'
english = 'after all, because (explains previous sentence)'
explain = 'https://kawakawalearningstudio.com/all/how-to-use-linking-words-and-phrases-to-connect-your-sentences/'
tags = ['common', 'conjunction']

[[cards]]
kanji = 'では'
kana = 'では'
english = 'then'
source = 'irasshai; anime'
level = 'n5'
tags = ['common', 'conjunction']

[[cards]]
kanji = 'でも、'
kana = 'でも、'
english = 'but (start of sentence; casual)'
level = 'n5'
explain = 'https://kawakawalearningstudio.com/all/how-to-use-linking-words-and-phrases-to-connect-your-sentences/'
tags = ['common', 'conjunction']

[[cards]]
kanji = 'どうせ'
kana = 'どうせ'
english = 'anyhow; at best'
level = 'n2'
source = 'wanikani'
tags = ['adverb', 'common']

