[[cards]]
kanji = '韓国'
kana = 'かんこく'
english = 'South Korea'
tags = ['common', 'countries', 'no-adjective', 'noun', 'world']
frequency_scores = { anime = 41425, leeds = 611, wikipedia = 675 }

[[cards]]
kanji = '北朝鮮'
kana = 'きたちょうせん'
english = 'North Korea'
tags = ['common', 'countries', 'noun', 'place', 'world']
frequency_scores = { anime = 36337, leeds = 1170, wikipedia = 2954 }

[[cards]]
kanji = '朝鮮'
kana = 'ちょうせん'
english = 'Korea'
tags = ['common', 'countries', 'noun', 'place', 'world']
frequency_scores = { anime = 37058, leeds = 2324, wikipedia = 921 }

[[cards]]
kanji = '米国'
kana = 'べいこく'
english = 'USA'
tags = ['common', 'noun']
frequency_scores = { anime = 15619, leeds = 720, wikipedia = 1071 }

[[cards]]
kanji = 'アフリカ'
kana = 'アフリカ'
english = 'Africa'
level = 'n4'
tags = ['common', 'gairaigo', 'no-adjective', 'noun']
frequency_scores = { anime = 9323, leeds = 3062, wikipedia = 1301 }

[[cards]]
kanji = 'アメリカ'
kana = 'アメリカ'
english = 'America'
level = 'n4'
tags = ['common', 'gairaigo', 'noun']
frequency_scores = { anime = 3494, leeds = 261, novels = 2133, wikipedia = 93 }

