[[cards]]
kanji = '嬉しい'
kana = 'うれしい'
english = 'happy; glad'
level = 'n3'
tags = ['common', 'emotion', 'i-adjective']
frequency_scores = { anime = 511, leeds = 1129, novels = 1391 }

[[cards]]
kanji = '悲しい'
kana = 'かなしい'
english = 'sad'
source = 'irasshai; anime'
level = 'n4'
tags = ['common', 'emotion', 'i-adjective']
frequency_scores = { anime = 1159, leeds = 2404, novels = 1518 }

[[cards]]
kanji = '寂しい'
kana = 'さびしい'
english = 'lonely'
source = 'irasshai; anime'
level = 'n4'
tags = ['common', 'emotion', 'i-adjective']
frequency_scores = { anime = 775, leeds = 3270, novels = 2540 }

[[cards]]
kanji = '幸せ'
kana = 'しあわせ'
english = 'happiness; good fortune; luck'
source = 'bonobono-anime'
level = 'n3'
tags = ['common', 'emotion', 'na-adjective', 'noun']
frequency_scores = { anime = 544, leeds = 1212, novels = 2284, wikipedia = 6782 }

[[cards]]
kanji = '心配'
kana = 'しんぱい'
english = 'worry'
source = 'wanikani; anime?'
level = 'n3'
tags = ['common', 'emotion', 'na-adjective', 'noun', 'suru-verb']
frequency_scores = { anime = 245, leeds = 1031, novels = 507, wikipedia = 7628 }

