[[cards]]
kanji = '気をつける'
kana = 'きをつける'
english = 'to be careful; to take care'
level = 'n2'
tags = ['common', 'expression', 'ichidan-verb']

[[cards]]
kanji = 'すれば'
kana = 'すれば'
english = 'if so'
source = 'wanikani; anime'
tags = ['common', 'expression']

[[cards]]
kanji = 'そう言えば'
kana = 'そういえば'
english = 'if you say so; now that you mention it'
level = 'n2'
explain = 'http://yesjapan.com/YJ6/question/742/when-do-you-use-soshite-and-sorekara'
tags = ['common', 'expression']
highest_frequency = 2928
highest_frequency_source = 'Novels'

[[cards]]
kanji = '其れから'
kana = 'それから'
english = 'after that (chronological order)'
level = 'n5'
explain = 'http://yesjapan.com/YJ6/question/742/when-do-you-use-soshite-and-sorekara'
tags = ['common', 'expression']
highest_frequency = 379
highest_frequency_source = 'Novels'

[[cards]]
kanji = '其れでは'
kana = 'それでは'
english = 'well then...; in that case...'
level = 'n5'
tags = ['common', 'expression']
highest_frequency = 2165
highest_frequency_source = 'Novels'

[[cards]]
kanji = '努めて'
kana = 'つとめて'
english = 'as much as possible'
source = 'wanikani'
level = 'n1'
tags = ['adverb', 'common']

[[cards]]
kanji = '取りあえず'
kana = 'とりあえず'
english = 'first of all'
source = 'anime-freq'
level = 'n1'
tags = ['adverb', 'common', 'expression']
highest_frequency = 1199
highest_frequency_source = 'Leeds'

[[cards]]
kanji = 'どれ位'
kana = 'どれくらい / どれぐらい'
english = 'how much; how long; how far'
source = 'irasshai'
tags = ['adverbial-noun', 'common', 'expression']

[[cards]]
kanji = 'なる程'
kana = 'なるほど'
english = 'I see; indeed; I should have known'
source = 'irasshai; anime'
level = 'n4'
tags = ['adverb', 'common', 'expression']
highest_frequency = 999
highest_frequency_source = 'Novels'

[[cards]]
kanji = 'もう一度'
kana = 'もういちど'
english = 'one more time; once again'
source = 'irasshai'
level = 'n5'
tags = ['common', 'count', 'expression', 'numbers']
highest_frequency = 748
highest_frequency_source = 'Anime'

