[[cards]]
kanji = '朝ご飯'
kana = 'あさごはん'
english = 'breakfast'
level = 'n5'
tags = ['common', 'food']

[[cards]]
kanji = '飴'
kana = 'あめ'
english = 'hard candy; toffee'
level = 'n5'
tags = ['common', 'food']

[[cards]]
kanji = 'お菓子'
kana = 'おかし'
english = 'candy; confections'
level = 'n5'
tags = []

[[cards]]
kanji = 'お皿'
kana = 'おさら'
english = 'plate'
level = 'n5'
tags = ['common', 'noun']

[[cards]]
kanji = 'お茶'
kana = 'おちゃ'
english = 'tea (usu. green)'
level = 'n5'
tags = []

[[cards]]
kanji = 'お弁当'
kana = 'おべんとう'
english = 'Japanese boxed lunch'
level = 'n5'
tags = []

[[cards]]
kanji = '喫茶店'
kana = 'きっさてん'
english = 'coffee shop'
level = 'n5'
tags = []

[[cards]]
kanji = '牛肉'
kana = 'ぎゅうにく'
english = 'beef'
level = 'n5'
tags = []

[[cards]]
kanji = '牛乳'
kana = 'ぎゅうにゅう'
english = "(cow's) milk"
level = 'n5'
tags = []

[[cards]]
kanji = '果物'
kana = 'くだもの'
english = 'fruit'
level = 'n5'
tags = []

[[cards]]
kanji = '紅茶'
kana = 'こうちゃ'
english = 'black tea'
level = 'n5'
tags = []

[[cards]]
kanji = '胡椒'
kana = 'こしょう'
english = 'pepper'
level = 'n2'
tags = ['common', 'food', 'noun']

[[cards]]
kanji = 'ご飯'
kana = 'ごはん'
english = 'cooked rice; meal'
level = 'n5'
tags = []

[[cards]]
kanji = '魚'
kana = 'さかな'
english = 'fish'
level = 'n5'
tags = []

[[cards]]
kanji = '砂糖'
kana = 'さとう'
english = 'sugar'
level = 'n5'
tags = []

[[cards]]
kanji = '皿'
kana = 'さら'
english = 'plate'
level = 'n3'
tags = ['common', 'noun']

[[cards]]
kanji = '塩'
kana = 'しお'
english = 'salt'
level = 'n5'
tags = []

[[cards]]
kanji = '生姜'
kana = 'しょうが'
english = 'ginger'
tags = ['common', 'food', 'noun']

[[cards]]
kanji = '食堂'
kana = 'しょくどう'
english = 'cafeteria; dining hall'
level = 'n5'
tags = []

[[cards]]
kanji = '食品'
kana = 'しょくひん'
english = 'foodstuffs; food products'
level = 'n3'
source = 'nihongo-charenji-n4-kotoba'
tags = ['common', 'noun']

[[cards]]
kanji = '西瓜'
kana = 'すいか'
english = 'watermellon'
tags = ['common', 'food', 'noun']

[[cards]]
kanji = '蕎麦'
kana = 'そば'
english = 'buckwheat; buckwheat noodles'
level = 'n2'
tags = ['common', 'food']

[[cards]]
kanji = '食べ物'
kana = 'たべもの'
english = 'food'
level = 'n5'
tags = []

[[cards]]
kanji = '卵'
kana = 'たまご'
english = 'egg'
level = 'n5'
tags = []

[[cards]]
kanji = '玉ねぎ'
kana = 'たまねぎ'
english = 'onion'
source = 'wanikani'
tags = ['common', 'food']

[[cards]]
kanji = '台所'
kana = 'だいどころ'
english = 'kitchen'
level = 'n5'
tags = []

[[cards]]
kanji = '茶碗'
kana = 'ちゃわん'
english = 'rice bowl; tea cup'
level = 'n5'
tags = []

[[cards]]
kanji = '冷たい'
kana = 'つめたい'
english = 'cold (to the touch); coldhearted'
level = 'n5'
tags = []

[[cards]]
kanji = '鳥肉'
kana = 'とりにく'
english = 'chicken meat; bird meat'
level = 'n5'
tags = []

[[cards]]
kanji = '茄子'
kana = 'なす'
english = 'eggplant'
source = 'wanikani'
tags = ['common', 'food', 'noun', 'vegetable']

[[cards]]
kanji = '生'
kana = 'なま'
english = 'raw; uncooked; fresh'
source = 'sekai-wa-fushigi-2'
level = 'n3'
tags = ['common', 'na-adjective', 'no-adjective', 'noun', 'prefix']

[[cards]]
kanji = '肉'
kana = 'にく'
english = 'meat'
level = 'n5'
tags = []

[[cards]]
kanji = '飲み物'
kana = 'のみもの'
english = 'drink; beverage'
level = 'n5'
tags = []

[[cards]]
kanji = '～杯'
kana = '～はい'
english = 'counter for cupfuls'
level = 'n5'
tags = []

[[cards]]
kanji = '箸'
kana = 'はし'
english = 'chopsticks'
level = 'n5'
tags = []

[[cards]]
kanji = '晩御飯'
kana = 'ばんごはん'
english = 'dinner'
level = 'n5'
tags = []

[[cards]]
kanji = '昼ご飯'
kana = 'ひるはん'
english = 'lunch'
level = 'n5'
tags = []

[[cards]]
kanji = '豚肉'
kana = 'ぶたにく'
english = 'pork'
level = 'n5'
tags = []

[[cards]]
kanji = '葡萄'
kana = 'ぶどう'
english = 'grape'
level = 'n4'
source = 'wanikani'
tags = ['common', 'food', 'noun']

[[cards]]
kanji = '不味い'
kana = 'まずい'
english = 'unappetising; unpleasant taste'
level = 'n5'
tags = []

[[cards]]
kanji = '水'
kana = 'みず'
english = 'water'
level = 'n5'
tags = []

[[cards]]
kanji = '八百屋'
kana = 'やおや'
english = 'greengrocer'
level = 'n5'
tags = []

[[cards]]
kanji = '野菜'
kana = 'やさい'
english = 'vegetable'
level = 'n5'
tags = []

[[cards]]
kanji = '夕飯'
kana = 'ゆうはん'
english = 'evening meal (5-7pmish)'
level = 'n5'
tags = []

[[cards]]
kanji = '料理'
kana = 'りょうり'
english = 'cooking; cuisine'
level = 'n5'
tags = []

[[cards]]
kanji = '林檎'
kana = 'りんご'
english = 'apple'
tags = ['common', 'food', 'noun']

[[cards]]
kanji = '冷蔵庫'
kana = 'れいぞうこ'
english = 'refrigerator'
level = 'n5'
tags = []

[[cards]]
kanji = 'カップ'
kana = 'カップ'
english = 'cup'
level = 'n5'
tags = []

[[cards]]
kanji = 'カレー'
kana = 'カレー'
english = 'curry'
level = 'n5'
tags = []

[[cards]]
kanji = 'コップ'
kana = 'コップ'
english = 'cup'
level = 'n5'
tags = []

[[cards]]
kanji = '珈琲'
kana = 'コーヒー'
english = 'coffee'
level = 'n5'
tags = []

[[cards]]
kanji = 'スプーン'
kana = 'スプーン'
english = 'spoon'
level = 'n5'
tags = []

[[cards]]
kanji = 'ナイフ'
kana = 'ナイフ'
english = 'knife'
level = 'n5'
tags = []

[[cards]]
kanji = 'バター'
kana = 'バター'
english = 'butter'
level = 'n5'
tags = []

[[cards]]
kanji = 'バナナ'
kana = 'バナナ'
english = 'banana'
tags = ['common']

[[cards]]
kanji = 'パン'
kana = 'パン'
english = 'bread'
level = 'n5'
tags = []

[[cards]]
kanji = 'ビール'
kana = 'ビール'
english = 'beer'
level = 'n3'
tags = ['common', 'drink', 'gairaigo', 'noun']

[[cards]]
kanji = 'フォーク'
kana = 'フォーク'
english = 'fork'
level = 'n5'
tags = []

[[cards]]
kanji = 'レストラン'
kana = 'レストラン'
english = 'restaurant'
level = 'n5'
tags = []

[[cards]]
kanji = 'ワイン'
kana = 'ワイン'
english = 'wine'
level = 'n3'
tags = ['common', 'drink', 'gairaigo', 'noun']

