[[cards]]
kanji = 'アイドル'
kana = 'アイドル'
english = 'member of a jpop band'
source = 'jpop; culture'
tags = ['common', 'gairaigo', 'noun', 'people']
frequency_scores = { anime = 1222, leeds = 4661, wikipedia = 2122 }

[[cards]]
kanji = 'オートバイ'
kana = 'オートバイ'
english = 'motorcycle'
source = 'n4 wiktionary'
level = 'n4'
tags = ['common', 'gairaigo', 'noun', 'transportation']
frequency_scores = { anime = 30266, leeds = 14240, wikipedia = 5227 }

[[cards]]
kanji = 'カーテン'
kana = 'カーテン'
english = 'curtain'
source = 'n4-wiki'
level = 'n4'
tags = ['common', 'house', 'noun', 'window']
frequency_scores = { anime = 7964, leeds = 7697 }

[[cards]]
kanji = 'カード'
kana = 'カード'
english = 'card'
level = 'n3'
tags = ['common', 'electronics', 'gairaigo', 'noun']
frequency_scores = { anime = 564, leeds = 1216, novels = 1986, wikipedia = 533 }

[[cards]]
kanji = 'ガス'
kana = 'ガス'
english = 'gas'
source = 'n4 wiktionary'
level = 'n4'
tags = ['chemistry', 'common', 'gairaigo', 'noun']
frequency_scores = { anime = 3410, leeds = 2259, novels = 2290, wikipedia = 1430 }

[[cards]]
kanji = 'ガソリン'
kana = 'ガソリン'
english = 'gasoline'
source = 'n4 wiktionary'
level = 'n4'
tags = ['automotive', 'common', 'gairaigo', 'noun']
frequency_scores = { anime = 13275, leeds = 5785, wikipedia = 4438 }

[[cards]]
kanji = 'ガソリンスタンド'
kana = 'ガソリンスタンド'
english = 'gas station'
source = 'n4-wiki'
level = 'n4'
tags = ['common', 'noun', 'places', 'travel']
frequency_scores = { anime = 38279 }

[[cards]]
kanji = '瓩'
kana = 'キログラム'
english = 'kilogram'
source = 'wiki-n5'
level = 'n5'
tags = ['ateji', 'common', 'dimensions', 'gairaigo', 'mass', 'noun', 'numbers', 'unit-of-measure', 'weight']
frequency_scores = { anime = 23914 }

[[cards]]
kanji = '粁'
kana = 'キロメートル'
english = 'kilometer'
source = 'wiki-n5'
level = 'n5'
tags = ['ateji', 'common', 'dimensions', 'distance', 'gairaigo', 'noun', 'numbers', 'unit-of-measure']
frequency_scores = { anime = 22582 }

[[cards]]
kanji = 'ケーキ'
kana = 'ケーキ'
english = 'cake'
source = 'irasshai'
level = 'n4'
tags = ['common', 'dessert', 'food', 'noun']
frequency_scores = { anime = 1396, leeds = 3466 }

[[cards]]
kanji = 'ゲーム'
kana = 'ゲーム'
english = 'game'
level = 'n3'
tags = ['common', 'gairaigo', 'games', 'noun', 'video games']
frequency_scores = { anime = 221, leeds = 589, novels = 1929, wikipedia = 158 }

[[cards]]
kanji = 'コンサート'
kana = 'コンサート'
english = 'concert'
source = 'n4-wiki'
level = 'n4'
tags = ['common', 'event', 'music', 'noun']
frequency_scores = { anime = 13310, leeds = 2420, wikipedia = 1868 }

[[cards]]
kanji = 'コンピューター'
kana = 'コンピューター'
english = 'computer'
source = 'irasshai'
level = 'n4'
tags = ['common', 'electronics', 'gairaigo', 'noun', 'technology']
frequency_scores = { anime = 12468, leeds = 3070, wikipedia = 930 }

[[cards]]
kanji = 'コート'
kana = 'コート'
english = 'coat'
source = 'irasshai'
level = 'n5'
tags = ['clothing', 'common', 'gairaigo', 'noun']
frequency_scores = { anime = 3023, leeds = 4379, novels = 2719, wikipedia = 3700 }

[[cards]]
kanji = 'サラダ'
kana = 'サラダ'
english = 'salad'
source = 'irasshai'
level = 'n4'
tags = ['common', 'food', 'noun']
frequency_scores = { anime = 7180, leeds = 5417 }

[[cards]]
kanji = 'サンダル'
kana = 'サンダル'
english = 'sandals'
source = 'n4-study'
level = 'n4'
tags = ['clothing', 'common', 'footwear', 'noun', 'shoes']
frequency_scores = { anime = 16376, leeds = 13167 }

[[cards]]
kanji = 'サンドイッチ'
kana = 'サンドイッチ'
english = 'sandwich'
source = 'irasshai; n4 wiktionary'
level = 'n4'
tags = ['common', 'food', 'gairaigo']
frequency_scores = { anime = 10232, leeds = 11018 }

[[cards]]
kanji = 'ジャム'
kana = 'ジャム'
english = 'jam'
source = 'n4 wiktionary'
level = 'n4'
tags = ['common', 'food', 'gairaigo', 'noun']
frequency_scores = { anime = 9839, leeds = 10121 }

[[cards]]
kanji = 'スクリーン'
kana = 'スクリーン'
english = 'screen'
source = 'wiki-n4'
level = 'n4'
tags = ['common', 'gairaigo', 'noun']
frequency_scores = { anime = 16193, leeds = 4781, novels = 2238, wikipedia = 5659 }

[[cards]]
kanji = 'ステレオ'
kana = 'ステレオ'
english = 'stereo'
source = 'irasshai'
level = 'n4'
tags = ['common', 'gairaigo', 'noun']
frequency_scores = { anime = 36663, leeds = 8467, wikipedia = 6757 }

[[cards]]
kanji = 'ステーキ'
kana = 'ステーキ'
english = 'steak'
level = 'n4'
tags = ['common', 'food', 'gairaigo', 'noun']
frequency_scores = { anime = 8610, leeds = 9956 }

[[cards]]
kanji = 'スーツ'
kana = 'スーツ'
english = 'suit (gairaigo)'
source = 'n4 wiktionary'
level = 'n4'
tags = ['clothing', 'common', 'gairaigo', 'noun']
frequency_scores = { anime = 5020, leeds = 4681, wikipedia = 6985 }

[[cards]]
kanji = 'スーツケース'
kana = 'スーツケース'
english = 'suitcase'
source = 'wiki-n4'
level = 'n4'
tags = ['common', 'gairaigo', 'noun', 'office', 'work']
frequency_scores = { anime = 30094 }

[[cards]]
kanji = 'ソフト'
kana = 'ソフト'
english = 'soft (gairaigo)'
source = 'wiki-n4'
level = 'n4'
tags = ['common', 'gairaigo', 'na-adjective', 'no-adjective']
frequency_scores = { anime = 4330, leeds = 1099, wikipedia = 996 }

[[cards]]
kanji = 'タイプ'
kana = 'タイプ'
english = 'type (gairaigo)'
source = 'wiki-n4'
level = 'n4'
tags = ['common', 'gairaigo', 'noun']
frequency_scores = { anime = 1489, leeds = 1155, novels = 2269, wikipedia = 1055 }

[[cards]]
kanji = 'タイム'
kana = 'タイム'
english = 'time (gairaigo)'
source = 'anime-freq'
level = 'n1'
tags = ['common', 'gairaigo']
frequency_scores = { anime = 1198, leeds = 2532, wikipedia = 1886 }

[[cards]]
kanji = 'テキスト'
kana = 'テキスト'
english = 'text'
source = 'n4 wiktionary'
level = 'n4'
tags = ['common', 'gairaigo', 'noun']
frequency_scores = { anime = 12154, leeds = 2331, wikipedia = 5078 }

[[cards]]
kanji = 'テニス'
kana = 'テニス'
english = 'tennis'
level = 'n4'
tags = ['common', 'gairaigo', 'noun', 'sport']
frequency_scores = { anime = 6273, leeds = 4213, wikipedia = 2395 }

[[cards]]
kanji = 'テープ'
kana = 'テープ'
english = 'tape'
source = 'irasshai'
level = 'n5'
tags = ['common', 'noun', 'office']
frequency_scores = { anime = 5299, leeds = 3965, wikipedia = 3837 }

[[cards]]
kanji = 'テープレコーダー'
kana = 'テープレコーダー'
english = 'tape recorder'
level = 'n5'
tags = ['common', 'dated', 'electronics', 'gairaigo', 'noun']
frequency_scores = { anime = 37501 }

[[cards]]
kanji = 'データ'
kana = 'データ'
english = 'data'
level = 'n1'
tags = ['common', 'gairaigo', 'noun']
frequency_scores = { anime = 1176, leeds = 594, wikipedia = 658 }

[[cards]]
kanji = 'ドラゴン'
kana = 'ドラゴン'
english = 'dragon (gairaigo)'
tags = ['common', 'gairaigo', 'monster', 'mythology', 'noun']
frequency_scores = { anime = 1147, leeds = 7512, wikipedia = 5324 }

[[cards]]
kanji = 'ハンター'
kana = 'ハンター'
english = 'hunter'
tags = ['common', 'gairaigo', 'noun']
frequency_scores = { anime = 1189, leeds = 11035, wikipedia = 6465 }

[[cards]]
kanji = 'ハンドバッグ'
kana = 'ハンドバッグ'
english = 'handbag; purse'
source = 'wiki-n4'
level = 'n4'
tags = ['common', 'gairaigo', 'noun']

[[cards]]
kanji = 'パソコン'
kana = 'パソコン'
english = 'personal computer'
source = 'irasshai'
level = 'n4'
tags = ['common', 'gairaigo', 'no-adjective', 'noun']
frequency_scores = { anime = 1228, leeds = 898, wikipedia = 2663 }

[[cards]]
kanji = 'パート'
kana = 'パート'
english = 'part'
source = 'wiki-n4'
level = 'n4'
tags = ['common', 'gairaigo', 'noun']
frequency_scores = { anime = 4100, leeds = 4034, wikipedia = 3795 }

[[cards]]
kanji = 'ビル'
kana = 'ビル'
english = 'multi-floor building (gairaigo)'
source = 'wiki-n4'
level = 'n4'
tags = ['common', 'gairaigo', 'noun']
frequency_scores = { anime = 3322, leeds = 1526, novels = 1555, wikipedia = 797 }

[[cards]]
kanji = 'ピアノ'
kana = 'ピアノ'
english = 'piano'
source = 'wiki-n4'
level = 'n4'
tags = ['common', 'gairaigo', 'noun']
frequency_scores = { anime = 2073, leeds = 2397, wikipedia = 1517 }

[[cards]]
kanji = 'ファックス'
kana = 'ファックス'
english = 'fax'
source = 'wiki-n4'
level = 'n4'
tags = ['common', 'gairaigo', 'noun', 'suru-verb']
frequency_scores = { anime = 29120, leeds = 10478 }

[[cards]]
kanji = 'ブロック'
kana = 'ブロック'
english = 'block; blocking'
source = 'anime-freq'
tags = ['common', 'gairaigo']
frequency_scores = { anime = 1142, leeds = 3902, wikipedia = 1959 }

[[cards]]
kanji = 'プレゼント'
kana = 'プレゼント'
english = 'present (gairaigo)'
source = 'wiki-n4'
level = 'n4'
tags = ['common', 'gairaigo', 'noun']
frequency_scores = { anime = 1341, leeds = 2000, wikipedia = 5701 }

[[cards]]
kanji = 'ベル'
kana = 'ベル'
english = 'bell (gairaigo)'
source = 'wiki-n4'
level = 'n4'
tags = ['common', 'gairaigo', 'noun']
frequency_scores = { anime = 4225, leeds = 4558, novels = 2086, wikipedia = 2974 }

[[cards]]
kanji = 'マスター'
kana = 'マスター'
english = 'master (gairaigo)'
source = 'anime-freq'
level = 'n3'
tags = ['common', 'gairaigo', 'noun', 'suru-verb']
frequency_scores = { anime = 372, leeds = 3599, novels = 1848, wikipedia = 3595 }

[[cards]]
kanji = 'メートル'
kana = 'メートル'
english = 'meter'
level = 'n5'
tags = ['common', 'dimensions', 'gairaigo', 'measure', 'noun']
frequency_scores = { anime = 1572, leeds = 2597, novels = 678, wikipedia = 806 }

[[cards]]
kanji = 'ライブ'
kana = 'ライブ'
english = 'live (eg performance, concert)'
tags = ['common', 'gairaigo', 'noun', 'noun-or-verb-acting-prenominally']
frequency_scores = { anime = 1152, leeds = 1097, wikipedia = 916 }

[[cards]]
kanji = 'ラジオカセット'
kana = 'ラジオカセット'
english = 'radio-cassette (full word)'
source = 'wiki-n5'
tags = ['gairaigo', 'noun', 'uncommon']

[[cards]]
kanji = 'ラジカセ'
kana = 'ラジカセ'
english = 'radio-cassette player (shortened word)'
source = 'wiki-n5'
level = 'n5'
tags = ['common', 'gairaigo', 'noun', 'old-technology', 'technology']
frequency_scores = { anime = 34005 }

[[cards]]
kanji = 'リポート'
kana = 'リポート'
english = 'report (gairaigo #2)'
source = 'wiki-n4'
level = 'n4'
tags = ['common', 'gairaigo', 'noun']
frequency_scores = { anime = 23858, leeds = 11125 }

[[cards]]
kanji = 'リーダー'
kana = 'リーダー'
english = 'leader (gairaigo)'
source = 'anime-freq'
tags = ['common', 'no-adjective', 'noun']
frequency_scores = { anime = 1525, leeds = 2610, wikipedia = 2867 }

[[cards]]
kanji = 'レジ'
kana = 'レジ'
english = '(cash) register'
source = 'wiki-n4'
level = 'n4'
tags = ['common', 'gairaigo', 'noun']
frequency_scores = { anime = 8918, leeds = 6245 }

[[cards]]
kanji = 'レポート'
kana = 'レポート'
english = 'report (gairaigo #1)'
source = 'wiki-n4'
level = 'n4'
tags = ['common', 'gairaigo', 'noun']
frequency_scores = { anime = 4556, leeds = 1557, wikipedia = 7557 }

[[cards]]
kanji = 'ワープロ'
kana = 'ワープロ'
english = 'word processor'
source = 'wiki-n4'
level = 'n4'
tags = ['common', 'computer', 'gairaigo', 'noun', 'program']
frequency_scores = { anime = 39232, leeds = 11338 }

