[[cards]]
kanji = 'オートバイ'
kana = 'オートバイ'
english = 'motorcycle'
source = 'n4 wiktionary'
level = 'n4'
tags = ['common', 'gairaigo', 'noun', 'transportation']

[[cards]]
kanji = 'カーテン'
kana = 'カーテン'
english = 'curtain'
source = 'n4-wiki'
level = 'n4'
tags = ['common', 'house', 'noun', 'window']

[[cards]]
kanji = 'ガス'
kana = 'ガス'
english = 'gas'
source = 'n4 wiktionary'
level = 'n4'
tags = ['chemistry', 'common', 'gairaigo', 'noun']

[[cards]]
kanji = 'ガソリン'
kana = 'ガソリン'
english = 'gasoline'
source = 'n4 wiktionary'
level = 'n4'
tags = ['automotive', 'common', 'gairaigo', 'noun']

[[cards]]
kanji = 'ガソリンスタンド'
kana = 'ガソリンスタンド'
english = 'gas station'
source = 'n4-wiki'
level = 'n4'
tags = ['common', 'noun', 'places', 'travel']

[[cards]]
kanji = 'ケーキ'
kana = 'ケーキ'
english = 'cake'
source = 'irasshai'
level = 'n4'
tags = ['common', 'dessert', 'food', 'noun']

[[cards]]
kanji = 'ゲーム'
kana = 'ゲーム'
english = 'game'
level = 'n3'
tags = ['common', 'gairaigo', 'games', 'noun', 'video games']

[[cards]]
kanji = 'コンサート'
kana = 'コンサート'
english = 'concert'
source = 'n4-wiki'
level = 'n4'
tags = ['common', 'event', 'music', 'noun']

[[cards]]
kanji = 'コンピューター'
kana = 'コンピューター'
english = 'computer'
source = 'irasshai'
level = 'n4'
tags = ['common', 'electronics', 'gairaigo', 'noun', 'technology']

[[cards]]
kanji = 'コート'
kana = 'コート'
english = 'coat'
source = 'irasshai'
level = 'n5'
tags = ['clothing', 'common', 'gairaigo', 'noun']

[[cards]]
kanji = 'サラダ'
kana = 'サラダ'
english = 'salad'
source = 'irasshai'
level = 'n4'
tags = ['common', 'food', 'noun']

[[cards]]
kanji = 'サンダル'
kana = 'サンダル'
english = 'sandals'
source = 'n4-study'
level = 'n4'
tags = ['clothing', 'common', 'footwear', 'noun', 'shoes']

[[cards]]
kanji = 'サンドイッチ'
kana = 'サンドイッチ'
english = 'sandwich'
source = 'irasshai; n4 wiktionary'
level = 'n4'
tags = ['common', 'food', 'gairaigo']

[[cards]]
kanji = 'ジャム'
kana = 'ジャム'
english = 'jam'
source = 'n4 wiktionary'
level = 'n4'
tags = ['common', 'food', 'gairaigo', 'noun']

[[cards]]
kanji = 'ステレオ'
kana = 'ステレオ'
english = 'stereo'
source = 'irasshai'
level = 'n4'
tags = ['common', 'gairaigo', 'noun']

[[cards]]
kanji = 'ステーキ'
kana = 'ステーキ'
english = 'steak'
level = 'n4'
tags = ['common', 'food', 'gairaigo', 'noun']

[[cards]]
kanji = 'スーツ'
kana = 'スーツ'
english = 'suit (gairaigo)'
source = 'n4 wiktionary'
level = 'n4'
tags = ['clothing', 'common', 'gairaigo', 'noun']

[[cards]]
kanji = 'スーツケース'
kana = 'スーツケース'
english = 'suitcase'
source = 'wiki-n4'
level = 'n4'
tags = ['common', 'gairaigo', 'noun', 'office', 'work']

[[cards]]
kanji = 'ソフト'
kana = 'ソフト'
english = 'soft (gairaigo)'
source = 'wiki-n4'
level = 'n4'
tags = ['common', 'gairaigo', 'na-adjective', 'no-adjective']

[[cards]]
kanji = 'タイプ'
kana = 'タイプ'
english = 'type (gairaigo)'
source = 'wiki-n4'
level = 'n4'
tags = ['common', 'gairaigo', 'noun']

[[cards]]
kanji = 'テキスト'
kana = 'テキスト'
english = 'text'
source = 'n4 wiktionary'
level = 'n4'
tags = ['common', 'gairaigo', 'noun']

[[cards]]
kanji = 'テニス'
kana = 'テニス'
english = 'tennis'
level = 'n4'
tags = ['common', 'gairaigo', 'noun', 'sport']

[[cards]]
kanji = 'テープ'
kana = 'テープ'
english = 'tape'
source = 'irasshai'
level = 'n5'
tags = ['common', 'noun', 'office']

[[cards]]
kanji = 'テープレコーダー'
kana = 'テープレコーダー'
english = 'tape recorder'
level = 'n5'
tags = ['common', 'dated', 'electronics', 'gairaigo', 'noun']

[[cards]]
kanji = 'データ'
kana = 'データ'
english = 'data'
level = 'n1'
tags = ['common', 'gairaigo', 'noun']

[[cards]]
kanji = 'ドラゴン'
kana = 'ドラゴン'
english = 'dragon (gairaigo)'
tags = ['common', 'gairaigo', 'monster', 'mythology', 'noun']

[[cards]]
kanji = 'ハンター'
kana = 'ハンター'
english = 'hunter'
tags = ['common', 'gairaigo', 'noun']

[[cards]]
kanji = 'ハンドバッグ'
kana = 'ハンドバッグ'
english = 'handbag; purse'
source = 'wiki-n4'
level = 'n4'
tags = ['common', 'gairaigo', 'noun']

[[cards]]
kanji = 'パソコン'
kana = 'パソコン'
english = 'personal computer'
source = 'irasshai'
level = 'n4'
tags = ['common', 'gairaigo', 'no-adjective', 'noun']

[[cards]]
kanji = 'パート'
kana = 'パート'
english = 'part'
source = 'wiki-n4'
level = 'n4'
tags = ['common', 'gairaigo', 'noun']

[[cards]]
kanji = 'ファックス'
kana = 'ファックス'
english = 'fax'
source = 'wiki-n4'
level = 'n4'
tags = ['common', 'gairaigo', 'noun', 'suru-verb']

[[cards]]
kanji = 'ベル'
kana = 'ベル'
english = 'bell (gairaigo)'
source = 'wiki-n4'
level = 'n4'
tags = ['common', 'gairaigo', 'noun']

[[cards]]
kanji = 'メートル'
kana = 'メートル'
english = 'meter'
level = 'n5'
tags = ['common', 'dimensions', 'gairaigo', 'measure', 'noun']

[[cards]]
kanji = 'ライブ'
kana = 'ライブ'
english = 'live (eg performance, concert)'
tags = ['common', 'gairaigo', 'noun', 'noun-or-verb-acting-prenominally']

[[cards]]
kanji = 'レジ'
kana = 'レジ'
english = '(cash) register'
source = 'wiki-n4'
level = 'n4'
tags = ['common', 'gairaigo', 'noun']

[[cards]]
kanji = 'ワープロ'
kana = 'ワープロ'
english = 'word processor'
source = 'wiki-n4'
level = 'n4'
tags = ['common', 'computer', 'gairaigo', 'noun', 'program']

