[[cards]]
kanji = 'アイドル'
kana = 'アイドル'
english = 'member of a jpop band'
source = 'jpop; culture'
tags = ['common', 'gairaigo', 'noun', 'people']
highest_frequency = 1222
highest_frequency_source = 'Anime'

[[cards]]
kanji = 'オートバイ'
kana = 'オートバイ'
english = 'motorcycle'
source = 'n4 wiktionary'
level = 'n4'
tags = ['common', 'gairaigo', 'noun', 'transportation']
highest_frequency = 5227
highest_frequency_source = 'Wikipedia'

[[cards]]
kanji = 'カーテン'
kana = 'カーテン'
english = 'curtain'
source = 'n4-wiki'
level = 'n4'
tags = ['common', 'house', 'noun', 'window']
highest_frequency = 7697
highest_frequency_source = 'Leeds'

[[cards]]
kanji = 'カード'
kana = 'カード'
english = 'card'
level = 'n3'
tags = ['common', 'electronics', 'gairaigo', 'noun']
highest_frequency = 533
highest_frequency_source = 'Wikipedia'

[[cards]]
kanji = 'ガス'
kana = 'ガス'
english = 'gas'
source = 'n4 wiktionary'
level = 'n4'
tags = ['chemistry', 'common', 'gairaigo', 'noun']
highest_frequency = 1430
highest_frequency_source = 'Wikipedia'

[[cards]]
kanji = 'ガソリン'
kana = 'ガソリン'
english = 'gasoline'
source = 'n4 wiktionary'
level = 'n4'
tags = ['automotive', 'common', 'gairaigo', 'noun']
highest_frequency = 4438
highest_frequency_source = 'Wikipedia'

[[cards]]
kanji = 'ガソリンスタンド'
kana = 'ガソリンスタンド'
english = 'gas station'
source = 'n4-wiki'
level = 'n4'
tags = ['common', 'noun', 'places', 'travel']
highest_frequency = 38279
highest_frequency_source = 'Anime'

[[cards]]
kanji = '瓩'
kana = 'キログラム'
english = 'kilogram'
source = 'wiki-n5'
level = 'n5'
tags = ['ateji', 'common', 'dimensions', 'gairaigo', 'mass', 'noun', 'numbers', 'unit-of-measure', 'weight']
highest_frequency = 23914
highest_frequency_source = 'Anime'

[[cards]]
kanji = '粁'
kana = 'キロメートル'
english = 'kilometer'
source = 'wiki-n5'
level = 'n5'
tags = ['ateji', 'common', 'dimensions', 'distance', 'gairaigo', 'noun', 'numbers', 'unit-of-measure']
highest_frequency = 22582
highest_frequency_source = 'Anime'

[[cards]]
kanji = 'ケーキ'
kana = 'ケーキ'
english = 'cake'
source = 'irasshai'
level = 'n4'
tags = ['common', 'dessert', 'food', 'noun']
highest_frequency = 1396
highest_frequency_source = 'Anime'

[[cards]]
kanji = 'ゲーム'
kana = 'ゲーム'
english = 'game'
level = 'n3'
tags = ['common', 'gairaigo', 'games', 'noun', 'video games']
highest_frequency = 158
highest_frequency_source = 'Wikipedia'

[[cards]]
kanji = 'コンサート'
kana = 'コンサート'
english = 'concert'
source = 'n4-wiki'
level = 'n4'
tags = ['common', 'event', 'music', 'noun']
highest_frequency = 1868
highest_frequency_source = 'Wikipedia'

[[cards]]
kanji = 'コンピューター'
kana = 'コンピューター'
english = 'computer'
source = 'irasshai'
level = 'n4'
tags = ['common', 'electronics', 'gairaigo', 'noun', 'technology']
highest_frequency = 930
highest_frequency_source = 'Wikipedia'

[[cards]]
kanji = 'コート'
kana = 'コート'
english = 'coat'
source = 'irasshai'
level = 'n5'
tags = ['clothing', 'common', 'gairaigo', 'noun']
highest_frequency = 2719
highest_frequency_source = 'Novels'

[[cards]]
kanji = 'サラダ'
kana = 'サラダ'
english = 'salad'
source = 'irasshai'
level = 'n4'
tags = ['common', 'food', 'noun']
highest_frequency = 5417
highest_frequency_source = 'Leeds'

[[cards]]
kanji = 'サンダル'
kana = 'サンダル'
english = 'sandals'
source = 'n4-study'
level = 'n4'
tags = ['clothing', 'common', 'footwear', 'noun', 'shoes']
highest_frequency = 13167
highest_frequency_source = 'Leeds'

[[cards]]
kanji = 'サンドイッチ'
kana = 'サンドイッチ'
english = 'sandwich'
source = 'irasshai; n4 wiktionary'
level = 'n4'
tags = ['common', 'food', 'gairaigo']
highest_frequency = 10232
highest_frequency_source = 'Anime'

[[cards]]
kanji = 'ジャム'
kana = 'ジャム'
english = 'jam'
source = 'n4 wiktionary'
level = 'n4'
tags = ['common', 'food', 'gairaigo', 'noun']
highest_frequency = 9839
highest_frequency_source = 'Anime'

[[cards]]
kanji = 'スクリーン'
kana = 'スクリーン'
english = 'screen'
source = 'wiki-n4'
level = 'n4'
tags = ['common', 'gairaigo', 'noun']
highest_frequency = 2238
highest_frequency_source = 'Novels'

[[cards]]
kanji = 'ステレオ'
kana = 'ステレオ'
english = 'stereo'
source = 'irasshai'
level = 'n4'
tags = ['common', 'gairaigo', 'noun']
highest_frequency = 6757
highest_frequency_source = 'Wikipedia'

[[cards]]
kanji = 'ステーキ'
kana = 'ステーキ'
english = 'steak'
level = 'n4'
tags = ['common', 'food', 'gairaigo', 'noun']
highest_frequency = 8610
highest_frequency_source = 'Anime'

[[cards]]
kanji = 'スーツ'
kana = 'スーツ'
english = 'suit (gairaigo)'
source = 'n4 wiktionary'
level = 'n4'
tags = ['clothing', 'common', 'gairaigo', 'noun']
highest_frequency = 4681
highest_frequency_source = 'Leeds'

[[cards]]
kanji = 'スーツケース'
kana = 'スーツケース'
english = 'suitcase'
source = 'wiki-n4'
level = 'n4'
tags = ['common', 'gairaigo', 'noun', 'office', 'work']
highest_frequency = 30094
highest_frequency_source = 'Anime'

[[cards]]
kanji = 'ソフト'
kana = 'ソフト'
english = 'soft (gairaigo)'
source = 'wiki-n4'
level = 'n4'
tags = ['common', 'gairaigo', 'na-adjective', 'no-adjective']
highest_frequency = 996
highest_frequency_source = 'Wikipedia'

[[cards]]
kanji = 'タイプ'
kana = 'タイプ'
english = 'type (gairaigo)'
source = 'wiki-n4'
level = 'n4'
tags = ['common', 'gairaigo', 'noun']
highest_frequency = 1055
highest_frequency_source = 'Wikipedia'

[[cards]]
kanji = 'タイム'
kana = 'タイム'
english = 'time (gairaigo)'
source = 'anime-freq'
level = 'n1'
tags = ['common', 'gairaigo']
highest_frequency = 1198
highest_frequency_source = 'Anime'

[[cards]]
kanji = 'テキスト'
kana = 'テキスト'
english = 'text'
source = 'n4 wiktionary'
level = 'n4'
tags = ['common', 'gairaigo', 'noun']
highest_frequency = 2331
highest_frequency_source = 'Leeds'

[[cards]]
kanji = 'テニス'
kana = 'テニス'
english = 'tennis'
level = 'n4'
tags = ['common', 'gairaigo', 'noun', 'sport']
highest_frequency = 2395
highest_frequency_source = 'Wikipedia'

[[cards]]
kanji = 'テープ'
kana = 'テープ'
english = 'tape'
source = 'irasshai'
level = 'n5'
tags = ['common', 'noun', 'office']
highest_frequency = 3837
highest_frequency_source = 'Wikipedia'

[[cards]]
kanji = 'テープレコーダー'
kana = 'テープレコーダー'
english = 'tape recorder'
level = 'n5'
tags = ['common', 'dated', 'electronics', 'gairaigo', 'noun']
highest_frequency = 37501
highest_frequency_source = 'Anime'

[[cards]]
kanji = 'データ'
kana = 'データ'
english = 'data'
level = 'n1'
tags = ['common', 'gairaigo', 'noun']
highest_frequency = 594
highest_frequency_source = 'Leeds'

[[cards]]
kanji = 'ドラゴン'
kana = 'ドラゴン'
english = 'dragon (gairaigo)'
tags = ['common', 'gairaigo', 'monster', 'mythology', 'noun']
highest_frequency = 1147
highest_frequency_source = 'Anime'

[[cards]]
kanji = 'ハンター'
kana = 'ハンター'
english = 'hunter'
tags = ['common', 'gairaigo', 'noun']
highest_frequency = 1189
highest_frequency_source = 'Anime'

[[cards]]
kanji = 'ハンドバッグ'
kana = 'ハンドバッグ'
english = 'handbag; purse'
source = 'wiki-n4'
level = 'n4'
tags = ['common', 'gairaigo', 'noun']

[[cards]]
kanji = 'パソコン'
kana = 'パソコン'
english = 'personal computer'
source = 'irasshai'
level = 'n4'
tags = ['common', 'gairaigo', 'no-adjective', 'noun']
highest_frequency = 898
highest_frequency_source = 'Leeds'

[[cards]]
kanji = 'パート'
kana = 'パート'
english = 'part'
source = 'wiki-n4'
level = 'n4'
tags = ['common', 'gairaigo', 'noun']
highest_frequency = 3795
highest_frequency_source = 'Wikipedia'

[[cards]]
kanji = 'ビル'
kana = 'ビル'
english = 'multi-floor building (gairaigo)'
source = 'wiki-n4'
level = 'n4'
tags = ['common', 'gairaigo', 'noun']
highest_frequency = 797
highest_frequency_source = 'Wikipedia'

[[cards]]
kanji = 'ピアノ'
kana = 'ピアノ'
english = 'piano'
source = 'wiki-n4'
level = 'n4'
tags = ['common', 'gairaigo', 'noun']
highest_frequency = 1517
highest_frequency_source = 'Wikipedia'

[[cards]]
kanji = 'ファックス'
kana = 'ファックス'
english = 'fax'
source = 'wiki-n4'
level = 'n4'
tags = ['common', 'gairaigo', 'noun', 'suru-verb']
highest_frequency = 10478
highest_frequency_source = 'Leeds'

[[cards]]
kanji = 'ブロック'
kana = 'ブロック'
english = 'block; blocking'
source = 'anime-freq'
tags = ['common', 'gairaigo']
highest_frequency = 1142
highest_frequency_source = 'Anime'

[[cards]]
kanji = 'プレゼント'
kana = 'プレゼント'
english = 'present (gairaigo)'
source = 'wiki-n4'
level = 'n4'
tags = ['common', 'gairaigo', 'noun']
highest_frequency = 1341
highest_frequency_source = 'Anime'

[[cards]]
kanji = 'ベル'
kana = 'ベル'
english = 'bell (gairaigo)'
source = 'wiki-n4'
level = 'n4'
tags = ['common', 'gairaigo', 'noun']
highest_frequency = 2086
highest_frequency_source = 'Novels'

[[cards]]
kanji = 'マスター'
kana = 'マスター'
english = 'master (gairaigo)'
source = 'anime-freq'
level = 'n3'
tags = ['common', 'gairaigo', 'noun', 'suru-verb']
highest_frequency = 372
highest_frequency_source = 'Anime'

[[cards]]
kanji = 'メートル'
kana = 'メートル'
english = 'meter'
level = 'n5'
tags = ['common', 'dimensions', 'gairaigo', 'measure', 'noun']
highest_frequency = 678
highest_frequency_source = 'Novels'

[[cards]]
kanji = 'ライブ'
kana = 'ライブ'
english = 'live (eg performance, concert)'
tags = ['common', 'gairaigo', 'noun', 'noun-or-verb-acting-prenominally']
highest_frequency = 916
highest_frequency_source = 'Wikipedia'

[[cards]]
kanji = 'ラジオカセット'
kana = 'ラジオカセット'
english = 'radio-cassette (full word)'
source = 'wiki-n5'
tags = ['gairaigo', 'noun', 'uncommon']

[[cards]]
kanji = 'ラジカセ'
kana = 'ラジカセ'
english = 'radio-cassette player (shortened word)'
source = 'wiki-n5'
level = 'n5'
tags = ['common', 'gairaigo', 'noun', 'old-technology', 'technology']
highest_frequency = 34005
highest_frequency_source = 'Anime'

[[cards]]
kanji = 'リポート'
kana = 'リポート'
english = 'report (gairaigo #2)'
source = 'wiki-n4'
level = 'n4'
tags = ['common', 'gairaigo', 'noun']
highest_frequency = 11125
highest_frequency_source = 'Leeds'

[[cards]]
kanji = 'リーダー'
kana = 'リーダー'
english = 'leader (gairaigo)'
source = 'anime-freq'
tags = ['common', 'no-adjective', 'noun']
highest_frequency = 1525
highest_frequency_source = 'Anime'

[[cards]]
kanji = 'レジ'
kana = 'レジ'
english = '(cash) register'
source = 'wiki-n4'
level = 'n4'
tags = ['common', 'gairaigo', 'noun']
highest_frequency = 6245
highest_frequency_source = 'Leeds'

[[cards]]
kanji = 'レポート'
kana = 'レポート'
english = 'report (gairaigo #1)'
source = 'wiki-n4'
level = 'n4'
tags = ['common', 'gairaigo', 'noun']
highest_frequency = 1557
highest_frequency_source = 'Leeds'

[[cards]]
kanji = 'ワープロ'
kana = 'ワープロ'
english = 'word processor'
source = 'wiki-n4'
level = 'n4'
tags = ['common', 'computer', 'gairaigo', 'noun', 'program']
highest_frequency = 11338
highest_frequency_source = 'Leeds'

