[[cards]]
kanji = 'けんか・する'
kana = 'けんか・する'
english = 'to quarrel'
source = 'wiktionary'
level = 'N4'
tags = ['generated', 'tsv']

[[cards]]
kanji = 'チェック・する'
kana = 'チェック・する'
english = 'to check'
source = 'wiktionary'
level = 'N4'
tags = ['generated', 'tsv']

[[cards]]
kanji = 'チェック・する'
kana = 'チェック・する'
english = 'to check'
source = 'wiktionary'
level = 'N4'
tags = ['generated', 'tsv']

