[[cards]]
kanji = '足'
kana = 'あし'
english = 'foot; leg'
make_kanji_card = true
hide_hiragana_card = true
level = 'n5'
tags = ['body', 'common']

[[cards]]
kanji = '頭'
kana = 'あたま'
english = 'head'
level = 'n5'
tags = ['anatomy', 'body', 'common']

[[cards]]
kanji = '医者'
kana = 'いしゃ'
english = 'doctor'
level = 'n5'
tags = ['common', 'people']

[[cards]]
kanji = '痛い'
kana = 'いたい'
english = 'painful ; sore'
level = 'n5'
tags = ['common', 'i-adjectives']

[[cards]]
kanji = 'お腹'
kana = 'おなか'
english = 'stomach'
level = 'n5'
tags = []

[[cards]]
kanji = '顔'
kana = 'かお'
english = 'face'
level = 'n5'
tags = []

[[cards]]
kanji = '風邪'
kana = 'かぜ'
english = 'cold; illness'
level = 'n5'
tags = []

[[cards]]
kanji = '体'
kana = 'からだ'
english = 'body'
make_kanji_card = true
hide_hiragana_card = true
level = 'n5'
tags = []

[[cards]]
kanji = '筋肉'
kana = 'きんにく'
english = 'muscle'
level = 'n3'
source = 'manga'
tags = ['common']

[[cards]]
kanji = '薬'
kana = 'くすり'
english = 'medicine'
level = 'n5'
tags = []

[[cards]]
kanji = '口'
kana = 'くち'
english = 'mouth; opening'
level = 'n5'
make_kanji_card = true
hide_hiragana_card = true
tags = []

[[cards]]
kanji = '元気'
kana = 'げんき'
english = 'lively; healthy'
level = 'n5'
make_kanji_card = true
hide_hiragana_card = true
tags = []

[[cards]]
kanji = '声'
kana = 'こえ'
english = 'voice'
level = 'n5'
tags = []

[[cards]]
kanji = '丈夫'
kana = 'じょうぶ'
english = 'healthy; strong; solid; robust'
level = 'n5'
tags = []

[[cards]]
kanji = '背'
kana = 'せい'
english = 'height'
level = 'n5'
tags = []

[[cards]]
kanji = '煙草'
kana = 'たばこ'
english = 'tabacco; cigarettes'
level = 'n5'
tags = []

[[cards]]
kanji = '手'
kana = 'て'
english = 'hand; arm'
level = 'n5'
make_kanji_card = true
hide_hiragana_card = true
tags = []

[[cards]]
kanji = '涙'
kana = 'なみだ'
english = 'tear(s)'
level = 'n3'
tags = ['body', 'common']

[[cards]]
kanji = '歯'
kana = 'は'
english = 'tooth'
level = 'n5'
tags = []

[[cards]]
kanji = '灰皿'
kana = 'はいざら'
english = 'ashtray'
level = 'n5'
tags = []

[[cards]]
kanji = '鼻'
kana = 'はな'
english = 'nose'
level = 'n5'
tags = []

[[cards]]
kanji = 'ひたい'
kana = 'ひたい'
english = 'forehead'
level = 'n3'
source = 'wanikani'
tags = ['body', 'common', 'noun']

[[cards]]
kanji = '病院'
kana = 'びょういん'
english = 'hospital'
level = 'n5'
tags = []

[[cards]]
kanji = '病気'
kana = 'びょうき'
english = 'sickness; illness; disease'
level = 'n5'
tags = []

[[cards]]
kanji = '太い'
kana = 'ふとい'
english = 'fat; thick'
level = 'n5'
make_kanji_card = true
hide_hiragana_card = true
tags = []

[[cards]]
kanji = '細い'
kana = 'ほそい'
english = 'thin; slender'
level = 'n5'
tags = []

[[cards]]
kanji = '骨'
kana = 'ほね'
english = 'bone'
level = 'n3'
tags = ['body', 'common']

[[cards]]
kanji = '耳'
kana = 'みみ'
english = 'ear'
level = 'n5'
make_kanji_card = true
hide_hiragana_card = true
tags = []

[[cards]]
kanji = '目'
kana = 'め'
english = 'eye; eyeball'
level = 'n5'
make_kanji_card = true
hide_hiragana_card = true
tags = []

[[cards]]
kanji = '眼鏡'
kana = 'めがね'
english = 'eyeglasses'
level = 'n5'
tags = []

[[cards]]
kanji = '目玉'
kana = 'めだま'
english = 'eyeball'
make_kanji_card = true
hide_hiragana_card = true
source = 'wanikani'
tags = ['body', 'common']

