[[cards]]
kanji = '欠伸'
kana = 'あくび'
english = 'yawn'
level = 'n2'
source = 'wanikani'
tags = ['common']

[[cards]]
kanji = '足'
kana = 'あし'
english = 'foot; leg'
make_kanji_card = true
hide_hiragana_card = true
level = 'n5'
tags = ['body', 'common']

[[cards]]
kanji = '頭'
kana = 'あたま'
english = 'head'
level = 'n5'
tags = ['anatomy', 'body', 'common']

[[cards]]
kanji = '息'
kana = 'いき'
english = 'breath; breathing'
level = 'n3'
tags = ['biology', 'common', 'noun']

[[cards]]
kanji = '医者'
kana = 'いしゃ'
english = 'doctor'
level = 'n5'
tags = ['common', 'people']

[[cards]]
kanji = '痛い'
kana = 'いたい'
english = 'painful ; sore'
level = 'n5'
tags = ['common', 'i-adjectives']

[[cards]]
kanji = '腕'
kana = 'うで'
english = 'arm'
level = 'n4'
tags = ['body', 'noun']

[[cards]]
kanji = '運動'
kana = 'うんどう'
english = 'exercise'
level = 'n3'
tags = ['activity', 'common', 'health', 'noun', 'suru-verb']

[[cards]]
kanji = 'お腹'
kana = 'おなか'
english = 'stomach'
level = 'n5'
tags = []

[[cards]]
kanji = '顔'
kana = 'かお'
english = 'face'
level = 'n5'
tags = []

[[cards]]
kanji = '踵'
kana = 'かかと'
english = 'heel'
level = 'n1'
tags = ['body', 'common']

[[cards]]
kanji = '風邪'
kana = 'かぜ'
english = 'cold; illness'
level = 'n5'
tags = []

[[cards]]
kanji = '体'
kana = 'からだ'
english = 'body'
make_kanji_card = true
hide_hiragana_card = true
level = 'n5'
tags = []

[[cards]]
kanji = '渇き'
kana = 'かわき'
english = 'thirst'
tags = ['common', 'noun']

[[cards]]
kanji = '看護師'
kana = 'かんごし'
english = 'nurse'
level = 'n4'
source = 'https://www.japanesepod101.com/japanese-word-lists/'
tags = ['common', 'noun', 'people', 'profession']

[[cards]]
kanji = '筋肉'
kana = 'きんにく'
english = 'muscle'
level = 'n3'
source = 'manga'
tags = ['common']

[[cards]]
kanji = '薬'
kana = 'くすり'
english = 'medicine'
level = 'n5'
tags = []

[[cards]]
kanji = '口'
kana = 'くち'
english = 'mouth; opening'
level = 'n5'
make_kanji_card = true
hide_hiragana_card = true
tags = []

[[cards]]
kanji = '首'
kana = 'くび'
english = 'neck'
level = 'n4'
tags = ['body', 'common']

[[cards]]
kanji = '怪我'
kana = 'けが'
english = 'injury'
level = 'n3'
source = 'wanikani'
tags = ['common', 'noun', 'suru-verb']

[[cards]]
kanji = '元気'
kana = 'げんき'
english = 'lively; healthy'
level = 'n5'
make_kanji_card = true
hide_hiragana_card = true
tags = []

[[cards]]
kanji = '声'
kana = 'こえ'
english = 'voice'
level = 'n5'
tags = []

[[cards]]
kanji = '丈夫'
kana = 'じょうぶ'
english = 'healthy; strong; solid; robust'
level = 'n5'
tags = []

[[cards]]
kanji = '背'
kana = 'せい'
english = 'height'
level = 'n5'
tags = []

[[cards]]
kanji = '背中'
kana = 'せなか'
english = 'back (of body)'
level = 'n4'
source = 'https://www.japanesepod101.com/japanese-word-lists/'
tags = ['body', 'common']

[[cards]]
kanji = '煙草'
kana = 'たばこ'
english = 'tabacco; cigarettes'
level = 'n5'
tags = []

[[cards]]
kanji = '手'
kana = 'て'
english = 'hand; arm'
level = 'n5'
make_kanji_card = true
hide_hiragana_card = true
tags = []

[[cards]]
kanji = '涙'
kana = 'なみだ'
english = 'tear(s)'
level = 'n3'
tags = ['body', 'common']

[[cards]]
kanji = '歯'
kana = 'は'
english = 'tooth'
level = 'n5'
tags = []

[[cards]]
kanji = '灰皿'
kana = 'はいざら'
english = 'ashtray'
level = 'n5'
tags = []

[[cards]]
kanji = '鼻'
kana = 'はな'
english = 'nose'
level = 'n5'
tags = []

[[cards]]
kanji = '額'
kana = 'ひたい'
english = 'forehead'
level = 'n3'
source = 'wanikani'
tags = ['body', 'common', 'noun']

[[cards]]
kanji = '病院'
kana = 'びょういん'
english = 'hospital'
level = 'n5'
tags = []

[[cards]]
kanji = '病気'
kana = 'びょうき'
english = 'sickness; illness; disease'
level = 'n5'
tags = []

[[cards]]
kanji = '太い'
kana = 'ふとい'
english = 'fat; thick'
level = 'n5'
tags = ['common', 'i-adjective']

[[cards]]
kanji = '細い'
kana = 'ほそい'
english = 'thin; slender'
level = 'n5'
tags = []

[[cards]]
kanji = '骨'
kana = 'ほね'
english = 'bone'
level = 'n3'
tags = ['body', 'common']

[[cards]]
kanji = '眉毛'
kana = 'まゆげ'
english = 'eyebrow'
source = 'wanikani'
tags = ['common', 'no-adjective', 'noun']

[[cards]]
kanji = '耳'
kana = 'みみ'
english = 'ear'
level = 'n5'
tags = ['body', 'common', 'noun']

[[cards]]
kanji = '目'
kana = 'め'
english = 'eye; eyeball'
level = 'n5'
make_kanji_card = true
hide_hiragana_card = true
tags = []

[[cards]]
kanji = '眼鏡'
kana = 'めがね'
english = 'eyeglasses'
level = 'n5'
tags = []

[[cards]]
kanji = '目玉'
kana = 'めだま'
english = 'eyeball'
make_kanji_card = true
hide_hiragana_card = true
source = 'wanikani'
tags = ['body', 'common']

[[cards]]
kanji = '指'
kana = 'ゆび'
english = 'finger; toe'
level = 'n4'
tags = ['body', 'common']

