[[cards]]
kanji = 'ああ'
kana = 'ああ'
english = 'like that (distant)'
level = 'n4'
source = 'jlptstudy.net'
tags = ['adverb', 'common']
highest_frequency = 178
highest_frequency_source = 'Novels'

[[cards]]
kanji = '彼処'
kana = 'あそこ'
english = 'there (way over there)'
level = 'n5'
tags = ['common', 'place']
highest_frequency = 1436
highest_frequency_source = 'Novels'

[[cards]]
kanji = '彼方'
kana = 'あちら'
english = 'that way (way over there); that one (way over there)'
level = 'n5'
tags = ['common', 'place']
highest_frequency = 2316
highest_frequency_source = 'Novels'

[[cards]]
kanji = 'あっち'
kana = 'あっち'
english = 'over there; that way'
level = 'n5'
tags = ['common', 'directions', 'locations', 'places']
highest_frequency = 817
highest_frequency_source = 'Anime'

[[cards]]
kanji = '彼の'
kana = 'あの'
english = 'that (way over there)'
level = 'n5'
tags = ['common', 'locations', 'places']
highest_frequency = 87
highest_frequency_source = 'Novels'

[[cards]]
kanji = '彼'
kana = 'あれ'
english = 'that (way over there)'
level = 'n5'
tags = ['common', 'kosoado', 'locations', 'places']
highest_frequency = 74
highest_frequency_source = 'Novels'

[[cards]]
kanji = '此奴'
kana = 'こいつ'
english = 'this person; this guy'
source = 'anime'
tags = ['common', 'kosoado', 'pronoun']
highest_frequency = 148
highest_frequency_source = 'Anime'

[[cards]]
kanji = '此処'
kana = 'ここ'
english = 'here; this place'
level = 'n5'
tags = []
highest_frequency = 102
highest_frequency_source = 'Novels'

[[cards]]
kanji = '此方'
kana = 'こちら'
english = 'this way; here; this person'
level = 'n5'
tags = []
highest_frequency = 298
highest_frequency_source = 'Anime'

[[cards]]
kanji = '此方'
kana = 'こっち'
english = 'this way; here; this person'
level = 'n5'
tags = []
highest_frequency = 132
highest_frequency_source = 'Anime'

[[cards]]
kanji = '此の'
kana = 'この'
english = 'this (thing)'
level = 'n5'
tags = []
highest_frequency = 34
highest_frequency_source = 'Wikipedia'

[[cards]]
kanji = '此れ'
kana = 'これ'
english = 'this'
level = 'n5'
tags = []
highest_frequency = 28
highest_frequency_source = 'Anime'

[[cards]]
kanji = 'こんな'
kana = 'こんな'
english = 'such ~; something like this'
level = 'n5'
tags = []
highest_frequency = 188
highest_frequency_source = 'Novels'

[[cards]]
kanji = '其処'
kana = 'そこ'
english = 'that place; there'
level = 'n5'
tags = []
highest_frequency = 119
highest_frequency_source = 'Anime'

[[cards]]
kanji = '其方'
kana = 'そちら'
english = 'that place; that way; that person'
level = 'n5'
tags = []
highest_frequency = 1873
highest_frequency_source = 'Anime'

[[cards]]
kanji = '其方'
kana = 'そっち'
english = 'that place; that way; that person'
level = 'n5'
tags = []
highest_frequency = 474
highest_frequency_source = 'Anime'

[[cards]]
kanji = '其の'
kana = 'その'
english = 'that (thing)'
level = 'n5'
tags = []
highest_frequency = 36
highest_frequency_source = 'Wikipedia'

[[cards]]
kanji = '其れ'
kana = 'それ'
english = 'that'
level = 'n5'
tags = []
highest_frequency = 25
highest_frequency_source = 'Anime'

[[cards]]
kanji = '何処'
kana = 'どこ'
english = 'where'
level = 'n5'
tags = []
highest_frequency = 1925
highest_frequency_source = 'Novels'

[[cards]]
kanji = '何方'
kana = 'どちら'
english = 'which way? ; where?'
level = 'n5'
tags = []
highest_frequency = 913
highest_frequency_source = 'Novels'

[[cards]]
kanji = '何方'
kana = 'どっち'
english = 'which one? ; which way?'
level = 'n5'
tags = []
highest_frequency = 1645
highest_frequency_source = 'Novels'

[[cards]]
kanji = '何の'
kana = 'どの'
english = 'which?'
level = 'n5'
tags = []
highest_frequency = 347
highest_frequency_source = 'Leeds'

[[cards]]
kanji = '何れ'
kana = 'どれ'
english = 'which (of three or more)'
level = 'n5'
tags = []
highest_frequency = 1035
highest_frequency_source = 'Novels'

