[[cards]]
kanji = '彼処'
kana = 'あそこ'
english = 'there (way over there)'
level = 'n5'
tags = ['common', 'place']

[[cards]]
kanji = '彼方'
kana = 'あちら'
english = 'that way (way over there); that one (way over there)'
level = 'n5'
tags = ['common', 'place']

[[cards]]
kanji = 'あっち'
kana = 'あっち'
english = 'over there; that way'
level = 'n5'
tags = ['common', 'directions', 'locations', 'places']

[[cards]]
kanji = '彼の'
kana = 'あの'
english = 'that (way over there)'
level = 'n5'
tags = ['common', 'locations', 'places']

[[cards]]
kanji = '彼'
kana = 'あれ'
english = 'that (way over there)'
level = 'n5'
tags = ['common', 'kosoado', 'locations', 'places']

[[cards]]
kanji = '此奴'
kana = 'こいつ'
english = 'this person; this guy'
source = 'anime'
tags = ['common', 'kosoado', 'pronoun']

[[cards]]
kanji = '此処'
kana = 'ここ'
english = 'here; this place'
level = 'n5'
tags = []

[[cards]]
kanji = '此方'
kana = 'こちら'
english = 'this way; here; this person'
level = 'n5'
tags = []

[[cards]]
kanji = '此方'
kana = 'こっち'
english = 'this way; here; this person'
level = 'n5'
tags = []

[[cards]]
kanji = '此の'
kana = 'この'
english = 'this (thing)'
level = 'n5'
tags = []

[[cards]]
kanji = '此れ'
kana = 'これ'
english = 'this'
level = 'n5'
tags = []

[[cards]]
kanji = 'こんな'
kana = 'こんな'
english = 'such ~; something like this'
level = 'n5'
tags = []

[[cards]]
kanji = '其処'
kana = 'そこ'
english = 'that place; there'
level = 'n5'
tags = []

[[cards]]
kanji = '其方'
kana = 'そちら'
english = 'that place; that way; that person'
level = 'n5'
tags = []

[[cards]]
kanji = '其方'
kana = 'そっち'
english = 'that place; that way; that person'
level = 'n5'
tags = []

[[cards]]
kanji = '其の'
kana = 'その'
english = 'that (thing)'
level = 'n5'
tags = []

[[cards]]
kanji = '其れ'
kana = 'それ'
english = 'that'
level = 'n5'
tags = []

[[cards]]
kanji = '何処'
kana = 'どこ'
english = 'where'
level = 'n5'
tags = []

[[cards]]
kanji = '何方'
kana = 'どちら'
english = 'which way? ; where?'
make_kanji_card = true
level = 'n5'
tags = []

[[cards]]
kanji = '何方'
kana = 'どっち'
english = 'which one? ; which way?'
level = 'n5'
tags = []

[[cards]]
kanji = '何の'
kana = 'どの'
english = 'which?'
level = 'n5'
tags = []

[[cards]]
kanji = '何れ'
kana = 'どれ'
english = 'which (of three or more)'
level = 'n5'
tags = []

