[[cards]]
kanji = 'ああ'
kana = 'ああ'
english = 'like that (distant)'
level = 'n4'
source = 'jlptstudy.net'
tags = ['adverb', 'common']
frequency_scores = { leeds = 1251, novels = 178 }

[[cards]]
kanji = '彼処'
kana = 'あそこ'
english = 'there (way over there)'
level = 'n5'
tags = ['common', 'place']
frequency_scores = { anime = 42511, leeds = 4926, novels = 1436 }

[[cards]]
kanji = '彼方'
kana = 'あちら'
english = 'that way (way over there); that one (way over there)'
level = 'n5'
tags = ['common', 'place']
frequency_scores = { anime = 2633, leeds = 10987, novels = 2316 }

[[cards]]
kanji = 'あっち'
kana = 'あっち'
english = 'over there; that way'
level = 'n5'
tags = ['common', 'directions', 'locations', 'places']
frequency_scores = { anime = 817, leeds = 7309, novels = 2569 }

[[cards]]
kanji = '彼の'
kana = 'あの'
english = 'that (way over there)'
level = 'n5'
tags = ['common', 'locations', 'places']
frequency_scores = { leeds = 419, novels = 87, wikipedia = 5252 }

[[cards]]
kanji = '彼'
kana = 'あれ'
english = 'that (way over there)'
level = 'n5'
tags = ['common', 'kosoado', 'locations', 'places']
frequency_scores = { anime = 276, leeds = 225, novels = 74, wikipedia = 91 }

[[cards]]
kanji = '此奴'
kana = 'こいつ'
english = 'this person; this guy'
source = 'anime'
tags = ['common', 'kosoado', 'pronoun']
frequency_scores = { anime = 148, leeds = 4716, novels = 783 }

[[cards]]
kanji = '此処'
kana = 'ここ'
english = 'here; this place'
level = 'n5'
tags = []
frequency_scores = { anime = 6870, leeds = 13567, novels = 102, wikipedia = 475 }

[[cards]]
kanji = '此方'
kana = 'こちら'
english = 'this way; here; this person'
level = 'n5'
tags = []
frequency_scores = { anime = 298, leeds = 435, novels = 319, wikipedia = 2305 }

[[cards]]
kanji = '此方'
kana = 'こっち'
english = 'this way; here; this person'
level = 'n5'
tags = []
frequency_scores = { anime = 132, leeds = 2150, novels = 490 }

[[cards]]
kanji = '此の'
kana = 'この'
english = 'this (thing)'
level = 'n5'
tags = []
frequency_scores = { leeds = 47, novels = 39, wikipedia = 34 }

[[cards]]
kanji = '此れ'
kana = 'これ'
english = 'this'
level = 'n5'
tags = []
frequency_scores = { anime = 28, leeds = 69, novels = 70, wikipedia = 41 }

[[cards]]
kanji = 'こんな'
kana = 'こんな'
english = 'such ~; something like this'
level = 'n5'
tags = []
frequency_scores = { leeds = 354, novels = 188 }

[[cards]]
kanji = '其処'
kana = 'そこ'
english = 'that place; there'
level = 'n5'
tags = []
frequency_scores = { anime = 119, leeds = 283, novels = 132, wikipedia = 480 }

[[cards]]
kanji = '其方'
kana = 'そちら'
english = 'that place; that way; that person'
level = 'n5'
tags = []
frequency_scores = { anime = 1873, leeds = 4104, novels = 2321 }

[[cards]]
kanji = '其方'
kana = 'そっち'
english = 'that place; that way; that person'
level = 'n5'
tags = []
frequency_scores = { anime = 474, leeds = 6280, novels = 1960 }

[[cards]]
kanji = '其の'
kana = 'その'
english = 'that (thing)'
level = 'n5'
tags = []
frequency_scores = { leeds = 9570, novels = 1549, wikipedia = 36 }

[[cards]]
kanji = '其れ'
kana = 'それ'
english = 'that'
level = 'n5'
tags = []
frequency_scores = { anime = 25, leeds = 65, novels = 30, wikipedia = 73 }

[[cards]]
kanji = 'そんな'
kana = 'そんな'
english = 'that sort of'
source = 'wiktionary'
level = 'n4'
tags = ['generated', 'tsv']

[[cards]]
kanji = '何処'
kana = 'どこ'
english = 'where'
level = 'n5'
tags = []
frequency_scores = { anime = 2091, leeds = 4334, novels = 1925, wikipedia = 3088 }

[[cards]]
kanji = '何方'
kana = 'どちら'
english = 'which way? ; where?'
level = 'n5'
tags = []
frequency_scores = { anime = 19563, leeds = 995, novels = 913, wikipedia = 1971 }

[[cards]]
kanji = '何方'
kana = 'どっち'
english = 'which one? ; which way?'
level = 'n5'
tags = []
frequency_scores = { anime = 19563, leeds = 2842, novels = 1645 }

[[cards]]
kanji = '何の'
kana = 'どの'
english = 'which?'
level = 'n5'
tags = []
frequency_scores = { leeds = 347, novels = 605, wikipedia = 7466 }

[[cards]]
kanji = '何れ'
kana = 'どれ'
english = 'which (of three or more)'
level = 'n5'
tags = []
frequency_scores = { anime = 25706, leeds = 1040, novels = 1035, wikipedia = 5247 }

