[[cards]]
kanji = '音読み'
kana = 'おんよみ'
english = 'Chinese-derived reading of Kanji'
source = 'irasshai'
tags = ['common', 'noun', 'suru-verb']
highest_frequency = 33035
highest_frequency_source = 'Anime'

[[cards]]
kanji = '訓読み'
kana = 'くんよみ'
source = 'irasshai'
english = 'native Japanese reading of Kanji'
tags = ['common', 'noun', 'suru-verb']
highest_frequency = 38528
highest_frequency_source = 'Anime'

[[cards]]
kanji = '敬語'
kana = 'けいご'
english = 'honorific language'
level = 'n2'
tags = ['common']
highest_frequency = 8689
highest_frequency_source = 'Anime'

[[cards]]
kanji = '謙譲語'
kana = 'けんじょうご'
english = 'humble language (humble keigo); speaking about oneself to those in power'
tags = ['uncommon']

[[cards]]
kanji = '尊敬語'
kana = 'そんけいご'
english = 'honorific language (honorific keigo); spoken about or to those in power'
tags = ['uncommon']

[[cards]]
kanji = '丁寧語'
kana = 'ていねいご'
english = 'polite language (eg masu, desu)'
tags = ['uncommon']

[[cards]]
kanji = '動詞'
kana = 'どうし'
english = 'verb'
level = 'n3'
tags = ['common']
highest_frequency = 6170
highest_frequency_source = 'Wikipedia'

[[cards]]
kanji = '方言'
kana = 'ほうげん'
english = 'dialect'
source = 'living-in-japan; wanikani'
level = 'n2'
tags = ['common', 'no-adjective', 'noun']
highest_frequency = 3418
highest_frequency_source = 'Wikipedia'

[[cards]]
kanji = '名詞'
kana = 'めいし'
english = 'noun'
level = 'n2'
tags = ['common']
highest_frequency = 5658
highest_frequency_source = 'Wikipedia'

[[cards]]
kanji = '文字'
kana = 'もじ'
english = 'letter (alphabet)'
level = 'n3'
source = 'wanikani'
tags = ['common', 'noun']
highest_frequency = 626
highest_frequency_source = 'Wikipedia'

