[[cards]]
kanji = '音読み'
kana = 'おんよみ'
english = 'Chinese-derived reading of Kanji'
source = 'irasshai'
tags = ['common', 'noun', 'suru-verb']
frequency_scores = { anime = 33035 }

[[cards]]
kanji = '訓読み'
kana = 'くんよみ'
source = 'irasshai'
english = 'native Japanese reading of Kanji'
tags = ['common', 'noun', 'suru-verb']
frequency_scores = { anime = 38528 }

[[cards]]
kanji = '敬語'
kana = 'けいご'
english = 'honorific language'
level = 'n2'
tags = ['common']
frequency_scores = { anime = 8689, leeds = 13486 }

[[cards]]
kanji = '謙譲語'
kana = 'けんじょうご'
english = 'humble language (humble keigo); speaking about oneself to those in power'
tags = ['uncommon']

[[cards]]
kanji = '尊敬語'
kana = 'そんけいご'
english = 'honorific language (honorific keigo); spoken about or to those in power'
tags = ['uncommon']

[[cards]]
kanji = '丁寧語'
kana = 'ていねいご'
english = 'polite language (eg masu, desu)'
tags = ['uncommon']

[[cards]]
kanji = '動詞'
kana = 'どうし'
english = 'verb'
level = 'n3'
tags = ['common']
frequency_scores = { anime = 23749, leeds = 7879, wikipedia = 6170 }

[[cards]]
kanji = '方言'
kana = 'ほうげん'
english = 'dialect'
source = 'living-in-japan; wanikani'
level = 'n2'
tags = ['common', 'no-adjective', 'noun']
frequency_scores = { anime = 17636, leeds = 8464, wikipedia = 3418 }

[[cards]]
kanji = '名詞'
kana = 'めいし'
english = 'noun'
level = 'n2'
tags = ['common']
frequency_scores = { anime = 30430, leeds = 7752, wikipedia = 5658 }

[[cards]]
kanji = '文字'
kana = 'もじ'
english = 'letter (alphabet)'
level = 'n3'
source = 'wanikani'
tags = ['common', 'noun']
frequency_scores = { anime = 2413, leeds = 941, novels = 1307, wikipedia = 626 }

