[[cards]]
kanji = '作者'
kana = 'さくしゃ'
english = 'author (of a particular work)'
level = 'n2'
source = 'read-nihon'
tags = ['books', 'common', 'people', 'writing']
frequency_scores = { anime = 8756, leeds = 3017, wikipedia = 2772 }

[[cards]]
kanji = '作家'
kana = 'さっか'
english = 'author (profession)'
level = 'n3'
tags = ['books', 'common', 'people', 'writing']
frequency_scores = { anime = 4011, leeds = 1911, novels = 2390, wikipedia = 905 }

[[cards]]
kanji = '小説'
kana = 'しょうせつ'
english = 'novel; short story'
source = 'wanikani'
level = 'n4'
tags = ['books', 'common', 'no-adjective', 'noun']
frequency_scores = { anime = 2586, leeds = 1304, novels = 1889, wikipedia = 529 }

[[cards]]
kanji = '本'
kana = 'ほん'
english = 'book'
source = 'irasshai'
level = 'n5'
tags = ['common', 'noun']
frequency_scores = { anime = 206, leeds = 184, novels = 254, wikipedia = 227 }

