[[cards]]
kanji = '愛好'
kana = 'あいこう'
english = 'adoration'
source = 'manga'
tags = ['common', 'noun', 'suru-verb']

[[cards]]
disabled = true
kanji = '以上'
kana = 'いじょう'
english = 'not less than'
level = 'n4'
source = 'manga'
tags = ['adverbial-noun', 'common', 'temporal-noun']

[[cards]]
disabled = true
kanji = '各地'
kana = 'かくち'
english = 'every place'
level = 'n2'
source = 'manga'
tags = ['common', 'no-adjective', 'noun']

[[cards]]
kanji = '現実'
kana = 'げんじつ'
english = 'reality'
level = 'n3'
source = 'manga'
explain = 'http://selftaughtjapanese.com/2015/04/30/words-to-express-truth-in-japanese/'
tags = ['common', 'noun']

[[cards]]
kanji = '個性'
kana = 'こせい'
english = 'individuality; personality'
level = 'n1'
source = 'manga'
tags = ['common']

[[cards]]
kanji = '最初'
kana = 'さいしょ'
english = 'beginning; outset'
level = 'n4'
source = 'manga'
tags = ['adverbial-noun', 'common', 'no-adjective', 'temporal-noun']

[[cards]]
disabled = true
kanji = '挫折'
kana = 'ざせつ'
english = 'setback; failure'
source = 'manga'
tags = ['common', 'noun', 'suru-verb']

[[cards]]
kanji = '社会'
kana = 'しゃかい'
english = 'society'
level = 'n4'
source = 'manga'
tags = ['common', 'manga']

[[cards]]
kanji = '互い'
kana = 'たがい'
english = 'mutual; reciprocal'
level = 'n3'
source = 'manga'
tags = ['common', 'noun']

[[cards]]
disabled = true
kanji = '特異体質'
kana = 'とくいたいしつ'
english = 'idiosyncrasy'
source = 'manga'
tags = ['no-adjective', 'noun', 'uncommon']

[[cards]]
kanji = '発見'
kana = 'はっけん'
english = 'discovery; finding'
level = 'n3'
source = 'manga'
tags = ['common', 'noun', 'suru-verb']

[[cards]]
disabled = true
kanji = '平等'
kana = 'びょうどう'
english = 'equality; impartiality'
level = 'n3'
source = 'manga'
tags = ['common']

[[cards]]
disabled = true
kanji = '無事'
kana = 'ぶじ'
english = 'safe and quietness'
level = 'n3'
source = 'manga'
tags = ['common']

[[cards]]
disabled = true
kanji = '許し'
kana = 'ゆるし'
english = 'forgiveness; pardon'
source = 'manga'
tags = ['common']

