[[cards]]
kanji = '愛好'
kana = 'あいこう'
english = 'adoration'
source = 'manga'
tags = ['common', 'noun', 'suru-verb']
highest_frequency = 5956
highest_frequency_source = 'Wikipedia'

[[cards]]
kanji = '運命'
kana = 'うんめい'
english = 'destiny'
source = 'anime-frequency'
level = 'n1'
tags = ['common', 'noun']
highest_frequency = 1006
highest_frequency_source = 'Anime'

[[cards]]
kanji = 'お土産'
kana = 'おみやげ'
english = 'present; souveir'
source = 'irasshai; anime; db super'
level = 'n4'
tags = ['common', 'noun']
highest_frequency = 12391
highest_frequency_source = 'Leeds'

[[cards]]
disabled = true
kanji = '各地'
kana = 'かくち'
english = 'every place'
level = 'n2'
source = 'manga'
tags = ['common', 'no-adjective', 'noun']
highest_frequency = 944
highest_frequency_source = 'Wikipedia'

[[cards]]
kanji = '勝手'
kana = 'かって'
english = 'as one pleases; selfishness'
source = 'wanikani; anime-frequency'
tags = ['common', 'no-adjective', 'noun']
highest_frequency = 318
highest_frequency_source = 'Anime'

[[cards]]
kanji = '決して'
kana = 'けっして'
english = 'by no means!'
source = 'anime; jpop'
level = 'n4'
tags = ['adverb', 'anime', 'common']
highest_frequency = 827
highest_frequency_source = 'Novels'

[[cards]]
kanji = '現実'
kana = 'げんじつ'
english = 'reality'
level = 'n3'
source = 'manga'
explain = 'http://selftaughtjapanese.com/2015/04/30/words-to-express-truth-in-japanese/'
tags = ['common', 'noun']
highest_frequency = 668
highest_frequency_source = 'Leeds'

[[cards]]
kanji = '後輩'
kana = 'こうはい'
english = 'junior (at school or work)'
source = 'anime; irasshai'
level = 'n2'
tags = ['anime', 'common', 'noun']
highest_frequency = 1804
highest_frequency_source = 'Anime'

[[cards]]
kanji = '個性'
kana = 'こせい'
english = 'individuality; personality'
level = 'n1'
source = 'manga'
tags = ['common']
highest_frequency = 2080
highest_frequency_source = 'Anime'

[[cards]]
kanji = '最初'
kana = 'さいしょ'
english = 'first; beginning; outset'
level = 'n4'
source = 'manga'
tags = ['adverbial-noun', 'common', 'no-adjective', 'temporal-noun']
highest_frequency = 255
highest_frequency_source = 'Wikipedia'

[[cards]]
kanji = '流石'
kana = 'さすが'
english = 'as one would expect'
source = 'anime-freq'
level = 'n2'
tags = ['adverb', 'common', 'na-adjective', 'no-adjective']
highest_frequency = 749
highest_frequency_source = 'Novels'

[[cards]]
disabled = true
kanji = '挫折'
kana = 'ざせつ'
english = 'setback; failure'
source = 'manga'
tags = ['common', 'noun', 'suru-verb']
highest_frequency = 7796
highest_frequency_source = 'Leeds'

[[cards]]
kanji = '社会'
kana = 'しゃかい'
english = 'society'
level = 'n4'
source = 'manga'
tags = ['common', 'manga']
highest_frequency = 213
highest_frequency_source = 'Leeds'

[[cards]]
kanji = 'ずっと'
kana = 'ずっと'
english = 'always; forever; all along; continuously in some state (for a long time or distance)'
level = 'n3'
tags = ['adverb', 'anime', 'common']
highest_frequency = 158
highest_frequency_source = 'Anime'

[[cards]]
kanji = '先輩'
kana = 'せんぱい'
english = 'senior (at school or work)'
source = 'anime; irasshai'
level = 'n4'
tags = ['anime', 'common', 'noun']
highest_frequency = 115
highest_frequency_source = 'Anime'

[[cards]]
kanji = '絶対'
kana = 'ぜったい'
english = 'absolute(ly); definite(ly); unconditionally'
source = 'anime'
level = 'n3'
tags = ['adverb', 'anime', 'common']
highest_frequency = 162
highest_frequency_source = 'Anime'

[[cards]]
kanji = '存在'
kana = 'そんざい'
english = 'existence; being'
source = 'anime; db super'
level = 'n3'
tags = ['common', 'no-adjective', 'noun', 'suru-verb']
highest_frequency = 107
highest_frequency_source = 'Wikipedia'

[[cards]]
kanji = '互い'
kana = 'たがい'
english = 'mutual; reciprocal'
level = 'n3'
source = 'manga'
tags = ['common', 'noun']
highest_frequency = 4076
highest_frequency_source = 'Anime'

[[cards]]
kanji = '確か'
kana = 'たしか'
english = 'certain; positive'
source = 'anime; db super'
level = 'n4'
tags = ['common', 'na-adjective', 'noun']
highest_frequency = 153
highest_frequency_source = 'Anime'

[[cards]]
kanji = '大体'
kana = 'だいたい'
english = 'main point; gist'
source = 'anime; db super; wanikani'
level = 'n4'
tags = ['adverbial-noun', 'common', 'noun', 'temporal-noun']
highest_frequency = 844
highest_frequency_source = 'Anime'

[[cards]]
kanji = '天使'
kana = 'てんし'
english = 'angel'
source = 'anime'
tags = ['common', 'no-adjective', 'noun']
highest_frequency = 1165
highest_frequency_source = 'Anime'

[[cards]]
disabled = true
kanji = '特異体質'
kana = 'とくいたいしつ'
english = 'idiosyncrasy'
source = 'manga'
tags = ['no-adjective', 'noun', 'uncommon']

[[cards]]
kanji = '何となく'
kana = 'なんとなく'
english = 'somehow or another'
level = 'n2'
tags = ['adverb', 'common', 'expressions']
highest_frequency = 2584
highest_frequency_source = 'Novels'

[[cards]]
kanji = '恥ずかしい'
kana = 'はずかしい'
english = 'embarassed; humiliated; shy'
source = 'anime'
level = 'n4'
tags = ['common', 'i-adjective']
highest_frequency = 656
highest_frequency_source = 'Anime'

[[cards]]
kanji = 'はっきり'
kana = 'はっきり'
english = 'clearly'
source = 'anime; db super'
level = 'n4'
tags = ['adverb', 'adverb-to', 'common', 'verb-suru']
highest_frequency = 641
highest_frequency_source = 'Novels'

[[cards]]
kanji = '発見'
kana = 'はっけん'
english = 'discovery; finding'
level = 'n3'
source = 'manga'
tags = ['common', 'noun', 'suru-verb']
highest_frequency = 446
highest_frequency_source = 'Wikipedia'

[[cards]]
kanji = '化け物'
kana = 'ばけもの'
english = 'goblin'
source = 'anime-frequency'
tags = ['common', 'noun']
highest_frequency = 1120
highest_frequency_source = 'Anime'

[[cards]]
kanji = '光'
kana = 'ひかり'
english = 'light'
source = 'anime'
level = 'n4'
tags = ['anime', 'common', 'noun']
highest_frequency = 269
highest_frequency_source = 'Novels'

[[cards]]
disabled = true
kanji = '平等'
kana = 'びょうどう'
english = 'equality; impartiality'
level = 'n3'
source = 'manga'
tags = ['common']
highest_frequency = 3943
highest_frequency_source = 'Leeds'

[[cards]]
kanji = '部活'
kana = 'ぶかつ'
english = 'club activities'
source = 'anime-freq'
tags = ['common']
highest_frequency = 1079
highest_frequency_source = 'Anime'

[[cards]]
disabled = true
kanji = '無事'
kana = 'ぶじ'
english = 'safe and quietness'
level = 'n3'
source = 'manga'
tags = ['common']
highest_frequency = 523
highest_frequency_source = 'Anime'

[[cards]]
kanji = '真逆'
kana = 'まさか'
english = 'by no means! certainly not!'
source = 'anime'
level = 'n3'
tags = ['adverb', 'common', 'no-adjective', 'noun']
highest_frequency = 156
highest_frequency_source = 'Anime'

[[cards]]
kanji = '全く'
kana = 'まったく'
english = 'completely'
source = 'anime; db super'
level = 'n3'
tags = ['adverb', 'common', 'no-adjective']
highest_frequency = 610
highest_frequency_source = 'Leeds'

[[cards]]
kanji = '漫画'
kana = 'まんが'
english = 'manga'
source = 'manga; anime'
level = 'n4'
tags = ['common', 'noun']
highest_frequency = 375
highest_frequency_source = 'Wikipedia'

[[cards]]
kanji = '若しも'
kana = 'もしも'
english = 'if (adverb)'
source = 'anime-frequency'
tags = ['adverb', 'common']
highest_frequency = 2171
highest_frequency_source = 'Novels'

[[cards]]
kanji = '約束'
kana = 'やくそく'
english = 'promise'
source = 'anime'
level = 'n4'
tags = ['common', 'noun', 'suru-verb']
highest_frequency = 341
highest_frequency_source = 'Anime'

[[cards]]
kanji = 'やばい'
kana = 'やばい'
english = 'risky (colloqial)'
source = 'anime-frequency'
tags = ['common', 'i-adjective']
highest_frequency = 1037
highest_frequency_source = 'Anime'

[[cards]]
disabled = true
kanji = '許し'
kana = 'ゆるし'
english = 'forgiveness; pardon'
source = 'manga'
tags = ['common']
highest_frequency = 7650
highest_frequency_source = 'Anime'

[[cards]]
kanji = 'アニメ'
kana = 'アニメ'
english = 'anime'
source = 'anime'
tags = ['common', 'noun']
highest_frequency = 433
highest_frequency_source = 'Wikipedia'

