[[cards]]
kanji = '愛好'
kana = 'あいこう'
english = 'adoration'
source = 'manga'
tags = ['common', 'noun', 'suru-verb']
frequency_scores = { anime = 23181, leeds = 9665, wikipedia = 5956 }

[[cards]]
kanji = '運命'
kana = 'うんめい'
english = 'destiny'
source = 'anime-frequency'
level = 'n1'
tags = ['common', 'noun']
frequency_scores = { anime = 1006, leeds = 3067, novels = 1445, wikipedia = 5409 }

[[cards]]
kanji = 'お土産'
kana = 'おみやげ'
english = 'present; souveir'
source = 'irasshai; anime; db super'
level = 'n4'
tags = ['common', 'noun']
frequency_scores = { anime = 14668, leeds = 12391 }

[[cards]]
disabled = true
kanji = '各地'
kana = 'かくち'
english = 'every place'
level = 'n2'
source = 'manga'
tags = ['common', 'no-adjective', 'noun']
frequency_scores = { anime = 6172, leeds = 2764, wikipedia = 944 }

[[cards]]
kanji = '勝手'
kana = 'かって'
english = 'as one pleases; selfishness'
source = 'wanikani; anime-frequency'
tags = ['common', 'no-adjective', 'noun']
frequency_scores = { anime = 318, leeds = 1709, novels = 1021, wikipedia = 6287 }

[[cards]]
kanji = '経験'
kana = 'けいけんする'
english = 'experience'
source = 'wiktionary; boku-no-hero'
level = 'n3'
tags = ['common', 'noun', 'suru-verb']
frequency_scores = { anime = 1315, leeds = 531, novels = 1190, wikipedia = 803 }

[[cards]]
kanji = '決して'
kana = 'けっして'
english = 'by no means!'
source = 'anime; jpop'
level = 'n4'
tags = ['adverb', 'anime', 'common']
frequency_scores = { anime = 1005, leeds = 1244, novels = 827 }

[[cards]]
kanji = '現実'
kana = 'げんじつ'
english = 'reality'
level = 'n3'
source = 'manga'
explain = 'http://selftaughtjapanese.com/2015/04/30/words-to-express-truth-in-japanese/'
tags = ['common', 'noun']
frequency_scores = { anime = 740, leeds = 668, novels = 1040, wikipedia = 2639 }

[[cards]]
kanji = '後輩'
kana = 'こうはい'
english = 'junior (at school or work)'
source = 'anime; irasshai'
level = 'n2'
tags = ['anime', 'common', 'noun']
frequency_scores = { anime = 1804, leeds = 5648, wikipedia = 6459 }

[[cards]]
kanji = '個性'
kana = 'こせい'
english = 'individuality; personality'
level = 'n1'
source = 'manga'
tags = ['common']
frequency_scores = { anime = 2080, leeds = 2975, wikipedia = 5549 }

[[cards]]
kanji = '最初'
kana = 'さいしょ'
english = 'first; beginning; outset'
level = 'n4'
source = 'manga'
tags = ['adverbial-noun', 'common', 'no-adjective', 'temporal-noun']
frequency_scores = { anime = 332, leeds = 428, novels = 464, wikipedia = 255 }

[[cards]]
kanji = '流石'
kana = 'さすが'
english = 'as one would expect'
source = 'anime-freq'
level = 'n2'
tags = ['adverb', 'common', 'na-adjective', 'no-adjective']
frequency_scores = { anime = 12278, leeds = 8794, novels = 749 }

[[cards]]
disabled = true
kanji = '挫折'
kana = 'ざせつ'
english = 'setback; failure'
source = 'manga'
tags = ['common', 'noun', 'suru-verb']
frequency_scores = { anime = 9758, leeds = 7796 }

[[cards]]
kanji = '社会'
kana = 'しゃかい'
english = 'society'
level = 'n4'
source = 'manga'
tags = ['common', 'manga']
frequency_scores = { anime = 1752, leeds = 213, novels = 1229, wikipedia = 239 }

[[cards]]
kanji = '象徴'
kana = 'しょうちょう'
english = 'abstract symbol; emblem'
source = 'boku-no-hero'
level = 'n1'
tags = ['common', 'no-adjective', 'noun', 'suru-verb']
frequency_scores = { anime = 5551, leeds = 3094, wikipedia = 2817 }

[[cards]]
kanji = 'ずっと'
kana = 'ずっと'
english = 'always; forever; all along; continuously in some state (for a long time or distance)'
level = 'n3'
tags = ['adverb', 'anime', 'common']
frequency_scores = { anime = 158, leeds = 859, novels = 421, wikipedia = 6118 }

[[cards]]
kanji = '先輩'
kana = 'せんぱい'
english = 'senior (at school or work)'
source = 'anime; irasshai'
level = 'n4'
tags = ['anime', 'common', 'noun']
frequency_scores = { anime = 115, leeds = 2448, novels = 1282, wikipedia = 4740 }

[[cards]]
kanji = '絶対'
kana = 'ぜったい'
english = 'absolute(ly); definite(ly); unconditionally'
source = 'anime'
level = 'n3'
tags = ['adverb', 'anime', 'common']
frequency_scores = { anime = 162, leeds = 911, novels = 716, wikipedia = 3009 }

[[cards]]
kanji = '存在'
kana = 'そんざい'
english = 'existence; being'
source = 'anime; db super; boku-no-hero'
level = 'n3'
tags = ['common', 'no-adjective', 'noun', 'suru-verb']
frequency_scores = { anime = 319, leeds = 383, novels = 415, wikipedia = 107 }

[[cards]]
kanji = '互い'
kana = 'たがい'
english = 'mutual; reciprocal'
level = 'n3'
source = 'manga'
tags = ['common', 'noun']
frequency_scores = { anime = 4076, leeds = 8336, wikipedia = 7294 }

[[cards]]
kanji = '確か'
kana = 'たしか'
english = 'certain; positive'
source = 'anime; db super'
level = 'n4'
tags = ['common', 'na-adjective', 'noun']
frequency_scores = { anime = 153, leeds = 566, novels = 450, wikipedia = 6530 }

[[cards]]
kanji = '大体'
kana = 'だいたい'
english = 'outline; gist; main point'
source = 'anime; db super; wanikani'
level = 'n4'
tags = ['adverbial-noun', 'common', 'noun', 'temporal-noun']
frequency_scores = { anime = 844, leeds = 1728, novels = 2669 }

[[cards]]
kanji = '天使'
kana = 'てんし'
english = 'angel'
source = 'anime'
tags = ['common', 'no-adjective', 'noun']
frequency_scores = { anime = 1165, leeds = 4696, wikipedia = 4287 }

[[cards]]
disabled = true
kanji = '特異体質'
kana = 'とくいたいしつ'
english = 'idiosyncrasy'
source = 'manga'
tags = ['no-adjective', 'noun', 'uncommon']

[[cards]]
kanji = '何となく'
kana = 'なんとなく'
english = 'somehow or another'
level = 'n2'
tags = ['adverb', 'common', 'expressions']
frequency_scores = { anime = 3427, leeds = 4735, novels = 2584 }

[[cards]]
kanji = '恥ずかしい'
kana = 'はずかしい'
english = 'embarassed; humiliated; shy'
source = 'anime'
level = 'n4'
tags = ['common', 'i-adjective']
frequency_scores = { anime = 656, leeds = 2890, novels = 1109 }

[[cards]]
kanji = 'はっきり'
kana = 'はっきり'
english = 'clearly'
source = 'anime; db super'
level = 'n4'
tags = ['adverb', 'adverb-to', 'common', 'verb-suru']
frequency_scores = { anime = 1320, leeds = 1087, novels = 641 }

[[cards]]
kanji = '発見'
kana = 'はっけん'
english = 'discovery; finding'
level = 'n3'
source = 'manga'
tags = ['common', 'noun', 'suru-verb']
frequency_scores = { anime = 1294, leeds = 987, novels = 1138, wikipedia = 446 }

[[cards]]
kanji = '化け物'
kana = 'ばけもの'
english = 'goblin'
source = 'anime-frequency'
tags = ['common', 'noun']
frequency_scores = { anime = 1120 }

[[cards]]
kanji = '光'
kana = 'ひかり'
english = 'light'
source = 'anime'
level = 'n4'
tags = ['anime', 'common', 'noun']
frequency_scores = { anime = 315, leeds = 1117, novels = 269, wikipedia = 323 }

[[cards]]
disabled = true
kanji = '平等'
kana = 'びょうどう'
english = 'equality; impartiality'
level = 'n3'
source = 'manga'
tags = ['common']
frequency_scores = { anime = 4560, leeds = 3943, wikipedia = 7462 }

[[cards]]
kanji = '部活'
kana = 'ぶかつ'
english = 'club activities'
source = 'anime-freq'
tags = ['common']
frequency_scores = { anime = 1079, leeds = 9548, wikipedia = 7884 }

[[cards]]
disabled = true
kanji = '無事'
kana = 'ぶじ'
english = 'safe and quietness'
level = 'n3'
source = 'manga'
tags = ['common']
frequency_scores = { anime = 523, leeds = 2269, novels = 1355, wikipedia = 5865 }

[[cards]]
kanji = '暴力'
kana = 'ぼうりょく'
english = 'violence; meyhem'
source = 'boku-no-hero'
level = 'n1'
tags = ['common', 'noun']
frequency_scores = { anime = 2705, leeds = 2850, wikipedia = 3109 }

[[cards]]
kanji = '真逆'
kana = 'まさか'
english = 'by no means! certainly not!'
source = 'anime'
level = 'n3'
tags = ['adverb', 'common', 'no-adjective', 'noun']
frequency_scores = { anime = 156, leeds = 3679, novels = 796 }

[[cards]]
kanji = '全く'
kana = 'まったく'
english = 'completely'
source = 'anime; db super'
level = 'n3'
tags = ['adverb', 'common', 'no-adjective']
frequency_scores = { anime = 824, leeds = 610, novels = 1102, wikipedia = 1075 }

[[cards]]
kanji = '漫画'
kana = 'まんが'
english = 'manga'
source = 'manga; anime'
level = 'n4'
tags = ['common', 'noun']
frequency_scores = { anime = 1438, leeds = 2368, wikipedia = 375 }

[[cards]]
kanji = '若しも'
kana = 'もしも'
english = 'if (adverb)'
source = 'anime-frequency'
tags = ['adverb', 'common']
frequency_scores = { anime = 22980, leeds = 4659, novels = 2171 }

[[cards]]
kanji = '約束'
kana = 'やくそく'
english = 'promise'
source = 'anime'
level = 'n4'
tags = ['common', 'noun', 'suru-verb']
frequency_scores = { anime = 341, leeds = 1955, novels = 1036, wikipedia = 3440 }

[[cards]]
kanji = 'やばい'
kana = 'やばい'
english = 'risky (colloqial)'
source = 'anime-frequency'
tags = ['common', 'i-adjective']
frequency_scores = { anime = 1037, leeds = 6990 }

[[cards]]
disabled = true
kanji = '許し'
kana = 'ゆるし'
english = 'forgiveness; pardon'
source = 'manga'
tags = ['common']
frequency_scores = { anime = 7650 }

[[cards]]
kanji = 'アニメ'
kana = 'アニメ'
english = 'anime'
source = 'anime'
tags = ['common', 'noun']
frequency_scores = { anime = 1113, leeds = 1875, wikipedia = 433 }

