[[cards]]
kanji = '愛'
kana = 'あい'
english = 'love; affection'
level = 'n3'
tags = ['common', 'noun', 'noun-suffix']

[[cards]]
kanji = '合図'
kana = 'あいず'
english = 'cue'
level = 'n3'
source = 'wanikani'
tags = ['common', 'noun', 'suru-verb']

[[cards]]
kanji = '垢'
kana = 'あか'
english = 'filth; dirt; grime'
level = 'n1'
tags = ['common', 'noun']

[[cards]]
kanji = '安心'
kana = 'あんしん'
english = 'relief; peace of mind'
level = 'n4'
source = 'wanikani'
tags = ['common', 'na-adjective', 'noun', 'suru-verb']

[[cards]]
kanji = '医学'
kana = 'いがく'
english = 'medical science; medicine (field)'
level = 'n4'
tags = ['common', 'noun']

[[cards]]
kanji = '医師'
kana = 'いし'
english = 'physician (more formal term)'
level = 'n3'
source = 'boku-no-hero-academia-anime'
tags = ['common', 'noun', 'people']

[[cards]]
kanji = '以上'
kana = 'いじょう'
english = 'more than ~'
level = 'n4'
tags = ['adverbial-noun', 'common', 'temporal-noun']

[[cards]]
kanji = '痛み'
kana = 'いたみ'
english = 'pain; injury; grief'
level = 'n3'
source = 'boku-no-hero-academia-anime'
tags = ['common', 'noun']

[[cards]]
kanji = '命'
kana = 'いのち'
english = 'life force; lifespan'
level = 'n3'
tags = ['common', 'noun']

[[cards]]
kanji = '内'
kana = 'うち'
english = 'inside; within; while'
level = 'n4'
source = 'wanikani'
tags = ['common', 'no-adjective', 'noun']

[[cards]]
kanji = '内側'
kana = 'うちがわ'
english = 'interior'
source = 'sekai-wa-fushigi-2'
tags = ['common', 'no-adjective', 'noun']

[[cards]]
kanji = '思い'
kana = 'おもい'
english = 'thought; imagination'
tags = ['common', 'noun']

[[cards]]
kanji = '会話'
kana = 'かいわ'
english = 'conversation'
level = 'n4'
tags = ['common', 'noun', 'suru-verb']

[[cards]]
kanji = '数'
kana = 'かず'
english = 'amount'
level = 'n3'
source = 'https://iknow.jp/courses/566921'
tags = ['common', 'noun']

[[cards]]
kanji = '刀'
kana = 'かたな'
english = ''
make_kanji_card = true
hide_hiragana_card = true
level = 'n3'
tags = ['common', 'weapons']

[[cards]]
kanji = '勝ち'
kana = 'かち'
english = 'victory; win'
level = 'n3'
source = 'wanikani'
tags = ['common', 'noun']

[[cards]]
kanji = '彼女'
kana = 'かのじょ'
english = 'she; her'
level = 'n4'
tags = ['common', 'pronoun']

[[cards]]
kanji = '剃刀'
kana = 'かみそり'
english = 'razor'
level = 'n2'
tags = ['common']

[[cards]]
kanji = '現象'
kana = 'げんしょう'
english = 'phenomenon'
level = 'n3'
source = 'sekai-wa-fushigi-2'
tags = ['common', 'noun']

[[cards]]
kanji = '斯う'
kana = 'こう'
english = 'in this way; such; thus'
level = 'n4'
source = 'https://iknow.jp/courses/566921'
tags = ['adverb', 'common']

[[cards]]
kanji = '心'
kana = 'こころ'
english = 'mind; heart; spirit'
level = 'n4'
tags = ['common', 'noun']

[[cards]]
kanji = '最後'
kana = 'さいご'
english = 'end; conclusion; final'
level = 'n4'
tags = ['common', 'no-adjective', 'noun']

[[cards]]
kanji = '姿勢'
kana = 'しせい'
english = 'posture; stance'
level = 'n2'
source = 'wanikani'
tags = ['body', 'common', 'noun']

[[cards]]
kanji = '品物'
kana = 'しなもの'
english = 'goods; articles; things'
level = 'n4'
source = 'nihongo-charenji-n4-kotoba'
tags = ['common', 'noun']

[[cards]]
kanji = '招待'
kana = 'しょうたい'
english = 'invitation'
level = 'n3'
source = 'wanikani'
tags = ['common', 'no-adjective', 'noun', 'suru-verb']

[[cards]]
kanji = '砂利'
kana = 'じゃり'
english = 'gravel; pebbles'
level = 'n1'
tags = ['common', 'no-adjective', 'noun']

[[cards]]
kanji = '準備'
kana = 'じゅんび'
english = 'preparation'
level = 'n3'
tags = ['common', 'noun', 'suru-verb']

[[cards]]
kanji = '人工'
kana = 'じんこう'
english = 'artificial'
level = 'n4'
source = 'wanikani'
make_kanji_card = true
hide_hiragana_card = true
tags = ['common', 'no-adjective', 'noun']

[[cards]]
kanji = '水中'
kana = 'すいちゅう'
english = 'underwater'
source = 'wanikani'
make_kanji_card = true
hide_hiragana_card = true
tags = ['common', 'no-adjective', 'noun']

[[cards]]
kanji = '外側'
kana = 'そとがわ'
english = 'exterior'
source = 'sekai-wa-fushigi-2'
tags = ['common', 'no-adjective', 'noun']

[[cards]]
kanji = '夫れ夫れ'
kana = 'それぞれ'
english = 'each'
source = 'sekai-wa-fushigi-2'
level = 'n3'
tags = ['adverbial-noun', 'common', 'no-adjective']

[[cards]]
kanji = '正しい'
kana = 'ただしい'
english = 'correct'
level = 'n4'
tags = ['common', 'i-adjective']

[[cards]]
kanji = '盾'
kana = 'たて'
english = 'shield'
level = 'n1'
tags = ['armor', 'common', 'weapons']

[[cards]]
kanji = '力'
kana = 'ちから'
english = 'strength; energy; power; force; might'
level = 'n4'
tags = ['common']

[[cards]]
kanji = '中古'
kana = 'ちゅうこ'
english = 'used; second-hand'
level = 'n3'
source = 'wanikani'
tags = ['common', 'no-adjective', 'temporal-noun']

[[cards]]
kanji = '中止'
kana = 'ちゅうし'
english = 'suspension; discontinuance; interruption'
level = 'n3'
tags = ['common', 'noun', 'suru-verb']

[[cards]]
kanji = '注文'
kana = 'ちゅうもん'
english = 'order; request'
level = 'n3'
source = 'wanikani'
tags = ['common', 'no-adjective', 'noun', 'suru-verb']

[[cards]]
kanji = '月'
kana = 'つき'
english = 'moon'
level = 'n3'
tags = ['common', 'space']

[[cards]]
kanji = '包み'
kana = 'つつみ'
english = 'package; parcel; bundle'
level = 'n3'
tags = ['common', 'nouns']

[[cards]]
kanji = '天才'
kana = 'てんさい'
english = 'genius; prodigy'
level = 'n1'
tags = ['common', 'noun']

[[cards]]
kanji = '扉'
kana = 'とびら'
english = 'gate'
level = 'n1'
source = 'tobira'
tags = ['common', 'noun']

[[cards]]
kanji = '道路'
kana = 'どうろ'
english = 'highway'
level = 'n3'
tags = ['common', 'noun', 'places']

[[cards]]
kanji = '虹'
kana = 'にじ'
english = 'rainbow'
level = 'n2'
tags = ['common', 'nature', 'outdoors']

[[cards]]
kanji = '日光'
kana = 'にっこう'
english = 'sunlight; sunshine; sunbeams'
level = 'n3'
tags = ['common', 'noun']

[[cards]]
kanji = '値段'
kana = 'ねだん'
english = 'price'
level = 'n4'
tags = ['common', 'noun']

[[cards]]
kanji = '外れ'
kana = 'はずれ'
english = 'extremity; verge; outskirts'
source = 'wanikani'
tags = ['common', 'noun']

[[cards]]
kanji = '花火'
kana = 'はなび'
english = 'fireworks'
make_kanji_card = true
hide_hiragana_card = true
level = 'n2'
tags = ['common']

[[cards]]
kanji = '半額'
kana = 'はんがく'
english = 'half price'
source = 'nihongo-charenji-n4-kotoba'
tags = ['common']

[[cards]]
kanji = '爆破'
kana = 'ばくは'
english = 'explosion'
level = 'n1'
source = 'boku-no-hero-academia-anime'
tags = ['common', 'noun', 'suru-verb']

[[cards]]
kanji = '非常口'
kana = 'ひじょうぐち'
english = 'emergency exit'
tags = ['building', 'common', 'noun']

[[cards]]
kanji = '秘密'
kana = 'ひみつ'
english = 'secret'
level = 'n3'
tags = ['common', 'na-adjective', 'no-adjective', 'noun']

[[cards]]
kanji = '不正'
kana = 'ふせい'
english = 'injustice'
make_kanji_card = true
hide_hiragana_card = true
level = 'n3'
source = 'wanikani'
tags = ['common', 'na-adjective', 'noun']

[[cards]]
kanji = '船'
kana = 'ふね'
english = 'boat'
level = 'n4'
tags = ['common', 'noun', 'transportation']

[[cards]]
kanji = '返事'
kana = 'へんじ'
english = 'response; reply; answer'
level = 'n4'
source = 'wanikani'
tags = ['common', 'noun', 'suru-verb']

[[cards]]
kanji = '別に'
kana = 'べつに'
english = 'not particularly'
level = 'n3'
tags = ['adverb', 'common']

[[cards]]
kanji = '褒美'
kana = 'ほうび'
english = 'reward'
level = 'n1'
source = 'wanikani'
tags = ['common', 'noun']

[[cards]]
kanji = '間違い'
kana = 'まちがい'
english = 'mistake; error'
level = 'n3'
tags = ['common', 'noun']

[[cards]]
kanji = '水色'
kana = 'みずいろ'
english = 'light blue; aqua'
source = 'wanikani'
make_kanji_card = true
hide_hiragana_card = true
tags = ['appearance', 'colors', 'common', 'moun', 'no-adjective']

[[cards]]
kanji = '野球'
kana = 'やきゅう'
english = 'baseball'
tags = ['common', 'noun', 'sports']

[[cards]]
kanji = '郵便'
kana = 'ゆうびん'
english = 'postal service'
level = 'n3'
tags = ['common', 'noun']

[[cards]]
kanji = '夢'
kana = 'ゆめ'
english = 'dream'
level = 'n4'
tags = ['common']

[[cards]]
kanji = '用意'
kana = 'ようい'
english = 'preparation; provision; arrangement'
level = 'n4'
source = 'nihongo-charenji-n4-kotoba'
tags = ['common', 'noun', 'suru-verb']

[[cards]]
kanji = '羊毛'
kana = 'ようもう'
english = 'wool'
level = 'n2'
source = 'wanikani'
tags = ['common', 'no-adjective', 'noun']

[[cards]]
kanji = '冷凍'
kana = 'れいとう'
english = 'freeze/freezing; cold storage; refridgeration'
level = 'n2'
source = 'nihongo-charenji-n4-kotoba'
tags = ['common', 'noun', 'suru-verb']

[[cards]]
kanji = '割引'
kana = 'わりびき'
english = 'discount; rebate'
level = 'n2'
source = 'nihongo-charenji-n4-kotoba'
tags = ['common', 'noun']

[[cards]]
kanji = 'セール'
kana = 'セール'
english = 'sale'
source = 'nihongo-charenji-n4-kotoba'
level = 'n1'
tags = ['common', 'gairaigo']

