[[cards]]
kanji = '愛'
kana = 'あい'
english = 'love; affection'
level = 'n3'
tags = ['common', 'noun', 'noun-suffix']

[[cards]]
kanji = '合図'
kana = 'あいず'
english = 'cue'
level = 'n3'
source = 'wanikani'
tags = ['common', 'noun', 'suru-verb']

[[cards]]
kanji = '垢'
kana = 'あか'
english = 'filth; dirt; grime'
level = 'n1'
tags = ['common', 'noun']

[[cards]]
kanji = '遊び'
kana = 'あそび'
english = 'playing'
level = 'n4'
source = 'jlptstudy.net'
tags = ['common', 'noun', 'noun-suffix']

[[cards]]
kanji = '安心'
kana = 'あんしん'
english = 'relief; peace of mind'
level = 'n4'
source = 'wanikani'
tags = ['common', 'na-adjective', 'noun', 'suru-verb']

[[cards]]
kanji = 'あんな'
kana = 'あんな'
english = 'such (distant)'
level = 'n4'
source = 'jlptstudy.net'
tags = ['common', 'kosoado', 'pre-noun-adjectival']

[[cards]]
kanji = '案内'
kana = 'あんない'
english = 'guidance'
level = 'n3'
source = 'jlptstudy.net'
tags = ['common', 'noun', 'suru-verb']

[[cards]]
kanji = '以下'
kana = 'いか'
english = 'not exceeding; below ~'
level = 'n4'
source = 'jlptstudy.net'
tags = ['common', 'noun']

[[cards]]
kanji = '以外'
kana = 'いがい'
english = 'with the exception of'
level = 'n4'
source = 'jlptstudy.net'
tags = ['adverbial-noun', 'common']

[[cards]]
kanji = '医学'
kana = 'いがく'
english = 'medical science; medicine (field)'
level = 'n4'
tags = ['common', 'noun']

[[cards]]
kanji = '医師'
kana = 'いし'
english = 'physician (more formal term)'
level = 'n3'
source = 'boku-no-hero-academia-anime'
tags = ['common', 'noun', 'people']

[[cards]]
kanji = '以上'
kana = 'いじょう'
english = 'more than ~'
level = 'n4'
tags = ['adverbial-noun', 'common', 'temporal-noun']

[[cards]]
kanji = '痛み'
kana = 'いたみ'
english = 'pain; injury; grief'
level = 'n3'
source = 'boku-no-hero-academia-anime'
tags = ['common', 'noun']

[[cards]]
kanji = '一年生'
kana = 'いちねんせい'
english = 'first year student'
tags = ['common', 'noun', 'person']

[[cards]]
kanji = '一杯'
kana = 'いっぱい'
english = 'full; amount necessary to fill a container'
level = 'n4'
source = 'irasshai'
tags = ['adverb', 'common', 'na-adjective', 'no-adjective', 'noun']

[[cards]]
kanji = '糸'
kana = 'いと'
english = 'thread; yarn'
level = 'n4'
source = 'jlptstudy.net'
tags = ['common', 'noun', 'noun-suffix']

[[cards]]
kanji = '以内'
kana = 'いない'
english = 'within; inside of'
level = 'n4'
source = 'jlptstudy.net'
tags = ['common', 'noun', 'suffix']

[[cards]]
kanji = '命'
kana = 'いのち'
english = 'life force; lifespan'
level = 'n3'
tags = ['common', 'noun']

[[cards]]
kanji = '内'
kana = 'うち'
english = 'inside; within; while'
level = 'n4'
source = 'wanikani'
tags = ['common', 'no-adjective', 'noun']

[[cards]]
kanji = '内側'
kana = 'うちがわ'
english = 'interior'
source = 'sekai-wa-fushigi-2'
tags = ['common', 'no-adjective', 'noun']

[[cards]]
kanji = '宇宙'
kana = 'うちゅう'
english = 'universe; cosmos'
level = 'n3'
tags = ['common', 'noun']

[[cards]]
kanji = '大きさ'
kana = 'おおきさ'
english = 'size; dimensions'
source = 'wanikani'
tags = ['common', 'noun']

[[cards]]
kanji = '贈り物'
kana = 'おくりもの'
english = 'present; gift'
level = 'n4'
source = 'jlptstudy.net'
tags = ['common', 'noun']

[[cards]]
kanji = 'お前'
kana = 'おまえ'
english = 'you (familiar, male language, often derogatory)'
level = 'n3'
source = 'anime'
tags = ['common', 'pronoun']

[[cards]]
kanji = '思い'
kana = 'おもい'
english = 'thought; imagination'
tags = ['common', 'noun']

[[cards]]
kanji = '思わず'
kana = 'おもわず'
english = 'subconsciously; involuntarily'
level = 'n3'
source = 'wanikani'
tags = ['adverb', 'common']

[[cards]]
kanji = '会長'
kana = 'かいちょう'
english = 'chairman; president of a society'
tags = ['common', 'noun']

[[cards]]
kanji = '会話'
kana = 'かいわ'
english = 'conversation'
level = 'n4'
tags = ['common', 'noun', 'suru-verb']

[[cards]]
kanji = '数'
kana = 'かず'
english = 'amount'
level = 'n3'
source = 'https://iknow.jp/courses/566921'
tags = ['common', 'noun']

[[cards]]
kanji = '火星'
kana = 'かせい'
english = 'Mars (planet)'
level = 'n1'
source = 'wanikani'
tags = ['common', 'no-adjective', 'noun', 'space']

[[cards]]
kanji = '方'
kana = 'かた'
english = 'person; way'
level = 'n5'
tags = ['common', 'noun']

[[cards]]
kanji = '硬い'
kana = 'かたい'
english = 'hard; solid; tough'
level = 'n4'
tags = ['common', 'i-adjectives']

[[cards]]
kanji = '刀'
kana = 'かたな'
english = ''
level = 'n3'
tags = ['common', 'weapons']

[[cards]]
kanji = '勝ち'
kana = 'かち'
english = 'victory; win'
level = 'n3'
source = 'wanikani'
tags = ['common', 'noun']

[[cards]]
kanji = '彼女'
kana = 'かのじょ'
english = 'she; her'
level = 'n4'
tags = ['common', 'pronoun']

[[cards]]
kanji = '黴'
kana = 'かび'
english = 'mold; mildew'
source = 'wanikani'
tags = ['common', 'noun']

[[cards]]
kanji = '剃刀'
kana = 'かみそり'
english = 'razor'
level = 'n2'
tags = ['common']

[[cards]]
kanji = '痒い'
kana = 'かゆい'
english = 'itchy'
level = 'n2'
tags = ['body', 'common', 'health', 'i-adjective']

[[cards]]
kanji = '完成'
kana = 'かんせい'
english = 'complete; completion'
level = 'n3'
source = 'wanikani'
tags = ['common', 'noun', 'suru-verb']

[[cards]]
kanji = '完成'
kana = 'かんせい'
english = 'complete; completion'
level = 'n3'
source = 'wanikani'
tags = ['common', 'noun', 'suru-verb']

[[cards]]
kanji = '気分'
kana = 'きぶん'
english = 'feeling; mood'
level = 'n4'
source = 'wanikani'
tags = ['common', 'noun']

[[cards]]
kanji = '消しゴム'
kana = 'けしゴム'
english = 'eraser'
level = 'n4'
tags = ['common', 'gairaigo', 'noun']

[[cards]]
kanji = '原因'
kana = 'げんいん'
english = 'cause; origin; source'
level = 'n4'
source = 'jlptstudy.net'
tags = ['common', 'noun', 'suru-verb']

[[cards]]
kanji = '現象'
kana = 'げんしょう'
english = 'phenomenon'
level = 'n3'
source = 'sekai-wa-fushigi-2'
tags = ['common', 'noun']

[[cards]]
kanji = '斯う'
kana = 'こう'
english = 'in this way; such; thus'
level = 'n4'
source = 'https://iknow.jp/courses/566921'
tags = ['adverb', 'common']

[[cards]]
kanji = '交通'
kana = 'こうつう'
english = 'traffic'
level = 'n4'
source = 'nihongo-sou-matome'
tags = ['common', 'noun', 'suru-verb']

[[cards]]
kanji = '公用'
kana = 'こうよう'
english = 'government business; official business'
level = 'n1'
source = 'wanikani'
tags = ['common', 'noun']

[[cards]]
kanji = '心'
kana = 'こころ'
english = 'mind; heart; spirit'
level = 'n4'
tags = ['common', 'noun']

[[cards]]
kanji = '怖い'
kana = 'こわい'
english = 'scary; frightening'
level = 'n4'
tags = ['common', 'i-adjective']

[[cards]]
kanji = '最後'
kana = 'さいご'
english = 'end; conclusion; final'
level = 'n4'
tags = ['common', 'no-adjective', 'noun']

[[cards]]
kanji = '市'
kana = 'し'
english = 'city'
level = 'n4'
source = 'wanikani'
tags = ['common', 'noun', 'suffix']

[[cards]]
kanji = '姿勢'
kana = 'しせい'
english = 'posture; stance'
level = 'n2'
source = 'wanikani'
tags = ['body', 'common', 'noun']

[[cards]]
kanji = '品物'
kana = 'しなもの'
english = 'goods; articles; things'
level = 'n4'
source = 'nihongo-charenji-n4-kotoba'
tags = ['common', 'noun']

[[cards]]
kanji = '招待'
kana = 'しょうたい'
english = 'invitation'
level = 'n3'
source = 'wanikani'
tags = ['common', 'no-adjective', 'noun', 'suru-verb']

[[cards]]
kanji = '少年'
kana = 'しょうねん'
english = 'young boy; juvenile'
level = 'n4'
tags = ['common', 'noun', 'people']

[[cards]]
kanji = '砂利'
kana = 'じゃり'
english = 'gravel; pebbles'
level = 'n1'
tags = ['common', 'no-adjective', 'noun']

[[cards]]
kanji = '準備'
kana = 'じゅんび'
english = 'preparation'
level = 'n3'
tags = ['common', 'noun', 'suru-verb']

[[cards]]
kanji = '人工'
kana = 'じんこう'
english = 'artificial'
level = 'n4'
source = 'wanikani'
tags = ['common', 'no-adjective', 'noun']

[[cards]]
kanji = '人生'
kana = 'じんせい'
english = 'human life'
level = 'n3'
source = 'office'
tags = ['common']

[[cards]]
kanji = '水中'
kana = 'すいちゅう'
english = 'underwater'
source = 'wanikani'
tags = ['common', 'no-adjective', 'noun']

[[cards]]
kanji = '総'
kana = 'そう'
english = 'gross; overall; whole'
level = 'n1'
source = 'nihongo-sou-matome'
tags = ['common', 'noun', 'prefix']

[[cards]]
kanji = '外側'
kana = 'そとがわ'
english = 'exterior'
source = 'sekai-wa-fushigi-2'
tags = ['common', 'no-adjective', 'noun']

[[cards]]
kanji = '夫れ夫れ'
kana = 'それぞれ'
english = 'each'
source = 'sekai-wa-fushigi-2'
level = 'n3'
tags = ['adverbial-noun', 'common', 'no-adjective']

[[cards]]
kanji = '宝'
kana = 'たから'
english = 'treasure'
level = 'n3'
source = 'wanikani'
tags = ['common', 'noun']

[[cards]]
kanji = '竹'
kana = 'たけ'
english = 'bamboo'
level = 'n2'
source = 'wanikani'
tags = ['common', 'noun']

[[cards]]
kanji = '正しい'
kana = 'ただしい'
english = 'correct'
level = 'n4'
tags = ['common', 'i-adjective']

[[cards]]
kanji = '盾'
kana = 'たて'
english = 'shield'
level = 'n1'
tags = ['armor', 'common', 'weapons']

[[cards]]
kanji = '力'
kana = 'ちから'
english = 'strength; energy; power; force; might'
level = 'n4'
tags = ['common']

[[cards]]
kanji = 'ちゃんと'
kana = 'ちゃんと'
english = 'properly; diligently'
level = 'n3'
source = 'living-in-japan'
tags = ['adverb', 'common', 'suru-verb']

[[cards]]
kanji = '中古'
kana = 'ちゅうこ'
english = 'used; secondhand'
level = 'n3'
source = 'wanikani'
tags = ['common', 'no-adjective', 'temporal-noun']

[[cards]]
kanji = '中古'
kana = 'ちゅうこ'
english = 'used; second-hand'
level = 'n3'
source = 'wanikani'
tags = ['common', 'no-adjective', 'temporal-noun']

[[cards]]
kanji = '中古車'
kana = 'ちゅうこしゃ'
english = 'used car'
tags = ['common', 'noun']

[[cards]]
kanji = '中止'
kana = 'ちゅうし'
english = 'suspension; discontinuance; interruption'
level = 'n3'
tags = ['common', 'noun', 'suru-verb']

[[cards]]
kanji = '注文'
kana = 'ちゅうもん'
english = 'order; request'
level = 'n3'
source = 'wanikani'
tags = ['common', 'no-adjective', 'noun', 'suru-verb']

[[cards]]
kanji = '月'
kana = 'つき'
english = 'moon'
level = 'n3'
tags = ['common', 'space']

[[cards]]
kanji = '包み'
kana = 'つつみ'
english = 'package; parcel; bundle'
level = 'n3'
tags = ['common', 'nouns']

[[cards]]
kanji = '手袋'
kana = 'てぶくろ'
english = 'glove; mitten'
level = 'n4'
tags = ['clothing', 'common', 'noun']

[[cards]]
kanji = '天才'
kana = 'てんさい'
english = 'genius; prodigy'
level = 'n1'
tags = ['common', 'noun']

[[cards]]
kanji = '通り'
kana = 'とおり'
english = 'avenue; street'
level = 'n3'
source = 'jlptstudy.net'
tags = ['adverbial-noun', 'common', 'noun']

[[cards]]
kanji = '特別'
kana = 'とくべつ'
english = 'special'
level = 'n4'
source = 'jlptstudy.net'
tags = ['adverb', 'common', 'no-adjective', 'noun']

[[cards]]
kanji = '扉'
kana = 'とびら'
english = 'gate'
level = 'n1'
source = 'tobira'
tags = ['common', 'noun']

[[cards]]
kanji = '道路'
kana = 'どうろ'
english = 'highway'
level = 'n3'
tags = ['common', 'noun', 'places']

[[cards]]
kanji = '何か'
kana = 'なにか'
english = 'something'
level = 'n3'
tags = ['common', 'expression']

[[cards]]
kanji = '何も'
kana = 'なにも'
english = 'nothing'
level = 'n3'
tags = ['adverb', 'common', 'expression']

[[cards]]
kanji = '日光'
kana = 'にっこう'
english = 'sunlight; sunshine; sunbeams'
level = 'n3'
tags = ['common', 'noun']

[[cards]]
kanji = '値段'
kana = 'ねだん'
english = 'price'
level = 'n4'
tags = ['common', 'noun']

[[cards]]
kanji = '外れ'
kana = 'はずれ'
english = 'extremity; verge; outskirts'
source = 'wanikani'
tags = ['common', 'noun']

[[cards]]
kanji = '花火'
kana = 'はなび'
english = 'fireworks'
level = 'n2'
tags = ['common']

[[cards]]
kanji = '半額'
kana = 'はんがく'
english = 'half price'
source = 'nihongo-charenji-n4-kotoba'
tags = ['common']

[[cards]]
kanji = '反対'
kana = 'はんたい'
english = 'opposite; inverse'
level = 'n4'
source = 'living-in-japan'
tags = ['common', 'na-adjective', 'no-adjective', 'noun', 'suru-verb']

[[cards]]
kanji = '爆破'
kana = 'ばくは'
english = 'explosion'
level = 'n1'
source = 'boku-no-hero-academia-anime'
tags = ['common', 'noun', 'suru-verb']

[[cards]]
kanji = '引き分け'
kana = 'ひきわけ'
english = 'tie (in a game)'
level = 'n2'
source = 'wanikani'
tags = ['common', 'noun']

[[cards]]
kanji = '非常口'
kana = 'ひじょうぐち'
english = 'emergency exit'
tags = ['building', 'common', 'noun']

[[cards]]
kanji = '酷い'
kana = 'ひどい'
english = 'cruel; heartless; violent'
level = 'n4'
source = 'anime'
tags = ['common', 'i-adjective']

[[cards]]
kanji = '秘密'
kana = 'ひみつ'
english = 'secret'
level = 'n3'
tags = ['common', 'na-adjective', 'no-adjective', 'noun']

[[cards]]
kanji = '不正'
kana = 'ふせい'
english = 'injustice'
level = 'n3'
source = 'wanikani'
tags = ['common', 'na-adjective', 'noun']

[[cards]]
kanji = '普通'
kana = 'ふつう'
english = 'general; ordinary'
level = 'n4'
source = 'nihongo-sou-matome'
tags = ['adverb', 'common', 'no-adjective']

[[cards]]
kanji = '船'
kana = 'ふね'
english = 'boat'
level = 'n4'
tags = ['common', 'noun', 'transportation']

[[cards]]
kanji = '返事'
kana = 'へんじ'
english = 'response; reply; answer'
level = 'n4'
source = 'wanikani'
tags = ['common', 'noun', 'suru-verb']

[[cards]]
kanji = '別に'
kana = 'べつに'
english = 'not particularly'
level = 'n3'
tags = ['adverb', 'common']

[[cards]]
kanji = '方'
kana = 'ほう'
english = 'direction; way; method; side'
level = 'n3'
tags = ['common', 'noun']

[[cards]]
kanji = '宝石'
kana = 'ほうせき'
english = 'gem; jewel; precious stone'
level = 'n3'
source = 'wanikani'
tags = ['common', 'no-adjective', 'noun']

[[cards]]
kanji = '褒美'
kana = 'ほうび'
english = 'reward'
level = 'n1'
source = 'wanikani'
tags = ['common', 'noun']

[[cards]]
kanji = '黒子'
kana = 'ほくろ'
english = 'mole; beauty spot'
source = 'wanikani'
tags = ['common', 'noun']

[[cards]]
kanji = '墓地'
kana = 'ぼち'
english = 'graveyard; cemetery'
level = 'n1'
tags = ['common', 'noun', 'places']

[[cards]]
kanji = '間違い'
kana = 'まちがい'
english = 'mistake; error'
level = 'n3'
tags = ['common', 'noun']

[[cards]]
kanji = '祭'
kana = 'まつり'
english = 'festival'
level = 'n3'
tags = ['common']

[[cards]]
kanji = '丸ごと'
kana = 'まるごと'
english = 'wholly'
level = 'n1'
source = 'wanikani'
tags = ['adverb', 'common']

[[cards]]
kanji = '蜜柑'
kana = 'みかん'
english = 'mandarin orange'
tags = ['common', 'food', 'fruit', 'noun']

[[cards]]
kanji = '水色'
kana = 'みずいろ'
english = 'light blue; aqua'
source = 'wanikani'
tags = ['appearance', 'colors', 'common', 'moun', 'no-adjective']

[[cards]]
kanji = '名字'
kana = 'みょうじ'
english = 'family name'
level = 'n2'
source = 'wanikani'
tags = ['common', 'names', 'noun', 'people']

[[cards]]
kanji = '名人'
kana = 'めいじん'
english = 'master; expert'
level = 'n3'
source = 'wanikani'
tags = ['common', 'noun', 'person']

[[cards]]
kanji = '申し訳ない'
kana = 'もうしわけない'
english = "I'm sorry; it's inexcusable; I feel guilty"
level = 'n2'
source = 'wanikani'
tags = ['common', 'expression', 'i-adjective']

[[cards]]
kanji = '若し'
kana = 'もし'
english = 'if; supposing'
level = 'n4'
tags = ['adverb', 'common']

[[cards]]
kanji = '元'
kana = 'もと'
english = 'origin; source'
level = 'n3'
source = 'wanikani'
tags = ['common', 'noun']

[[cards]]
kanji = '矢'
kana = 'や'
english = 'arrow'
level = 'n1'
source = 'wanikani'
tags = ['common', 'noun', 'weapon']

[[cards]]
kanji = '野球'
kana = 'やきゅう'
english = 'baseball'
tags = ['common', 'noun', 'sports']

[[cards]]
kanji = '郵便'
kana = 'ゆうびん'
english = 'postal service'
level = 'n3'
tags = ['common', 'noun']

[[cards]]
kanji = '幽霊'
kana = 'ゆうれい'
english = 'specter; phantom'
level = 'n1'
source = 'wanikani'
tags = ['common', 'noun']

[[cards]]
kanji = '床'
kana = 'ゆか'
english = 'floor'
level = 'n3'
source = 'common'
tags = ['buildings', 'common', 'noun']

[[cards]]
kanji = '輸入'
kana = 'ゆにゅう'
english = 'introduction; importation'
level = 'n3'
source = 'jlptstudy.net'
tags = ['common', 'noun', 'suru-verb']

[[cards]]
kanji = '夢'
kana = 'ゆめ'
english = 'dream'
level = 'n4'
tags = ['common']

[[cards]]
kanji = '用'
kana = 'よう'
english = 'task'
level = 'n4'
source = 'wanikani'
tags = ['common', 'noun', 'noun-suffix']

[[cards]]
kanji = '用'
kana = 'よう'
english = 'task; business'
level = 'n4'
tags = ['common', 'noun']

[[cards]]
kanji = '用意'
kana = 'ようい'
english = 'preparation; provision; arrangement'
level = 'n4'
source = 'nihongo-charenji-n4-kotoba'
tags = ['common', 'noun', 'suru-verb']

[[cards]]
kanji = '妖怪'
kana = 'ようかい'
english = 'ghost'
source = 'games'
tags = ['common', 'noun']

[[cards]]
kanji = '羊毛'
kana = 'ようもう'
english = 'wool'
level = 'n2'
source = 'wanikani'
tags = ['common', 'no-adjective', 'noun']

[[cards]]
kanji = '予約'
kana = 'よやく'
english = 'reservation; appointment'
level = 'n4'
source = 'jlptstudy.net'
tags = ['common', 'noun', 'suru-verb']

[[cards]]
kanji = '冷凍'
kana = 'れいとう'
english = 'freeze/freezing; cold storage; refridgeration'
level = 'n2'
source = 'nihongo-charenji-n4-kotoba'
tags = ['common', 'noun', 'suru-verb']

[[cards]]
kanji = '冷房'
kana = 'れいぼう'
english = 'air conditioning'
level = 'n4'
source = 'jlptstudy.net'
tags = ['common', 'noun', 'suru-verb']

[[cards]]
kanji = '割引'
kana = 'わりびき'
english = 'discount; rebate'
level = 'n2'
source = 'nihongo-charenji-n4-kotoba'
tags = ['common', 'noun']

[[cards]]
kanji = 'セール'
kana = 'セール'
english = 'sale'
source = 'nihongo-charenji-n4-kotoba'
level = 'n1'
tags = ['common', 'gairaigo']

[[cards]]
kanji = 'ホッチキス'
kana = 'ホッチキス'
english = 'stapler'
source = 'irasshai'
tags = ['gairaigo', 'noun', 'uncommon']

