[[cards]]
kanji = '悪魔'
kana = 'あくま'
english = 'devil; demon'
source = 'anime; jisho'
level = 'n3'
tags = ['common', 'monster', 'mythical', 'noun']
frequency_scores = { anime = 710, leeds = 4603, novels = 2157, wikipedia = 3876 }

[[cards]]
kanji = '鬼'
kana = 'おに'
english = 'demon; ogre'
source = 'majoras mask'
level = 'n3'
tags = ['common', 'monster', 'mythical', 'noun']
frequency_scores = { anime = 677, leeds = 3680, novels = 1141, wikipedia = 2323 }

[[cards]]
kanji = '怪獣'
kana = 'かいじゅう'
english = 'monster'
source = 'films'
level = 'n1'
tags = ['common', 'monster', 'mythical', 'noun']
frequency_scores = { anime = 4990, leeds = 10154, wikipedia = 4129 }

[[cards]]
kanji = '神'
kana = 'かみ'
english = 'god; deity; spirit'
source = 'anime'
level = 'n3'
tags = ['anime', 'common', 'noun', 'noun-prefix', 'religion']
frequency_scores = { anime = 184, leeds = 694, novels = 362, wikipedia = 364 }

[[cards]]
kanji = '幽霊'
kana = 'ゆうれい'
english = 'specter; phantom'
level = 'n1'
source = 'wanikani'
tags = ['common', 'noun']
frequency_scores = { anime = 1830, leeds = 8719, novels = 2279, wikipedia = 9403 }

[[cards]]
kanji = '妖怪'
kana = 'ようかい'
english = 'ghost'
source = 'games'
tags = ['common', 'noun']
frequency_scores = { anime = 3737, leeds = 11053, wikipedia = 6299 }

