[[cards]]
kanji = '挨拶'
kana = 'あいさつ'
english = 'greeting; salutation'
level = 'n4'
source = 'jlptstudy.net'
tags = ['common', 'no-adjective', 'noun', 'suru-verb']
frequency_scores = { anime = 1517, leeds = 2257, novels = 1421, wikipedia = 6535 }

[[cards]]
kanji = '間'
kana = 'あいだ'
english = 'space or time between; gap; interval'
level = 'n4'
source = 'jlptstudy.net'
tags = ['adverbial-noun', 'common', 'noun', 'temporal-noun']
frequency_scores = { anime = 323, leeds = 254, novels = 156, wikipedia = 123 }

[[cards]]
kanji = '浅い'
kana = 'あさい'
english = 'shallow; superficial'
level = 'n4'
source = 'jlptstudy.net'
tags = ['common', 'i-adjective']
frequency_scores = { anime = 4470, leeds = 5922, novels = 2703, wikipedia = 5850 }

[[cards]]
kanji = '明日'
kana = 'あす'
english = 'tomorrow (more formal)'
level = 'n4'
source = 'jlptstudy.net'
tags = ['alternate', 'common', 'formal', 'temporal-noun']
frequency_scores = { anime = 205, leeds = 746, novels = 875, wikipedia = 5183 }

[[cards]]
kanji = '安心'
kana = 'あんしん'
english = 'relief'
level = 'n4'
source = 'jlptstudy.net'
tags = ['common', 'na-adjective', 'noun', 'suru-verb']
frequency_scores = { anime = 589, leeds = 1465, novels = 1143 }

[[cards]]
kanji = '安全'
kana = 'あんぜん'
english = 'safety; security'
level = 'n4'
source = 'jlptstudy.net'
tags = ['common', 'na-adjective', 'noun']
frequency_scores = { anime = 1162, leeds = 760, novels = 1660, wikipedia = 1037 }

[[cards]]
kanji = '意見'
kana = 'いけん'
english = 'opinion; view'
level = 'n4'
source = 'jlptstudy.net'
tags = ['common', 'no-adjective', 'noun', 'suru-verb']
frequency_scores = { anime = 1951, leeds = 377, novels = 1652, wikipedia = 1621 }

[[cards]]
kanji = '石'
kana = 'いし'
english = 'stone'
level = 'n4'
tags = ['common', 'noun']
frequency_scores = { anime = 644, leeds = 1936, novels = 704, wikipedia = 378 }

[[cards]]
kanji = '一度'
kana = 'いちど'
english = 'once; one time; on one occasion'
level = 'n4'
source = 'irasshai'
tags = ['adverbial noun', 'common']
frequency_scores = { anime = 1112, leeds = 1522, novels = 1032 }

[[cards]]
kanji = '一生懸命'
kana = 'いっしょうけんめい'
english = 'very hard; with utmost effort; for dear life'
level = 'n4'
tags = ['adverbial-noun', 'common', 'na-adjective', 'noun']
frequency_scores = { anime = 2195, leeds = 3109 }

[[cards]]
kanji = '受付'
kana = 'うけつけ'
english = 'reception (desk); information desk'
level = 'n4'
source = 'jlptstudy.net'
tags = ['building', 'common', 'noun']
frequency_scores = { anime = 6665, leeds = 3626, wikipedia = 9928 }

[[cards]]
kanji = '嘘'
kana = 'うそ'
english = 'lie'
level = 'n3'
tags = ['common', 'no-adjective', 'noun']
frequency_scores = { anime = 354, leeds = 2744, novels = 849, wikipedia = 7797 }

[[cards]]
kanji = '美しい'
kana = 'うつくしい'
english = 'beautiful; lovely'
level = 'n4'
source = 'jlptstudy.net'
tags = ['common', 'i-adjective']
frequency_scores = { anime = 972, leeds = 1067, novels = 581, wikipedia = 2739 }

[[cards]]
kanji = '裏'
kana = 'うら'
english = 'opposite side; other side; underside; bottom; behind'
level = 'n4'
source = 'zelda'
tags = ['common', 'directions', 'noun']
frequency_scores = { anime = 911, leeds = 1559, novels = 993, wikipedia = 1676 }

[[cards]]
kanji = '運転手'
kana = 'うんてんしゅ'
english = 'driver; chauffer'
level = 'n4'
source = 'jlptstudy.net'
tags = ['common', 'job', 'noun', 'people']
frequency_scores = { leeds = 4352, wikipedia = 9506 }

[[cards]]
kanji = 'お祝い'
kana = 'おいわい'
english = 'congratulation; celebration; festival; celebatory gift'
level = 'n4'
source = 'jlptstudy.net'
tags = ['common', 'noun', 'suru-verb']
frequency_scores = { anime = 4058, leeds = 6824 }

[[cards]]
kanji = '会議'
kana = 'かいぎ'
english = 'meeting; conference'
source = 'n4-study'
level = 'n4'
tags = ['common', 'no-adjective', 'noun', 'suru-verb']
frequency_scores = { anime = 1174, leeds = 704, novels = 2563, wikipedia = 554 }

[[cards]]
kanji = '会議室'
kana = 'かいぎしつ'
english = 'conference room'
source = 'n4-study'
level = 'n4'
tags = ['common', 'noun', 'office', 'place']

[[cards]]
kanji = '関係'
kana = 'かんけい'
english = 'relationship; connection'
source = 'n4-study'
level = 'n4'
tags = ['common', 'no-adjective', 'noun', 'suru-verb']
frequency_scores = { anime = 285, leeds = 196, novels = 436, wikipedia = 180 }

[[cards]]
kanji = '気'
kana = 'き'
english = 'spirit; mind; heart; nature; feelings'
level = 'n4'
tags = ['common', 'noun']
frequency_scores = { anime = 62, leeds = 204, novels = 111, wikipedia = 1258 }

[[cards]]
kanji = '機会'
kana = 'きかい'
english = 'chance; opportunity'
source = 'n4-study'
level = 'n4'
tags = ['common', 'noun']
frequency_scores = { anime = 1675, leeds = 924, novels = 1767, wikipedia = 1747 }

[[cards]]
kanji = '危険'
kana = 'きけん'
english = 'danger; peril'
source = 'n4-study'
level = 'n4'
tags = ['na-adjective', 'noun']
frequency_scores = { anime = 539, leeds = 1075, novels = 718, wikipedia = 1741 }

[[cards]]
kanji = '近所'
kana = 'きんじょ'
english = 'neighborhood'
source = 'jlptstudy'
level = 'n4'
tags = ['no-adjective', 'noun', 'places']
frequency_scores = { anime = 3108, leeds = 2339, novels = 2197 }

[[cards]]
kanji = '具合'
kana = 'ぐあい'
english = 'condition; state'
source = 'n4-study'
level = 'n4'
tags = ['common', 'noun']
frequency_scores = { anime = 2226, leeds = 3119, novels = 2440, wikipedia = 5852 }

[[cards]]
kanji = '政治'
kana = 'せいじ'
english = 'politics'
source = 'n4-wikipedia'
level = 'n4'
tags = ['common', 'noun', 'politics', 'profession']
frequency_scores = { anime = 5395, leeds = 477, novels = 2550, wikipedia = 273 }

[[cards]]
kanji = '西洋'
kana = 'せいよう'
english = 'the West; western countries'
source = 'n4-wikipedia; wanikani'
level = 'n4'
tags = ['common', 'geography', 'no-adjective', 'noun']
frequency_scores = { anime = 16609, leeds = 3889, wikipedia = 2929 }

[[cards]]
kanji = '戦争'
kana = 'せんそう'
english = 'war'
source = 'anime; wikipedia-n4'
level = 'n4'
tags = ['common', 'fighting', 'noun', 'suru-verb', 'war']
frequency_scores = { anime = 881, leeds = 647, novels = 941, wikipedia = 212 }

[[cards]]
kanji = '注意'
kana = 'ちゅうい'
english = 'caution; being careful'
source = 'wanikani'
level = 'n4'
tags = ['common', 'noun', 'suru-verb']
frequency_scores = { anime = 1638, leeds = 945, novels = 1266, wikipedia = 2204 }

[[cards]]
kanji = '途中'
kana = 'とちゅう'
english = 'on the way; en route'
source = 'n4-wikipedia'
level = 'n4'
tags = ['adverbial-noun', 'common', 'temporal-noun', 'travel']
frequency_scores = { anime = 1055, leeds = 1125, novels = 995, wikipedia = 907 }

[[cards]]
kanji = '二階建て'
kana = 'にかいだて'
english = 'two-story building'
source = 'n4-wikipedia'
level = 'n4'
tags = ['buildings', 'common', 'noun', 'places']

[[cards]]
kanji = '筈'
kana = 'はず'
english = 'expectation that something will or would have taken place'
source = 'anime-frequency'
level = 'n4'
explain = 'http://maggiesensei.com/2012/11/14/request-lesson-how-and-when-to-use-%E3%81%AF%E3%81%9Ahazu/'
tags = ['common', 'grammar']
frequency_scores = { anime = 9113, leeds = 5553, novels = 1850 }

[[cards]]
kanji = '発音'
kana = 'はつおん'
english = 'pronunciation'
source = 'irasshai'
level = 'n4'
tags = ['common', 'language', 'noun', 'speaking', 'suru-verb']
frequency_scores = { anime = 10684, leeds = 3383, wikipedia = 3089 }

[[cards]]
kanji = '船'
kana = 'ふね'
english = 'boat'
source = 'irasshai'
level = 'n4'
tags = ['common', 'noun', 'ocean', 'transportation', 'vehicle']
frequency_scores = { anime = 675, leeds = 1735, novels = 398, wikipedia = 327 }

[[cards]]
kanji = '不便'
kana = 'ふべん'
english = 'inconvenience'
source = 'n4-wikipedia'
level = 'n4'
tags = ['common', 'na-adjective', 'noun']
frequency_scores = { anime = 8103, leeds = 6343 }

[[cards]]
kanji = '法律'
kana = 'ほうりつ'
english = 'law'
source = 'n4-wikipedia'
level = 'n4'
tags = ['common', 'government', 'no-adjective', 'noun', 'profession']
frequency_scores = { anime = 9784, leeds = 661, wikipedia = 962 }

[[cards]]
kanji = '真ん中'
kana = 'まんなか'
english = 'midpoint; center; heart'
source = 'bonobono-anime'
level = 'n4'
tags = ['common', 'noun']
frequency_scores = { anime = 3031, leeds = 4371, novels = 2672 }

[[cards]]
kanji = 'やっと'
kana = 'やっと'
english = "barely!; by the skin of one's teeth"
source = 'n4-wikipedia'
level = 'n4'
tags = ['adverb', 'common', 'onomatopoeia']
frequency_scores = { anime = 708, leeds = 1638, novels = 1026 }

[[cards]]
kanji = '用事'
kana = 'ようじ'
english = 'tasks; things to do'
source = 'n4-wikipedia'
level = 'n4'
tags = ['common', 'noun']
frequency_scores = { anime = 2035, leeds = 7093 }

[[cards]]
kanji = '理由'
kana = 'りゆう'
english = 'reason; motive'
source = 'n4'
level = 'n4study'
tags = ['common', 'noun']
frequency_scores = { anime = 396, leeds = 456, novels = 565, wikipedia = 586 }

[[cards]]
kanji = '両方'
kana = 'りょうほう'
english = 'both; both sides'
source = 'n4study'
level = 'n4'
tags = ['common', 'no-adjective', 'noun']
frequency_scores = { anime = 3150, leeds = 2161, novels = 2839, wikipedia = 2536 }

[[cards]]
kanji = '留守'
kana = 'るす'
english = 'absent; away from home'
source = 'irasshai'
level = 'n4'
tags = ['common', 'no-adjective', 'noun', 'suru-verb']
frequency_scores = { anime = 4593, leeds = 9928, wikipedia = 9235 }

[[cards]]
kanji = '訳'
kana = 'わけ'
english = 'draw conclusion from reasoning'
source = 'anime-frequency'
level = 'n4'
explain = 'http://www.guidetojapanese.org/learn/grammar/reasoning'
tags = ['common']
frequency_scores = { anime = 764, leeds = 797, novels = 1166, wikipedia = 2115 }

[[cards]]
kanji = '忘れ物'
kana = 'わすれもの'
english = 'lost item; something forgotten'
source = 'jlpt-study'
level = 'n4'
tags = ['common', 'noun']
frequency_scores = { anime = 3259 }

[[cards]]
kanji = '割合'
kana = 'わりあい'
english = 'rate; ratio; percentage'
source = 'n4-wikipedia'
level = 'n4'
tags = ['adverb', 'common', 'math', 'noun']
frequency_scores = { anime = 16726, leeds = 2798 }

[[cards]]
kanji = 'アクセサリー'
kana = 'アクセサリー'
english = 'accessory'
level = 'n4'
source = 'jlptstudy.net'
tags = ['common', 'gairaigo']
frequency_scores = { anime = 16663, leeds = 8001 }

[[cards]]
kanji = 'アジア'
kana = 'アジア'
english = 'Asia'
level = 'n4'
source = 'jlptstudy.net'
tags = ['common', 'gairaigo', 'no-adjective', 'noun']
frequency_scores = { anime = 15197, leeds = 1253, wikipedia = 649 }

[[cards]]
kanji = 'アルバイト'
kana = 'アルバイト'
english = 'part-time job (from German)'
level = 'n4'
tags = ['common', 'gairaigo', 'noun', 'suru-verb']
frequency_scores = { anime = 6902, leeds = 4093, wikipedia = 7199 }

