[[cards]]
kanji = 'ああ'
kana = 'ああ'
english = 'like that (distant)'
level = 'n4'
source = 'jlptstudy.net'
tags = ['adverb', 'common']

[[cards]]
kanji = '挨拶'
kana = 'あいさつ'
english = 'greeting; salutation'
level = 'n4'
source = 'jlptstudy.net'
tags = ['common', 'no-adjective', 'noun', 'suru-verb']

[[cards]]
kanji = '間'
kana = 'あいだ'
english = 'space or time between; gap; interval'
level = 'n4'
source = 'jlptstudy.net'
tags = ['adverbial-noun', 'common', 'noun', 'temporal-noun']

[[cards]]
kanji = '赤ん坊'
kana = 'あかぼう'
english = 'infant'
level = 'n4'
source = 'jlptstudy.net'
tags = ['common', 'noun', 'people']

[[cards]]
kanji = '浅い'
kana = 'あさい'
english = 'shallow; superficial'
level = 'n4'
source = 'jlptstudy.net'
tags = ['common', 'i-adjective']

[[cards]]
kanji = '味'
kana = 'あじ'
english = 'flavor; taste'
level = 'n4'
source = 'jlptstudy.net'
tags = ['common', 'noun']

[[cards]]
kanji = 'あっ'
kana = 'あっ'
english = 'ah; oh; hey!'
level = 'n4'
source = 'jlptstudy.net'
tags = ['common']

[[cards]]
kanji = '安心'
kana = 'あんしん'
english = 'peace of mind; relief'
level = 'n4'
source = 'jlptstudy.net'
tags = ['common', 'na-adjective', 'noun', 'suru-verb']

[[cards]]
kanji = '安全'
kana = 'あんぜん'
english = 'safety; security'
level = 'n4'
source = 'jlptstudy.net'
tags = ['common', 'na-adjective', 'noun']

[[cards]]
kanji = '意見'
kana = 'いけん'
english = 'opinion; view'
level = 'n4'
source = 'jlptstudy.net'
tags = ['common', 'no-adjective', 'noun', 'suru-verb']

[[cards]]
kanji = '石'
kana = 'いし'
english = 'stone'
level = 'n4'
tags = ['common', 'noun']

[[cards]]
kanji = 'アクセサリー'
kana = 'アクセサリー'
english = 'accessory'
level = 'n4'
source = 'jlptstudy.net'
tags = ['common', 'gairaigo']

[[cards]]
kanji = 'アジア'
kana = 'アジア'
english = 'Asia'
level = 'n4'
source = 'jlptstudy.net'
tags = ['common', 'gairaigo', 'no-adjective', 'noun']

[[cards]]
kanji = 'アフリカ'
kana = 'アフリカ'
english = 'Africa'
level = 'n4'
tags = ['common', 'gairaigo', 'no-adjective', 'noun']

[[cards]]
kanji = 'アメリカ'
kana = 'アメリカ'
english = 'America'
level = 'n4'
tags = ['common', 'gairaigo', 'noun']

[[cards]]
kanji = 'アルコール'
kana = 'アルコール'
english = 'alcohol'
level = 'n4'
source = 'jlptstudy.net'
tags = ['common', 'gairaigo', 'no-adjective', 'noun']

[[cards]]
kanji = 'アルバイト'
kana = 'アルバイト'
english = 'part-time job (from German)'
level = 'n4'
tags = ['common', 'gairaigo', 'noun', 'suru-verb']

