[[cards]]
kanji = 'ああ'
kana = 'ああ'
english = 'like that (distant)'
level = 'n4'
source = 'jlptstudy.net'
tags = ['adverb', 'common']

[[cards]]
kanji = '挨拶'
kana = 'あいさつ'
english = 'greeting; salutation'
level = 'n4'
source = 'jlptstudy.net'
tags = ['common', 'no-adjective', 'noun', 'suru-verb']

[[cards]]
kanji = '間'
kana = 'あいだ'
english = 'space or time between; gap; interval'
level = 'n4'
source = 'jlptstudy.net'
tags = ['adverbial-noun', 'common', 'noun', 'temporal-noun']

[[cards]]
kanji = '赤ん坊'
kana = 'あかんぼう'
english = 'infant'
level = 'n4'
source = 'jlptstudy.net'
tags = ['common', 'noun', 'people']

[[cards]]
kanji = '浅い'
kana = 'あさい'
english = 'shallow; superficial'
level = 'n4'
source = 'jlptstudy.net'
tags = ['common', 'i-adjective']

[[cards]]
kanji = '味'
kana = 'あじ'
english = 'flavor; taste'
level = 'n4'
source = 'jlptstudy.net'
tags = ['common', 'noun']

[[cards]]
kanji = '明日'
kana = 'あす'
english = 'tomorrow (more formal)'
level = 'n4'
source = 'jlptstudy.net'
tags = ['alternate', 'common', 'formal', 'temporal-noun']

[[cards]]
kanji = 'あっ'
kana = 'あっ'
english = 'ah; oh; hey!'
level = 'n4'
source = 'jlptstudy.net'
tags = ['common']

[[cards]]
kanji = '安心'
kana = 'あんしん'
english = 'peace of mind; relief'
level = 'n4'
source = 'jlptstudy.net'
tags = ['common', 'na-adjective', 'noun', 'suru-verb']

[[cards]]
kanji = '安全'
kana = 'あんぜん'
english = 'safety; security'
level = 'n4'
source = 'jlptstudy.net'
tags = ['common', 'na-adjective', 'noun']

[[cards]]
kanji = '意見'
kana = 'いけん'
english = 'opinion; view'
level = 'n4'
source = 'jlptstudy.net'
tags = ['common', 'no-adjective', 'noun', 'suru-verb']

[[cards]]
kanji = '石'
kana = 'いし'
english = 'stone'
level = 'n4'
tags = ['common', 'noun']

[[cards]]
kanji = '一度'
kana = 'いちど'
english = 'once; one time; on one occasion'
level = 'n4'
source = 'irasshai'
tags = ['adverbial noun', 'common']

[[cards]]
kanji = '一生懸命'
kana = 'いっしょうけんめい'
english = 'very hard; with utmost effort; for dear life'
level = 'n4'
tags = ['adverbial-noun', 'common', 'na-adjective', 'noun']

[[cards]]
kanji = '受付'
kana = 'うけつけ'
english = 'reception (desk); information desk'
level = 'n4'
source = 'jlptstudy.net'
tags = ['building', 'common', 'noun']

[[cards]]
kanji = '嘘'
kana = 'うそ'
english = 'lie'
level = 'n3'
tags = ['common', 'no-adjective', 'noun']

[[cards]]
kanji = '美しい'
kana = 'うつくしい'
english = 'beautiful; lovely'
level = 'n4'
source = 'jlptstudy.net'
tags = ['common', 'i-adjective']

[[cards]]
kanji = '腕'
kana = 'うで'
english = 'arm'
level = 'n4'
tags = ['anatomy', 'body', 'common', 'noun']

[[cards]]
kanji = '裏'
kana = 'うら'
english = 'opposite side; other side; underside; bottom; behind'
level = 'n4'
source = 'zelda'
tags = ['common', 'directions', 'noun']

[[cards]]
kanji = '運転手'
kana = 'うんてんしゅ'
english = 'driver; chauffer'
level = 'n4'
source = 'jlptstudy.net'
tags = ['common', 'job', 'noun', 'people']

[[cards]]
kanji = '枝'
kana = 'えだ'
english = 'branch; limb; twig'
level = 'n4'
source = 'jlptstudy.net'
tags = ['common', 'nature', 'noun']

[[cards]]
kanji = 'お祝い'
kana = 'おいわい'
english = 'congratulation; celebration; festival; celebatory gift'
level = 'n4'
source = 'jlptstudy.net'
tags = ['common', 'noun', 'suru-verb']

[[cards]]
kanji = 'ずっと'
kana = 'ずっと'
english = 'continuously in some state (for a long time or distance); all along; the whole time; long ago; far away'
level = 'n3'
tags = ['adverb', 'anime', 'common']

[[cards]]
kanji = '幼児'
kana = 'ようじ'
english = 'toddler'
level = 'n2'
source = 'jisho.org'
tags = ['common', 'noun', 'people']

[[cards]]
kanji = 'アクセサリー'
kana = 'アクセサリー'
english = 'accessory'
level = 'n4'
source = 'jlptstudy.net'
tags = ['common', 'gairaigo']

[[cards]]
kanji = 'アジア'
kana = 'アジア'
english = 'Asia'
level = 'n4'
source = 'jlptstudy.net'
tags = ['common', 'gairaigo', 'no-adjective', 'noun']

[[cards]]
kanji = 'アナウンサー'
kana = 'アナウンサー'
english = 'announcer'
level = 'n4'
tags = ['common', 'gairaigo', 'noun', 'people']

[[cards]]
kanji = 'アルコール'
kana = 'アルコール'
english = 'alcohol'
level = 'n4'
source = 'jlptstudy.net'
tags = ['common', 'gairaigo', 'no-adjective', 'noun']

[[cards]]
kanji = 'アルバイト'
kana = 'アルバイト'
english = 'part-time job (from German)'
level = 'n4'
tags = ['common', 'gairaigo', 'noun', 'suru-verb']

