[[cards]]
kanji = 'ああ'
kana = 'ああ'
english = 'like that (distant)'
level = 'n4'
source = 'jlptstudy.net'
tags = ['adverb', 'common']

[[cards]]
kanji = '挨拶'
kana = 'あいさつ'
english = 'greeting; salutation'
level = 'n4'
source = 'jlptstudy.net'
tags = ['common', 'no-adjective', 'noun', 'suru-verb']

[[cards]]
kanji = '間'
kana = 'あいだ'
english = 'space or time between; gap; interval'
level = 'n4'
source = 'jlptstudy.net'
tags = ['adverbial-noun', 'common', 'noun', 'temporal-noun']

[[cards]]
kanji = '赤ん坊'
kana = 'あかんぼう'
english = 'infant'
level = 'n4'
source = 'jlptstudy.net'
tags = ['common', 'noun', 'people']

[[cards]]
kanji = '浅い'
kana = 'あさい'
english = 'shallow; superficial'
level = 'n4'
source = 'jlptstudy.net'
tags = ['common', 'i-adjective']

[[cards]]
kanji = '明日'
kana = 'あす'
english = 'tomorrow (more formal)'
level = 'n4'
source = 'jlptstudy.net'
tags = ['alternate', 'common', 'formal', 'temporal-noun']

[[cards]]
kanji = 'あっ'
kana = 'あっ'
english = 'ah; oh; hey!'
level = 'n4'
source = 'jlptstudy.net'
tags = ['common']

[[cards]]
kanji = '安心'
kana = 'あんしん'
english = 'relief'
level = 'n4'
source = 'jlptstudy.net'
tags = ['common', 'na-adjective', 'noun', 'suru-verb']

[[cards]]
kanji = '安全'
kana = 'あんぜん'
english = 'safety; security'
level = 'n4'
source = 'jlptstudy.net'
tags = ['common', 'na-adjective', 'noun']

[[cards]]
kanji = '意見'
kana = 'いけん'
english = 'opinion; view'
level = 'n4'
source = 'jlptstudy.net'
tags = ['common', 'no-adjective', 'noun', 'suru-verb']

[[cards]]
kanji = '石'
kana = 'いし'
english = 'stone'
level = 'n4'
tags = ['common', 'noun']

[[cards]]
kanji = '一度'
kana = 'いちど'
english = 'once; one time; on one occasion'
level = 'n4'
source = 'irasshai'
tags = ['adverbial noun', 'common']

[[cards]]
kanji = '一生懸命'
kana = 'いっしょうけんめい'
english = 'very hard; with utmost effort; for dear life'
level = 'n4'
tags = ['adverbial-noun', 'common', 'na-adjective', 'noun']

[[cards]]
kanji = '受付'
kana = 'うけつけ'
english = 'reception (desk); information desk'
level = 'n4'
source = 'jlptstudy.net'
tags = ['building', 'common', 'noun']

[[cards]]
kanji = '嘘'
kana = 'うそ'
english = 'lie'
level = 'n3'
tags = ['common', 'no-adjective', 'noun']

[[cards]]
kanji = '美しい'
kana = 'うつくしい'
english = 'beautiful; lovely'
level = 'n4'
source = 'jlptstudy.net'
tags = ['common', 'i-adjective']

[[cards]]
kanji = '腕'
kana = 'うで'
english = 'arm'
level = 'n4'
tags = ['anatomy', 'body', 'common', 'noun']

[[cards]]
kanji = '裏'
kana = 'うら'
english = 'opposite side; other side; underside; bottom; behind'
level = 'n4'
source = 'zelda'
tags = ['common', 'directions', 'noun']

[[cards]]
kanji = '運転手'
kana = 'うんてんしゅ'
english = 'driver; chauffer'
level = 'n4'
source = 'jlptstudy.net'
tags = ['common', 'job', 'noun', 'people']

[[cards]]
kanji = '枝'
kana = 'えだ'
english = 'branch; limb; twig'
level = 'n4'
source = 'jlptstudy.net'
tags = ['common', 'nature', 'noun']

[[cards]]
kanji = 'お祝い'
kana = 'おいわい'
english = 'congratulation; celebration; festival; celebatory gift'
level = 'n4'
source = 'jlptstudy.net'
tags = ['common', 'noun', 'suru-verb']

[[cards]]
kanji = '会議'
kana = 'かいぎ'
english = 'meeting; conference'
source = 'n4-study'
level = 'n4'
tags = ['common', 'no-adjective', 'noun', 'suru-verb']

[[cards]]
kanji = '会議室'
kana = 'かいぎしつ'
english = 'conference room'
source = 'n4-study'
level = 'n4'
tags = ['common', 'noun', 'office', 'place']

[[cards]]
kanji = '関係'
kana = 'かんけい'
english = 'relationship; connection'
source = 'n4-study'
level = 'n4'
tags = ['common', 'no-adjective', 'noun', 'suru-verb']

[[cards]]
kanji = '気'
kana = 'き'
english = 'spirit; mind; heart; nature; feelings'
level = 'n4'
tags = ['common', 'noun']

[[cards]]
kanji = '機会'
kana = 'きかい'
english = 'chance; opportunity'
source = 'n4-study'
level = 'n4'
tags = ['common', 'noun']

[[cards]]
kanji = '危険'
kana = 'きけん'
english = 'danger; peril'
source = 'n4-study'
level = 'n4'
tags = ['na-adjective', 'noun']

[[cards]]
kanji = '近所'
kana = 'きんじょ'
english = 'neighborhood'
source = 'jlptstudy'
level = 'n4'
tags = ['no-adjective', 'noun', 'places']

[[cards]]
kanji = '具合'
kana = 'ぐあい'
english = 'condition; state'
source = 'n4-study'
level = 'n4'
tags = ['common', 'noun']

[[cards]]
kanji = 'ずっと'
kana = 'ずっと'
english = 'continuously in some state (for a long time or distance); all along; the whole time; long ago; far away'
level = 'n3'
tags = ['adverb', 'anime', 'common']

[[cards]]
kanji = '政治'
kana = 'せいじ'
english = 'politics'
source = 'n4-wikipedia'
level = 'n4'
tags = ['common', 'noun', 'politics', 'profession']

[[cards]]
kanji = '西洋'
kana = 'せいよう'
english = 'the West; western countries'
source = 'n4-wikipedia; wanikani'
level = 'n4'
tags = ['common', 'geography', 'no-adjective', 'noun']

[[cards]]
kanji = '戦争'
kana = 'せんそう'
english = 'war'
source = 'anime; wikipedia-n4'
level = 'n4'
tags = ['common', 'fighting', 'noun', 'suru-verb', 'war']

[[cards]]
kanji = '途中'
kana = 'とちゅう'
english = 'on the way; en route'
source = 'n4-wikipedia'
level = 'n4'
tags = ['adverbial-noun', 'common', 'temporal-noun', 'travel']

[[cards]]
kanji = '二階建て'
kana = 'にかいだて'
english = 'two-story building'
source = 'n4-wikipedia'
level = 'n4'
tags = ['buildings', 'common', 'noun', 'places']

[[cards]]
kanji = '発音'
kana = 'はつおん'
english = 'pronunciation'
source = 'irasshai'
level = 'n4'
tags = ['common', 'language', 'noun', 'speaking', 'suru-verb']

[[cards]]
kanji = '船'
kana = 'ふね'
english = 'boat'
source = 'irasshai'
level = 'n4'
tags = ['common', 'noun', 'ocean', 'transportation', 'vehicle']

[[cards]]
kanji = '不便'
kana = 'ふべん'
english = 'inconvenience'
source = 'n4-wikipedia'
level = 'n4'
tags = ['common', 'na-adjective', 'noun']

[[cards]]
kanji = '法律'
kana = 'ほうりつ'
english = 'law'
source = 'n4-wikipedia'
level = 'n4'
tags = ['common', 'government', 'no-adjective', 'noun', 'profession']

[[cards]]
kanji = '真ん中'
kana = 'まんなか'
english = 'midpoint; center; heart'
source = 'bonobono-anime'
level = 'n4'
tags = ['common', 'noun']

[[cards]]
kanji = '木綿'
kana = 'もめん'
english = 'cotton (material)'
source = 'n4-wikipedia'
level = 'n4'
tags = ['clothing', 'common', 'fabric', 'material', 'noun']

[[cards]]
kanji = 'やっと'
kana = 'やっと'
english = "barely!; by the skin of one's teeth"
source = 'n4-wikipedia'
level = 'n4'
tags = ['adverb', 'common', 'onomatopoeia']

[[cards]]
kanji = '用事'
kana = 'ようじ'
english = 'tasks; things to do'
source = 'n4-wikipedia'
level = 'n4'
tags = ['common', 'noun']

[[cards]]
kanji = '幼児'
kana = 'ようじ'
english = 'toddler'
level = 'n2'
source = 'jisho.org'
tags = ['common', 'noun', 'people']

[[cards]]
kanji = '理由'
kana = 'りゆう'
english = 'reason; motive'
source = 'n4'
level = 'n4study'
tags = ['common', 'noun']

[[cards]]
kanji = '両方'
kana = 'りょうほう'
english = 'both; both sides'
source = 'n4study'
level = 'n4'
tags = ['common', 'no-adjective', 'noun']

[[cards]]
kanji = '留守'
kana = 'るす'
english = 'absent; away from home'
source = 'irasshai'
level = 'n4'
tags = ['common', 'no-adjective', 'noun', 'suru-verb']

[[cards]]
kanji = '忘れ物'
kana = 'わすれもの'
english = 'lost item; something forgotten'
source = 'jlpt-study'
level = 'n4'
tags = ['common', 'noun']

[[cards]]
kanji = '割合'
kana = 'わりあい'
english = 'rate; ratio; percentage'
source = 'n4-wikipedia'
level = 'n4'
tags = ['adverb', 'common', 'math', 'noun']

[[cards]]
kanji = 'アクセサリー'
kana = 'アクセサリー'
english = 'accessory'
level = 'n4'
source = 'jlptstudy.net'
tags = ['common', 'gairaigo']

[[cards]]
kanji = 'アジア'
kana = 'アジア'
english = 'Asia'
level = 'n4'
source = 'jlptstudy.net'
tags = ['common', 'gairaigo', 'no-adjective', 'noun']

[[cards]]
kanji = 'アナウンサー'
kana = 'アナウンサー'
english = 'announcer'
level = 'n4'
tags = ['common', 'gairaigo', 'noun', 'people']

[[cards]]
kanji = 'アルコール'
kana = 'アルコール'
english = 'alcohol'
level = 'n4'
source = 'jlptstudy.net'
tags = ['common', 'gairaigo', 'no-adjective', 'noun']

[[cards]]
kanji = 'アルバイト'
kana = 'アルバイト'
english = 'part-time job (from German)'
level = 'n4'
tags = ['common', 'gairaigo', 'noun', 'suru-verb']

