[[cards]]
kanji = 'いい'
kana = 'いい'
english = 'good; OK'
level = 'n5'
tags = ['common', 'i-adjectives']
highest_frequency = 19
highest_frequency_source = 'Anime'

[[cards]]
kanji = '否'
kana = 'いいえ'
english = "no; not at all; don't mention it"
level = 'n5'
tags = ['basic', 'common']
highest_frequency = 1611
highest_frequency_source = 'Novels'

[[cards]]
kanji = '一緒'
kana = 'いっしょ'
english = 'together'
level = 'n5'
tags = ['adverbial-noun', 'no-adjective', 'temporal-noun']
highest_frequency = 103
highest_frequency_source = 'Anime'

[[cards]]
kanji = '意味'
kana = 'いみ'
english = 'meaning'
level = 'n5'
tags = []
highest_frequency = 222
highest_frequency_source = 'Anime'

[[cards]]
kanji = '嫌'
kana = 'いや'
english = 'disagreeable; unpleasant; no'
level = 'n5'
tags = []
highest_frequency = 283
highest_frequency_source = 'Anime'

[[cards]]
kanji = '入口'
kana = 'いりぐち'
english = 'entrance; gate'
level = 'n5'
tags = []
highest_frequency = 1874
highest_frequency_source = 'Novels'

[[cards]]
kanji = '歌'
kana = 'うた'
english = 'song'
level = 'n5'
tags = []
highest_frequency = 458
highest_frequency_source = 'Wikipedia'

[[cards]]
kanji = '絵'
kana = 'え'
english = 'picture; drawing; painting'
level = 'n5'
tags = []
highest_frequency = 659
highest_frequency_source = 'Anime'

[[cards]]
kanji = '映画'
kana = 'えいが'
english = 'movie'
level = 'n5'
tags = ['common', 'entertainment', 'no-adjective', 'noun']
highest_frequency = 99
highest_frequency_source = 'Wikipedia'

[[cards]]
kanji = '英語'
kana = 'えいご'
english = 'English language'
level = 'n5'
tags = []
highest_frequency = 441
highest_frequency_source = 'Leeds'

[[cards]]
kanji = 'ええ'
kana = 'ええ'
english = 'yes; um...'
level = 'n5'
tags = []
highest_frequency = 485
highest_frequency_source = 'Novels'

[[cards]]
kanji = '駅'
kana = 'えき'
english = 'train station'
level = 'n5'
tags = []
highest_frequency = 45
highest_frequency_source = 'Wikipedia'

[[cards]]
kanji = '～円'
kana = '～えん'
english = 'yen'
level = 'n5'
tags = []

[[cards]]
kanji = 'お金'
kana = 'おかね'
english = 'money'
level = 'n5'
tags = []
highest_frequency = 763
highest_frequency_source = 'Leeds'

[[cards]]
kanji = 'お酒'
kana = 'おさけ'
english = 'alcohol; sake (rice wine)'
level = 'n5'
tags = []

[[cards]]
kanji = '同じ'
kana = 'おなじ'
english = 'same; identical'
level = 'n5'
tags = ['common', 'noun']
highest_frequency = 132
highest_frequency_source = 'Wikipedia'

[[cards]]
kanji = '音楽'
kana = 'おんがく'
english = 'music'
level = 'n5'
tags = []
highest_frequency = 167
highest_frequency_source = 'Wikipedia'

[[cards]]
kanji = '会社'
kana = 'かいしゃ'
english = 'company; corporation'
level = 'n5'
tags = []
highest_frequency = 113
highest_frequency_source = 'Wikipedia'

[[cards]]
kanji = '階段'
kana = 'かいだん'
english = 'stairs'
level = 'n5'
tags = []
highest_frequency = 822
highest_frequency_source = 'Novels'

[[cards]]
kanji = '買い物'
kana = 'かいもの'
english = 'shopping; purchased goods'
level = 'n5'
tags = []
highest_frequency = 1945
highest_frequency_source = 'Anime'

[[cards]]
kanji = '鍵'
kana = 'かぎ'
english = 'key(s)'
level = 'n5'
tags = []
highest_frequency = 982
highest_frequency_source = 'Anime'

[[cards]]
kanji = '片仮名'
kana = 'かたかな'
english = 'katakana'
level = 'n5'
tags = []
highest_frequency = 9117
highest_frequency_source = 'Wikipedia'

[[cards]]
kanji = '角'
kana = 'かど'
english = 'corner (eg. of a desk); edge'
level = 'n5'
tags = []
highest_frequency = 160
highest_frequency_source = 'Wikipedia'

[[cards]]
kanji = '漢字'
kana = 'かんじ'
english = 'Chinese character(s)'
level = 'n5'
tags = []
highest_frequency = 2706
highest_frequency_source = 'Leeds'

[[cards]]
kanji = '北'
kana = 'きた'
english = 'north'
level = 'n5'
tags = []
highest_frequency = 150
highest_frequency_source = 'Wikipedia'

[[cards]]
kanji = '切手'
kana = 'きって'
english = 'stamp (postage)'
level = 'n5'
tags = []
highest_frequency = 6117
highest_frequency_source = 'Wikipedia'

[[cards]]
kanji = '切符'
kana = 'きっぷ'
english = 'ticket'
level = 'n5'
tags = []
highest_frequency = 6480
highest_frequency_source = 'Wikipedia'

[[cards]]
kanji = '銀行'
kana = 'ぎんこう'
english = 'bank'
level = 'n5'
tags = []
highest_frequency = 668
highest_frequency_source = 'Wikipedia'

[[cards]]
kanji = '下さい'
kana = 'ください'
english = 'please [give/do] for me'
level = 'n5'
tags = []

[[cards]]
kanji = '車'
kana = 'くるま'
english = 'car; vehicle'
level = 'n5'
tags = []
highest_frequency = 96
highest_frequency_source = 'Wikipedia'

[[cards]]
kanji = '結構'
kana = 'けっこう'
english = 'nice; sufficient; enough'
level = 'n5'
tags = []
highest_frequency = 417
highest_frequency_source = 'Anime'

[[cards]]
kanji = '結婚'
kana = 'けっこん'
english = 'marriage'
level = 'n5'
tags = []
highest_frequency = 537
highest_frequency_source = 'Wikipedia'

[[cards]]
kanji = '交差点'
kana = 'こうさてん'
english = 'intersection; crossing'
level = 'n5'
tags = []
highest_frequency = 7280
highest_frequency_source = 'Leeds'

[[cards]]
kanji = '交番'
kana = 'こうばん'
english = 'police box'
level = 'n5'
tags = []
highest_frequency = 17035
highest_frequency_source = 'Anime'

[[cards]]
kanji = '言葉'
kana = 'ことば'
english = 'word; language'
level = 'n5'
tags = ['common', 'noun']
highest_frequency = 147
highest_frequency_source = 'Novels'

[[cards]]
kanji = 'さあ'
kana = 'さあ'
english = 'come on...; well...; about that...'
level = 'n5'
tags = []
highest_frequency = 708
highest_frequency_source = 'Novels'

[[cards]]
kanji = '～さん'
kana = '～さん'
english = 'Mr.; Ms.; etc. (honorific/respectful/sonkeigo)'
level = 'n5'
tags = []

[[cards]]
kanji = '散歩'
kana = 'さんぽ'
english = 'walk; stroll'
level = 'n5'
tags = []
highest_frequency = 2780
highest_frequency_source = 'Anime'

[[cards]]
kanji = '雑誌'
kana = 'ざっし'
english = 'magazine; journal'
level = 'n5'
tags = []
highest_frequency = 766
highest_frequency_source = 'Wikipedia'

[[cards]]
kanji = '写真'
kana = 'しゃしん'
english = 'photograph'
level = 'n5'
tags = []
highest_frequency = 315
highest_frequency_source = 'Leeds'

[[cards]]
kanji = '新聞'
kana = 'しんぶん'
english = 'newspaper'
level = 'n5'
tags = []
highest_frequency = 669
highest_frequency_source = 'Wikipedia'

[[cards]]
kanji = '自転車'
kana = 'じてんしゃ'
english = 'bicycle'
level = 'n5'
tags = []
highest_frequency = 1964
highest_frequency_source = 'Wikipedia'

[[cards]]
kanji = '全部'
kana = 'ぜんぶ'
english = 'all; entire; whole'
level = 'n5'
tags = ['adverbial-noun', 'common', 'no-adjective', 'temporal-noun']
highest_frequency = 241
highest_frequency_source = 'Anime'

[[cards]]
kanji = 'そう'
kana = 'そう'
english = 'seems like; really; appears to be the case'
level = 'n5'
tags = []
highest_frequency = 18
highest_frequency_source = 'Anime'

[[cards]]
kanji = '大使館'
kana = 'たいしかん'
english = 'embassy'
level = 'n5'
tags = []
highest_frequency = 5552
highest_frequency_source = 'Leeds'

[[cards]]
kanji = '沢山'
kana = 'たくさん'
english = 'a lot; many; much'
level = 'n5'
tags = ['adverbial-noun', 'common', 'no-adjective', 'noun']
highest_frequency = 1067
highest_frequency_source = 'Novels'

[[cards]]
kanji = '縦'
kana = 'たて'
english = 'the vertical/height; front-to-back/length'
level = 'n5'
tags = ['common', 'noun']
highest_frequency = 3791
highest_frequency_source = 'Wikipedia'

[[cards]]
kanji = '建物'
kana = 'たてもの'
english = 'building'
level = 'n5'
tags = []
highest_frequency = 1045
highest_frequency_source = 'Novels'

[[cards]]
kanji = '楽しい'
kana = 'たのしい'
english = 'enjoyable; fun; pleasant'
level = 'n5'
tags = ['common', 'i-adective']
highest_frequency = 255
highest_frequency_source = 'Anime'

[[cards]]
kanji = '小さな'
kana = 'ちいさな'
english = 'small; little'
level = 'n5'
tags = ['common', 'pre-noun-adjectival']
highest_frequency = 366
highest_frequency_source = 'Novels'

[[cards]]
kanji = '次'
kana = 'つぎ'
english = 'next'
level = 'n5'
tags = ['common', 'no-adjective', 'noun']
highest_frequency = 164
highest_frequency_source = 'Anime'

[[cards]]
kanji = '出口'
kana = 'でぐち'
english = 'exit'
level = 'n5'
tags = []
highest_frequency = 3413
highest_frequency_source = 'Anime'

[[cards]]
kanji = '隣'
kana = 'となり'
english = 'next to; nextdoor to; neighbor'
level = 'n5'
tags = ['common', 'no-adjective', 'noun']
highest_frequency = 953
highest_frequency_source = 'Novels'

[[cards]]
kanji = 'どうぞ'
kana = 'どうぞ'
english = "please; here you are; you're welcome"
level = 'n5'
tags = []
highest_frequency = 1457
highest_frequency_source = 'Novels'

[[cards]]
kanji = 'どうも'
kana = 'どうも'
english = 'thanks; much (thanks, regret, etc.)'
level = 'n5'
tags = []
highest_frequency = 534
highest_frequency_source = 'Anime'

[[cards]]
kanji = '無い'
kana = 'ない'
english = "nonexistent; not being (there); doesn't have"
level = 'n5'
tags = []
highest_frequency = 57
highest_frequency_source = 'Wikipedia'

[[cards]]
kanji = '何'
kana = 'なに / なん'
english = 'what'
level = 'n5'
tags = []
highest_frequency = 14
highest_frequency_source = 'Anime'

[[cards]]
kanji = '名前'
kana = 'なまえ'
english = 'name'
level = 'n5'
tags = []
highest_frequency = 195
highest_frequency_source = 'Anime'

[[cards]]
kanji = '西'
kana = 'にし'
english = 'west'
level = 'n5'
tags = []
highest_frequency = 117
highest_frequency_source = 'Wikipedia'

[[cards]]
kanji = '荷物'
kana = 'にもつ'
english = 'luggage'
level = 'n5'
tags = []
highest_frequency = 1573
highest_frequency_source = 'Novels'

[[cards]]
kanji = 'はい'
kana = 'はい'
english = 'yes'
level = 'n5'
tags = []
highest_frequency = 342
highest_frequency_source = 'Novels'

[[cards]]
kanji = '葉書'
kana = 'はがき'
english = 'postcard'
level = 'n5'
tags = []
highest_frequency = 14959
highest_frequency_source = 'Leeds'

[[cards]]
kanji = '箱'
kana = 'はこ'
english = 'box; crate; chest'
level = 'n5'
tags = []
highest_frequency = 861
highest_frequency_source = 'Novels'

[[cards]]
kanji = '橋'
kana = 'はし'
english = 'bridge'
level = 'n5'
tags = []
highest_frequency = 353
highest_frequency_source = 'Wikipedia'

[[cards]]
kanji = '始め'
kana = 'はじめ'
english = 'beginning; start; origin'
level = 'n5'
tags = []
highest_frequency = 1543
highest_frequency_source = 'Novels'

[[cards]]
kanji = '話'
kana = 'はなし'
english = 'talk; story; speech'
level = 'n5'
tags = []
highest_frequency = 81
highest_frequency_source = 'Anime'

[[cards]]
kanji = '半'
kana = 'はん'
english = 'half; half-past'
level = 'n5'
tags = []
highest_frequency = 715
highest_frequency_source = 'Novels'

[[cards]]
kanji = '半分'
kana = 'はんぶん'
english = 'half'
level = 'n5'
tags = []
highest_frequency = 915
highest_frequency_source = 'Novels'

[[cards]]
kanji = '東'
kana = 'ひがし'
english = 'east'
level = 'n5'
tags = []
highest_frequency = 106
highest_frequency_source = 'Wikipedia'

[[cards]]
kanji = '左'
kana = 'ひだり'
english = 'left'
level = 'n5'
tags = []
highest_frequency = 631
highest_frequency_source = 'Wikipedia'

[[cards]]
kanji = '平仮名'
kana = 'ひらがな'
english = 'hiragana'
level = 'n5'
tags = []
highest_frequency = 20960
highest_frequency_source = 'Anime'

[[cards]]
kanji = '辺'
kana = 'へん'
english = 'area; vicinity; region'
level = 'n5'
tags = ['common', 'noun']
highest_frequency = 1097
highest_frequency_source = 'Anime'

[[cards]]
kanji = '他'
kana = 'ほか'
english = 'other (person, place, thing); the rest'
level = 'n5'
tags = ['common', 'no-adjective', 'noun']
highest_frequency = 110
highest_frequency_source = 'Wikipedia'

[[cards]]
kanji = '本当'
kana = 'ほんとう'
english = 'truth'
level = 'n5'
explain = 'http://selftaughtjapanese.com/2015/04/30/words-to-express-truth-in-japanese/'
tags = ['adverb', 'common', 'na-adjective', 'no-adjective', 'noun']
highest_frequency = 230
highest_frequency_source = 'Anime'

[[cards]]
kanji = '又'
kana = 'また'
english = 'again'
level = 'n5'
tags = ['adverb', 'common', 'conjunction', 'prefix']
highest_frequency = 40
highest_frequency_source = 'Wikipedia'

[[cards]]
kanji = '右'
kana = 'みぎ'
english = 'right'
level = 'n5'
tags = []
highest_frequency = 534
highest_frequency_source = 'Novels'

[[cards]]
kanji = '店'
kana = 'みせ'
english = 'store; shop'
level = 'n5'
tags = []
highest_frequency = 305
highest_frequency_source = 'Leeds'

[[cards]]
kanji = '道'
kana = 'みち'
english = 'road, street, path (all inclusive)'
level = 'n5'
explain = 'https://hinative.com/en-US/questions/240900'
tags = ['common', 'noun', 'transportation']
highest_frequency = 159
highest_frequency_source = 'Wikipedia'

[[cards]]
kanji = '南'
kana = 'みなみ'
english = 'south'
level = 'n5'
tags = []
highest_frequency = 147
highest_frequency_source = 'Wikipedia'

[[cards]]
kanji = 'もしもし'
kana = 'もしもし'
english = 'hello (said on phone)'
level = 'n5'
tags = []

[[cards]]
kanji = '物'
kana = 'もの'
english = 'thing'
level = 'n5'
tags = []
highest_frequency = 213
highest_frequency_source = 'Wikipedia'

[[cards]]
kanji = '門'
kana = 'もん'
english = 'gate'
level = 'n5'
tags = []
highest_frequency = 516
highest_frequency_source = 'Wikipedia'

[[cards]]
kanji = '～屋'
kana = '～や'
english = 'shop for ～; seller of ～'
level = 'n5'
tags = []

[[cards]]
kanji = '郵便局'
kana = 'ゆうびんきょく'
english = 'post office'
level = 'n5'
tags = []

[[cards]]
kanji = '良い'
kana = 'よい'
english = 'good; OK'
level = 'n5'
tags = ['common', 'i-adjectives']
highest_frequency = 192
highest_frequency_source = 'Wikipedia'

[[cards]]
kanji = '横'
kana = 'よこ'
english = 'horizontal; lying down; side; width'
level = 'n5'
tags = []
highest_frequency = 435
highest_frequency_source = 'Novels'

[[cards]]
kanji = '旅行'
kana = 'りょこう'
english = 'travel; trip; journey'
level = 'n5'
tags = []
highest_frequency = 747
highest_frequency_source = 'Leeds'

[[cards]]
kanji = '廊下'
kana = 'ろうか'
english = 'hallway; corridor'
level = 'n5'
tags = []
highest_frequency = 786
highest_frequency_source = 'Novels'

[[cards]]
kanji = 'エレベーター'
kana = 'エレベーター'
english = 'elevator'
level = 'n5'
tags = []
highest_frequency = 5003
highest_frequency_source = 'Wikipedia'

[[cards]]
kanji = 'カメラ'
kana = 'カメラ'
english = 'camera'
level = 'n5'
tags = []
highest_frequency = 1503
highest_frequency_source = 'Leeds'

[[cards]]
kanji = 'キロ'
kana = 'キロ'
english = 'kilogram ; kilometer'
level = 'n5'
tags = []
highest_frequency = 1463
highest_frequency_source = 'Novels'

[[cards]]
kanji = 'ギター'
kana = 'ギター'
english = 'guitar'
level = 'n5'
tags = []
highest_frequency = 1976
highest_frequency_source = 'Wikipedia'

[[cards]]
kanji = 'グラム'
kana = 'グラム'
english = 'gram'
level = 'n5'
tags = []
highest_frequency = 6447
highest_frequency_source = 'Anime'

[[cards]]
kanji = 'スポーツ'
kana = 'スポーツ'
english = 'sports'
level = 'n5'
tags = []
highest_frequency = 632
highest_frequency_source = 'Wikipedia'

[[cards]]
kanji = 'タクシー'
kana = 'タクシー'
english = 'taxi'
level = 'n5'
tags = []
highest_frequency = 2775
highest_frequency_source = 'Leeds'

[[cards]]
kanji = 'デパート'
kana = 'デパート'
english = 'department store'
level = 'n5'
tags = []
highest_frequency = 6238
highest_frequency_source = 'Leeds'

[[cards]]
kanji = 'ニュース'
kana = 'ニュース'
english = 'news'
level = 'n5'
tags = []
highest_frequency = 542
highest_frequency_source = 'Leeds'

[[cards]]
kanji = 'バス'
kana = 'バス'
english = 'bus'
level = 'n5'
tags = []
highest_frequency = 236
highest_frequency_source = 'Wikipedia'

[[cards]]
kanji = 'パーティー'
kana = 'パーティー'
english = 'party'
level = 'n5'
tags = []
highest_frequency = 1393
highest_frequency_source = 'Anime'

[[cards]]
kanji = 'フィルム'
kana = 'フィルム'
english = 'film'
level = 'n5'
tags = []
highest_frequency = 2221
highest_frequency_source = 'Wikipedia'

[[cards]]
kanji = 'ページ'
kana = 'ページ'
english = 'page'
level = 'n5'
tags = []
highest_frequency = 364
highest_frequency_source = 'Leeds'

[[cards]]
kanji = 'ホテル'
kana = 'ホテル'
english = 'hotel'
level = 'n5'
tags = []
highest_frequency = 946
highest_frequency_source = 'Leeds'

[[cards]]
kanji = 'ポスト'
kana = 'ポスト'
english = 'post'
level = 'n5'
tags = []
highest_frequency = 3416
highest_frequency_source = 'Wikipedia'

[[cards]]
kanji = 'マッチ'
kana = 'マッチ'
english = 'match'
level = 'n5'
tags = []
highest_frequency = 3794
highest_frequency_source = 'Wikipedia'

[[cards]]
kanji = 'ラジオ'
kana = 'ラジオ'
english = 'radio'
level = 'n5'
tags = []
highest_frequency = 457
highest_frequency_source = 'Wikipedia'

[[cards]]
kanji = 'レコード'
kana = 'レコード'
english = 'record'
level = 'n5'
tags = []
highest_frequency = 1051
highest_frequency_source = 'Wikipedia'

