[[cards]]
kanji = 'ああ'
kana = 'ああ'
english = 'Ah!; Oh!; yes.'
level = 'n5'
tags = ['common', 'expression']

[[cards]]
kanji = '青'
kana = 'あお'
english = 'blue'
level = 'n5'
tags = ['color', 'common', 'no-adjective', 'noun']

[[cards]]
kanji = '赤'
kana = 'あか'
english = 'red'
level = 'n5'
make_kanji_card = true
hide_hiragana_card = true
tags = ['color', 'common', 'no-adjective', 'noun']

[[cards]]
kanji = 'あのう'
kana = 'あのう'
english = 'um...; well...'
level = 'n5'
tags = ['common', 'expressions']

[[cards]]
kanji = 'いい'
kana = 'いい'
english = 'good; OK'
level = 'n5'
tags = ['common', 'expressions']

[[cards]]
kanji = '否'
kana = 'いいえ'
english = "no; not at all; don't mention it"
level = 'n5'
tags = ['basic', 'common']

[[cards]]
kanji = '一緒'
kana = 'いっしょ'
english = 'together'
level = 'n5'
tags = ['adverbial-noun', 'no-adjective', 'temporal-noun']

[[cards]]
kanji = '意味'
kana = 'いみ'
english = 'meaning'
level = 'n5'
tags = []

[[cards]]
kanji = '嫌'
kana = 'いや'
english = 'disagreeable; unpleasant; no'
level = 'n5'
tags = []

[[cards]]
kanji = '入口'
kana = 'いりぐち'
english = 'entrance; gate'
make_kanji_card = true
hide_hiragana_card = true
level = 'n5'
tags = []

[[cards]]
kanji = '色'
kana = 'いろ'
english = 'color'
make_kanji_card = true
hide_hiragana_card = true
level = 'n5'
tags = []

[[cards]]
kanji = '上'
kana = 'うえ'
english = 'above; up; on top of'
make_kanji_card = true
hide_hiragana_card = true
level = 'n5'
tags = []

[[cards]]
kanji = '後ろ'
kana = 'うしろ'
english = 'behind'
level = 'n5'
tags = []

[[cards]]
kanji = '歌'
kana = 'うた'
english = 'song'
level = 'n5'
tags = []

[[cards]]
kanji = '絵'
kana = 'え'
english = 'picture; drawing; painting'
level = 'n5'
tags = []

[[cards]]
kanji = '映画'
kana = 'えいが'
english = 'movie'
level = 'n5'
tags = []

[[cards]]
kanji = '英語'
kana = 'えいご'
english = 'English language'
make_kanji_card = true
hide_hiragana_card = true
level = 'n5'
tags = []

[[cards]]
kanji = 'ええ'
kana = 'ええ'
english = 'yes; um...'
level = 'n5'
tags = []

[[cards]]
kanji = '駅'
kana = 'えき'
english = 'train station'
make_kanji_card = true
level = 'n5'
tags = []

[[cards]]
kanji = '～円'
kana = '～えん'
english = 'yen'
level = 'n5'
tags = []

[[cards]]
kanji = 'お金'
kana = 'おかね'
english = 'money'
make_kanji_card = true
hide_hiragana_card = true
level = 'n5'
tags = []

[[cards]]
kanji = 'お酒'
kana = 'おさけ'
english = 'alcohol; sake (rice wine)'
level = 'n5'
tags = []

[[cards]]
kanji = '同じ'
kana = 'おなじ'
english = 'same; identical'
make_kanji_card = true
hide_hiragana_card = true
level = 'n5'
tags = ['common', 'noun']

[[cards]]
kanji = '音楽'
kana = 'おんがく'
english = 'music'
level = 'n5'
tags = []

[[cards]]
kanji = '会社'
kana = 'かいしゃ'
english = 'company; corporation'
make_kanji_card = true
hide_hiragana_card = true
level = 'n5'
tags = []

[[cards]]
kanji = '階段'
kana = 'かいだん'
english = 'stairs'
level = 'n5'
tags = []

[[cards]]
kanji = '買い物'
kana = 'かいもの'
english = 'shopping; purchased goods'
make_kanji_card = true
hide_hiragana_card = true
level = 'n5'
tags = []

[[cards]]
kanji = '鍵'
kana = 'かぎ'
english = 'key(s)'
level = 'n5'
tags = []

[[cards]]
kanji = '片仮名'
kana = 'かたかな'
english = 'katakana'
level = 'n5'
tags = []

[[cards]]
kanji = '角'
kana = 'かど'
english = 'corner (eg. of a desk); edge'
level = 'n5'
tags = []

[[cards]]
kanji = '漢字'
kana = 'かんじ'
english = 'Chinese character(s)'
level = 'n5'
tags = []

[[cards]]
kanji = '外国'
kana = 'がいこく'
english = 'foreign country'
make_kanji_card = true
hide_hiragana_card = true
level = 'n5'
tags = []

[[cards]]
kanji = '黄色'
kana = 'きいろ'
english = 'yellow'
level = 'n5'
tags = []

[[cards]]
kanji = '北'
kana = 'きた'
english = 'north'
level = 'n5'
make_kanji_card = true
hide_hiragana_card = true
tags = []

[[cards]]
kanji = '切手'
kana = 'きって'
english = 'stamp (postage)'
level = 'n5'
tags = []

[[cards]]
kanji = '切符'
kana = 'きっぷ'
english = 'ticket'
level = 'n5'
tags = []

[[cards]]
kanji = '銀行'
kana = 'ぎんこう'
english = 'bank'
level = 'n5'
tags = []

[[cards]]
kanji = '下さい'
kana = 'ください'
english = 'please [give/do] for me'
level = 'n5'
tags = []

[[cards]]
kanji = '国'
kana = 'くに'
english = 'country'
level = 'n5'
tags = []

[[cards]]
kanji = '車'
kana = 'くるま'
english = 'car; vehicle'
level = 'n5'
tags = []

[[cards]]
kanji = '黒'
kana = 'くろ'
english = 'black'
level = 'n5'
tags = []

[[cards]]
kanji = '結構'
kana = 'けっこう'
english = 'nice; sufficient; enough'
level = 'n5'
tags = []

[[cards]]
kanji = '結婚'
kana = 'けっこん'
english = 'marriage'
level = 'n5'
tags = []

[[cards]]
kanji = '交差点'
kana = 'こうさてん'
english = 'intersection; crossing'
level = 'n5'
tags = []

[[cards]]
kanji = '交番'
kana = 'こうばん'
english = 'police box'
level = 'n5'
tags = []

[[cards]]
kanji = '言葉'
kana = 'ことば'
english = 'word; language'
level = 'n5'
tags = []

[[cards]]
kanji = '子供'
kana = 'こども'
english = 'child'
level = 'n5'
tags = []

[[cards]]
kanji = '～語'
kana = '～ご'
english = 'language (suffix); counter for words'
level = 'n5'
tags = []

[[cards]]
kanji = 'さあ'
kana = 'さあ'
english = 'come on...; well...; about that...'
level = 'n5'
tags = []

[[cards]]
kanji = '～さん'
kana = '～さん'
english = 'Mr.; Ms.; etc. (honorific/respectful/sonkeigo)'
level = 'n5'
tags = []

[[cards]]
kanji = '散歩'
kana = 'さんぽ'
english = 'walk; stroll'
level = 'n5'
tags = []

[[cards]]
kanji = '雑誌'
kana = 'ざっし'
english = 'magazine; journal'
level = 'n5'
tags = []

[[cards]]
kanji = '然し'
kana = 'しかし'
english = 'however'
level = 'n5'
tags = []

[[cards]]
kanji = '下'
kana = 'した'
english = 'below; under; bottom'
level = 'n5'
tags = []

[[cards]]
kanji = '写真'
kana = 'しゃしん'
english = 'photograph'
level = 'n5'
tags = []

[[cards]]
kanji = '白'
kana = 'しろ'
english = 'white'
level = 'n5'
tags = []

[[cards]]
kanji = '新聞'
kana = 'しんぶん'
english = 'newspaper'
level = 'n5'
tags = []

[[cards]]
kanji = '自転車'
kana = 'じてんしゃ'
english = 'bicycle'
level = 'n5'
tags = []

[[cards]]
kanji = 'じゃあ'
kana = 'じゃあ'
english = 'well then...'
level = 'n5'
tags = []

[[cards]]
kanji = '全部'
kana = 'ぜんぶ'
english = 'all; entire; whole'
level = 'n5'
tags = ['adverbial-noun', 'common', 'no-adjective', 'temporal-noun']

[[cards]]
kanji = 'そう'
kana = 'そう'
english = 'seems like; really; appears to be the case'
level = 'n5'
tags = []

[[cards]]
kanji = '然うして'
kana = 'そうして'
english = 'after that; therefore (conjunction)'
level = 'n5'
tags = []

[[cards]]
kanji = '外'
kana = 'そと'
english = 'outside; exterior'
level = 'n5'
tags = ['common', 'noun']

[[cards]]
kanji = '側'
kana = 'そば'
english = 'near; close; vicinity'
level = 'n5'
tags = ['common', 'noun']

[[cards]]
kanji = '其れから'
kana = 'それから'
english = 'and then; after that'
level = 'n5'
tags = []

[[cards]]
kanji = '其れでは'
kana = 'それでは'
english = 'in that case; well then...'
level = 'n5'
tags = []

[[cards]]
kanji = '大使館'
kana = 'たいしかん'
english = 'embassy'
level = 'n5'
tags = []

[[cards]]
kanji = '沢山'
kana = 'たくさん'
english = 'a lot; many; much'
level = 'n5'
tags = ['adverbial-noun', 'common', 'no-adjective', 'noun']

[[cards]]
kanji = '～達'
kana = '～たち'
english = 'pluralizing suffix'
level = 'n5'
tags = []

[[cards]]
kanji = '縦'
kana = 'たて'
english = 'the vertical/height; front-to-back/length'
level = 'n5'
tags = ['common', 'noun']

[[cards]]
kanji = '建物'
kana = 'たてもの'
english = 'building'
level = 'n5'
tags = []

[[cards]]
kanji = '楽しい'
kana = 'たのしい'
english = 'enjoyable; fun; pleasant'
level = 'n5'
tags = ['common', 'i-adective']

[[cards]]
kanji = '小さな'
kana = 'ちいさな'
english = 'small; little'
level = 'n5'
tags = ['common', 'pre-noun-adjectival']

[[cards]]
kanji = '近く'
kana = 'ちかく'
english = 'near; vicinity'
level = 'n5'
tags = ['adverbial-noun', 'common', 'no-adjective']

[[cards]]
kanji = '茶色'
kana = 'ちゃいろ'
english = 'brown'
level = 'n5'
make_kanji_card = true
tags = []

[[cards]]
kanji = '次'
kana = 'つぎ'
english = 'next'
level = 'n5'
tags = ['common', 'no-adjective', 'noun']

[[cards]]
kanji = '出口'
kana = 'でぐち'
english = 'exit'
level = 'n5'
make_kanji_card = true
tags = []

[[cards]]
kanji = 'でも'
kana = 'でも'
english = 'but'
level = 'n5'
tags = []

[[cards]]
kanji = '所'
kana = 'ところ'
english = 'place; area'
level = 'n5'
tags = []

[[cards]]
kanji = '隣'
kana = 'となり'
english = 'next to; nextdoor to; neighbor'
level = 'n5'
tags = ['common', 'no-adjective', 'noun']

[[cards]]
kanji = 'どうぞ'
kana = 'どうぞ'
english = "please; here you are; you're welcome"
level = 'n5'
tags = []

[[cards]]
kanji = 'どうも'
kana = 'どうも'
english = 'thanks; much (thanks, regret, etc.)'
level = 'n5'
tags = []

[[cards]]
kanji = '無い'
kana = 'ない'
english = "nonexistent; not being (there); doesn't have"
level = 'n5'
tags = []

[[cards]]
kanji = '中'
kana = 'なか'
english = 'inside; middle; center; among'
level = 'n5'
make_kanji_card = true
hide_hiragana_card = true
tags = []

[[cards]]
kanji = '何'
kana = 'なに / なん'
english = 'what'
level = 'n5'
tags = []

[[cards]]
kanji = '名前'
kana = 'なまえ'
english = 'name'
level = 'n5'
make_kanji_card = true
hide_hiragana_card = true
tags = []

[[cards]]
kanji = '西'
kana = 'にし'
english = 'west'
level = 'n5'
tags = []

[[cards]]
kanji = '荷物'
kana = 'にもつ'
english = 'luggage'
level = 'n5'
tags = []

[[cards]]
kanji = 'はい'
kana = 'はい'
english = 'yes'
level = 'n5'
tags = []

[[cards]]
kanji = '葉書'
kana = 'はがき'
english = 'postcard'
level = 'n5'
tags = []

[[cards]]
kanji = '箱'
kana = 'はこ'
english = 'box; crate; chest'
level = 'n5'
tags = []

[[cards]]
kanji = '橋'
kana = 'はし'
english = 'bridge'
level = 'n5'
tags = []

[[cards]]
kanji = '始め'
kana = 'はじめ'
english = 'beginning; start; origin'
level = 'n5'
tags = []

[[cards]]
kanji = '話'
kana = 'はなし'
english = 'talk; story; speech'
level = 'n5'
tags = []

[[cards]]
kanji = '半'
kana = 'はん'
english = 'half; half-past'
level = 'n5'
tags = []

[[cards]]
kanji = '半分'
kana = 'はんぶん'
english = 'half'
level = 'n5'
tags = []

[[cards]]
kanji = '～番'
kana = '～ばん'
english = 'number in a series; ～st/th best'
level = 'n5'
tags = []

[[cards]]
kanji = '番号'
kana = 'ばんごう'
english = 'number'
level = 'n5'
tags = []

[[cards]]
kanji = '東'
kana = 'ひがし'
english = 'east'
level = 'n5'
tags = []

[[cards]]
kanji = '左'
kana = 'ひだり'
english = 'left'
level = 'n5'
tags = []

[[cards]]
kanji = '平仮名'
kana = 'ひらがな'
english = 'hiragana'
level = 'n5'
tags = []

[[cards]]
kanji = '辺'
kana = 'へん'
english = 'area; vicinity; region'
level = 'n5'
tags = ['common', 'noun']

[[cards]]
kanji = '方'
kana = 'ほう'
english = 'way; direction; method; side'
level = 'n5'
tags = ['common', 'noun']

[[cards]]
kanji = '他'
kana = 'ほか'
english = 'other (person, place, thing); the rest'
level = 'n5'
tags = ['common', 'no-adjective', 'noun']

[[cards]]
kanji = '本当'
kana = 'ほんとう'
english = 'truth; reality'
level = 'n5'
tags = ['adverb', 'common', 'na-adjective', 'no-adjective', 'noun']

[[cards]]
kanji = '前'
kana = 'まえ'
english = 'before; in front of'
level = 'n5'
tags = ['adverbial-noun', 'common', 'suffix', 'temporal-noun']

[[cards]]
kanji = '～前'
kana = '～まえ'
english = 'in front of ～'
level = 'n5'
tags = []

[[cards]]
kanji = '又'
kana = 'また'
english = 'again'
level = 'n5'
tags = ['adverb', 'common', 'conjunction', 'prefix']

[[cards]]
kanji = '町'
kana = 'まち'
english = 'town; city'
level = 'n5'
tags = []

[[cards]]
kanji = '右'
kana = 'みぎ'
english = 'right'
level = 'n5'
tags = []

[[cards]]
kanji = '店'
kana = 'みせ'
english = 'store; shop'
level = 'n5'
tags = []

[[cards]]
kanji = '道'
kana = 'みち'
english = 'road; street'
level = 'n5'
tags = []

[[cards]]
kanji = '緑'
kana = 'みどり'
english = 'green'
level = 'n5'
tags = ['common', 'no-adjective', 'noun']

[[cards]]
kanji = '南'
kana = 'みなみ'
english = 'south'
level = 'n5'
tags = []

[[cards]]
kanji = '向こう'
kana = 'むこう'
english = 'opposite side; far away; beyond; over there'
level = 'n5'
tags = ['common', 'noun']

[[cards]]
kanji = 'もしもし'
kana = 'もしもし'
english = 'hello (said on phone)'
level = 'n5'
tags = []

[[cards]]
kanji = '物'
kana = 'もの'
english = 'thing'
level = 'n5'
tags = []

[[cards]]
kanji = '門'
kana = 'もん'
english = 'gate'
level = 'n5'
tags = []

[[cards]]
kanji = '～屋'
kana = '～や'
english = 'shop for ～; seller of ～'
level = 'n5'
tags = []

[[cards]]
kanji = '郵便局'
kana = 'ゆうびんきょく'
english = 'post office'
level = 'n5'
tags = []

[[cards]]
kanji = '良い'
kana = 'よい'
english = 'good; OK'
level = 'n5'
tags = ['common', 'expressions']

[[cards]]
kanji = '横'
kana = 'よこ'
english = 'horizontal; lying down; side; width'
level = 'n5'
tags = []

[[cards]]
kanji = '旅行'
kana = 'りょこう'
english = 'travel; trip; journey'
level = 'n5'
tags = []

[[cards]]
kanji = '廊下'
kana = 'ろうか'
english = 'hallway; corridor'
level = 'n5'
tags = []

[[cards]]
kanji = 'エレベーター'
kana = 'エレベーター'
english = 'elevator'
level = 'n5'
tags = []

[[cards]]
kanji = 'カメラ'
kana = 'カメラ'
english = 'camera'
level = 'n5'
tags = []

[[cards]]
kanji = 'キロ'
kana = 'キロ'
english = 'kilogram ; kilometer'
level = 'n5'
tags = []

[[cards]]
kanji = 'ギター'
kana = 'ギター'
english = 'guitar'
level = 'n5'
tags = []

[[cards]]
kanji = 'グラム'
kana = 'グラム'
english = 'gram'
level = 'n5'
tags = []

[[cards]]
kanji = 'スポーツ'
kana = 'スポーツ'
english = 'sports'
level = 'n5'
tags = []

[[cards]]
kanji = 'タクシー'
kana = 'タクシー'
english = 'taxi'
level = 'n5'
tags = []

[[cards]]
kanji = 'デパート'
kana = 'デパート'
english = 'department store'
level = 'n5'
tags = []

[[cards]]
kanji = 'ニュース'
kana = 'ニュース'
english = 'news'
level = 'n5'
tags = []

[[cards]]
kanji = 'バス'
kana = 'バス'
english = 'bus'
level = 'n5'
tags = []

[[cards]]
kanji = 'パーティー'
kana = 'パーティー'
english = 'party'
level = 'n5'
tags = []

[[cards]]
kanji = 'フィルム'
kana = 'フィルム'
english = 'film'
level = 'n5'
tags = []

[[cards]]
kanji = 'ページ'
kana = 'ページ'
english = 'page'
level = 'n5'
tags = []

[[cards]]
kanji = 'ホテル'
kana = 'ホテル'
english = 'hotel'
level = 'n5'
tags = []

[[cards]]
kanji = 'ポスト'
kana = 'ポスト'
english = 'post'
level = 'n5'
tags = []

[[cards]]
kanji = 'マッチ'
kana = 'マッチ'
english = 'match'
level = 'n5'
tags = []

[[cards]]
kanji = 'ラジオ'
kana = 'ラジオ'
english = 'radio'
level = 'n5'
tags = []

[[cards]]
kanji = 'レコード'
kana = 'レコード'
english = 'record'
level = 'n5'
tags = []

