[[cards]]
kanji = 'いい'
kana = 'いい'
english = 'good; OK'
level = 'n5'
tags = ['common', 'i-adjectives']
frequency_scores = { anime = 19, leeds = 142, novels = 73 }

[[cards]]
kanji = '否'
kana = 'いいえ'
english = "no; not at all; don't mention it"
level = 'n5'
tags = ['basic', 'common']
frequency_scores = { leeds = 4372, novels = 1611, wikipedia = 6152 }

[[cards]]
kanji = '一緒'
kana = 'いっしょ'
english = 'together'
level = 'n5'
tags = ['adverbial-noun', 'no-adjective', 'temporal-noun']
frequency_scores = { anime = 103, leeds = 556, novels = 374, wikipedia = 2428 }

[[cards]]
kanji = '意味'
kana = 'いみ'
english = 'meaning'
level = 'n5'
tags = []
frequency_scores = { anime = 222, leeds = 237, novels = 313, wikipedia = 309 }

[[cards]]
kanji = '嫌'
kana = 'いや'
english = 'disagreeable; unpleasant; no'
level = 'n5'
tags = []
frequency_scores = { anime = 283, leeds = 2101, novels = 985, wikipedia = 9417 }

[[cards]]
kanji = '入口'
kana = 'いりぐち'
english = 'entrance; gate'
level = 'n5'
tags = []
frequency_scores = { anime = 11021, leeds = 7113, novels = 1874 }

[[cards]]
kanji = '歌'
kana = 'うた'
english = 'song'
level = 'n5'
tags = []
frequency_scores = { anime = 761, leeds = 1297, novels = 1598, wikipedia = 458 }

[[cards]]
kanji = '絵'
kana = 'え'
english = 'picture; drawing; painting'
level = 'n5'
tags = []
frequency_scores = { anime = 659, leeds = 1131, novels = 1024, wikipedia = 1454 }

[[cards]]
kanji = '映画'
kana = 'えいが'
english = 'movie'
level = 'n5'
tags = ['common', 'entertainment', 'no-adjective', 'noun']
frequency_scores = { anime = 1476, leeds = 292, novels = 2064, wikipedia = 99 }

[[cards]]
kanji = '英語'
kana = 'えいご'
english = 'English language'
level = 'n5'
tags = []
frequency_scores = { anime = 2543, leeds = 441, wikipedia = 449 }

[[cards]]
kanji = 'ええ'
kana = 'ええ'
english = 'yes; um...'
level = 'n5'
tags = []
frequency_scores = { leeds = 3075, novels = 485 }

[[cards]]
kanji = '駅'
kana = 'えき'
english = 'train station'
level = 'n5'
tags = []
frequency_scores = { anime = 2183, leeds = 807, novels = 1730, wikipedia = 45 }

[[cards]]
kanji = '～円'
kana = '～えん'
english = 'yen'
level = 'n5'
tags = []

[[cards]]
kanji = 'お金'
kana = 'おかね'
english = 'money'
level = 'n5'
tags = []
frequency_scores = { anime = 967, leeds = 763, novels = 2222 }

[[cards]]
kanji = 'お酒'
kana = 'おさけ'
english = 'alcohol; sake (rice wine)'
level = 'n5'
tags = []

[[cards]]
kanji = '同じ'
kana = 'おなじ'
english = 'same; identical'
level = 'n5'
tags = ['common', 'noun']
frequency_scores = { leeds = 221, novels = 179, wikipedia = 132 }

[[cards]]
kanji = '音楽'
kana = 'おんがく'
english = 'music'
level = 'n5'
tags = []
frequency_scores = { anime = 1169, leeds = 420, novels = 2580, wikipedia = 167 }

[[cards]]
kanji = '会社'
kana = 'かいしゃ'
english = 'company; corporation'
level = 'n5'
tags = []
frequency_scores = { anime = 1435, leeds = 241, novels = 1532, wikipedia = 113 }

[[cards]]
kanji = '階段'
kana = 'かいだん'
english = 'stairs'
level = 'n5'
tags = []
frequency_scores = { anime = 2627, leeds = 3512, novels = 822, wikipedia = 4659 }

[[cards]]
kanji = '買い物'
kana = 'かいもの'
english = 'shopping; purchased goods'
level = 'n5'
tags = []
frequency_scores = { anime = 1945, leeds = 2173, wikipedia = 9623 }

[[cards]]
kanji = '鍵'
kana = 'かぎ'
english = 'key(s)'
level = 'n5'
tags = []
frequency_scores = { anime = 982, leeds = 3329, novels = 1529, wikipedia = 4187 }

[[cards]]
kanji = '片仮名'
kana = 'かたかな'
english = 'katakana'
level = 'n5'
tags = []
frequency_scores = { anime = 22573, wikipedia = 9117 }

[[cards]]
kanji = '角'
kana = 'かど'
english = 'corner (eg. of a desk); edge'
level = 'n5'
tags = []
frequency_scores = { anime = 3052, leeds = 3373, novels = 1290, wikipedia = 160 }

[[cards]]
kanji = '漢字'
kana = 'かんじ'
english = 'Chinese character(s)'
level = 'n5'
tags = []
frequency_scores = { anime = 9151, leeds = 2706, wikipedia = 2780 }

[[cards]]
kanji = '北'
kana = 'きた'
english = 'north'
level = 'n5'
tags = []
frequency_scores = { anime = 1367, leeds = 1524, novels = 1641, wikipedia = 150 }

[[cards]]
kanji = '切手'
kana = 'きって'
english = 'stamp (postage)'
level = 'n5'
tags = []
frequency_scores = { anime = 23426, leeds = 7724, wikipedia = 6117 }

[[cards]]
kanji = '切符'
kana = 'きっぷ'
english = 'ticket'
level = 'n5'
tags = []
frequency_scores = { anime = 10595, leeds = 7604, wikipedia = 6480 }

[[cards]]
kanji = '銀行'
kana = 'ぎんこう'
english = 'bank'
level = 'n5'
tags = []
frequency_scores = { anime = 7938, leeds = 997, wikipedia = 668 }

[[cards]]
kanji = '下さい'
kana = 'ください'
english = 'please [give/do] for me'
level = 'n5'
tags = []

[[cards]]
kanji = '車'
kana = 'くるま'
english = 'car; vehicle'
level = 'n5'
tags = []
frequency_scores = { anime = 726, leeds = 468, novels = 417, wikipedia = 96 }

[[cards]]
kanji = '結構'
kana = 'けっこう'
english = 'nice; sufficient; enough'
level = 'n5'
tags = []
frequency_scores = { anime = 417, leeds = 800, novels = 1502 }

[[cards]]
kanji = '結婚'
kana = 'けっこん'
english = 'marriage'
level = 'n5'
tags = []
frequency_scores = { anime = 1131, leeds = 913, novels = 1204, wikipedia = 537 }

[[cards]]
kanji = '交差点'
kana = 'こうさてん'
english = 'intersection; crossing'
level = 'n5'
tags = []
frequency_scores = { anime = 10532, leeds = 7280 }

[[cards]]
kanji = '交番'
kana = 'こうばん'
english = 'police box'
level = 'n5'
tags = []
frequency_scores = { anime = 17035 }

[[cards]]
kanji = '言葉'
kana = 'ことば'
english = 'word; language'
level = 'n5'
tags = ['common', 'noun']
frequency_scores = { anime = 271, leeds = 271, novels = 147, wikipedia = 823 }

[[cards]]
kanji = 'さあ'
kana = 'さあ'
english = 'come on...; well...; about that...'
level = 'n5'
tags = []
frequency_scores = { leeds = 3789, novels = 708 }

[[cards]]
kanji = '～さん'
kana = '～さん'
english = 'Mr.; Ms.; etc. (honorific/respectful/sonkeigo)'
level = 'n5'
tags = []

[[cards]]
kanji = '散歩'
kana = 'さんぽ'
english = 'walk; stroll'
level = 'n5'
tags = []
frequency_scores = { anime = 2780, leeds = 2924, wikipedia = 9921 }

[[cards]]
kanji = '雑誌'
kana = 'ざっし'
english = 'magazine; journal'
level = 'n5'
tags = []
frequency_scores = { anime = 4044, leeds = 1227, novels = 2978, wikipedia = 766 }

[[cards]]
kanji = '写真'
kana = 'しゃしん'
english = 'photograph'
level = 'n5'
tags = []
frequency_scores = { anime = 696, leeds = 315, novels = 815, wikipedia = 774 }

[[cards]]
kanji = '新聞'
kana = 'しんぶん'
english = 'newspaper'
level = 'n5'
tags = []
frequency_scores = { anime = 3268, leeds = 681, novels = 1298, wikipedia = 669 }

[[cards]]
kanji = '自転車'
kana = 'じてんしゃ'
english = 'bicycle'
level = 'n5'
tags = []
frequency_scores = { anime = 4164, leeds = 2072, novels = 2916, wikipedia = 1964 }

[[cards]]
kanji = '全部'
kana = 'ぜんぶ'
english = 'all; entire; whole'
level = 'n5'
tags = ['adverbial-noun', 'common', 'no-adjective', 'temporal-noun']
frequency_scores = { anime = 241, leeds = 950, novels = 1013, wikipedia = 4636 }

[[cards]]
kanji = 'そう'
kana = 'そう'
english = 'seems like; really; appears to be the case'
level = 'n5'
tags = []
frequency_scores = { anime = 18, leeds = 102, novels = 32, wikipedia = 2445 }

[[cards]]
kanji = '大使館'
kana = 'たいしかん'
english = 'embassy'
level = 'n5'
tags = []
frequency_scores = { anime = 11901, leeds = 5552 }

[[cards]]
kanji = '沢山'
kana = 'たくさん'
english = 'a lot; many; much'
level = 'n5'
tags = ['adverbial-noun', 'common', 'no-adjective', 'noun']
frequency_scores = { anime = 5710, leeds = 2313, novels = 1067, wikipedia = 6304 }

[[cards]]
kanji = '縦'
kana = 'たて'
english = 'the vertical/height; front-to-back/length'
level = 'n5'
tags = ['common', 'noun']
frequency_scores = { anime = 6983, leeds = 4613, wikipedia = 3791 }

[[cards]]
kanji = '建物'
kana = 'たてもの'
english = 'building'
level = 'n5'
tags = []
frequency_scores = { anime = 2944, leeds = 1363, novels = 1045, wikipedia = 1145 }

[[cards]]
kanji = '楽しい'
kana = 'たのしい'
english = 'enjoyable; fun; pleasant'
level = 'n5'
tags = ['common', 'i-adective']
frequency_scores = { anime = 255, leeds = 560, novels = 1008, wikipedia = 7224 }

[[cards]]
kanji = '小さな'
kana = 'ちいさな'
english = 'small; little'
level = 'n5'
tags = ['common', 'pre-noun-adjectival']
frequency_scores = { leeds = 1012, novels = 366, wikipedia = 1484 }

[[cards]]
kanji = '次'
kana = 'つぎ'
english = 'next'
level = 'n5'
tags = ['common', 'no-adjective', 'noun']
frequency_scores = { anime = 164, leeds = 269, novels = 370, wikipedia = 370 }

[[cards]]
kanji = '出口'
kana = 'でぐち'
english = 'exit'
level = 'n5'
tags = []
frequency_scores = { anime = 3413, leeds = 5934, wikipedia = 4909 }

[[cards]]
kanji = '隣'
kana = 'となり'
english = 'next to; nextdoor to; neighbor'
level = 'n5'
tags = ['common', 'no-adjective', 'noun']
frequency_scores = { anime = 978, leeds = 2005, novels = 953 }

[[cards]]
kanji = 'どうぞ'
kana = 'どうぞ'
english = "please; here you are; you're welcome"
level = 'n5'
tags = []
frequency_scores = { leeds = 1720, novels = 1457 }

[[cards]]
kanji = 'どうも'
kana = 'どうも'
english = 'thanks; much (thanks, regret, etc.)'
level = 'n5'
tags = []
frequency_scores = { anime = 534, leeds = 1279, novels = 856 }

[[cards]]
kanji = '無い'
kana = 'ない'
english = "nonexistent; not being (there); doesn't have"
level = 'n5'
tags = []
frequency_scores = { anime = 410, leeds = 359, novels = 896, wikipedia = 57 }

[[cards]]
kanji = '何'
kana = 'なに / なん'
english = 'what'
level = 'n5'
tags = []
frequency_scores = { anime = 14, leeds = 109, novels = 46, wikipedia = 1993 }

[[cards]]
kanji = '名前'
kana = 'なまえ'
english = 'name'
level = 'n5'
tags = []
frequency_scores = { anime = 195, leeds = 334, novels = 479, wikipedia = 464 }

[[cards]]
kanji = '西'
kana = 'にし'
english = 'west'
level = 'n5'
tags = []
frequency_scores = { anime = 2583, leeds = 2107, novels = 1821, wikipedia = 117 }

[[cards]]
kanji = '荷物'
kana = 'にもつ'
english = 'luggage'
level = 'n5'
tags = []
frequency_scores = { anime = 1637, leeds = 3147, novels = 1573, wikipedia = 5432 }

[[cards]]
kanji = 'はい'
kana = 'はい'
english = 'yes'
level = 'n5'
tags = []
frequency_scores = { leeds = 2558, novels = 342 }

[[cards]]
kanji = '葉書'
kana = 'はがき'
english = 'postcard'
level = 'n5'
tags = []
frequency_scores = { anime = 16764, leeds = 14959 }

[[cards]]
kanji = '箱'
kana = 'はこ'
english = 'box; crate; chest'
level = 'n5'
tags = []
frequency_scores = { anime = 1897, leeds = 1966, novels = 861, wikipedia = 2154 }

[[cards]]
kanji = '橋'
kana = 'はし'
english = 'bridge'
level = 'n5'
tags = []
frequency_scores = { anime = 2258, leeds = 3120, novels = 1770, wikipedia = 353 }

[[cards]]
kanji = '始め'
kana = 'はじめ'
english = 'beginning; start; origin'
level = 'n5'
tags = []
frequency_scores = { anime = 2650, leeds = 5685, novels = 1543 }

[[cards]]
kanji = '話'
kana = 'はなし'
english = 'talk; story; speech'
level = 'n5'
tags = []
frequency_scores = { anime = 81, leeds = 178, novels = 137, wikipedia = 324 }

[[cards]]
kanji = '半'
kana = 'はん'
english = 'half; half-past'
level = 'n5'
tags = []
frequency_scores = { anime = 2461, leeds = 1628, novels = 715, wikipedia = 1407 }

[[cards]]
kanji = '半分'
kana = 'はんぶん'
english = 'half'
level = 'n5'
tags = []
frequency_scores = { anime = 1457, leeds = 1739, novels = 915, wikipedia = 2505 }

[[cards]]
kanji = '東'
kana = 'ひがし'
english = 'east'
level = 'n5'
tags = []
frequency_scores = { anime = 2831, leeds = 1755, novels = 1610, wikipedia = 106 }

[[cards]]
kanji = '左'
kana = 'ひだり'
english = 'left'
level = 'n5'
tags = []
frequency_scores = { anime = 1842, leeds = 1254, novels = 723, wikipedia = 631 }

[[cards]]
kanji = '平仮名'
kana = 'ひらがな'
english = 'hiragana'
level = 'n5'
tags = []
frequency_scores = { anime = 20960 }

[[cards]]
kanji = '辺'
kana = 'へん'
english = 'area; vicinity; region'
level = 'n5'
tags = ['common', 'noun']
frequency_scores = { anime = 1097, leeds = 2363, novels = 2139, wikipedia = 3286 }

[[cards]]
kanji = '他'
kana = 'ほか'
english = 'other (person, place, thing); the rest'
level = 'n5'
tags = ['common', 'no-adjective', 'noun']
frequency_scores = { anime = 260, leeds = 260, novels = 309, wikipedia = 110 }

[[cards]]
kanji = '本当'
kana = 'ほんとう'
english = 'truth'
level = 'n5'
explain = 'http://selftaughtjapanese.com/2015/04/30/words-to-express-truth-in-japanese/'
tags = ['adverb', 'common', 'na-adjective', 'no-adjective', 'noun']
frequency_scores = { anime = 230, leeds = 1258, novels = 790, wikipedia = 3987 }

[[cards]]
kanji = '又'
kana = 'また'
english = 'again'
level = 'n5'
tags = ['adverb', 'common', 'conjunction', 'prefix']
frequency_scores = { leeds = 3139, novels = 1270, wikipedia = 40 }

[[cards]]
kanji = '右'
kana = 'みぎ'
english = 'right'
level = 'n5'
tags = []
frequency_scores = { anime = 1229, leeds = 1421, novels = 534, wikipedia = 699 }

[[cards]]
kanji = '店'
kana = 'みせ'
english = 'store; shop'
level = 'n5'
tags = []
frequency_scores = { anime = 400, leeds = 305, novels = 499, wikipedia = 413 }

[[cards]]
kanji = '道'
kana = 'みち'
english = 'road, street, path (all inclusive)'
level = 'n5'
explain = 'https://hinative.com/en-US/questions/240900'
tags = ['common', 'noun', 'transportation']
frequency_scores = { anime = 422, leeds = 561, novels = 308, wikipedia = 159 }

[[cards]]
kanji = '南'
kana = 'みなみ'
english = 'south'
level = 'n5'
tags = []
frequency_scores = { anime = 2542, leeds = 1800, novels = 1377, wikipedia = 147 }

[[cards]]
kanji = 'もしもし'
kana = 'もしもし'
english = 'hello (said on phone)'
level = 'n5'
tags = []

[[cards]]
kanji = '物'
kana = 'もの'
english = 'thing'
level = 'n5'
tags = []
frequency_scores = { anime = 313, leeds = 382, novels = 306, wikipedia = 213 }

[[cards]]
kanji = '門'
kana = 'もん'
english = 'gate'
level = 'n5'
tags = []
frequency_scores = { anime = 1863, leeds = 3585, novels = 909, wikipedia = 516 }

[[cards]]
kanji = '～屋'
kana = '～や'
english = 'shop for ～; seller of ～'
level = 'n5'
tags = []

[[cards]]
kanji = '郵便局'
kana = 'ゆうびんきょく'
english = 'post office'
level = 'n5'
tags = []

[[cards]]
kanji = '良い'
kana = 'よい'
english = 'good; OK'
level = 'n5'
tags = ['common', 'i-adjectives']
frequency_scores = { anime = 270, leeds = 195, novels = 557, wikipedia = 192 }

[[cards]]
kanji = '横'
kana = 'よこ'
english = 'horizontal; lying down; side; width'
level = 'n5'
tags = []
frequency_scores = { anime = 2386, leeds = 1715, novels = 435, wikipedia = 1504 }

[[cards]]
kanji = '旅行'
kana = 'りょこう'
english = 'travel; trip; journey'
level = 'n5'
tags = []
frequency_scores = { anime = 2027, leeds = 747, novels = 2252, wikipedia = 1695 }

[[cards]]
kanji = '廊下'
kana = 'ろうか'
english = 'hallway; corridor'
level = 'n5'
tags = []
frequency_scores = { anime = 3195, leeds = 6552, novels = 786 }

[[cards]]
kanji = 'エレベーター'
kana = 'エレベーター'
english = 'elevator'
level = 'n5'
tags = []
frequency_scores = { anime = 5310, leeds = 6648, wikipedia = 5003 }

[[cards]]
kanji = 'カメラ'
kana = 'カメラ'
english = 'camera'
level = 'n5'
tags = []
frequency_scores = { anime = 1604, leeds = 1503, novels = 2173, wikipedia = 1839 }

[[cards]]
kanji = 'キロ'
kana = 'キロ'
english = 'kilogram ; kilometer'
level = 'n5'
tags = []
frequency_scores = { anime = 2662, leeds = 2051, novels = 1463 }

[[cards]]
kanji = 'ギター'
kana = 'ギター'
english = 'guitar'
level = 'n5'
tags = []
frequency_scores = { anime = 2607, leeds = 3117, wikipedia = 1976 }

[[cards]]
kanji = 'グラム'
kana = 'グラム'
english = 'gram'
level = 'n5'
tags = []
frequency_scores = { anime = 6447, leeds = 7778, wikipedia = 7580 }

[[cards]]
kanji = 'スポーツ'
kana = 'スポーツ'
english = 'sports'
level = 'n5'
tags = []
frequency_scores = { anime = 3433, leeds = 1048, wikipedia = 632 }

[[cards]]
kanji = 'タクシー'
kana = 'タクシー'
english = 'taxi'
level = 'n5'
tags = []
frequency_scores = { anime = 7408, leeds = 2775, wikipedia = 4123 }

[[cards]]
kanji = 'デパート'
kana = 'デパート'
english = 'department store'
level = 'n5'
tags = []
frequency_scores = { anime = 8983, leeds = 6238 }

[[cards]]
kanji = 'ニュース'
kana = 'ニュース'
english = 'news'
level = 'n5'
tags = []
frequency_scores = { anime = 3109, leeds = 542, wikipedia = 961 }

[[cards]]
kanji = 'バス'
kana = 'バス'
english = 'bus'
level = 'n5'
tags = []
frequency_scores = { anime = 1221, leeds = 1102, novels = 1766, wikipedia = 236 }

[[cards]]
kanji = 'パーティー'
kana = 'パーティー'
english = 'party'
level = 'n5'
tags = []
frequency_scores = { anime = 1393, leeds = 3974, wikipedia = 3883 }

[[cards]]
kanji = 'フィルム'
kana = 'フィルム'
english = 'film'
level = 'n5'
tags = []
frequency_scores = { anime = 8638, leeds = 3820, wikipedia = 2221 }

[[cards]]
kanji = 'ページ'
kana = 'ページ'
english = 'page'
level = 'n5'
tags = []
frequency_scores = { anime = 3032, leeds = 364, novels = 772 }

[[cards]]
kanji = 'ホテル'
kana = 'ホテル'
english = 'hotel'
level = 'n5'
tags = []
frequency_scores = { anime = 2293, leeds = 946, novels = 1427, wikipedia = 1329 }

[[cards]]
kanji = 'ポスト'
kana = 'ポスト'
english = 'post'
level = 'n5'
tags = []
frequency_scores = { anime = 5388, leeds = 3421, wikipedia = 3416 }

[[cards]]
kanji = 'マッチ'
kana = 'マッチ'
english = 'match'
level = 'n5'
tags = []
frequency_scores = { anime = 4967, leeds = 4782, wikipedia = 3794 }

[[cards]]
kanji = 'ラジオ'
kana = 'ラジオ'
english = 'radio'
level = 'n5'
tags = []
frequency_scores = { anime = 4671, leeds = 1998, wikipedia = 457 }

[[cards]]
kanji = 'レコード'
kana = 'レコード'
english = 'record'
level = 'n5'
tags = []
frequency_scores = { anime = 10133, leeds = 3245, wikipedia = 1051 }

