[[cards]]
kanji = '池'
kana = 'いけ'
english = 'pond'
level = 'n5'
tags = ['common', 'nature', 'noun', 'outdoors']
highest_frequency = 1405
highest_frequency_source = 'Wikipedia 10k'

[[cards]]
kanji = '岩'
kana = 'いわ'
english = 'boulder; crag; cliff'
level = 'n3'
tags = ['common', 'nature', 'noun', 'outdoors']
highest_frequency = 1253
highest_frequency_source = 'Novel 3k'

[[cards]]
kanji = '海'
kana = 'うみ'
english = 'sea; ocean'
level = 'n5'
tags = []
highest_frequency = 256
highest_frequency_source = 'Anime 45k'

[[cards]]
kanji = '海岸'
kana = 'かいがん'
english = 'coast; beach'
level = 'n4'
tags = ['common', 'no-adjective', 'noun', 'ocean']
highest_frequency = 1835
highest_frequency_source = 'Wikipedia 10k'

[[cards]]
kanji = '火山'
kana = 'かざん'
english = 'volcano'
level = 'n2'
tags = ['common', 'no-adjective', 'noun']
highest_frequency = 3205
highest_frequency_source = 'Wikipedia 10k'

[[cards]]
kanji = '川'
kana = 'かわ'
english = 'river'
level = 'n5'
tags = []
highest_frequency = 98
highest_frequency_source = 'Wikipedia 10k'

[[cards]]
kanji = '木'
kana = 'き'
english = 'tree; wood'
level = 'n5'
tags = ['common', 'nature', 'noun']
highest_frequency = 425
highest_frequency_source = 'Wikipedia 10k'

[[cards]]
kanji = '草'
kana = 'くさ'
english = 'grass'
level = 'n4'
tags = ['common', 'nature', 'plants']
highest_frequency = 1539
highest_frequency_source = 'Novel 3k'

[[cards]]
kanji = '草地'
kana = 'くさち'
english = 'meadow, grassland'
tags = ['nature', 'noun', 'outdoors', 'uncommon']

[[cards]]
kanji = '公園'
kana = 'こうえん'
english = '(public) park'
level = 'n5'
tags = []
highest_frequency = 531
highest_frequency_source = 'Wikipedia 10k'

[[cards]]
kanji = '潮'
kana = 'しお'
english = 'tide; current; sea water'
level = 'n1'
tags = ['common']
highest_frequency = 4633
highest_frequency_source = 'Wikipedia 10k'

[[cards]]
kanji = '滝'
kana = 'たき'
english = 'waterfall'
level = 'n2'
source = 'sekai-wa-fushigi-2'
tags = ['common', 'geography', 'nature']
highest_frequency = 3162
highest_frequency_source = 'Wikipedia 10k'

[[cards]]
kanji = '地域'
kana = 'ちいき'
english = 'area; region'
level = 'n3'
source = 'sekai-wa-fushigi-2'
tags = ['common', 'geography']
highest_frequency = 134
highest_frequency_source = 'Wikipedia 10k'

[[cards]]
kanji = '地球'
kana = 'ちきゅう'
english = 'the Earth'
level = 'n3'
tags = ['common', 'no-adjective']
highest_frequency = 616
highest_frequency_source = 'Anime 45k'

[[cards]]
kanji = '地図'
kana = 'ちず'
english = 'map'
level = 'n5'
tags = ['common']
highest_frequency = 2259
highest_frequency_source = 'Novel 3k'

[[cards]]
kanji = '土'
kana = 'つち'
english = 'earth, soil, dirt, clay, mud'
level = 'n3'
tags = ['common', 'earth', 'nature']
highest_frequency = 982
highest_frequency_source = 'Leeds 15k'

[[cards]]
kanji = '虹'
kana = 'にじ'
english = 'rainbow'
level = 'n2'
tags = ['common', 'nature', 'outdoors']
highest_frequency = 5557
highest_frequency_source = 'Anime 45k'

[[cards]]
kanji = '庭'
kana = 'にわ'
english = 'garden'
level = 'n5'
tags = []
highest_frequency = 1273
highest_frequency_source = 'Novel 3k'

[[cards]]
kanji = '灰'
kana = 'はい'
english = 'ash; ashes'
level = 'n3'
tags = ['common', 'fire', 'nature']
highest_frequency = 342
highest_frequency_source = 'Novel 3k'

[[cards]]
kanji = '花'
kana = 'はな'
english = 'flower'
level = 'n5'
tags = []
highest_frequency = 297
highest_frequency_source = 'Anime 45k'

[[cards]]
kanji = '林'
kana = 'はやし'
english = 'woods; forest'
level = 'n4'
tags = ['common', 'nature', 'places', 'plants']
highest_frequency = 865
highest_frequency_source = 'Wikipedia 10k'

[[cards]]
kanji = '湖'
kana = 'みずうみ'
english = 'lake'
level = 'n4'
tags = ['common', 'nature', 'noun', 'outdoors']
highest_frequency = 859
highest_frequency_source = 'Wikipedia 10k'

[[cards]]
kanji = '森'
kana = 'もり'
english = 'big forest'
level = 'n4'
tags = ['common', 'nature', 'noun']
highest_frequency = 606
highest_frequency_source = 'Novel 3k'

[[cards]]
kanji = '山'
kana = 'やま'
english = 'mountain'
level = 'n5'
tags = []
highest_frequency = 124
highest_frequency_source = 'Wikipedia 10k'

