[[cards]]
kanji = '池'
kana = 'いけ'
english = 'pond'
level = 'n5'
tags = ['common', 'nature', 'noun', 'outdoors']

[[cards]]
kanji = '海'
kana = 'うみ'
english = 'sea; ocean'
make_kanji_card = true
level = 'n5'
tags = []

[[cards]]
kanji = '川'
kana = 'かわ'
english = 'river'
make_kanji_card = true
level = 'n5'
tags = []

[[cards]]
kanji = '木'
kana = 'き'
english = 'tree; wood'
level = 'n5'
tags = []

[[cards]]
kanji = '公園'
kana = 'こうえん'
english = '(public) park'
level = 'n5'
tags = []

[[cards]]
kanji = '滝'
kana = 'たき'
english = 'waterfall'
level = 'n2'
source = 'sekai-wa-fushigi-2'
tags = ['common', 'geography', 'nature']

[[cards]]
kanji = '地域'
kana = 'ちいき'
english = 'area; region'
level = 'n3'
source = 'sekai-wa-fushigi-2'
tags = ['common', 'geography']

[[cards]]
kanji = '地図'
kana = 'ちず'
english = 'map'
level = 'n5'
tags = ['common']

[[cards]]
kanji = '庭'
kana = 'にわ'
english = 'garden'
level = 'n5'
tags = []

[[cards]]
kanji = '花'
kana = 'はな'
english = 'flower'
level = 'n5'
tags = []

[[cards]]
kanji = '山'
kana = 'やま'
english = 'mountain'
level = 'n5'
tags = []

