[[cards]]
kanji = '池'
kana = 'いけ'
english = 'pond'
level = 'n5'
tags = ['common', 'nature', 'noun', 'outdoors']
frequency_scores = { anime = 5802, leeds = 4564, wikipedia = 1405 }

[[cards]]
kanji = '泉'
kana = 'いずみ'
english = 'spring; fountain'
source = 'wanikani; japan visit name?'
level = 'n3'
tags = ['common', 'nature', 'noun', 'water']
frequency_scores = { anime = 1285, leeds = 4511, wikipedia = 1645 }

[[cards]]
kanji = '岩'
kana = 'いわ'
english = 'boulder; crag; cliff'
level = 'n3'
tags = ['common', 'nature', 'noun', 'outdoors']
frequency_scores = { anime = 2874, leeds = 5357, novels = 1253, wikipedia = 1401 }

[[cards]]
kanji = '海'
kana = 'うみ'
english = 'sea; ocean'
level = 'n5'
tags = []
frequency_scores = { anime = 256, leeds = 629, novels = 543, wikipedia = 363 }

[[cards]]
kanji = '海岸'
kana = 'かいがん'
english = 'coast; beach'
level = 'n4'
tags = ['common', 'no-adjective', 'noun', 'ocean']
frequency_scores = { anime = 6176, leeds = 4606, wikipedia = 1835 }

[[cards]]
kanji = '火山'
kana = 'かざん'
english = 'volcano'
level = 'n2'
tags = ['common', 'no-adjective', 'noun']
frequency_scores = { anime = 13165, leeds = 7547, wikipedia = 3205 }

[[cards]]
kanji = '川'
kana = 'かわ'
english = 'river'
level = 'n5'
tags = []
frequency_scores = { anime = 1494, leeds = 1724, novels = 1292, wikipedia = 98 }

[[cards]]
kanji = '草'
kana = 'くさ'
english = 'grass'
level = 'n4'
tags = ['common', 'nature', 'plants']
frequency_scores = { anime = 3085, leeds = 4331, novels = 1539, wikipedia = 1983 }

[[cards]]
kanji = '草地'
kana = 'くさち'
english = 'meadow, grassland'
tags = ['nature', 'noun', 'outdoors', 'uncommon']

[[cards]]
kanji = '公園'
kana = 'こうえん'
english = '(public) park'
level = 'n5'
tags = []
frequency_scores = { anime = 2724, leeds = 1806, novels = 2383, wikipedia = 531 }

[[cards]]
kanji = '潮'
kana = 'しお'
english = 'tide; current; sea water'
level = 'n1'
tags = ['common']
frequency_scores = { anime = 10386, leeds = 9488, wikipedia = 4633 }

[[cards]]
kanji = '地震'
kana = 'じしん'
english = 'earthquake'
source = 'irasshai'
level = 'n4'
tags = ['common', 'noun']
frequency_scores = { anime = 4761, leeds = 1828, wikipedia = 1323 }

[[cards]]
kanji = '蒸気'
kana = 'じょうき'
english = 'steam'
source = 'wanikani'
level = 'n2'
tags = ['common', 'nature', 'noun', 'physics', 'water']
frequency_scores = { anime = 11550, leeds = 11149, wikipedia = 2423 }

[[cards]]
kanji = '滝'
kana = 'たき'
english = 'waterfall'
level = 'n2'
source = 'sekai-wa-fushigi-2'
tags = ['common', 'geography', 'nature']
frequency_scores = { anime = 6164, leeds = 6737, wikipedia = 3162 }

[[cards]]
kanji = '地域'
kana = 'ちいき'
english = 'area; region'
level = 'n3'
source = 'sekai-wa-fushigi-2'
tags = ['common', 'geography']
frequency_scores = { anime = 4854, leeds = 367, wikipedia = 134 }

[[cards]]
kanji = '地球'
kana = 'ちきゅう'
english = 'the Earth'
level = 'n3'
tags = ['common', 'no-adjective']
frequency_scores = { anime = 616, leeds = 1128, novels = 1187, wikipedia = 775 }

[[cards]]
kanji = '地図'
kana = 'ちず'
english = 'map'
level = 'n5'
tags = ['common']
frequency_scores = { anime = 2932, leeds = 2551, novels = 2259, wikipedia = 3427 }

[[cards]]
kanji = '土'
kana = 'つち'
english = 'earth, soil, dirt, clay, mud'
level = 'n3'
tags = ['common', 'earth', 'nature']
frequency_scores = { anime = 2579, leeds = 982, novels = 1251, wikipedia = 1324 }

[[cards]]
kanji = '虹'
kana = 'にじ'
english = 'rainbow'
level = 'n2'
tags = ['common', 'nature', 'outdoors']
frequency_scores = { anime = 5557, leeds = 7991, wikipedia = 6042 }

[[cards]]
kanji = '庭'
kana = 'にわ'
english = 'garden'
level = 'n5'
tags = []
frequency_scores = { anime = 2725, leeds = 3124, novels = 1273, wikipedia = 4182 }

[[cards]]
kanji = '灰'
kana = 'はい'
english = 'ash; ashes'
level = 'n3'
tags = ['common', 'fire', 'nature']
frequency_scores = { anime = 4736, leeds = 9966, novels = 342, wikipedia = 5332 }

[[cards]]
kanji = '湖'
kana = 'みずうみ'
english = 'lake'
level = 'n4'
tags = ['common', 'nature', 'noun', 'outdoors']
frequency_scores = { anime = 5190, leeds = 4433, wikipedia = 859 }

[[cards]]
kanji = '山'
kana = 'やま'
english = 'mountain'
level = 'n5'
tags = []
frequency_scores = { anime = 707, leeds = 1026, novels = 425, wikipedia = 124 }

