[[cards]]
kanji = '池'
kana = 'いけ'
english = 'pond'
level = 'n5'
tags = ['common', 'nature', 'noun', 'outdoors']

[[cards]]
kanji = '海'
kana = 'うみ'
english = 'sea; ocean'
level = 'n5'
tags = []

[[cards]]
kanji = '海岸'
kana = 'かいがん'
english = 'coast; beach'
level = 'n4'
tags = ['common', 'no-adjective', 'noun', 'ocean']

[[cards]]
kanji = '火山'
kana = 'かざん'
english = 'volcano'
level = 'n2'
tags = ['common', 'no-adjective', 'noun']

[[cards]]
kanji = '川'
kana = 'かわ'
english = 'river'
level = 'n5'
tags = []

[[cards]]
kanji = '木'
kana = 'き'
english = 'tree; wood'
level = 'n5'
tags = ['common', 'nature', 'noun']

[[cards]]
kanji = '草'
kana = 'くさ'
english = 'grass'
level = 'n4'
tags = ['common', 'nature', 'plants']

[[cards]]
kanji = '草地'
kana = 'くさち'
english = 'meadow, grassland'
tags = ['nature', 'noun', 'outdoors', 'uncommon']

[[cards]]
kanji = '公園'
kana = 'こうえん'
english = '(public) park'
level = 'n5'
tags = []

[[cards]]
kanji = '潮'
kana = 'しお'
english = 'tide; current; sea water'
level = 'n1'
tags = ['common']

[[cards]]
kanji = '滝'
kana = 'たき'
english = 'waterfall'
level = 'n2'
source = 'sekai-wa-fushigi-2'
tags = ['common', 'geography', 'nature']

[[cards]]
kanji = '地域'
kana = 'ちいき'
english = 'area; region'
level = 'n3'
source = 'sekai-wa-fushigi-2'
tags = ['common', 'geography']

[[cards]]
kanji = '地球'
kana = 'ちきゅう'
english = 'the Earth'
level = 'n3'
tags = ['common', 'no-adjective']

[[cards]]
kanji = '地図'
kana = 'ちず'
english = 'map'
level = 'n5'
tags = ['common']

[[cards]]
kanji = '土'
kana = 'つち'
english = 'earth, soil, dirt, clay, mud'
level = 'n3'
tags = ['common', 'earth', 'nature']

[[cards]]
kanji = '虹'
kana = 'にじ'
english = 'rainbow'
level = 'n2'
tags = ['common', 'nature', 'outdoors']

[[cards]]
kanji = '庭'
kana = 'にわ'
english = 'garden'
level = 'n5'
tags = []

[[cards]]
kanji = '灰'
kana = 'はい'
english = 'ash; ashes'
level = 'n3'
tags = ['common', 'fire', 'nature']

[[cards]]
kanji = '花'
kana = 'はな'
english = 'flower'
level = 'n5'
tags = []

[[cards]]
kanji = '林'
kana = 'はやし'
english = 'woods; forest'
level = 'n4'
tags = ['common', 'nature', 'places', 'plants']

[[cards]]
kanji = '湖'
kana = 'みずうみ'
english = 'lake'
level = 'n4'
tags = ['common', 'nature', 'noun', 'outdoors']

[[cards]]
kanji = '森'
kana = 'もり'
english = 'big forest'
level = 'n4'
tags = ['common', 'nature', 'noun']

[[cards]]
kanji = '山'
kana = 'やま'
english = 'mountain'
level = 'n5'
tags = []

