[[cards]]
kanji = 'きらきら'
kana = 'きらきら'
english = 'glittering; sparkling'
source = 'wanikani'
tags = ['adverb', 'adverb-taking-to', 'common', 'suru-verb']
frequency_scores = { anime = 11450 }

[[cards]]
kanji = 'そろそろ'
kana = 'そろそろ'
english = 'slowly, gradually -- OR -- soon, any time now'
source = 'wiktionary'
level = 'n4'
tags = ['generated', 'onomatopoia', 'tsv']
frequency_scores = { anime = 392, leeds = 2544, novels = 1462 }

[[cards]]
kanji = 'どんどん'
kana = 'どんどん'
english = 'rapidly; drumming; pounding'
source = 'n4-wikipedia; ramen'
level = 'n4'
tags = ['adverb', 'adverb-to', 'common']
frequency_scores = { anime = 1364, leeds = 1409, novels = 2314 }

[[cards]]
kanji = 'ふんわり'
kana = 'ふんわり'
english = 'gently; fluffily'
source = 'food-package'
tags = ['common', 'onomatopoeia']
frequency_scores = { anime = 18702 }

[[cards]]
kanji = 'わくわく'
kana = 'わくわく'
english = 'excited; nervous; trembling (ono)'
source = 'anime; db super'
tags = ['adverb', 'adverb-to', 'common', 'suru-verb']
frequency_scores = { anime = 5534, leeds = 8449 }

[[cards]]
kanji = 'ニコニコ'
kana = 'ニコニコ'
english = 'smilingly; with a friendly grin'
level = 'n2'
tags = ['adverb', 'adverb-taking-to', 'common', 'suru-verb']
frequency_scores = { anime = 13638, leeds = 10929, wikipedia = 8025 }

[[cards]]
kanji = 'ペコペコ'
kana = 'ペコペコ'
english = 'very hungry; starving'
source = 'irasshai'
level = 'n1'
tags = ['adverb', 'adverb-taking-to', 'common', 'na-adjective', 'suru-verb']
frequency_scores = { anime = 15433 }

[[cards]]
kanji = 'ペラペラ'
kana = 'ペラペラ'
english = 'fluently (speaking)'
source = 'irasshai'
tags = ['adverb', 'adverb-taking-to', 'common', 'na-adjective']
frequency_scores = { anime = 14942 }

