[[cards]]
kanji = 'そろそろ'
kana = 'そろそろ'
english = 'slowly, gradually -- OR -- soon, any time now'
source = 'wiktionary'
level = 'n4'
tags = ['generated', 'tsv', 'onomatopoia']
highest_frequency = 392
highest_frequency_source = 'Anime'

[[cards]]
kanji = 'きらきら'
kana = 'きらきら'
english = 'glittering; sparkling'
source = 'wanikani'
tags = ['adverb', 'adverb-taking-to', 'common', 'suru-verb']
highest_frequency = 11450
highest_frequency_source = 'Anime'

[[cards]]
kanji = 'どんどん'
kana = 'どんどん'
english = 'rapidly; drumming; pounding'
source = 'n4-wikipedia; ramen'
level = 'n4'
tags = ['adverb', 'adverb-to', 'common']
highest_frequency = 1364
highest_frequency_source = 'Anime'

[[cards]]
kanji = 'ふんわり'
kana = 'ふんわり'
english = 'gently; fluffily'
source = 'food-package'
tags = ['common', 'onomatopoeia']
highest_frequency = 18702
highest_frequency_source = 'Anime'

[[cards]]
kanji = 'わくわく'
kana = 'わくわく'
english = 'excited; nervous; trembling (ono)'
source = 'anime; db super'
tags = ['adverb', 'adverb-to', 'common', 'suru-verb']
highest_frequency = 5534
highest_frequency_source = 'Anime'

[[cards]]
kanji = 'ニコニコ'
kana = 'ニコニコ'
english = 'smilingly; with a friendly grin'
level = 'n2'
tags = ['adverb', 'adverb-taking-to', 'common', 'suru-verb']
highest_frequency = 8025
highest_frequency_source = 'Wikipedia'

[[cards]]
kanji = 'ペコペコ'
kana = 'ペコペコ'
english = 'very hungry; starving'
source = 'irasshai'
level = 'n1'
tags = ['adverb', 'adverb-taking-to', 'common', 'na-adjective', 'suru-verb']
highest_frequency = 15433
highest_frequency_source = 'Anime'

[[cards]]
kanji = 'ペラペラ'
kana = 'ペラペラ'
english = 'fluently (speaking)'
source = 'irasshai'
tags = ['adverb', 'adverb-taking-to', 'common', 'na-adjective']
highest_frequency = 14942
highest_frequency_source = 'Anime'

