[[cards]]
kanji = '相手'
kana = 'あいて'
english = 'partner; opponent (sports)'
level = 'n3'
tags = ['common', 'noun', 'people']

[[cards]]
kanji = '赤ちゃん'
kana = 'あかちゃん'
english = 'baby'
level = 'n4'
tags = ['common', 'noun', 'people']

[[cards]]
kanji = '貴方'
kana = 'あなた'
english = 'you (equal or lower status); dear (wife to husband)'
level = 'n5'
tags = ['common', 'people', 'pronouns']

[[cards]]
kanji = '兄'
kana = 'あに'
english = 'older brother (humble/kenjougo)'
level = 'n5'
tags = ['common', 'family', 'humble', 'kenjougo', 'people']

[[cards]]
kanji = '姉'
kana = 'あね'
english = 'older sister (humble/kenjougo)'
level = 'n5'
tags = ['common', 'family', 'humble', 'kenjougo', 'people']

[[cards]]
kanji = '妹'
kana = 'いもうと'
english = 'younger sister (humble / kenjougo)'
level = 'n5'
tags = []

[[cards]]
kanji = '王'
kana = 'おう'
english = 'king; monarch; sovereign'
make_kanji_card = true
hide_hiragana_card = true
source = 'wanikani'
level = 'n3'
tags = ['common', 'noun']

[[cards]]
kanji = '王様'
kana = 'おうさま'
english = 'king (sonkeigo)'
make_kanji_card = true
hide_hiragana_card = true
source = 'wanikani'
level = 'n3'
tags = ['common', 'noun']

[[cards]]
kanji = '大勢'
kana = 'おおぜい'
english = 'crowd of people'
level = 'n5'
tags = []

[[cards]]
kanji = 'お母さん'
kana = 'おかあさん'
english = 'mother (honorific/respectful/sonkeigo)'
make_kanji_card = true
level = 'n5'
tags = []

[[cards]]
kanji = '奥さん'
kana = 'おくさん'
english = 'wife (honorific/respectful/sonkeigo)'
level = 'n5'
tags = []

[[cards]]
kanji = 'お祖父さん'
kana = 'おじいさん'
english = 'grandfather; male senior citizen'
level = 'n5'
tags = []

[[cards]]
kanji = '伯父さん'
kana = 'おじさん'
english = 'uncle; old man'
level = 'n5'
tags = []

[[cards]]
kanji = 'お父さん'
kana = 'おとうさん'
english = 'father (honorific/respectful/sonkeigo)'
level = 'n5'
tags = []

[[cards]]
kanji = '弟'
kana = 'おとうと'
english = 'little brother (humble/kenjougo)'
level = 'n5'
tags = []

[[cards]]
kanji = '男'
kana = 'おとこ'
english = 'man; male'
make_kanji_card = true
level = 'n5'
tags = []

[[cards]]
kanji = '男の子'
kana = 'おとこのこ'
english = 'boy'
make_kanji_card = true
level = 'n5'
tags = []

[[cards]]
kanji = '大人'
kana = 'おとな'
english = 'adult'
make_kanji_card = true
level = 'n5'
tags = []

[[cards]]
kanji = 'お兄さん'
kana = 'おにいさん'
english = 'older brother (honorific/respectful/sonkeigo)'
level = 'n5'
tags = []

[[cards]]
kanji = 'お姉さん'
kana = 'おねえさん'
english = 'older sister (honorific/respectful/sonkeigo)'
level = 'n5'
tags = []

[[cards]]
kanji = 'お祖母さん'
kana = 'おばあさん'
english = 'grandmother'
level = 'n5'
tags = []

[[cards]]
kanji = '伯母さん'
kana = 'おばさん'
english = 'aunt (honorific/respectful/sonkeigo)'
level = 'n5'
tags = []

[[cards]]
kanji = 'お巡りさん'
kana = 'おまわりさん'
english = 'police officer (friendly term)'
make_kanji_card = true
level = 'n5'
tags = []

[[cards]]
kanji = '女'
kana = 'おんな'
english = 'woman; female'
make_kanji_card = true
level = 'n5'
tags = []

[[cards]]
kanji = '女の子'
kana = 'おんなのこ'
english = 'girl'
make_kanji_card = true
level = 'n5'
tags = []

[[cards]]
kanji = '家族'
kana = 'かぞく'
english = 'family'
level = 'n5'
tags = []

[[cards]]
kanji = '方'
kana = 'かた'
english = 'person (sonkeigo); method or way of'
make_kanji_card = true
level = 'n5'
tags = []

[[cards]]
kanji = '金持ち'
kana = 'かねもち'
english = 'rich person'
tags = ['common', 'noun', 'people']

[[cards]]
kanji = '看護師'
kana = 'かんごし'
english = 'hospital nurse'
level = 'n4'
tags = ['common']

[[cards]]
kanji = '外国人'
kana = 'がいこくじん'
english = 'foreigner'
level = 'n5'
tags = ['common', 'noun']

[[cards]]
kanji = '外人'
kana = 'がいじん'
english = 'foreigner (less polite)'
tags = ['common', 'noun']

[[cards]]
kanji = '兄弟'
kana = 'きょうだい'
english = 'siblings'
level = 'n5'
tags = []

[[cards]]
kanji = '警官'
kana = 'けいかん'
english = 'police'
level = 'n5'
tags = []

[[cards]]
kanji = '作者'
kana = 'さくしゃ'
english = 'author (of a particular work)'
level = 'n2'
source = 'read-nihon'
tags = ['common', 'people']

[[cards]]
kanji = '作家'
kana = 'さっか'
english = 'author (profession)'
level = 'n3'
tags = ['common', 'people']

[[cards]]
kanji = '社長'
kana = 'しゃちょう'
english = 'company president; manager; director'
level = 'n4'
source = 'wanikani'
tags = ['common', 'noun']

[[cards]]
kanji = '自分'
kana = 'じぶん'
english = 'myself; oneself'
level = 'n5'
tags = []

[[cards]]
kanji = '女王'
kana = 'じょおう'
english = 'queen'
make_kanji_card = true
hide_hiragana_card = true
source = 'wanikani'
level = 'n3'
tags = ['common', 'noun']

[[cards]]
kanji = '人口'
kana = 'じんこう'
english = 'population'
level = 'n4'
source = 'wanikani'
tags = ['common', 'noun']

[[cards]]
kanji = '声優'
kana = 'せいゆう'
english = 'actor; performer'
tags = ['noun', 'people', 'uncommon']

[[cards]]
kanji = '選手'
kana = 'せんしゅ'
english = 'athelete; player (sports)'
level = 'n3'
source = 'wanikani'
tags = ['common', 'noun', 'sports']

[[cards]]
kanji = '祖父'
kana = 'そふ'
english = 'grandfather; old man'
level = 'n5'
tags = ['common', 'family', 'people']

[[cards]]
kanji = '祖母'
kana = 'そぼ'
english = 'grandmother'
level = 'n4'
tags = ['common', 'family', 'people']

[[cards]]
kanji = '父'
kana = 'ちち'
english = "(one's own) father (humble/kenjougo)"
level = 'n5'
tags = []

[[cards]]
kanji = '天才'
kana = 'てんさい'
english = 'genius'
level = 'n1'
source = 'wanikani'
tags = ['common', 'noun']

[[cards]]
kanji = '年寄り'
kana = 'としより'
english = 'elderly person'
source = 'sekai-wa-fushigi-2'
level = 'n3'
tags = ['common', 'no-adjective', 'noun']

[[cards]]
kanji = '友達'
kana = 'ともだち'
english = 'friend (spoken form)'
level = 'n5'
explain = 'https://hinative.com/en-US/questions/696835'
tags = []

[[cards]]
kanji = '泥棒'
kana = 'どろぼう'
english = 'thief'
level = 'n4'
tags = ['common', 'noun', 'suru-verb']

[[cards]]
kanji = '～人'
kana = '～にん'
english = 'counter for people'
level = 'n5'
tags = []

[[cards]]
kanji = '俳優'
kana = 'はいゆう'
english = 'actor; performer'
level = 'n3'
tags = ['common', 'no-adjective', 'noun', 'people']

[[cards]]
kanji = '白人'
kana = 'はくじん'
english = 'white person; Caucasian'
make_kanji_card = true
hide_hiragana_card = true
source = 'wanikani'
tags = ['common', 'no-adjective']

[[cards]]
kanji = '母'
kana = 'はは'
english = "(one's own) mother (humble/kenjougo)"
level = 'n5'
tags = []

[[cards]]
kanji = '人'
kana = 'ひと'
english = 'man; person'
level = 'n5'
tags = []

[[cards]]
kanji = '一人'
kana = 'ひとり'
english = 'one person'
level = 'n5'
tags = []

[[cards]]
kanji = '二人'
kana = 'ふたり'
english = 'two people'
level = 'n5'
tags = []

[[cards]]
kanji = '星'
kana = 'ほし'
english = 'star'
level = 'n4'
tags = ['common', 'noun', 'space']

[[cards]]
kanji = '皆さん'
kana = 'みなさん'
english = 'everyone (sonkeigo)'
level = 'n5'
tags = ['common', 'honorific', 'noun', 'respectful', 'sonkeigo']

[[cards]]
kanji = '皆'
kana = 'みんな'
english = 'everyone'
level = 'n5'
tags = []

[[cards]]
kanji = '息子'
kana = 'むすこ'
english = 'son'
level = 'n4'
tags = ['common', 'family', 'noun', 'people']

[[cards]]
kanji = '娘'
kana = 'むすめ'
english = '(my) daughter'
level = 'n4'
tags = ['common', 'family', 'noun', 'people']

[[cards]]
kanji = '役人'
kana = 'やくにん'
english = 'government official'
level = 'n2'
tags = ['common', 'government']

[[cards]]
kanji = '友人'
kana = 'ゆうじん'
english = 'friend (written form)'
level = 'n3'
source = 'wanikani'
explain = 'https://hinative.com/en-US/questions/696835'
tags = ['common', 'noun', 'people']

[[cards]]
kanji = '両親'
kana = 'りょうしん'
english = 'parents; both parents'
level = 'n5'
tags = []

[[cards]]
kanji = '若い'
kana = 'わかい'
english = 'young; youthful'
level = 'n5'
tags = []

[[cards]]
kanji = '私'
kana = 'わたくし'
english = 'I; me (more formal)'
level = 'n5'
tags = []

[[cards]]
kanji = '私'
kana = 'わたし'
english = 'I; me'
level = 'n5'
tags = []

