[[cards]]
kanji = '田舎'
kana = 'いなか'
english = 'countryside; rural area'
source = 'living-in-japan'
tags = ['common', 'no-adjective', 'noun', 'places']

[[cards]]
kanji = '空港'
kana = 'くうこう'
english = 'airport'
source = 'n4-study'
level = 'n4'
tags = ['common', 'places', 'travel']

[[cards]]
kanji = '日本'
kana = 'にほん'
english = 'Japan'
level = 'n3'
tags = ['common', 'noun', 'places']

[[cards]]
kanji = '港'
kana = 'みなと'
english = 'harbor; port'
source = 'jlptstudy'
level = 'n4'
tags = ['common', 'noun', 'ocean', 'places']

[[cards]]
kanji = 'コンビニ'
kana = 'コンビニ'
english = 'convenience store'
source = 'wanikani'
tags = ['common', 'gairaigo', 'noun', 'places']

[[cards]]
kanji = 'スーパー'
kana = 'スーパー'
english = 'supermarket'
source = 'nihongo-charenji-n4-kotoba'
tags = ['common', 'gairaigo']

