[[cards]]
kanji = '田舎'
kana = 'いなか'
english = 'countryside; rural area'
source = 'living-in-japan'
tags = ['common', 'no-adjective', 'noun', 'places']

[[cards]]
kanji = '映画館'
kana = 'えいがかん'
english = 'movie theater'
level = 'n5'
tags = ['buildings', 'common', 'entertainment', 'noun', 'places']

[[cards]]
kanji = '外国'
kana = 'がいこく'
english = 'foreign country'
level = 'n5'
tags = []

[[cards]]
kanji = '空港'
kana = 'くうこう'
english = 'airport'
source = 'n4-study'
level = 'n4'
tags = ['common', 'places', 'travel']

[[cards]]
kanji = '国'
kana = 'くに'
english = 'country'
level = 'n5'
tags = []

[[cards]]
kanji = '工場'
kana = 'こうじょう'
english = 'factory'
source = 'wanikani'
level = 'n4'
tags = ['business', 'common', 'industry', 'noun', 'places']

[[cards]]
kanji = '住所'
kana = 'じゅうしょ'
english = 'address (of a house); residence'
source = 'irasshai?; wanikani; japanese forms'
level = 'n4'
tags = ['common', 'noun', 'places']

[[cards]]
kanji = '世界'
kana = 'せかい'
english = 'the world'
source = 'irasshai'
level = 'n4'
tags = ['common', 'no-adjective', 'noun']

[[cards]]
kanji = '所'
kana = 'ところ'
english = 'place; area (can be abstract; less formal)'
level = 'n5'
explain = 'https://japanese.stackexchange.com/questions/58236/difference-between-%E5%A0%B4%E6%89%80-and-%E6%89%80'
tags = ['common', 'noun']

[[cards]]
kanji = '日本'
kana = 'にほん'
english = 'Japan'
level = 'n3'
tags = ['common', 'noun', 'places']

[[cards]]
kanji = '場所'
kana = 'ばしょ'
english = 'place (always physical, slightly more formal)'
source = 'irasshai; anime'
level = 'n4'
explain = 'https://japanese.stackexchange.com/questions/58236/difference-between-%E5%A0%B4%E6%89%80-and-%E6%89%80'
tags = ['common', 'noun', 'places']

[[cards]]
kanji = '町'
kana = 'まち'
english = 'town; city'
level = 'n5'
tags = []

[[cards]]
kanji = '港'
kana = 'みなと'
english = 'harbor; port'
source = 'jlptstudy'
level = 'n4'
tags = ['common', 'noun', 'ocean', 'places']

[[cards]]
kanji = 'コンビニ'
kana = 'コンビニ'
english = 'convenience store'
source = 'wanikani'
tags = ['common', 'gairaigo', 'noun', 'places']

[[cards]]
kanji = 'スーパー'
kana = 'スーパー'
english = 'supermarket'
source = 'nihongo-charenji-n4-kotoba'
tags = ['common', 'gairaigo']

