[[cards]]
kanji = '田舎'
kana = 'いなか'
english = 'countryside; rural area'
tags = ['common', 'no-adjective', 'noun', 'places']

[[cards]]
kanji = 'スーパー'
kana = 'スーパー'
english = 'supermarket'
source = 'nihongo-charenji-n4-kotoba'
tags = ['common', 'gairaigo']

