[[cards]]
kanji = '上'
kana = 'うえ'
english = 'above; up; on top of'
level = 'n5'
tags = ['adverbial-noun', 'common', 'no-adjective', 'noun', 'noun-suffix']
frequency_scores = { anime = 175, leeds = 171, novels = 109, wikipedia = 208 }

[[cards]]
kanji = '後ろ'
kana = 'うしろ'
english = 'behind'
level = 'n5'
tags = ['common', 'no-adjective', 'noun']
frequency_scores = { anime = 893, leeds = 2287, novels = 564, wikipedia = 4519 }

[[cards]]
kanji = '表'
kana = 'おもて'
english = 'surface; front; outside; face'
source = 'wanikani; anime'
level = 'n4'
tags = ['common', 'noun']
frequency_scores = { anime = 2476, leeds = 1317, novels = 1582, wikipedia = 1016 }

[[cards]]
kanji = '下'
kana = 'した'
english = 'below; under; bottom'
level = 'n5'
tags = ['common', 'no-adjective', 'noun', 'noun-prefix']
frequency_scores = { anime = 414, leeds = 453, novels = 183, wikipedia = 347 }

[[cards]]
kanji = '外'
kana = 'そと'
english = 'outside; exterior'
level = 'n5'
tags = ['common', 'noun']
frequency_scores = { anime = 328, leeds = 612, novels = 243, wikipedia = 266 }

[[cards]]
kanji = '側'
kana = 'そば'
english = 'near; close; vicinity'
level = 'n5'
tags = ['common', 'noun']
frequency_scores = { anime = 846, leeds = 424, novels = 554, wikipedia = 1766 }

[[cards]]
kanji = '近く'
kana = 'ちかく'
english = 'near; vicinity'
level = 'n5'
tags = ['adverbial-noun', 'common', 'no-adjective']
frequency_scores = { anime = 789, leeds = 809, novels = 699, wikipedia = 2364 }

[[cards]]
kanji = '中'
kana = 'なか'
english = 'inside; middle; center; among'
level = 'n5'
tags = ['common', 'noun']
frequency_scores = { anime = 67, leeds = 90, novels = 63, wikipedia = 86 }

[[cards]]
kanji = '前'
kana = 'まえ'
english = 'before; in front of'
level = 'n5'
tags = ['adverbial-noun', 'common', 'suffix', 'temporal-noun']
frequency_scores = { anime = 66, leeds = 144, novels = 83, wikipedia = 513 }

[[cards]]
kanji = '向こう'
kana = 'むこう'
english = 'opposite side; far away; beyond; over there'
level = 'n5'
tags = ['common', 'noun']
frequency_scores = { anime = 587, leeds = 2627, novels = 742 }

