[[cards]]
kanji = '田舎'
kana = 'いなか'
english = 'countryside; rural area'
source = 'living-in-japan'
tags = ['common', 'no-adjective', 'noun', 'places']

[[cards]]
kanji = 'コンビニ'
kana = 'コンビニ'
english = 'convenience store'
source = 'wanikani'
tags = ['common', 'gairaigo', 'noun', 'places']

[[cards]]
kanji = 'スーパー'
kana = 'スーパー'
english = 'supermarket'
source = 'nihongo-charenji-n4-kotoba'
tags = ['common', 'gairaigo']

