[[cards]]
kanji = '枝'
kana = 'えだ'
english = 'branch'
level = 'n4'
source = 'jlptstudy.net'
tags = ['common', 'nature', 'noun']
highest_frequency = 1402
highest_frequency_source = 'Novels'

[[cards]]
kanji = '木'
kana = 'き'
english = 'tree; wood'
level = 'n5'
tags = ['common', 'nature', 'noun']
highest_frequency = 425
highest_frequency_source = 'Wikipedia'

[[cards]]
kanji = '植物'
kana = 'しょくぶつ'
english = 'plant'
source = 'wanikani'
level = 'n3'
tags = ['common', 'noun', 'plants']
highest_frequency = 1153
highest_frequency_source = 'Wikipedia'

[[cards]]
kanji = '葉'
kana = 'は'
english = 'leaf'
source = 'wanikani; n4-wiki'
level = 'n4'
tags = ['biology', 'botany', 'common', 'nature', 'noun', 'plants']
highest_frequency = 345
highest_frequency_source = 'Anime'

[[cards]]
kanji = '花'
kana = 'はな'
english = 'flower'
level = 'n5'
tags = ['common', 'nature', 'noun', 'plants']
highest_frequency = 297
highest_frequency_source = 'Anime'

[[cards]]
kanji = '林'
kana = 'はやし'
english = 'woods; forest'
level = 'n4'
tags = ['common', 'nature', 'places', 'plants']
highest_frequency = 865
highest_frequency_source = 'Wikipedia'

[[cards]]
kanji = '森'
kana = 'もり'
english = 'big forest'
level = 'n4'
tags = ['common', 'nature', 'noun']
highest_frequency = 606
highest_frequency_source = 'Novels'

