[[cards]]
kanji = '計画'
kana = 'けいかく'
english = 'project; plan'
source = 'wanikani'
level = 'n3'
tags = ['common', 'noun', 'suru-verb']
highest_frequency = 221
highest_frequency_source = 'Wikipedia'

[[cards]]
kanji = '支度'
kana = 'したく'
english = 'preparation; arrangements'
source = 'wanikani'
level = 'n3'
tags = ['common', 'noun', 'suru-verb']
highest_frequency = 4932
highest_frequency_source = 'Anime'

[[cards]]
kanji = '積もり'
kana = 'つもり'
english = 'intention; plan'
source = 'jlptstudy'
level = 'n4'
tags = ['common', 'noun']
highest_frequency = 194
highest_frequency_source = 'Anime'

[[cards]]
kanji = '予定'
kana = 'よてい'
english = 'plans; arrangement'
level = 'n4'
source = 'wanikani'
tags = ['common', 'noun', 'suru-verb']
highest_frequency = 468
highest_frequency_source = 'Wikipedia'

