[[cards]]
kanji = '計画'
kana = 'けいかく'
english = 'project; plan'
source = 'wanikani'
level = 'n3'
tags = ['common', 'noun', 'suru-verb']
frequency_scores = { anime = 937, leeds = 474, novels = 1192, wikipedia = 221 }

[[cards]]
kanji = '支度'
kana = 'したく'
english = 'preparation; arrangements'
source = 'wanikani'
level = 'n3'
tags = ['common', 'noun', 'suru-verb']
frequency_scores = { anime = 4932, leeds = 13424 }

[[cards]]
kanji = '積もり'
kana = 'つもり'
english = 'intention; plan'
source = 'jlptstudy'
level = 'n4'
tags = ['common', 'noun']
frequency_scores = { anime = 194, leeds = 1015, novels = 321 }

[[cards]]
kanji = '予定'
kana = 'よてい'
english = 'plans; arrangement'
level = 'n4'
source = 'wanikani'
tags = ['common', 'noun', 'suru-verb']
frequency_scores = { anime = 905, leeds = 528, novels = 1896, wikipedia = 468 }

