[[cards]]
kanji = '貴方'
kana = 'あんた'
english = 'you (familiar form of "anata")'
source = 'anime-freq'
tags = ['common', 'pronoun']
frequency_scores = { anime = 1022, leeds = 4636, novels = 1686 }

[[cards]]
kanji = '俺'
kana = 'おれ'
english = 'I; me (male, rough/arrogant)'
source = 'anime'
level = 'n1'
tags = ['anime', 'common', 'pronoun']
frequency_scores = { anime = 20, leeds = 699, novels = 118, wikipedia = 3950 }

[[cards]]
kanji = '貴様'
kana = 'きさま'
english = 'you bastard'
source = 'anime'
tags = ['pronoun', 'uncommon', 'uncommon-but-ive-heard-this']
frequency_scores = { anime = 224, novels = 1861 }

[[cards]]
kanji = '君'
kana = 'きみ'
english = 'you; buddy; pal'
source = 'anime'
level = 'n4'
tags = ['common', 'pronoun']
frequency_scores = { anime = 30, leeds = 234, novels = 201, wikipedia = 3058 }

[[cards]]
kanji = '僕'
kana = 'ぼく'
english = 'I; me (male language)'
source = 'irasshai; anime'
level = 'n4'
tags = ['anime', 'common', 'male', 'male-language', 'pronoun']
frequency_scores = { anime = 48, leeds = 274, novels = 197, wikipedia = 2602 }

[[cards]]
kanji = '奴'
kana = 'やつ'
english = 'fellow; chap (derogatory)'
source = 'anime-freq'
tags = ['anime', 'common', 'derogatory', 'pronoun', 'rude']
frequency_scores = { anime = 185, leeds = 2537, novels = 432, wikipedia = 5318 }

[[cards]]
kanji = '私たち'
kana = 'わたしたち'
english = 'we (less formal)'
source = 'irasshai'
explain = 'https://japanese.stackexchange.com/a/36681'
tags = ['common', 'pronoun']

[[cards]]
kanji = '我々'
kana = 'われわれ'
english = 'we (more formal)'
source = 'anime'
level = 'n3'
explain = 'https://japanese.stackexchange.com/a/36681'
tags = ['anime', 'common', 'pronoun']
frequency_scores = { anime = 335, leeds = 727, novels = 839, wikipedia = 4516 }

