[[cards]]
kanji = '貴方'
kana = 'あんた'
english = 'you (familiar form of "anata")'
source = 'anime-freq'
tags = ['common', 'pronoun']
highest_frequency = 1022
highest_frequency_source = 'Anime'

[[cards]]
kanji = '俺'
kana = 'おれ'
english = 'I; me (male, rough/arrogant)'
source = 'anime'
level = 'n1'
tags = ['anime', 'common', 'pronoun']
highest_frequency = 20
highest_frequency_source = 'Anime'

[[cards]]
kanji = '貴様'
kana = 'きさま'
english = 'you bastard'
source = 'anime'
tags = ['pronoun', 'uncommon', 'uncommon-but-ive-heard-this']
highest_frequency = 224
highest_frequency_source = 'Anime'

[[cards]]
kanji = '君'
kana = 'きみ'
english = 'you; buddy; pal'
source = 'anime'
level = 'n4'
tags = ['common', 'pronoun']
highest_frequency = 30
highest_frequency_source = 'Anime'

[[cards]]
kanji = '僕'
kana = 'ぼく'
english = 'I; me (male language)'
source = 'irasshai; anime'
level = 'n4'
tags = ['anime', 'common', 'male', 'male-language', 'pronoun']
highest_frequency = 48
highest_frequency_source = 'Anime'

[[cards]]
kanji = '奴'
kana = 'やつ'
english = 'fellow; chap (derogatory)'
source = 'anime-freq'
tags = ['anime', 'common', 'derogatory', 'pronoun', 'rude']
highest_frequency = 185
highest_frequency_source = 'Anime'

[[cards]]
kanji = '私たち'
kana = 'わたしたち'
english = 'we (less formal)'
source = 'irasshai'
explain = 'https://japanese.stackexchange.com/a/36681'
tags = ['common', 'pronoun']

[[cards]]
kanji = '我々'
kana = 'われわれ'
english = 'we (more formal)'
source = 'anime'
level = 'n3'
explain = 'https://japanese.stackexchange.com/a/36681'
tags = ['anime', 'common', 'pronoun']
highest_frequency = 335
highest_frequency_source = 'Anime'

