[[cards]]
kanji = '如何'
kana = 'いかが'
english = 'how (polite)'
level = 'n5'
tags = ['adverb', 'common', 'na-adjective', 'question']
frequency_scores = { anime = 4193, leeds = 7145 }

[[cards]]
kanji = '幾つ'
kana = 'いくつ'
english = 'how many? ; how old?'
level = 'n5'
tags = ['adverb', 'common', 'question']
frequency_scores = { anime = 6597, leeds = 3842, novels = 1524 }

[[cards]]
kanji = '幾ら'
kana = 'いくら'
english = 'how much? ; how many?'
level = 'n5'
tags = ['adverb', 'common', 'noun', 'question']
frequency_scores = { anime = 10010, leeds = 5812, novels = 928 }

[[cards]]
kanji = '何時'
kana = 'いつ'
english = 'when'
level = 'n5'
tags = []
frequency_scores = { anime = 6325, leeds = 7439, novels = 282, wikipedia = 7518 }

[[cards]]
kanji = '誰'
kana = 'だれ'
english = 'who'
level = 'n5'
tags = []
frequency_scores = { anime = 56, leeds = 375, novels = 175, wikipedia = 2020 }

[[cards]]
kanji = '誰か'
kana = 'だれか'
english = 'somebody; anybody'
level = 'n5'
tags = []
frequency_scores = { anime = 1488, leeds = 2095, novels = 1034 }

[[cards]]
kanji = '如何'
kana = 'どう'
english = 'how?'
level = 'n5'
tags = []
frequency_scores = { anime = 4193, leeds = 7145, novels = 82, wikipedia = 1521 }

[[cards]]
kanji = '如何して'
kana = 'どうして'
english = 'why?'
level = 'n5'
tags = []
frequency_scores = { anime = 146, leeds = 1574, novels = 337 }

[[cards]]
kanji = '何方'
kana = 'どなた'
english = 'who? (honorific/respectful/sonkeigo)'
level = 'n5'
tags = []
frequency_scores = { anime = 19563, leeds = 5733 }

[[cards]]
kanji = 'どんな'
kana = 'どんな'
english = 'what kind of? ; like what?'
level = 'n5'
tags = []
frequency_scores = { leeds = 632, novels = 345, wikipedia = 6950 }

[[cards]]
kanji = '何故'
kana = 'なぜ'
english = 'why? (formal)'
level = 'n5'
tags = []
frequency_scores = { anime = 1618, leeds = 2423, novels = 2046, wikipedia = 4254 }

