[[cards]]
kanji = '鉛筆'
kana = 'えんぴつ'
english = 'pencil'
level = 'n5'
tags = []

[[cards]]
kanji = '科学'
kana = 'かがく'
english = 'science'
level = 'n4'
tags = ['common', 'field', 'noun']

[[cards]]
kanji = '紙'
kana = 'かみ'
english = 'paper'
level = 'n5'
tags = []

[[cards]]
kanji = '学生'
kana = 'がくせい'
english = 'student'
level = 'n5'
tags = []

[[cards]]
kanji = '学校'
kana = 'がっこう'
english = 'school'
level = 'n5'
tags = []

[[cards]]
kanji = '教科書'
kana = 'きょうかしょ'
english = 'textbook'
source = 'irasshai'
level = 'n3'
tags = ['book', 'common', 'noun', 'reading', 'school']

[[cards]]
kanji = '教室'
kana = 'きょうしつ'
english = 'classroom'
level = 'n5'
tags = []

[[cards]]
kanji = '高校'
kana = 'こうこう'
english = 'high school'
source = 'irasshai'
level = 'n4'
tags = ['common', 'grade', 'noun', 'place', 'school']

[[cards]]
kanji = '高校生'
kana = 'こうこうせい'
english = 'high school student'
source = 'irasshai'
level = 'n4'
tags = ['common', 'noun', 'people', 'school']

[[cards]]
kanji = '作文'
kana = 'さくぶん'
english = 'essay writing; composition'
level = 'n5'
tags = []

[[cards]]
kanji = '試験'
kana = 'しけん'
english = 'exam'
level = 'n4'
tags = ['common', 'noun', 'school', 'suru-verb']

[[cards]]
kanji = '仕事'
kana = 'しごと'
english = 'work; job'
level = 'n5'
tags = []

[[cards]]
kanji = '質問'
kana = 'しつもん'
english = 'question; inquiry'
level = 'n5'
tags = []

[[cards]]
kanji = '宿題'
kana = 'しゅくだい'
english = 'homework'
level = 'n5'
tags = []

[[cards]]
kanji = '小学生'
kana = 'しょうがくせい'
english = 'elementary school student'
source = 'irasshai'
level = 'n2'
tags = ['common', 'noun', 'people', 'student']

[[cards]]
kanji = '心理学'
kana = 'しんりがく'
english = 'psychology'
source = 'wanikani'
tags = ['common', 'noun', 'school', 'subject']

[[cards]]
kanji = '辞書'
kana = 'じしょ'
english = 'dictionary'
level = 'n5'
tags = []

[[cards]]
kanji = '字引'
kana = 'じびき'
english = 'dictionary (older word)'
level = 'n5'
tags = []

[[cards]]
kanji = '授業'
kana = 'じゅぎょう'
english = 'lesson; instruction; class work'
level = 'n5'
tags = []

[[cards]]
kanji = '生徒'
kana = 'せいと'
english = 'pupil'
level = 'n5'
tags = []

[[cards]]
kanji = '先生'
kana = 'せんせい'
english = 'teacher; master; doctor (honorific/respectful/sonkeigo)'
level = 'n5'
tags = []

[[cards]]
kanji = '大学'
kana = 'だいがく'
english = 'university'
level = 'n5'
tags = []

[[cards]]
kanji = '大学生'
kana = 'だいがくせい'
english = 'university student'
source = 'irasshai'
level = 'n4'
tags = ['common', 'noun', 'people', 'student']

[[cards]]
kanji = '中学'
kana = 'ちゅうがく'
english = 'middle school'
source = 'irasshai'
level = 'n3'
tags = ['common', 'noun', 'school']

[[cards]]
kanji = '中学生'
kana = 'ちゅうがくせい'
english = 'middle school student'
source = 'irasshai'
tags = ['common', 'noun', 'people', 'student']

[[cards]]
kanji = '中学生'
kana = 'ちゅうがくせい'
english = 'middle school student'
source = 'irasshai'
tags = ['common', 'noun', 'people', 'school']

[[cards]]
kanji = '中学校'
kana = 'ちゅうがっこう'
english = 'middle school'
source = 'irasshai'
level = 'n4'
tags = ['common', 'grade', 'noun', 'place', 'school']

[[cards]]
kanji = '地理'
kana = 'ちり'
english = 'geography'
source = 'wanikani'
level = 'n4'
tags = ['common', 'noun', 'school', 'subject']

[[cards]]
kanji = '机'
kana = 'つくえ'
english = 'desk'
level = 'n5'
tags = []

[[cards]]
kanji = '手紙'
kana = 'てがみ'
english = 'letter'
level = 'n5'
tags = []

[[cards]]
kanji = '図書館'
kana = 'としょかん'
english = 'library'
level = 'n5'
tags = []

[[cards]]
kanji = '夏休み'
kana = 'なつやすみ'
english = 'summer vacation'
level = 'n5'
tags = []

[[cards]]
kanji = '入試'
kana = 'にゅうし'
english = 'entrance exam'
source = 'manga'
tags = ['common']

[[cards]]
kanji = '封筒'
kana = 'ふうとう'
english = 'envelope'
level = 'n5'
tags = []

[[cards]]
kanji = '文章'
kana = 'ぶんしょう'
english = 'sentence; text; essay; prose'
level = 'n5'
tags = []

[[cards]]
kanji = '勉強'
kana = 'べんきょう'
english = 'study; diligence'
level = 'n5'
tags = []

[[cards]]
kanji = '本'
kana = 'ほん'
english = 'book'
level = 'n5'
tags = []

[[cards]]
kanji = '～枚'
kana = '～まい'
english = 'counter for flat things'
level = 'n5'
tags = []

[[cards]]
kanji = '万年筆'
kana = 'まんねんひつ'
english = 'fountain pen'
level = 'n5'
tags = []

[[cards]]
kanji = '難しい'
kana = 'むずかしい'
english = 'difficult'
level = 'n5'
tags = []

[[cards]]
kanji = '名刺'
kana = 'めいし'
english = 'business card'
level = 'n2'
tags = ['common']

[[cards]]
kanji = '問題'
kana = 'もんだい'
english = 'question (on a test); problem'
level = 'n5'
tags = []

[[cards]]
kanji = '留学'
kana = 'りゅうがく'
english = 'study abroad'
level = 'n3'
tags = ['common', 'noun', 'school', 'study', 'suru-verb']

[[cards]]
kanji = '留学生'
kana = 'りゅうがくせい'
english = 'foreign exchange student'
level = 'n5'
tags = []

[[cards]]
kanji = '練習'
kana = 'れんしゅう'
english = 'practice; practicing'
level = 'n5'
tags = []

[[cards]]
kanji = 'クラス'
kana = 'クラス'
english = 'class'
level = 'n5'
tags = []

[[cards]]
kanji = 'コピー'
kana = 'コピー'
english = 'copy (noun or verb)'
level = 'n5'
tags = []

[[cards]]
kanji = 'テスト'
kana = 'テスト'
english = 'test'
level = 'n5'
tags = []

[[cards]]
kanji = 'ノート'
kana = 'ノート'
english = 'notebook'
level = 'n5'
tags = []

[[cards]]
kanji = 'ペン'
kana = 'ペン'
english = 'pen'
level = 'n5'
tags = []

[[cards]]
kanji = 'ボールペン'
kana = 'ボールペン'
english = 'ballpoint pen'
level = 'n5'
tags = []

