[[cards]]
kanji = '医大'
kana = 'いだい'
english = 'medical university'
source = 'wanikani'
tags = ['common', 'noun', 'place', 'school']
frequency_scores = { anime = 25193 }

[[cards]]
kanji = '鉛筆'
kana = 'えんぴつ'
english = 'pencil'
level = 'n5'
tags = []
frequency_scores = { anime = 12641, leeds = 10089 }

[[cards]]
kanji = '科学'
kana = 'かがく'
english = 'science'
level = 'n4'
tags = ['common', 'field', 'noun']
frequency_scores = { anime = 2614, leeds = 635, novels = 1648, wikipedia = 497 }

[[cards]]
kanji = '紙'
kana = 'かみ'
english = 'paper'
level = 'n5'
tags = []
frequency_scores = { anime = 2201, leeds = 1189, novels = 1324, wikipedia = 1154 }

[[cards]]
kanji = '学生'
kana = 'がくせい'
english = 'student'
level = 'n5'
tags = []
frequency_scores = { anime = 1797, leeds = 627, novels = 2009, wikipedia = 818 }

[[cards]]
kanji = '学校'
kana = 'がっこう'
english = 'school'
level = 'n5'
tags = []
frequency_scores = { anime = 228, leeds = 392, novels = 544, wikipedia = 89 }

[[cards]]
kanji = '教科書'
kana = 'きょうかしょ'
english = 'textbook'
source = 'irasshai'
level = 'n3'
tags = ['book', 'common', 'noun', 'reading', 'school']
frequency_scores = { anime = 5275, leeds = 2318 }

[[cards]]
kanji = '教室'
kana = 'きょうしつ'
english = 'classroom'
level = 'n5'
tags = []
frequency_scores = { anime = 1241, leeds = 1744, novels = 1224, wikipedia = 3787 }

[[cards]]
kanji = '高校'
kana = 'こうこう'
english = 'high school'
source = 'irasshai'
level = 'n4'
tags = ['common', 'grade', 'noun', 'place', 'school']
frequency_scores = { anime = 729, leeds = 1190, novels = 2549, wikipedia = 398 }

[[cards]]
kanji = '高校生'
kana = 'こうこうせい'
english = 'high school student'
source = 'irasshai'
level = 'n4'
tags = ['common', 'noun', 'people', 'school']
frequency_scores = { anime = 1509, leeds = 2997 }

[[cards]]
kanji = '作文'
kana = 'さくぶん'
english = 'composition; writing (essay, prose, etc.)'
level = 'n5'
tags = ['noun', 'suru-verb']
frequency_scores = { anime = 12583, leeds = 7471 }

[[cards]]
kanji = '試験'
kana = 'しけん'
english = 'exam'
level = 'n4'
tags = ['common', 'noun', 'school', 'suru-verb']
frequency_scores = { anime = 730, leeds = 842, wikipedia = 682 }

[[cards]]
kanji = '質問'
kana = 'しつもん'
english = 'question; inquiry'
level = 'n5'
tags = []
frequency_scores = { anime = 1145, leeds = 443, novels = 1002, wikipedia = 4293 }

[[cards]]
kanji = '宿題'
kana = 'しゅくだい'
english = 'homework'
level = 'n5'
tags = []
frequency_scores = { anime = 2154, leeds = 5859 }

[[cards]]
kanji = '小学生'
kana = 'しょうがくせい'
english = 'elementary school student'
source = 'irasshai'
level = 'n2'
tags = ['common', 'noun', 'people', 'student']
frequency_scores = { anime = 2739, leeds = 3057, wikipedia = 5289 }

[[cards]]
kanji = '心理学'
kana = 'しんりがく'
english = 'psychology'
source = 'wanikani'
tags = ['common', 'noun', 'school', 'subject']

[[cards]]
kanji = '辞書'
kana = 'じしょ'
english = 'dictionary'
level = 'n5'
tags = []
frequency_scores = { anime = 8996, leeds = 3344, wikipedia = 8941 }

[[cards]]
kanji = '辞典'
kana = 'じてん'
english = 'dictionary, lexicon'
level = 'n4'
tags = ['common', 'grammar', 'noun', 'school']
frequency_scores = { anime = 23894, leeds = 3718, wikipedia = 6490 }

[[cards]]
kanji = '字引'
kana = 'じびき'
english = 'dictionary (older word)'
level = 'n5'
tags = []

[[cards]]
kanji = '授業'
kana = 'じゅぎょう'
english = 'lesson; instruction; class work'
level = 'n5'
tags = []
frequency_scores = { anime = 942, leeds = 927, novels = 2341, wikipedia = 3388 }

[[cards]]
kanji = '生徒'
kana = 'せいと'
english = 'pupil'
level = 'n5'
tags = []
frequency_scores = { anime = 247, leeds = 1236, novels = 612, wikipedia = 1379 }

[[cards]]
kanji = '先生'
kana = 'せんせい'
english = 'teacher; master; doctor (honorific/respectful/sonkeigo)'
level = 'n5'
tags = []
frequency_scores = { anime = 104, leeds = 294, novels = 304, wikipedia = 4323 }

[[cards]]
kanji = '卒業'
kana = 'そつぎょう'
english = 'graduation'
source = 'irasshai'
level = 'n4'
tags = ['common', 'noun', 'school', 'suru-verb']
frequency_scores = { anime = 1087, leeds = 1642, wikipedia = 243 }

[[cards]]
kanji = '卒業生'
kana = 'そつぎょうせい'
english = 'graduate; alumnus'
source = 'jisho'
tags = ['common', 'noun', 'school', 'suru-verb']
frequency_scores = { anime = 5900, leeds = 6810 }

[[cards]]
kanji = '体育'
kana = 'たいいく'
english = 'physical education'
source = 'wanikani'
level = 'n3'
tags = ['common', 'school']
frequency_scores = { anime = 3078, leeds = 5870, wikipedia = 1960 }

[[cards]]
kanji = '大学'
kana = 'だいがく'
english = 'university'
level = 'n5'
tags = []
frequency_scores = { anime = 2120, leeds = 380, novels = 1768, wikipedia = 48 }

[[cards]]
kanji = '大学生'
kana = 'だいがくせい'
english = 'university student'
source = 'irasshai'
level = 'n4'
tags = ['common', 'noun', 'people', 'student']
frequency_scores = { anime = 8288, leeds = 4180, wikipedia = 7787 }

[[cards]]
kanji = '中学'
kana = 'ちゅうがく'
english = 'middle school'
source = 'irasshai'
level = 'n3'
tags = ['common', 'noun', 'school']
frequency_scores = { anime = 1242, leeds = 2930, wikipedia = 2210 }

[[cards]]
kanji = '中学生'
kana = 'ちゅうがくせい'
english = 'middle school student'
source = 'irasshai'
tags = ['common', 'noun', 'people', 'student']
frequency_scores = { anime = 3038, leeds = 3884, wikipedia = 5069 }

[[cards]]
kanji = '中学生'
kana = 'ちゅうがくせい'
english = 'middle school student'
source = 'irasshai'
tags = ['common', 'noun', 'people', 'school']
frequency_scores = { anime = 3038, leeds = 3884, wikipedia = 5069 }

[[cards]]
kanji = '中学校'
kana = 'ちゅうがっこう'
english = 'middle school'
source = 'irasshai'
level = 'n4'
tags = ['common', 'grade', 'noun', 'place', 'school']
frequency_scores = { anime = 6194, leeds = 3906, wikipedia = 543 }

[[cards]]
kanji = '地理'
kana = 'ちり'
english = 'geography'
source = 'wanikani'
level = 'n4'
tags = ['common', 'noun', 'school', 'subject']
frequency_scores = { anime = 20588, leeds = 5696, wikipedia = 2631 }

[[cards]]
kanji = '机'
kana = 'つくえ'
english = 'desk'
level = 'n5'
tags = []
frequency_scores = { anime = 3353, leeds = 4009, novels = 1037 }

[[cards]]
kanji = '手紙'
kana = 'てがみ'
english = 'letter'
level = 'n5'
tags = []
frequency_scores = { anime = 1195, leeds = 2115, novels = 865, wikipedia = 3113 }

[[cards]]
kanji = '手帳'
kana = 'てちょう'
english = 'notebook; memo pad'
level = 'n2'
tags = ['common', 'noun', 'school']
frequency_scores = { anime = 7050, leeds = 5583 }

[[cards]]
kanji = '図書館'
kana = 'としょかん'
english = 'library'
level = 'n5'
tags = []
frequency_scores = { anime = 3888, leeds = 2053 }

[[cards]]
kanji = '夏休み'
kana = 'なつやすみ'
english = 'summer vacation'
level = 'n5'
tags = []
frequency_scores = { anime = 1493, leeds = 3966 }

[[cards]]
kanji = '入試'
kana = 'にゅうし'
english = 'entrance exam'
source = 'manga'
tags = ['common']
frequency_scores = { anime = 6790, leeds = 6029, wikipedia = 8767 }

[[cards]]
kanji = '能力'
kana = 'のうりょく'
english = 'ability'
source = 'jlpt'
level = 'n3'
tags = ['common', 'noun']
frequency_scores = { anime = 273, leeds = 729, novels = 885, wikipedia = 665 }

[[cards]]
kanji = '封筒'
kana = 'ふうとう'
english = 'envelope'
level = 'n5'
tags = []
frequency_scores = { anime = 10636, leeds = 9619 }

[[cards]]
kanji = '文章'
kana = 'ぶんしょう'
english = 'sentence; text; essay; prose'
level = 'n5'
tags = []
frequency_scores = { anime = 5871, leeds = 1057, wikipedia = 3868 }

[[cards]]
kanji = '勉強'
kana = 'べんきょう'
english = 'study; diligence'
level = 'n5'
tags = []
frequency_scores = { anime = 541, leeds = 602, novels = 1990, wikipedia = 4728 }

[[cards]]
kanji = '～枚'
kana = '～まい'
english = 'counter for flat things'
level = 'n5'
tags = []

[[cards]]
kanji = '万年筆'
kana = 'まんねんひつ'
english = 'fountain pen'
level = 'n5'
tags = []
frequency_scores = { anime = 30696 }

[[cards]]
kanji = '難しい'
kana = 'むずかしい'
english = 'difficult'
level = 'n5'
tags = []
frequency_scores = { anime = 733, leeds = 607, novels = 1991, wikipedia = 2225 }

[[cards]]
kanji = '問題'
kana = 'もんだい'
english = 'question (on a test); problem'
level = 'n5'
tags = []
frequency_scores = { anime = 253, leeds = 121, novels = 378, wikipedia = 202 }

[[cards]]
kanji = '留学'
kana = 'りゅうがく'
english = 'study abroad'
level = 'n3'
tags = ['common', 'noun', 'school', 'study', 'suru-verb']
frequency_scores = { anime = 8812, leeds = 2352, wikipedia = 2090 }

[[cards]]
kanji = '留学生'
kana = 'りゅうがくせい'
english = 'foreign exchange student'
level = 'n5'
tags = []
frequency_scores = { anime = 12296, leeds = 4976 }

[[cards]]
kanji = '練習'
kana = 'れんしゅう'
english = 'practice; practicing'
level = 'n5'
tags = []
frequency_scores = { anime = 442, leeds = 1005, wikipedia = 1849 }

[[cards]]
kanji = 'クラス'
kana = 'クラス'
english = 'class'
level = 'n5'
tags = []
frequency_scores = { anime = 516, leeds = 1263, novels = 1688, wikipedia = 824 }

[[cards]]
kanji = 'コピー'
kana = 'コピー'
english = 'copy (noun or verb)'
level = 'n5'
tags = []
frequency_scores = { anime = 3633, leeds = 1957, wikipedia = 2782 }

[[cards]]
kanji = 'テスト'
kana = 'テスト'
english = 'test'
level = 'n5'
tags = []
frequency_scores = { anime = 953, leeds = 1427, wikipedia = 1848 }

[[cards]]
kanji = 'ノート'
kana = 'ノート'
english = 'notebook'
level = 'n5'
tags = []
frequency_scores = { anime = 1218, leeds = 2425, wikipedia = 5506 }

[[cards]]
kanji = 'ペン'
kana = 'ペン'
english = 'pen'
level = 'n5'
tags = []
frequency_scores = { anime = 2256, leeds = 4369, wikipedia = 5497 }

[[cards]]
kanji = 'ボールペン'
kana = 'ボールペン'
english = 'ballpoint pen'
level = 'n5'
tags = []
frequency_scores = { anime = 16913, leeds = 14166 }

