[[cards]]
kanji = '医大'
kana = 'いだい'
english = 'medical university'
source = 'wanikani'
tags = ['common', 'noun', 'place', 'school']
highest_frequency = 25193
highest_frequency_source = 'Anime'

[[cards]]
kanji = '鉛筆'
kana = 'えんぴつ'
english = 'pencil'
level = 'n5'
tags = []
highest_frequency = 10089
highest_frequency_source = 'Leeds'

[[cards]]
kanji = '科学'
kana = 'かがく'
english = 'science'
level = 'n4'
tags = ['common', 'field', 'noun']
highest_frequency = 497
highest_frequency_source = 'Wikipedia'

[[cards]]
kanji = '紙'
kana = 'かみ'
english = 'paper'
level = 'n5'
tags = []
highest_frequency = 1154
highest_frequency_source = 'Wikipedia'

[[cards]]
kanji = '学生'
kana = 'がくせい'
english = 'student'
level = 'n5'
tags = []
highest_frequency = 627
highest_frequency_source = 'Leeds'

[[cards]]
kanji = '学校'
kana = 'がっこう'
english = 'school'
level = 'n5'
tags = []
highest_frequency = 89
highest_frequency_source = 'Wikipedia'

[[cards]]
kanji = '教科書'
kana = 'きょうかしょ'
english = 'textbook'
source = 'irasshai'
level = 'n3'
tags = ['book', 'common', 'noun', 'reading', 'school']
highest_frequency = 2318
highest_frequency_source = 'Leeds'

[[cards]]
kanji = '教室'
kana = 'きょうしつ'
english = 'classroom'
level = 'n5'
tags = []
highest_frequency = 1224
highest_frequency_source = 'Novels'

[[cards]]
kanji = '高校'
kana = 'こうこう'
english = 'high school'
source = 'irasshai'
level = 'n4'
tags = ['common', 'grade', 'noun', 'place', 'school']
highest_frequency = 398
highest_frequency_source = 'Wikipedia'

[[cards]]
kanji = '高校生'
kana = 'こうこうせい'
english = 'high school student'
source = 'irasshai'
level = 'n4'
tags = ['common', 'noun', 'people', 'school']
highest_frequency = 1509
highest_frequency_source = 'Anime'

[[cards]]
kanji = '作文'
kana = 'さくぶん'
english = 'composition; writing (essay, prose, etc.)'
level = 'n5'
tags = ['noun', 'suru-verb']
highest_frequency = 7471
highest_frequency_source = 'Leeds'

[[cards]]
kanji = '試験'
kana = 'しけん'
english = 'exam'
level = 'n4'
tags = ['common', 'noun', 'school', 'suru-verb']
highest_frequency = 682
highest_frequency_source = 'Wikipedia'

[[cards]]
kanji = '質問'
kana = 'しつもん'
english = 'question; inquiry'
level = 'n5'
tags = []
highest_frequency = 443
highest_frequency_source = 'Leeds'

[[cards]]
kanji = '宿題'
kana = 'しゅくだい'
english = 'homework'
level = 'n5'
tags = []
highest_frequency = 2154
highest_frequency_source = 'Anime'

[[cards]]
kanji = '小学生'
kana = 'しょうがくせい'
english = 'elementary school student'
source = 'irasshai'
level = 'n2'
tags = ['common', 'noun', 'people', 'student']
highest_frequency = 2739
highest_frequency_source = 'Anime'

[[cards]]
kanji = '心理学'
kana = 'しんりがく'
english = 'psychology'
source = 'wanikani'
tags = ['common', 'noun', 'school', 'subject']

[[cards]]
kanji = '辞書'
kana = 'じしょ'
english = 'dictionary'
level = 'n5'
tags = []
highest_frequency = 3344
highest_frequency_source = 'Leeds'

[[cards]]
kanji = '辞典'
kana = 'じてん'
english = 'dictionary, lexicon'
level = 'n4'
tags = ['common', 'grammar', 'noun', 'school']
highest_frequency = 3718
highest_frequency_source = 'Leeds'

[[cards]]
kanji = '字引'
kana = 'じびき'
english = 'dictionary (older word)'
level = 'n5'
tags = []

[[cards]]
kanji = '授業'
kana = 'じゅぎょう'
english = 'lesson; instruction; class work'
level = 'n5'
tags = []
highest_frequency = 927
highest_frequency_source = 'Leeds'

[[cards]]
kanji = '生徒'
kana = 'せいと'
english = 'pupil'
level = 'n5'
tags = []
highest_frequency = 247
highest_frequency_source = 'Anime'

[[cards]]
kanji = '先生'
kana = 'せんせい'
english = 'teacher; master; doctor (honorific/respectful/sonkeigo)'
level = 'n5'
tags = []
highest_frequency = 104
highest_frequency_source = 'Anime'

[[cards]]
kanji = '卒業'
kana = 'そつぎょう'
english = 'graduation'
source = 'irasshai'
level = 'n4'
tags = ['common', 'noun', 'school', 'suru-verb']
highest_frequency = 243
highest_frequency_source = 'Wikipedia'

[[cards]]
kanji = '卒業生'
kana = 'そつぎょうせい'
english = 'graduate; alumnus'
source = 'jisho'
tags = ['common', 'noun', 'school', 'suru-verb']
highest_frequency = 5900
highest_frequency_source = 'Anime'

[[cards]]
kanji = '体育'
kana = 'たいいく'
english = 'physical education'
source = 'wanikani'
level = 'n3'
tags = ['common', 'school']
highest_frequency = 1960
highest_frequency_source = 'Wikipedia'

[[cards]]
kanji = '大学'
kana = 'だいがく'
english = 'university'
level = 'n5'
tags = []
highest_frequency = 48
highest_frequency_source = 'Wikipedia'

[[cards]]
kanji = '大学生'
kana = 'だいがくせい'
english = 'university student'
source = 'irasshai'
level = 'n4'
tags = ['common', 'noun', 'people', 'student']
highest_frequency = 4180
highest_frequency_source = 'Leeds'

[[cards]]
kanji = '中学'
kana = 'ちゅうがく'
english = 'middle school'
source = 'irasshai'
level = 'n3'
tags = ['common', 'noun', 'school']
highest_frequency = 1242
highest_frequency_source = 'Anime'

[[cards]]
kanji = '中学生'
kana = 'ちゅうがくせい'
english = 'middle school student'
source = 'irasshai'
tags = ['common', 'noun', 'people', 'student']
highest_frequency = 3038
highest_frequency_source = 'Anime'

[[cards]]
kanji = '中学生'
kana = 'ちゅうがくせい'
english = 'middle school student'
source = 'irasshai'
tags = ['common', 'noun', 'people', 'school']
highest_frequency = 3038
highest_frequency_source = 'Anime'

[[cards]]
kanji = '中学校'
kana = 'ちゅうがっこう'
english = 'middle school'
source = 'irasshai'
level = 'n4'
tags = ['common', 'grade', 'noun', 'place', 'school']
highest_frequency = 543
highest_frequency_source = 'Wikipedia'

[[cards]]
kanji = '地理'
kana = 'ちり'
english = 'geography'
source = 'wanikani'
level = 'n4'
tags = ['common', 'noun', 'school', 'subject']
highest_frequency = 2631
highest_frequency_source = 'Wikipedia'

[[cards]]
kanji = '机'
kana = 'つくえ'
english = 'desk'
level = 'n5'
tags = []
highest_frequency = 1037
highest_frequency_source = 'Novels'

[[cards]]
kanji = '手紙'
kana = 'てがみ'
english = 'letter'
level = 'n5'
tags = []
highest_frequency = 865
highest_frequency_source = 'Novels'

[[cards]]
kanji = '手帳'
kana = 'てちょう'
english = 'notebook; memo pad'
level = 'n2'
tags = ['common', 'noun', 'school']
highest_frequency = 5583
highest_frequency_source = 'Leeds'

[[cards]]
kanji = '図書館'
kana = 'としょかん'
english = 'library'
level = 'n5'
tags = []
highest_frequency = 2053
highest_frequency_source = 'Leeds'

[[cards]]
kanji = '夏休み'
kana = 'なつやすみ'
english = 'summer vacation'
level = 'n5'
tags = []
highest_frequency = 1493
highest_frequency_source = 'Anime'

[[cards]]
kanji = '入試'
kana = 'にゅうし'
english = 'entrance exam'
source = 'manga'
tags = ['common']
highest_frequency = 6029
highest_frequency_source = 'Leeds'

[[cards]]
kanji = '能力'
kana = 'のうりょく'
english = 'ability'
source = 'jlpt'
level = 'n3'
tags = ['common', 'noun']
highest_frequency = 273
highest_frequency_source = 'Anime'

[[cards]]
kanji = '封筒'
kana = 'ふうとう'
english = 'envelope'
level = 'n5'
tags = []
highest_frequency = 9619
highest_frequency_source = 'Leeds'

[[cards]]
kanji = '文章'
kana = 'ぶんしょう'
english = 'sentence; text; essay; prose'
level = 'n5'
tags = []
highest_frequency = 1057
highest_frequency_source = 'Leeds'

[[cards]]
kanji = '勉強'
kana = 'べんきょう'
english = 'study; diligence'
level = 'n5'
tags = []
highest_frequency = 541
highest_frequency_source = 'Anime'

[[cards]]
kanji = '～枚'
kana = '～まい'
english = 'counter for flat things'
level = 'n5'
tags = []

[[cards]]
kanji = '万年筆'
kana = 'まんねんひつ'
english = 'fountain pen'
level = 'n5'
tags = []
highest_frequency = 30696
highest_frequency_source = 'Anime'

[[cards]]
kanji = '難しい'
kana = 'むずかしい'
english = 'difficult'
level = 'n5'
tags = []
highest_frequency = 607
highest_frequency_source = 'Leeds'

[[cards]]
kanji = '問題'
kana = 'もんだい'
english = 'question (on a test); problem'
level = 'n5'
tags = []
highest_frequency = 121
highest_frequency_source = 'Leeds'

[[cards]]
kanji = '留学'
kana = 'りゅうがく'
english = 'study abroad'
level = 'n3'
tags = ['common', 'noun', 'school', 'study', 'suru-verb']
highest_frequency = 2090
highest_frequency_source = 'Wikipedia'

[[cards]]
kanji = '留学生'
kana = 'りゅうがくせい'
english = 'foreign exchange student'
level = 'n5'
tags = []
highest_frequency = 4976
highest_frequency_source = 'Leeds'

[[cards]]
kanji = '練習'
kana = 'れんしゅう'
english = 'practice; practicing'
level = 'n5'
tags = []
highest_frequency = 442
highest_frequency_source = 'Anime'

[[cards]]
kanji = 'クラス'
kana = 'クラス'
english = 'class'
level = 'n5'
tags = []
highest_frequency = 516
highest_frequency_source = 'Anime'

[[cards]]
kanji = 'コピー'
kana = 'コピー'
english = 'copy (noun or verb)'
level = 'n5'
tags = []
highest_frequency = 1957
highest_frequency_source = 'Leeds'

[[cards]]
kanji = 'テスト'
kana = 'テスト'
english = 'test'
level = 'n5'
tags = []
highest_frequency = 953
highest_frequency_source = 'Anime'

[[cards]]
kanji = 'ノート'
kana = 'ノート'
english = 'notebook'
level = 'n5'
tags = []
highest_frequency = 1218
highest_frequency_source = 'Anime'

[[cards]]
kanji = 'ペン'
kana = 'ペン'
english = 'pen'
level = 'n5'
tags = []
highest_frequency = 2256
highest_frequency_source = 'Anime'

[[cards]]
kanji = 'ボールペン'
kana = 'ボールペン'
english = 'ballpoint pen'
level = 'n5'
tags = []
highest_frequency = 14166
highest_frequency_source = 'Leeds'

