[[cards]]
kanji = '実験'
kana = 'じっけん'
english = 'experiment'
source = 'wanikani'
level = 'n3'
tags = ['common', 'noun', 'suru-verb']
frequency_scores = { anime = 1268, leeds = 1286, novels = 2578, wikipedia = 1053 }

