[[cards]]
kanji = 'めっちゃ'
kana = 'めっちゃ'
english = 'very (Osaka/Kansai hougen)'
source = 'wanikani; anime'
explain = 'https://www.italki.com/question/75853'
tags = ['anime', 'hougen', 'kansai', 'osaka', 'slang', 'uncommon']
frequency_scores = { anime = 3274, leeds = 10165 }

