[[cards]]
kanji = '機関'
kana = 'きかん'
english = 'engine'
level = 'n3'
tags = ['cars', 'common', 'physics', 'technology', 'vehicles']
frequency_scores = { anime = 1762, leeds = 662, novels = 2359, wikipedia = 248 }

[[cards]]
kanji = '汽車'
kana = 'きしゃ'
english = 'train (long distance); steam train (original meaning)'
level = 'n4'
tags = ['common', 'noun', 'train', 'transportation']
frequency_scores = { anime = 22387, leeds = 13506, wikipedia = 8985 }

[[cards]]
kanji = '携帯'
kana = 'けいたい'
english = 'mobile phone'
level = 'n1'
tags = ['common', 'no-adjective', 'noun', 'suru-verb']
frequency_scores = { anime = 747, leeds = 868, wikipedia = 1607 }

[[cards]]
kanji = '自動車'
kana = 'じどうしゃ'
english = 'automobile'
level = 'n5'
tags = []
frequency_scores = { anime = 14592, leeds = 1674, wikipedia = 452 }

[[cards]]
kanji = '地下鉄'
kana = 'ちかてつ'
english = 'underground train; subway'
level = 'n5'
tags = ['common', 'transportation']
frequency_scores = { anime = 10372, leeds = 4000, wikipedia = 1865 }

[[cards]]
kanji = '電気'
kana = 'でんき'
english = 'electricity'
level = 'n5'
tags = []
frequency_scores = { anime = 3087, leeds = 1605, novels = 2643, wikipedia = 717 }

[[cards]]
kanji = '電車'
kana = 'でんしゃ'
english = 'electric train'
level = 'n5'
tags = []
frequency_scores = { anime = 2206, leeds = 1589, novels = 2361, wikipedia = 768 }

[[cards]]
kanji = '電卓'
kana = 'でんたく'
english = 'calculator'
source = 'wanikani'
tags = ['common']
frequency_scores = { anime = 33868 }

[[cards]]
kanji = '電池'
kana = 'でんち'
english = 'battery'
source = 'wanikani'
level = 'n2'
tags = ['common', 'electronics', 'noun']
frequency_scores = { anime = 8984, leeds = 5007, wikipedia = 4807 }

[[cards]]
kanji = '電灯'
kana = 'でんとう'
english = 'electric light'
source = 'wiktionary'
level = 'n4'
tags = ['common', 'light', 'noun']
frequency_scores = { anime = 12158, leeds = 12133 }

[[cards]]
kanji = '電報'
kana = 'でんぽう'
english = 'telegram'
source = 'wiktionary'
level = 'n4'
tags = ['common', 'communication', 'noun', 'old']
frequency_scores = { anime = 25467, leeds = 14748, wikipedia = 8381 }

[[cards]]
kanji = '電話'
kana = 'でんわ'
english = 'telephone; telephone call'
level = 'n5'
tags = []
frequency_scores = { anime = 497, leeds = 395, novels = 474, wikipedia = 942 }

[[cards]]
kanji = '飛行機'
kana = 'ひこうき'
english = 'airplane'
level = 'n5'
tags = []
frequency_scores = { anime = 3683, leeds = 2370, wikipedia = 3765 }

[[cards]]
kanji = '無線'
kana = 'むせん'
english = 'wireless; radio'
level = 'n1'
tags = ['common']
frequency_scores = { anime = 6220, leeds = 3839, novels = 2464, wikipedia = 2450 }

