[[cards]]
kanji = '機関'
kana = 'きかん'
english = 'engine'
level = 'n3'
tags = ['cars', 'common', 'physics', 'technology', 'vehicles']
highest_frequency = 248
highest_frequency_source = 'Wikipedia 10k'

[[cards]]
kanji = '汽車'
kana = 'きしゃ'
english = 'train (long distance); steam train (original meaning)'
level = 'n4'
tags = ['common', 'noun', 'train', 'transportation']
highest_frequency = 8985
highest_frequency_source = 'Wikipedia 10k'

[[cards]]
kanji = '携帯'
kana = 'けいたい'
english = 'mobile phone'
level = 'n1'
tags = ['common', 'no-adjective', 'noun', 'suru-verb']
highest_frequency = 747
highest_frequency_source = 'Anime 45k'

[[cards]]
kanji = '自動車'
kana = 'じどうしゃ'
english = 'automobile'
level = 'n5'
tags = []
highest_frequency = 452
highest_frequency_source = 'Wikipedia 10k'

[[cards]]
kanji = '地下鉄'
kana = 'ちかてつ'
english = 'underground train; subway'
level = 'n5'
tags = ['common', 'transportation']
highest_frequency = 1865
highest_frequency_source = 'Wikipedia 10k'

[[cards]]
kanji = '電気'
kana = 'でんき'
english = 'electricity'
level = 'n5'
tags = []
highest_frequency = 717
highest_frequency_source = 'Wikipedia 10k'

[[cards]]
kanji = '電車'
kana = 'でんしゃ'
english = 'electric train'
level = 'n5'
tags = []
highest_frequency = 768
highest_frequency_source = 'Wikipedia 10k'

[[cards]]
kanji = '電卓'
kana = 'でんたく'
english = 'calculator'
source = 'wanikani'
tags = ['common']
highest_frequency = 33868
highest_frequency_source = 'Anime 45k'

[[cards]]
kanji = '電池'
kana = 'でんち'
english = 'battery'
source = 'wanikani'
level = 'n2'
tags = ['common', 'electronics', 'noun']
highest_frequency = 4807
highest_frequency_source = 'Wikipedia 10k'

[[cards]]
kanji = '電話'
kana = 'でんわ'
english = 'telephone; telephone call'
level = 'n5'
tags = []
highest_frequency = 395
highest_frequency_source = 'Leeds 15k'

[[cards]]
kanji = '飛行機'
kana = 'ひこうき'
english = 'airplane'
level = 'n5'
tags = []
highest_frequency = 2370
highest_frequency_source = 'Leeds 15k'

[[cards]]
kanji = '無線'
kana = 'むせん'
english = 'wireless; radio'
level = 'n1'
tags = ['common']
highest_frequency = 2450
highest_frequency_source = 'Wikipedia 10k'

