[[cards]]
kanji = '秋'
kana = 'あき'
english = 'autumn; fall'
level = 'n5'
tags = ['common', 'noun', 'season', 'time']
frequency_scores = { anime = 1768, leeds = 1904, novels = 1941, wikipedia = 804 }

[[cards]]
kanji = '朝'
kana = 'あさ'
english = 'morning'
level = 'n5'
tags = ['common', 'time']
frequency_scores = { anime = 456, leeds = 581, novels = 626, wikipedia = 358 }

[[cards]]
kanji = '明後日'
kana = 'あさって'
english = 'day after tomorrow'
level = 'n5'
tags = ['common', 'time']
frequency_scores = { anime = 7488, leeds = 11290 }

[[cards]]
kanji = '明日'
kana = 'あした'
english = 'tomorrow'
level = 'n5'
tags = ['common', 'time']
frequency_scores = { anime = 205, leeds = 746, novels = 875, wikipedia = 5183 }

[[cards]]
kanji = '後'
kana = 'あと'
english = 'after; in the future'
level = 'n5'
tags = ['common', 'places']
frequency_scores = { anime = 190, leeds = 198, novels = 216, wikipedia = 50 }

[[cards]]
kanji = '以後'
kana = 'いご'
english = 'from now on; hereafter'
source = 'wanikani'
level = 'n2'
tags = ['common', 'temporal-noun']
frequency_scores = { anime = 5947, leeds = 4013, wikipedia = 758 }

[[cards]]
kanji = '一日'
kana = 'いちにち'
english = 'one day (duration)'
level = 'n5'
tags = ['common', 'duration', 'time']

[[cards]]
kanji = '五日'
kana = 'いつか'
english = 'five days; fifth day of the month'
level = 'n5'
tags = []
frequency_scores = { anime = 531, leeds = 3852, novels = 2196 }

[[cards]]
kanji = '何時も'
kana = 'いつも'
english = 'always'
level = 'n5'
tags = []
frequency_scores = { anime = 20544, leeds = 466, novels = 298, wikipedia = 6007 }

[[cards]]
kanji = '今'
kana = 'いま'
english = 'now'
level = 'n5'
tags = []
frequency_scores = { anime = 38, leeds = 130, novels = 107, wikipedia = 1084 }

[[cards]]
kanji = '一昨日'
kana = 'おととい'
english = 'day before yesterday'
level = 'n5'
tags = []
frequency_scores = { anime = 8970, leeds = 7223 }

[[cards]]
kanji = '一昨年'
kana = 'おととし'
english = 'year before last'
level = 'n5'
tags = []
frequency_scores = { anime = 13051, leeds = 7565 }

[[cards]]
kanji = '開始'
kana = 'かいし'
english = 'start (literary?)'
source = 'wanikani; frequency'
level = 'n3'
tags = ['common', 'noun', 'suru-verb']
frequency_scores = { anime = 956, leeds = 952, novels = 2218, wikipedia = 151 }

[[cards]]
kanji = '～か月'
kana = '～かげつ'
english = 'counter for number of months'
level = 'n5'
tags = []

[[cards]]
kanji = '火曜日'
kana = 'かようび'
english = 'Tuesday'
level = 'n5'
tags = []
frequency_scores = { anime = 22571, leeds = 5083, wikipedia = 7872 }

[[cards]]
kanji = '～月'
kana = '～がつ'
english = 'month of the year'
level = 'n5'
tags = []

[[cards]]
kanji = '季節'
kana = 'きせつ'
english = 'season; time of year'
level = 'n4'
source = 'wanikani'
tags = ['common', 'no-adjective', 'noun', 'seasons']
frequency_scores = { anime = 2803, leeds = 2035, wikipedia = 4736 }

[[cards]]
kanji = '昨日'
kana = 'きのう'
english = 'yesterday'
level = 'n5'
tags = []
frequency_scores = { anime = 329, leeds = 512, novels = 930 }

[[cards]]
kanji = '今日'
kana = 'きょう'
english = 'today'
level = 'n5'
tags = []
frequency_scores = { anime = 73, leeds = 194, novels = 292, wikipedia = 1341 }

[[cards]]
kanji = '去年'
kana = 'きょねん'
english = 'last year'
level = 'n5'
tags = []
frequency_scores = { anime = 1757, leeds = 2118, novels = 2413 }

[[cards]]
kanji = '近日'
kana = 'きんじつ'
english = 'in a few days; soon'
source = 'wanikani'
tags = ['adverbial-noun', 'common', 'temporal-noun', 'time']
frequency_scores = { anime = 19263, leeds = 12973 }

[[cards]]
kanji = '近年'
kana = 'きんねん'
english = 'recent years'
source = 'wanikani'
tags = ['adverbial-noun', 'common', 'temporal-noun', 'time']
frequency_scores = { anime = 17594, leeds = 3840, wikipedia = 892 }

[[cards]]
kanji = '金曜日'
kana = 'きんようび'
english = 'Friday'
level = 'n5'
tags = []
frequency_scores = { anime = 15551, leeds = 3535, wikipedia = 3974 }

[[cards]]
kanji = '今朝'
kana = 'けさ'
english = 'this morning'
level = 'n5'
tags = []
frequency_scores = { anime = 2296, leeds = 3246, novels = 2682 }

[[cards]]
kanji = '月末'
kana = 'げつまつ'
english = 'end of the month'
source = 'wanikani'
level = 'n2'
tags = ['adverbial-noun', 'common', 'temporal-noun']
frequency_scores = { anime = 22588, leeds = 11098 }

[[cards]]
kanji = '月曜日'
kana = 'げつようび'
english = 'Monday'
level = 'n5'
tags = []
frequency_scores = { anime = 6809, leeds = 3880, wikipedia = 5281 }

[[cards]]
kanji = '現在'
kana = 'げんざい'
english = 'present time'
source = 'wikipedia 10k frequent'
level = 'n3'
tags = ['adverbial-noun', 'common', 'temporal-noun']
frequency_scores = { anime = 1090, leeds = 249, novels = 1075, wikipedia = 49 }

[[cards]]
kanji = '九日'
kana = 'ここのか'
english = 'the ninth of the month; nine days'
level = 'n5'
tags = []

[[cards]]
kanji = '今年'
kana = 'ことし'
english = 'this year'
level = 'n5'
tags = []
frequency_scores = { anime = 918, leeds = 537, novels = 2603 }

[[cards]]
kanji = '古来'
kana = 'こらい'
english = 'ancient; from time immemorial'
source = 'wanikani'
tags = ['adverb', 'common', 'no-adjective', 'noun', 'time']
frequency_scores = { anime = 13447, leeds = 11040, wikipedia = 7798 }

[[cards]]
kanji = '今回'
kana = 'こんかい'
english = 'this time; lately'
level = 'n3'
explain = 'https://japanese.stackexchange.com/a/52295'
tags = ['adverbial-noun', 'anime', 'common', 'temporal-noun']
frequency_scores = { anime = 387, leeds = 265, novels = 1589, wikipedia = 4395 }

[[cards]]
kanji = '今月'
kana = 'こんげつ'
english = 'this month'
level = 'n5'
tags = []
frequency_scores = { anime = 4781, leeds = 2758 }

[[cards]]
kanji = '今週'
kana = 'こんしゅう'
english = 'this week'
level = 'n5'
tags = []
frequency_scores = { anime = 3882, leeds = 1906 }

[[cards]]
kanji = '今度'
kana = 'こんど'
english = 'this time (or next time)'
source = 'anime'
level = 'n4'
explain = 'https://japanese.stackexchange.com/a/52295'
tags = ['adverbial-noun', 'common', 'temporal-noun']
frequency_scores = { anime = 280, leeds = 903, novels = 422, wikipedia = 5070 }

[[cards]]
kanji = '今晩'
kana = 'こんばん'
english = 'tonight; this evening (7-10pmish)'
level = 'n5'
tags = []
frequency_scores = { anime = 5611, leeds = 8450 }

[[cards]]
kanji = '今夜'
kana = 'こんや'
english = 'tonight (more formal / in writing)'
source = 'nihongo-charenji-n4-kotoba'
level = 'n4'
tags = ['common']
frequency_scores = { anime = 1292, leeds = 4422, novels = 1193 }

[[cards]]
kanji = '午後'
kana = 'ごご'
english = 'afternoon; P.M.'
level = 'n5'
tags = []
frequency_scores = { anime = 2525, leeds = 893, novels = 1464, wikipedia = 2258 }

[[cards]]
kanji = '午前'
kana = 'ごぜん'
english = 'morning; A.M.'
level = 'n5'
tags = []
frequency_scores = { anime = 4625, leeds = 1266, wikipedia = 2419 }

[[cards]]
kanji = '最近'
kana = 'さいきん'
english = 'recently'
level = 'n4'
tags = ['adverbial-noun', 'common', 'no-adjective', 'temporal-noun']
frequency_scores = { anime = 424, leeds = 285, novels = 1521, wikipedia = 2208 }

[[cards]]
kanji = '先'
kana = 'さき'
english = 'the previous; the former; the future'
level = 'n5'
tags = []
frequency_scores = { anime = 155, leeds = 374, novels = 240, wikipedia = 558 }

[[cards]]
kanji = 'さ来月'
kana = 'さらいげつ'
english = 'month after next'
source = 'n4 wiktionary'
level = 'n4'
tags = ['adverbial-noun', 'common', 'temporal-noun', 'time']

[[cards]]
kanji = '再来週'
kana = 'さらいしゅう'
english = 'week after next'
source = 'irasshai'
level = 'n4'
tags = ['adverbial-noun', 'common', 'temporal-noun', 'time']
frequency_scores = { anime = 16679 }

[[cards]]
kanji = '再来週'
kana = 'さらいしゅう'
english = 'week after next'
source = 'irasshai'
level = 'n4'
tags = ['adverbial-noun', 'common', 'temporal-noun']
frequency_scores = { anime = 16679 }

[[cards]]
kanji = '再来年'
kana = 'さらいねん'
english = 'year after next'
level = 'n5'
tags = []
frequency_scores = { anime = 19580 }

[[cards]]
kanji = '～週間'
kana = '～しゅうかん'
english = 'counter for weeks'
level = 'n5'
tags = []

[[cards]]
kanji = '週末'
kana = 'しゅうまつ'
english = 'weekend'
source = 'irasshai'
tags = ['common', 'week']
frequency_scores = { anime = 7094, leeds = 2813 }

[[cards]]
kanji = '醤油'
kana = 'しょうゆ'
english = 'soy sauce'
level = 'n5'
tags = []
frequency_scores = { anime = 5689, leeds = 6746, wikipedia = 9353 }

[[cards]]
kanji = '将来'
kana = 'しょうらい'
english = 'future (usually near); prospects'
source = 'irasshai?'
level = 'n4'
tags = ['common']
frequency_scores = { anime = 2123, leeds = 966, wikipedia = 2389 }

[[cards]]
kanji = '～時'
kana = '～じ'
english = "hour; o'clock"
level = 'n5'
tags = []

[[cards]]
kanji = '次回'
kana = 'じかい'
english = 'next time'
source = 'wanikani'
tags = ['adverbial-noun', 'common', 'temporal-noun']
frequency_scores = { anime = 364, leeds = 2152, wikipedia = 7786 }

[[cards]]
kanji = '時間'
kana = 'じかん'
english = 'time'
level = 'n5'
tags = []
frequency_scores = { anime = 107, leeds = 154, novels = 208, wikipedia = 142 }

[[cards]]
kanji = '～時間'
kana = '～じかん'
english = 'counter for hours'
level = 'n5'
tags = []

[[cards]]
kanji = '～中'
kana = '～じゅう'
english = 'during; while'
level = 'n5'
tags = []

[[cards]]
kanji = '水曜日'
kana = 'すいようび'
english = 'Wednesday'
level = 'n5'
tags = []
frequency_scores = { anime = 23066, leeds = 5361, wikipedia = 7967 }

[[cards]]
kanji = '直ぐ'
kana = 'すぐ'
english = 'soon; immediately'
level = 'n5'
tags = []
frequency_scores = { anime = 19545, leeds = 13771, novels = 182, wikipedia = 1232 }

[[cards]]
kanji = '直ぐに'
kana = 'すぐに'
english = 'immediately'
source = 'n4-study'
level = 'n5'
tags = ['adverb', 'common']
frequency_scores = { anime = 36192, leeds = 10196 }

[[cards]]
kanji = '先月'
kana = 'せんげつ'
english = 'last month'
level = 'n5'
tags = []
frequency_scores = { anime = 7594, leeds = 5010 }

[[cards]]
kanji = '先週'
kana = 'せんしゅう'
english = 'last week'
level = 'n5'
tags = []
frequency_scores = { anime = 4357, leeds = 2319 }

[[cards]]
kanji = '先日'
kana = 'せんじつ'
english = 'the other day (a recent day)'
level = 'n3'
tags = ['adverbial-noun', 'common', 'noun', 'temporal-noun', 'time']
frequency_scores = { anime = 2740, leeds = 1209 }

[[cards]]
kanji = '誕生日'
kana = 'たんじょうび'
english = 'birthday'
level = 'n5'
tags = []
frequency_scores = { wikipedia = 5299 }

[[cards]]
kanji = '一日'
kana = 'ついたち'
english = 'first day of the month'
level = 'n5'
tags = []

[[cards]]
kanji = '十日'
kana = 'とおか'
english = 'tenth day of the month; ten days'
level = 'n5'
tags = []

[[cards]]
kanji = '～時'
kana = '～とき'
english = 'at the time of ～'
level = 'n5'
tags = []

[[cards]]
kanji = '時々'
kana = 'ときどき'
english = 'sometimes; at times'
level = 'n5'
tags = []
frequency_scores = { anime = 2529, leeds = 2631, novels = 2100, wikipedia = 7992 }

[[cards]]
kanji = '時計'
kana = 'とけい'
english = 'watch; clock'
level = 'n5'
tags = []
frequency_scores = { anime = 3541, leeds = 2797, novels = 1756, wikipedia = 3775 }

[[cards]]
kanji = '年'
kana = 'とし'
english = 'year'
level = 'n5'
tags = []
frequency_scores = { anime = 121, leeds = 54, novels = 165, wikipedia = 18 }

[[cards]]
kanji = '同時'
kana = 'どうじ'
english = 'same time; concurrent'
source = 'wanikani'
level = 'n3'
tags = ['common', 'no-adjective', 'noun']
frequency_scores = { anime = 6595, leeds = 3895, wikipedia = 1710 }

[[cards]]
kanji = '土曜日'
kana = 'どようび'
english = 'Saturday'
level = 'n5'
tags = []
frequency_scores = { anime = 7648, leeds = 2947, wikipedia = 3588 }

[[cards]]
kanji = '夏'
kana = 'なつ'
english = 'summer'
level = 'n5'
tags = []
frequency_scores = { anime = 459, leeds = 880, novels = 1194, wikipedia = 540 }

[[cards]]
kanji = '七日'
kana = 'なのか'
english = 'seventh day of the month ; seven days'
level = 'n5'
tags = []

[[cards]]
kanji = '～日'
kana = '～にち'
english = '～ day of the month; duration in days'
level = 'n5'
tags = []

[[cards]]
kanji = '日曜日'
kana = 'にちようび'
english = 'Sunday'
level = 'n5'
tags = []
frequency_scores = { anime = 6044, leeds = 2682, wikipedia = 3627 }

[[cards]]
kanji = '～年'
kana = '～ねん'
english = 'counter for years'
level = 'n5'
tags = []

[[cards]]
kanji = '年中'
kana = 'ねんじゅう'
english = 'throughout the year; year round'
level = 'n3'
source = 'wanikani'
tags = ['adverb', 'common', 'noun']
frequency_scores = { anime = 12164, leeds = 10211, wikipedia = 5611 }

[[cards]]
kanji = '年内'
kana = 'ねんない'
english = 'by the end of the year; within the year'
source = 'wanikani'
tags = ['common', 'noun', 'time']
frequency_scores = { anime = 21231, leeds = 10113 }

[[cards]]
kanji = '年末'
kana = 'ねんまつ'
english = 'end of the year'
source = 'wanikani'
tags = ['adverbial-noun', 'common', 'temporal-noun']
frequency_scores = { anime = 9827, leeds = 4816 }

[[cards]]
kanji = '二十日'
kana = 'はつか'
english = '20th day of the month; 20 days'
level = 'n5'
tags = []

[[cards]]
kanji = '春'
kana = 'はる'
english = 'spring'
level = 'n5'
tags = []
frequency_scores = { anime = 413, leeds = 1615, novels = 1350, wikipedia = 653 }

[[cards]]
kanji = '晩'
kana = 'ばん'
english = 'evening (7-10pmish)'
level = 'n5'
tags = []
frequency_scores = { anime = 1914, leeds = 4330, novels = 1643, wikipedia = 5140 }

[[cards]]
kanji = '一月'
kana = 'ひとつき'
english = 'one month'
level = 'n5'
tags = []
frequency_scores = { anime = 12181, leeds = 5291 }

[[cards]]
kanji = '暇'
kana = 'ひま'
english = 'free time; leisure'
level = 'n5'
tags = []
frequency_scores = { anime = 869, leeds = 3571, novels = 1761 }

[[cards]]
kanji = '昼'
kana = 'ひる'
english = 'noon'
level = 'n5'
tags = []
frequency_scores = { anime = 2643, leeds = 2828, novels = 2376, wikipedia = 4009 }

[[cards]]
kanji = '昼休み'
kana = 'ひるやすみ'
english = 'lunch break'
source = 'jlptstudy'
level = 'n4'
tags = ['adverbial-noun', 'common', 'temporal-noun', 'time', 'work']
frequency_scores = { anime = 4890, leeds = 9418 }

[[cards]]
kanji = '秒'
kana = 'びょう'
english = 'second (unit of time)'
source = 'wanikani'
level = 'n3'
tags = ['common', 'measurement', 'noun', 'time', 'unit']
frequency_scores = { anime = 831, leeds = 1323, novels = 1084, wikipedia = 1045 }

[[cards]]
kanji = '二日'
kana = 'ふつか'
english = 'second day of the month; two days'
level = 'n5'
tags = []

[[cards]]
kanji = '冬'
kana = 'ふゆ'
english = 'winter'
level = 'n5'
tags = []
frequency_scores = { anime = 1144, leeds = 1817, novels = 1765, wikipedia = 1426 }

[[cards]]
kanji = '～分'
kana = '～ふん'
english = 'counter for minutes'
level = 'n5'
tags = []

[[cards]]
kanji = '毎朝'
kana = 'まいあさ'
english = 'every morning'
level = 'n5'
tags = []
frequency_scores = { anime = 7512, leeds = 8171 }

[[cards]]
kanji = '毎週'
kana = 'まいしゅう'
english = 'every wek'
level = 'n5'
tags = []
frequency_scores = { anime = 8088, leeds = 3509, wikipedia = 1853 }

[[cards]]
kanji = '毎月'
kana = 'まいつき / まいげつ'
english = 'every month'
level = 'n5'
tags = []
frequency_scores = { anime = 9970, leeds = 3809, wikipedia = 5207 }

[[cards]]
kanji = '毎日'
kana = 'まいにち'
english = 'every day'
level = 'n5'
tags = []
frequency_scores = { anime = 649, leeds = 698, novels = 1311, wikipedia = 3043 }

[[cards]]
kanji = '毎年'
kana = 'まいねん / まいとし'
english = 'every year'
level = 'n5'
tags = []
frequency_scores = { anime = 3165, leeds = 1850, wikipedia = 1054 }

[[cards]]
kanji = '毎晩'
kana = 'まいばん'
english = 'every night'
level = 'n5'
tags = []
frequency_scores = { anime = 7857, leeds = 10547 }

[[cards]]
kanji = '三日'
kana = 'みっか'
english = 'third day of the month; three days'
level = 'n5'
tags = []

[[cards]]
kanji = '未来'
kana = 'みらい'
english = 'the future (usually distant)'
level = 'n3'
tags = ['common', 'no-adjective', 'noun']
frequency_scores = { anime = 366, leeds = 1560, novels = 1964, wikipedia = 2541 }

[[cards]]
kanji = '六日'
kana = 'むいか'
english = 'the sixth day; six days'
level = 'n5'
tags = []

[[cards]]
kanji = '昔'
kana = 'むかし'
english = 'olden days'
source = 'sekai-wa-fushigi-2'
level = 'n4'
tags = ['adverbial-noun', 'common', 'no-adjective', 'temporal-noun']
frequency_scores = { anime = 342, leeds = 741, novels = 635, wikipedia = 3863 }

[[cards]]
kanji = '木曜日'
kana = 'もくようび'
english = 'Thursday'
level = 'n5'
tags = []
frequency_scores = { anime = 28939, leeds = 5266, wikipedia = 6860 }

[[cards]]
kanji = '休み'
kana = 'やすみ'
english = 'rest; vacation; holiday'
level = 'n5'
tags = []
frequency_scores = { anime = 1077, leeds = 2099, novels = 2923 }

[[cards]]
kanji = '夕方'
kana = 'ゆうがた'
english = 'evening or dusk (before sunset; 5-7pmish)'
level = 'n5'
tags = []
frequency_scores = { anime = 3656, leeds = 2184, novels = 2493, wikipedia = 3851 }

[[cards]]
kanji = '夕べ'
kana = 'ゆうべ'
english = 'evening (5-7pmish); last night'
level = 'n5'
tags = []
frequency_scores = { anime = 9837, leeds = 15001 }

[[cards]]
kanji = '八日'
kana = 'ようか'
english = 'eigth day of the month; eight days'
level = 'n5'
tags = []

[[cards]]
kanji = '四日'
kana = 'よっか'
english = 'fourth of the month; four days'
level = 'n5'
tags = []

[[cards]]
kanji = '夜'
kana = 'よる'
english = 'evening; night (after 10pm)'
level = 'n5'
tags = []
frequency_scores = { anime = 207, leeds = 571, novels = 265, wikipedia = 989 }

[[cards]]
kanji = '来月'
kana = 'らいげつ'
english = 'next month'
level = 'n5'
tags = []
frequency_scores = { anime = 7099, leeds = 6212 }

[[cards]]
kanji = '来週'
kana = 'らいしゅう'
english = 'next week'
level = 'n5'
tags = []
frequency_scores = { anime = 2140, leeds = 3271 }

[[cards]]
kanji = '来年'
kana = 'らいねん'
english = 'next year'
source = 'irasshai'
level = 'n5'
tags = ['adverbial-noun', 'common', 'noun', 'temporal-noun', 'time']
frequency_scores = { anime = 2761, leeds = 1994 }

[[cards]]
kanji = '両日'
kana = 'りょうじつ'
english = 'both days'
source = 'wanikani'
tags = ['common', 'temporal-noun', 'time']

[[cards]]
kanji = 'カレンダー'
kana = 'カレンダー'
english = 'calendar'
level = 'n5'
tags = []
frequency_scores = { anime = 15488, leeds = 5594 }

