[[cards]]
kanji = '要る'
kana = 'いる'
english = 'to be needed'
source = 'irasshai'
level = 'n5'
tags = ['common']
frequency_scores = { anime = 1829, leeds = 4434, novels = 15 }

[[cards]]
kanji = '掛かる'
kana = 'かかる'
english = 'to take (time or money)'
source = 'n5-wiki'
level = 'n5'
tags = ['common']
frequency_scores = { anime = 2844, leeds = 4086, novels = 233, wikipedia = 4141 }

[[cards]]
kanji = '片付ける'
kana = 'かたづける'
english = 'to tidy up ~'
source = 'wiki-n4'
level = 'n4'
tags = ['common']
frequency_scores = { anime = 2723, leeds = 6563 }

[[cards]]
kanji = '閉める'
kana = 'しめる'
english = 'to close ~; to shut ~'
source = 'irasshai?'
level = 'n5'
tags = ['common']
frequency_scores = { anime = 4048, leeds = 7412, novels = 2432 }

[[cards]]
kanji = '育てる'
kana = 'そだてる'
english = 'to raise ~'
source = 'wiki-n4'
level = 'n4'
tags = ['common']
frequency_scores = { anime = 1786, leeds = 1996, wikipedia = 3470 }

[[cards]]
kanji = '捕まえる'
kana = 'つかまえる'
english = 'to catch ~; to arrrest ~'
source = 'wiki-n4'
level = 'n4'
tags = ['common']
frequency_scores = { anime = 1033, leeds = 8023 }

[[cards]]
kanji = '付ける'
kana = 'つける'
english = 'to attach ~'
source = 'wanikani'
level = 'n5'
tags = ['common']
frequency_scores = { anime = 661, leeds = 1192, novels = 1954, wikipedia = 289 }

[[cards]]
kanji = '包む'
kana = 'つつむ'
english = 'to wrap ~; to pack ~'
source = 'wiki-n4'
level = 'n4'
tags = ['common']
frequency_scores = { anime = 2736, leeds = 3915, novels = 927, wikipedia = 5106 }

[[cards]]
kanji = '張る'
kana = 'はる'
english = 'to affix ~; to paste ~'
source = 'wiki-n5'
level = 'n5'
tags = ['common']
frequency_scores = { anime = 1191, leeds = 2811, novels = 1188, wikipedia = 2649 }

[[cards]]
kanji = '弾く'
kana = 'ひく'
english = 'to play ~ (stringed instrument)'
source = 'irasshai'
level = 'n5'
tags = ['common']
frequency_scores = { anime = 1715, leeds = 3218, novels = 1171, wikipedia = 5778 }

[[cards]]
kanji = '渡る'
kana = 'わたる'
english = 'to cross over'
source = 'wiki-n5'
level = 'n5'
tags = ['common']
frequency_scores = { anime = 1948, leeds = 2273, novels = 1383, wikipedia = 342 }

