[[cards]]
kanji = '会う'
kana = 'あう'
english = 'to meet'
english-conjugated = { base = 'meet', past = 'met', plural = 'meets', continous = 'meeting' }
verb-type = 'godan-u'
transitive = false
level = 'n5'
explain = 'https://www.tofugu.com/japanese/japanese-homophones/'
tags = ['common']

[[cards]]
kanji = '合う'
kana = 'あう'
english = 'to do together; to match'
english-conjugated = { base = 'do together', past = 'did together', plural = 'does together', continous = 'doing together' }
verb-type = 'godan-u'
transitive = false
level = 'n4'
source = 'jlptstudy.net'
explain = 'https://www.tofugu.com/japanese/japanese-homophones/'
tags = ['common']

[[cards]]
kanji = '上がる'
kana = 'あがる'
english = 'to rise'
english-conjugated = { base = 'rise', past = 'rose', plural = 'rises', continous = 'rising' }
verb-type = 'godan-ru'
transitive = false
level = 'n4'
source = 'jlptstudy.net'
tags = ['common']

[[cards]]
kanji = '空く'
kana = 'あく'
english = 'to be empty or open (eg. seat)'
english-conjugated = { base = 'be empty', past = 'was empty', plural = 'are empty', continous = 'being empty' }
verb-type = 'godan-ku'
transitive = false
level = 'n4'
source = 'jlptstudy.net'
explain = 'https://forum.wordreference.com/threads/%E7%A9%BA%E3%81%8F-aku-suku.2664128/'
tags = ['common']

[[cards]]
kanji = '開く'
kana = 'あく'
english = 'to become open (eg. door); to become open (eg. business)'
english-conjugated = { base = 'become open (eg. door)', past = 'became open (eg. door)', plural = 'becomes open (eg. doors)', continous = 'becoming open (eg. door)' }
verb-type = 'godan-ku'
transitive = false
level = 'n5'
tags = ['common']

[[cards]]
kanji = '開ける'
kana = 'あける'
english = 'to open ~ (eg. a door); to open ~ (eg. for business)'
verb-type = 'ichidan'
transitive = true
level = 'n5'
tags = ['common']

[[cards]]
kanji = '上げる'
kana = 'あげる'
english = 'to raise ~; to give ~'
verb-type = 'ichidan'
transitive = true
level = 'n5'
tags = ['common']

[[cards]]
kanji = '遊ぶ'
kana = 'あそぶ'
english = 'to play'
english-conjugated = { base = 'play', past = 'played', plural = 'plays', continous = 'playing' }
verb-type = 'godan-bu'
transitive = false
level = 'n5'
tags = ['common']

[[cards]]
kanji = '集まる'
kana = 'あつまる'
english = 'to gather; to assemble'
english-conjugated = { base = 'gather', past = 'gathered', plural = 'gathers', continous = 'gathering' }
verb-type = 'godan-ru'
transitive = false
level = 'n4'
source = 'jlptstudy.net'
tags = ['common']

[[cards]]
kanji = '集める'
kana = 'あつめる'
english = 'to gather ~; to assemble ~'
english-conjugated = { base = 'gather', past = 'gathered', plural = 'gathers', continous = 'gathering' }
verb-type = 'ichidan'
transitive = true
level = 'n4'
source = 'jlptstudy.net'
tags = ['common']

[[cards]]
kanji = '浴びる'
kana = 'あびる'
english = 'to bathe in ~ (eg. water, light); to take ~ (eg. shower)'
verb-type = 'ichidan'
transitive = true
level = 'n5'
tags = ['common']

[[cards]]
kanji = '謝る'
kana = 'あやまる'
english = 'to apologize'
english-conjugated = { base = 'apologize', past = 'apologized', plural = 'apologizes', continous = 'apologizing' }
verb-type = 'godan-ru'
transitive = false
source = 'jlptstudy.net'
level = 'n4'
tags = ['common']

[[cards]]
kanji = '有る'
kana = 'ある'
english = 'to be, to exist, to have (inanimate)'
verb-type = 'irregular'
transitive = false
level = 'n5'
tags = ['common']

[[cards]]
kanji = '歩く'
kana = 'あるく'
english = 'to walk'
english-conjugated = { base = 'walk', past = 'walked', plural = 'walks', continuous = 'walking' }
verb-type = 'godan-ku'
transitive = false
level = 'n5'
tags = ['common']

[[cards]]
kanji = '生きる'
kana = 'いきる'
english = 'to live; to exist'
verb-type = 'ichidan'
transitive = false
level = 'n4'
source = 'jlptstudy.net'
tags = ['common']

[[cards]]
kanji = '苛める'
kana = 'いじめる'
english = 'to bully ~'
english-conjugated = { base = 'bully', past = 'bullied', plural = 'bullies', continous = 'bullying' }
verb-type = 'ichidan'
transitive = true
level = 'n4'
source = 'wanikani'
tags = ['common']

[[cards]]
kanji = '急ぐ'
kana = 'いそぐ'
english = 'to hurry ~; to rush ~'
english-conjugated = { base = 'hurry', past = 'hurried', plural = 'hurries', continous = 'hurrying' }
verb-type = 'godan-gu'
transitive = true
source = 'jlptstudy.net'
level = 'n4'
tags = ['common']

[[cards]]
kanji = '致す'
kana = 'いたす'
english = 'to do ~ (kenjougo)'
english-conjugated = { base = 'do', past = 'did', plural = 'does', continous = 'doing' }
verb-type = 'godan-su'
transitive = true
source = 'jlptstudy.net'
level = 'n4'
tags = ['common', 'kenjougo']

[[cards]]
kanji = '頂く'
kana = 'いただく'
english = 'to receive ~ (kenjougo); to accept ~ (kenjougo); to eat/drink ~ (kenjougo)'
english-conjugated = { base = 'receive', past = 'received', plural = 'receives', continous = 'receiving' }
verb-type = 'godan-ku'
transitive = true
source = 'jlptstudy.net'
level = 'n4'
tags = ['common']

[[cards]]
kanji = '祈る'
kana = 'いのる'
english = 'to pray ~; to wish ~'
english-conjugated = { base = 'pray', past = 'prayed', plural = 'prays', continous = 'praying' }
verb-type = 'godan-ru'
transitive = true
level = 'n4'
source = 'jlptstudy.net'
tags = ['common']

[[cards]]
kanji = 'いらっしゃる'
kana = 'いらっしゃる'
english = 'to come (sonkeigo); to go (sonkeigo)'
english-conjugated = { base = 'come', past = 'came', plural = 'comes', continous = 'coming' }
verb-type = 'godan-aru-special'
transitive = false
source = 'jlptstudy.net'
level = 'n4'
tags = ['common', 'sonkeigo']

[[cards]]
kanji = '入れる'
kana = 'いれる'
english = 'to put inside ~'
english-conjugated = { base = 'put inside', past = 'put inside', plural = 'puts inside', continous = 'putting inside' }
verb-type = 'ichidan'
transitive = true
level = 'n5'
tags = ['common']

[[cards]]
kanji = '植える'
kana = 'うえる'
english = 'to plant ~; to grow ~; to insert ~'
english-conjugated = { base = 'plant', past = 'planted', plural = 'plants', continous = 'planting' }
verb-type = 'ichidan'
transitive = true
source = 'jlptstudy.net'
level = 'n4'
tags = ['common']

[[cards]]
kanji = '飢える'
kana = 'うえる'
english = 'to starve; to be famished; to be hungry'
english-conjugated = { base = 'starve', past = 'starved', plural = 'starves', continous = 'starving' }
verb-type = 'ichidan'
transitive = false
level = 'n2'
tags = ['common']

[[cards]]
kanji = '撃つ'
kana = 'うつ'
english = 'to shoot ~'
english-conjugation = { base = 'shoot', past = 'shot', plural = 'shoots', continous = 'shooting' }
verb-type = 'godan-tsu'
transitive = true
level = 'n3'
tags = ['common']

[[cards]]
kanji = '生まれる'
kana = 'うまれる'
english = 'to be born'
verb-type = 'ichidan'
transitive = false
level = 'n5'
tags = ['common']

[[cards]]
kanji = '生む'
kana = 'うむ'
english = 'to give birth to ~'
english-conjugated = { base = 'give birth', past = 'gave birth', plural = 'gives birth', continous = 'giving birth' }
verb-type = 'godan-mu'
transitive = true
level = 'n1'
tags = ['common']

[[cards]]
kanji = '売る'
kana = 'うる'
english = 'to sell ~'
verb-type = 'godan-ru'
transitive = true
level = 'n5'
tags = ['common']

[[cards]]
kanji = '怒る'
kana = 'おこる'
english = 'to get angry'
verb-type = 'godan-ru'
transitive = false
level = 'n4'
tags = ['common']

[[cards]]
kanji = '落ちる'
kana = 'おちる'
english = 'to fall down'
verb-type = 'ichidan'
transitive = false
level = 'n4'
tags = ['common']

[[cards]]
kanji = '泳ぐ'
kana = 'およぐ'
english = 'to swim'
verb-type = 'godan-gu'
transitive = false
level = 'n5'
tags = ['common']

[[cards]]
kanji = '返す'
kana = 'かえす'
english = 'to return ~ (something); to restore ~; to put back ~'
verb-type = 'godan-su'
transitive = true
level = 'n5'
tags = ['common']

[[cards]]
kanji = '書く'
kana = 'かく'
english = 'to write or compose ~'
verb-type = 'godan-ku'
transitive = true
level = 'n5'
tags = ['common']

[[cards]]
kanji = '隠す'
kana = 'かくす'
english = 'to hide ~'
english-conjugated = { base = 'hide', past = 'hid', plural = 'hides', continous = 'hiding' }
verb-type = 'godan-su'
transitive = true
level = 'n3'
source = 'wanikani'
tags = ['common']

[[cards]]
kanji = '貸す'
kana = 'かす'
english = 'to lend ~'
level = 'n5'
verb-type = 'godan-su'
transitive = true
tags = ['common']

[[cards]]
kanji = '勝つ'
kana = 'かつ'
english = 'to win'
english-conjugated = { base = 'win', past = 'won', plural = 'wins', continous = 'winning' }
verb-type = 'godan-tsu'
transitive = false
level = 'n4'
tags = ['common']

[[cards]]
kanji = '擽る'
kana = 'くすぐ'
english = 'to tickle ~'
english-conjugated = { base = 'tickle', past = 'tickled', plural = 'tickles', continous = 'tickling' }
verb-type = 'godan-ru'
transitive = true
tags = ['common']

[[cards]]
kanji = '曇る'
kana = 'くもる'
english = 'to get cloudy'
level = 'n5'
verb-type = 'godan-ru'
transitive = false
tags = ['common']

[[cards]]
kanji = '消す'
kana = 'けす'
english = 'to delete ~; to erase/cross out ~; to turn off ~s power'
verb-type = 'godan-su'
transitive = true
level = 'n5'
tags = ['common']

[[cards]]
kanji = '越える'
kana = 'こえる'
english = 'to pass over ~; to cross over ~; to go beyond ~'
english-conjugated = { base = 'cross over', past = 'crossed over', plural = 'crosses over', continous = 'crossing over' }
verb-type = 'ichidan'
transitive = true
source = 'wanikani'
level = 'n3'
tags = ['common']

[[cards]]
kanji = '答える'
kana = 'こたえる'
english = 'to answer'
english-conjugation = { base = 'answer', past = 'answered', plural = 'answers', continous = 'answering' }
verb-type = 'ichidan'
transitive = false
level = 'n5'
tags = ['common']

[[cards]]
kanji = '探す'
kana = 'さがす'
english = 'to search'
english-conjugation = { base = 'search', past = 'searched', plural = 'searches', continous = 'searching' }
verb-type = 'godan-su'
transitive = true
level = 'n4'
tags = ['common']

[[cards]]
kanji = '喋る'
kana = 'しゃべる'
english = 'to chat; to chatter'
level = 'n3'
verb-type = 'godan-ru'
transitive = false
tags = ['common']

[[cards]]
kanji = '育つ'
kana = 'そだつ'
english = 'to be raised; to be brought up'
english-conjugated = { base = 'raised', past = 'been raised', plural = 'are raised', continous = 'being raised' }
verb-type = 'godan-tsu'
transitive = false
level = 'n3'
source = 'wanikani'
tags = ['common']

[[cards]]
kanji = '足す'
kana = 'たす'
english = 'to add ~ (numbers); to add ~ (to something)'
verb-type = 'godan-su'
transitive = true
source = 'nihongo-charenji-n4-kotoba'
level = 'n4'
tags = ['common']

[[cards]]
kanji = '正す'
kana = 'ただす'
english = 'to correct ~; to rectify ~'
english-conjugated = { base = 'correct', past = 'corrected', plural = 'corrects', continous = 'correcting' }
verb-type = 'godan-su'
transitive = true
source = 'wanikani'
tags = ['common']

[[cards]]
kanji = '立つ'
kana = 'たつ'
english = 'to stand'
verb-type = 'godan-tsu'
transitive = false
level = 'n5'
tags = ['common']

[[cards]]
kanji = '立てる'
kana = 'たてる'
english = 'to stand up ~'
verb-type = 'ichidan'
transitive = true
level = 'n4'
source = 'wanikani'
tags = ['common']

[[cards]]
kanji = '足りる'
kana = 'たりる'
english = 'to be sufficient; to be enough'
verb-type = 'ichidan'
transitive = false
source = 'nihongo-charenji-n4-kotoba'
level = 'n4'
tags = ['common']

[[cards]]
kanji = '出す'
kana = 'だす'
english = 'to take out ~'
english-conjugated = { base = 'take out', past = 'took out', plural = 'takes out', continous = 'taking out' }
verb-type = 'godan-su'
transitive = true
level = 'n5'
tags = ['common']

[[cards]]
kanji = '使う'
kana = 'つかう'
english = 'to use ~ (colloquial)'
english-conjugated = { base = 'use', past = 'used', plural = 'uses', continous = 'using' }
level = 'n5'
verb-type = 'godan-u'
transitive = true
tags = ['common']

[[cards]]
kanji = '出かける'
kana = 'でかける'
english = 'to go out; to set out'
english-conjugated = { base = 'go out', past = 'went out', plural = 'goes out', continous = 'going out' }
verb-type = 'ichidan'
transitive = false
level = 'n5'
tags = ['common']

[[cards]]
kanji = '出る'
kana = 'でる'
english = 'to exit'
english-conjugated = { base = 'exit', past = 'exited', plural = 'exits', continous = 'exiting' }
verb-type = 'ichidan'
transitive = false
level = 'n5'
tags = ['common']

[[cards]]
kanji = '通る'
kana = 'とおる'
english = 'to go past; to go by'
english-conjugated = { base = 'go past', past = 'went past', plural = 'goes past', continous = 'going past' }
verb-type = ''
transitive = false
level = ''
source = ''
tags = []

[[cards]]
kanji = '止まる'
kana = 'とまる'
english = 'to stop (moving, doing, ...); to come to a halt'
english-conjugated = { base = 'stop', past = 'stopped', plural = 'stops', continous = 'stopping' }
verb-type = 'godan-ru'
transitive = false
level = 'n5'
tags = ['common']

[[cards]]
kanji = '止める'
kana = 'とめる'
english = 'to stop ~'
english-conjugated = { base = 'stop', past = 'stopped', plural = 'stop', continous = 'stopping' }
verb-type = 'ichidan'
transitive = true
level = 'n4'
tags = ['common']

[[cards]]
kanji = '泣く'
kana = 'なく'
english = 'to cry'
english-conjugated = { base = 'cry', past = 'cried', plural = 'cries', continous = 'crying' }
level = 'n4'
verb-type = 'godan-ku'
transitive = false
tags = ['common']

[[cards]]
kanji = '無くす'
kana = 'なくす'
english = 'to lose ~ (something)'
english-conjugated = { base = 'lose', past = 'lost', plural = 'loses', continous = 'losing' }
level = 'n5'
verb-type = 'godan-su'
transitive = true
tags = ['common']

[[cards]]
kanji = '成る'
kana = 'なる'
english = 'to become; to reach'
english-conjugated = { base = 'become', past = 'became', plural = 'becomes', continous = 'becoming' }
verb-type = 'godan-ru'
transitive = false
level = 'n5'
tags = ['common']

[[cards]]
kanji = '盗む'
kana = 'ぬすむ'
english = 'to steal ~'
verb-type = 'godan-mu'
transitive = true
level = 'n4'
tags = ['common']

[[cards]]
kanji = '残る'
kana = 'のこる'
english = 'to remain; to be left'
english-conjugated = { base = 'remain', past = 'remained', plural = 'remains', continous = 'remaining' }
verb-type = 'godan-ru'
transitive = false
source = 'nihongo-charenji-n4-kotoba'
level = 'n4'
tags = ['common']

[[cards]]
kanji = '上る'
kana = 'のぼる'
english = 'to climb'
english-conjugation = { base = 'climb', past = 'climbed', plural = 'climbs', continous = 'climbing' }
verb-type = 'godan-ru'
transitive = false
level = 'n5'
tags = ['common']

[[cards]]
kanji = '飲む'
kana = 'のむ'
english = 'to drink ~; to swallow ~'
english-conjugated = { base = 'drink', past = 'drank', plural = 'drinks', continous = 'drinking' }
verb-type = 'godan-mu'
transitive = true
level = 'n5'
tags = ['common']

[[cards]]
kanji = '履く'
kana = 'はく'
english = 'to put on or wear ~ (lower-body clothing)'
english-conjugated = { base = 'wear', past = 'wore', plural = 'wears', continous = 'wearing' }
verb-type = 'godan-ku'
transitive = true
level = 'n3'
tags = ['common']

[[cards]]
kanji = '走る'
kana = 'はしる'
english = 'to run'
english-conjugated = { base = 'run', past = 'ran', plural = 'runs', continous = 'running' }
verb-type = 'godan-ru'
transitive = false
level = 'n5'
tags = ['common']

[[cards]]
kanji = '始まる'
kana = 'はじまる'
english = 'to begin'
english-conjugated = { base = 'begin', past = 'began', plural = 'begins', continous = 'beginning' }
verb-type = 'godan-ru'
transitive = false
level = 'n5'
tags = ['common']

[[cards]]
kanji = '外れる'
kana = 'はずれる'
english = 'to be disconnected'
english-conjugated = { base = 'be disconnected', past = 'been disconnected', plural = 'be disconnected', continous = 'being disconnected' }
verb-type = 'ichidan'
transitive = false
level = 'n2'
tags = ['common']

[[cards]]
kanji = '働く'
kana = 'はたらく'
english = 'to work'
english-conjugated = { base = 'work', past = 'worked', plural = 'works', continous = 'working' }
verb-type = 'godan-ku'
transitive = false
level = 'n5'
tags = ['common']

[[cards]]
kanji = '引く'
kana = 'ひく'
english = 'to pull ~; to subtract ~'
english-conjugated = { base = 'pull', past = 'pulled', plural = 'pulls', continous = 'pulling' }
verb-type = 'godan-ku'
transitive = true
level = 'n5'
tags = ['common']

[[cards]]
kanji = '太る'
kana = 'ふとる'
english = 'to get fat'
english-conjugated = { base = 'get fat', past = 'got fat', plural = 'gets fat', continous = 'getting fat' }
verb-type = 'godan-ru'
transitive = false
level = 'n4'
tags = ['common']

[[cards]]
kanji = '曲がる'
kana = 'まがる'
english = 'to bend; to twist; to turn'
english-conjugated = { base = 'twist', past = 'twisted', plural = 'twists', continous = 'twising' }
verb-type = 'godan-ru'
transitive = false
level = 'n5'
tags = ['common']

[[cards]]
kanji = '混ぜる'
kana = 'まぜる'
english = 'to mix ~; to stir ~; to blend ~'
english-conjugated = { base = 'mix', past = 'mixed', plural = 'mixes', continous = 'mixing' }
verb-type = 'ichidan'
transitive = true
source = 'sekai-wa-fushigi-2'
level = 'n2'
tags = ['common']

[[cards]]
kanji = '待つ'
kana = 'まつ'
english = 'to wait; to wait on ~'
english-conjugated = { base = 'wait', past = 'waited', plural = 'waits', continous = 'waiting' }
verb-type = 'godan-tsu'
transitive = true
level = 'n5'
note = 'both transitive and intransitive'
tags = ['common', 'intransitive', 'transitive']

[[cards]]
kanji = '守る'
kana = 'まもる'
english = 'to protect'
english-conjugated = { base = 'protect', past = 'protected', plural = 'protects', continous = 'protecting' }
verb-type = 'godan-ru'
transitive = false
level = 'n3'
tags = ['common']

[[cards]]
kanji = '見える'
kana = 'みえる'
english = 'can see'
english-conjugated = { base = 'can see', past = 'could see', plural = 'can see', continous = 'can see' }
verb-type = 'ichidan'
transitive = false
level = 'n4'
tags = ['common']

[[cards]]
kanji = '見せる'
kana = 'みせる'
english = 'to show ~'
english-conjugated = { base = 'show', past = 'showed', plural = 'shows', continous = 'showing' }
verb-type = 'ichidan'
transitive = true
level = 'n5'
tags = ['common']

[[cards]]
kanji = '見る'
kana = 'みる'
english = 'to see ~'
english-conjugated = { base = 'see', past = 'saw', plural = 'sees', continous = 'seeing' }
verb-type = 'ichidan'
transitive = true
level = 'n5'
tags = ['common']

[[cards]]
kanji = '向かう'
kana = 'むかう'
english = 'to face'
english-conjugated = { base = 'face', past = 'faced', plural = 'faces', continous = 'facing' }
verb-type = 'godan-u'
transitive = false
level = 'n4'
source = 'jlptstudy.net'
tags = ['common']

[[cards]]
kanji = '用いる'
kana = 'もちいる'
english = 'to use ~; to utilize ~ (literary)'
english-conjugated = { base = 'use', past = 'used', plural = 'uses', continous = 'using' }
verb-type = 'ichidan'
transitive = true
explain = 'https://www.japanesepod101.com/blog/yomi-and-breakdown-of-the-words/'
level = 'n3'
tags = ['common']

[[cards]]
kanji = '休む'
kana = 'やすむ'
english = 'to rest; to take a break; to take a day off'
english-conjugated = { base = 'rest', past = 'rested', plural = 'rests', continous = 'resting' }
verb-type = 'godan-mu'
transitive = false
level = 'n5'
tags = ['common']

[[cards]]
kanji = '遣る'
kana = 'やる'
english = 'to do ~ (casual)'
english-conjugated = { base = 'do', past = 'did', plural = 'does', continous = 'doing' }
verb-type = 'godan-ru'
transitive = true
level = 'n1'
tags = ['common']

[[cards]]
kanji = '読む'
kana = 'よむ'
english = 'to read'
english-conjugated = { base = 'read', past = 'read', plural = 'reads', continous = 'reading' }
verb-type = 'godan-mu'
transitive = false
level = 'n5'
tags = ['common']

[[cards]]
kanji = '喜ぶ'
kana = 'よろこ'
english = 'to be delighted'
english-conjugated = { base = 'be delighted', past = 'been delighted', plural = 'are delighted', continous = 'being delighted' }
verb-type = 'godan-bu'
transitive = false
level = 'n4'
source = 'jlptstudy.net'
tags = ['common']

[[cards]]
kanji = '分かる'
kana = 'わかる'
english = 'to understand'
english-conjugated = { base = 'understand', past = 'understood', plural = 'understands', continous = 'understanding' }
verb-type = 'godan-ru'
transitive = false
level = 'n5'
tags = ['common']

[[cards]]
kanji = '分ける'
kana = 'わける'
english = 'to separate ~; to divide ~'
english-conjugated = { base = 'separate', past = 'separated', plural = 'separates', continous = 'separating' }
verb-type = 'ichidan'
transitive = true
level = 'n3'
source = 'wanikani'
tags = ['common']

