[[cards]]
kanji = '会う'
kana = 'あう'
english = 'to meet'
english-conjugated = { base = 'meet', past = 'met', plural = 'meets', continous = 'meeting' }
verb-type = 'godan-u'
transitive = false
level = 'n5'
explain = 'https://www.tofugu.com/japanese/japanese-homophones/'
tags = ['common']

[[cards]]
kanji = '合う'
kana = 'あう'
english = 'to do together; to match'
english-conjugated = { base = 'do together', past = 'did together', plural = 'does together', continous = 'doing together' }
verb-type = 'godan-u'
transitive = false
level = 'n4'
source = 'jlptstudy.net'
explain = 'https://www.tofugu.com/japanese/japanese-homophones/'
tags = ['common']

[[cards]]
kanji = '上がる'
kana = 'あがる'
english = 'to rise'
english-conjugated = { base = 'rise', past = 'rose', plural = 'rises', continous = 'rising' }
verb-type = 'godan-ru'
transitive = false
level = 'n4'
source = 'jlptstudy.net'
tags = ['common']

[[cards]]
kanji = '空く'
kana = 'あく'
english = 'to be empty or open (eg. seat)'
english-conjugated = { base = 'be empty', past = 'was empty', plural = 'are empty', continous = 'being empty' }
verb-type = 'godan-ku'
transitive = false
level = 'n4'
source = 'jlptstudy.net'
explain = 'https://forum.wordreference.com/threads/%E7%A9%BA%E3%81%8F-aku-suku.2664128/'
tags = ['common']

[[cards]]
kanji = '開く'
kana = 'あく'
english = 'to become open (eg. door); to become open (eg. business)'
english-conjugated = { base = 'become open (eg. door)', past = 'became open (eg. door)', plural = 'becomes open (eg. doors)', continous = 'becoming open (eg. door)' }
verb-type = 'godan-ku'
transitive = false
level = 'n5'
tags = ['common']

[[cards]]
kanji = '開ける'
kana = 'あける'
english = 'to open ~ (eg. a door); to open ~ (eg. for business)'
verb-type = 'ichidan'
transitive = true
level = 'n5'
tags = ['common']

[[cards]]
kanji = '上げる'
kana = 'あげる'
english = 'to raise ~; to give ~'
make_kanji_card = true
hide_hiragana_card = true
verb-type = 'ichidan'
transitive = true
level = 'n5'
tags = ['common']

[[cards]]
kanji = '遊ぶ'
kana = 'あそぶ'
english = 'to play'
english-conjugated = { base = 'play', past = 'played', plural = 'plays', continous = 'playing' }
verb-type = 'godan-bu'
transitive = false
level = 'n5'
tags = ['common']

[[cards]]
kanji = '浴びる'
kana = 'あびる'
english = 'to bathe in ~ (eg. water, light); to take ~ (eg. shower)'
verb-type = 'ichidan'
transitive = true
level = 'n5'
tags = ['common']

[[cards]]
kanji = '有る'
kana = 'ある'
english = 'to be, to exist, to have (inanimate)'
verb-type = 'irregular'
transitive = false
level = 'n5'
tags = ['common']

[[cards]]
kanji = '歩く'
kana = 'あるく'
english = 'to walk'
english-conjugated = { base = 'walk', past = 'walked', plural = 'walks', continuous = 'walking' }
verb-type = 'godan-ku'
transitive = false
level = 'n5'
tags = ['common']

[[cards]]
kanji = '生きる'
kana = 'いきる'
english = 'to live; to exist'
verb-type = 'ichidan'
transitive = false
level = 'n4'
source = 'jlptstudy.net'
tags = ['common']

[[cards]]
kanji = '撃つ'
kana = 'うつ'
english = 'to shoot ~'
english-conjugation = { base = 'shoot', past = 'shot', plural = 'shoots', continous = 'shooting' }
verb-type = 'godan-tsu'
transitive = true
level = 'n3'
tags = ['common']

[[cards]]
kanji = '生まれる'
kana = 'うまれる'
english = 'to be born'
verb-type = 'ichidan'
transitive = false
level = 'n5'
tags = ['common']

[[cards]]
kanji = '売る'
kana = 'うる'
english = 'to sell ~'
verb-type = 'godan-ru'
transitive = true
level = 'n5'
tags = ['common']

[[cards]]
kanji = '怒る'
kana = 'おこる'
english = 'to get angry'
verb-type = 'godan-ru'
transitive = false
level = 'n4'
tags = ['common']

[[cards]]
kanji = '落ちる'
kana = 'おちる'
english = 'to fall down'
make_kanji_card = true
verb-type = 'ichidan'
transitive = false
level = 'n4'
tags = ['common']

[[cards]]
kanji = '泳ぐ'
kana = 'およぐ'
english = 'to swim'
verb-type = 'godan-gu'
transitive = false
level = 'n5'
tags = ['common']

[[cards]]
kanji = '返す'
kana = 'かえす'
english = 'to return ~ (something); to restore ~; to put back ~'
verb-type = 'godan-su'
transitive = true
level = 'n5'
tags = ['common']

[[cards]]
kanji = '書く'
kana = 'かく'
english = 'to write or compose ~'
verb-type = 'godan-ku'
transitive = true
level = 'n5'
tags = ['common']

[[cards]]
kanji = '貸す'
kana = 'かす'
english = 'to lend ~'
level = 'n5'
verb-type = 'godan-su'
transitive = true
tags = ['common']

[[cards]]
kanji = '曇る'
kana = 'くもる'
english = 'to get cloudy'
level = 'n5'
verb-type = 'godan-ru'
transitive = false
tags = ['common']

[[cards]]
kanji = '消す'
kana = 'けす'
english = 'to delete ~; to erase/cross out ~; to turn off ~s power'
verb-type = 'godan-su'
transitive = true
level = 'n5'
tags = ['common']

[[cards]]
kanji = '答える'
kana = 'こたえる'
english = 'to answer'
english-conjugation = { base = 'answer', past = 'answered', plural = 'answers', continous = 'answering' }
verb-type = 'ichidan'
transitive = false
level = 'n5'
tags = ['common']

[[cards]]
kanji = '探す'
kana = 'さがす'
english = 'to search'
english-conjugation = { base = 'search', past = 'searched', plural = 'searches', continous = 'searching' }
verb-type = 'godan-su'
transitive = true
level = 'n4'
tags = ['common']

[[cards]]
kanji = '喋る'
kana = 'しゃべる'
english = 'to chat; to chatter'
level = 'n3'
verb-type = 'godan-ru'
transitive = false
tags = ['common']

[[cards]]
kanji = '足す'
kana = 'たす'
english = 'to add ~ (numbers); to add ~ (to something)'
verb-type = 'godan-su'
transitive = true
source = 'nihongo-charenji-n4-kotoba'
level = 'n4'
tags = ['common']

[[cards]]
kanji = '立つ'
kana = 'たつ'
english = 'to stand'
make_kanji_card = true
hide_hiragana_card = true
verb-type = 'godan-tsu'
transitive = false
level = 'n5'
tags = ['common']

[[cards]]
kanji = '立てる'
kana = 'たてる'
english = 'to stand up ~'
make_kanji_card = true
hide_hiragana_card = true
verb-type = 'ichidan'
transitive = true
level = 'n4'
source = 'wanikani'
tags = ['common']

[[cards]]
kanji = '足りる'
kana = 'たりる'
english = 'to be sufficient; to be enough'
verb-type = 'ichidan'
transitive = false
source = 'nihongo-charenji-n4-kotoba'
level = 'n4'
tags = ['common']

[[cards]]
kanji = '出す'
kana = 'だす'
english = 'to take out ~'
make_kanji_card = true
hide_hiragana_card = true
verb-type = 'godan-su'
transitive = true
level = 'n5'
tags = ['common']

[[cards]]
kanji = '使う'
kana = 'つかう'
english = 'to use ~'
level = 'n5'
verb-type = 'godan-u'
transitive = true
tags = ['common']

[[cards]]
kanji = '出る'
kana = 'でる'
english = 'to exit'
verb-type = 'ichidan'
transitive = false
level = 'n5'
tags = ['common']

[[cards]]
kanji = '止まる'
kana = 'とまる'
english = 'to stop (moving); to come to a halt; to stop (doing)'
verb-type = 'godan-ru'
transitive = false
level = 'n5'
tags = ['common']

[[cards]]
kanji = '泣く'
kana = 'なく'
english = 'to cry'
level = 'n4'
verb-type = 'godan-ku'
transitive = false
tags = ['common']

[[cards]]
kanji = '無くす'
kana = 'なくす'
english = 'to lose ~ (something)'
english-conjugated = { base = 'lose', past = 'lost', plural = 'loses', continous = 'losing' }
level = 'n5'
verb-type = 'godan-su'
transitive = true
tags = ['common']

[[cards]]
kanji = '成る'
kana = 'なる'
english = 'to become; to reach'
english-conjugated = { base = 'become', past = 'became', plural = 'becomes', continous = 'becoming' }
verb-type = 'godan-ru'
transitive = false
level = 'n5'
tags = ['common']

[[cards]]
kanji = '盗む'
kana = 'ぬすむ'
english = 'to steal ~'
verb-type = 'godan-mu'
transitive = true
level = 'n4'
tags = ['common']

[[cards]]
kanji = '残る'
kana = 'のこる'
english = 'to remain; to be left'
english-conjugated = { base = 'remain', past = 'remained', plural = 'remains', continous = 'remaining' }
verb-type = 'godan-ru'
transitive = false
source = 'nihongo-charenji-n4-kotoba'
level = 'n4'
tags = ['common']

[[cards]]
kanji = '上る'
kana = 'のぼる'
english = 'to climb'
english-conjugation = { base = 'climb', past = 'climbed', plural = 'climbs', continous = 'climbing' }
verb-type = 'godan-ru'
transitive = false
level = 'n5'
tags = ['common']

[[cards]]
kanji = '飲む'
kana = 'のむ'
english = 'to drink ~; to swallow ~'
english-conjugated = { base = 'drink', past = 'drank', plural = 'drinks', continous = 'drinking' }
verb-type = 'godan-mu'
transitive = true
level = 'n5'
tags = ['common']

[[cards]]
kanji = '履く'
kana = 'はく'
english = 'to put on or wear ~ (lower-body clothing)'
english-conjugated = { base = 'wear', past = 'wore', plural = 'wears', continous = 'wearing' }
verb-type = 'godan-ku'
transitive = true
level = 'n3'
tags = ['common']

[[cards]]
kanji = '走る'
kana = 'はしる'
english = 'to run'
english-conjugated = { base = 'run', past = 'ran', plural = 'runs', continous = 'running' }
verb-type = 'godan-ru'
transitive = false
level = 'n5'
tags = ['common']

[[cards]]
kanji = '始まる'
kana = 'はじまる'
english = 'to begin'
english-conjugated = { base = 'begin', past = 'began', plural = 'begins', continous = 'beginning' }
verb-type = 'godan-ru'
transitive = false
level = 'n5'
tags = ['common']

[[cards]]
kanji = '働く'
kana = 'はたらく'
english = 'to work'
english-conjugated = { base = 'work', past = 'worked', plural = 'works', continous = 'working' }
verb-type = 'godan-ku'
transitive = false
level = 'n5'
tags = ['common']

[[cards]]
kanji = '曲がる'
kana = 'まがる'
english = 'to bend; to twist; to turn'
english-conjugated = { base = 'twist', past = 'twisted', plural = 'twists', continous = 'twising' }
verb-type = 'godan-ru'
transitive = false
level = 'n5'
tags = ['common']

[[cards]]
kanji = '混ぜる'
kana = 'まぜる'
english = 'to mix ~; to stir ~; to blend ~'
english-conjugated = { base = 'mix', past = 'mixed', plural = 'mixes', continous = 'mixing' }
verb-type = 'ichidan'
transitive = true
source = 'sekai-wa-fushigi-2'
level = 'n2'
tags = ['common']

[[cards]]
kanji = '待つ'
kana = 'まつ'
english = 'to wait; to wait on ~'
english-conjugated = { base = 'wait', past = 'waited', plural = 'waits', continous = 'waiting' }
verb-type = 'godan-tsu'
transitive = true
level = 'n5'
note = 'both transitive and intransitive'
tags = ['common', 'intransitive', 'transitive']

[[cards]]
kanji = '守る'
kana = 'まもる'
english = 'to protect'
english-conjugated = { base = 'protect', past = 'protected', plural = 'protects', continous = 'protecting' }
verb-type = 'godan-ru'
transitive = false
level = 'n3'
tags = ['common']

[[cards]]
kanji = '読む'
kana = 'よむ'
english = 'to read'
english-conjugated = { base = 'read', past = 'read', plural = 'reads', continous = 'reading' }
verb-type = 'godan-mu'
transitive = false
level = 'n5'
tags = ['common']

