[[cards]]
kanji = '暖かい'
kana = 'あたたかい'
english = 'warm (air temp)'
level = 'n5'
tags = ['common', 'i-adjective', 'temperature', 'weather']
highest_frequency = 2522
highest_frequency_source = 'Anime'

[[cards]]
kanji = '暑い'
kana = 'あつい'
english = 'hot; warm'
level = 'n5'
tags = ['common', 'i-adjectives', 'weather']
highest_frequency = 1505
highest_frequency_source = 'Anime'

[[cards]]
kanji = '雨'
kana = 'あめ'
english = 'rain'
level = 'n5'
tags = ['common', 'weather']
highest_frequency = 804
highest_frequency_source = 'Anime'

[[cards]]
kanji = '嵐'
kana = 'あらし'
english = 'storm'
level = 'n3'
tags = ['common']
highest_frequency = 2866
highest_frequency_source = 'Novels'

[[cards]]
kanji = '大雨'
kana = 'おおあめ'
english = 'heavy rain'
source = 'wanikani'
tags = ['common', 'nature', 'noun', 'rain', 'weather']
highest_frequency = 9634
highest_frequency_source = 'Leeds'

[[cards]]
kanji = '傘'
kana = 'かさ'
english = 'umbrella'
level = 'n5'
tags = ['accessories', 'clothing', 'common', 'weather']
highest_frequency = 2872
highest_frequency_source = 'Anime'

[[cards]]
kanji = '風'
kana = 'かぜ'
english = 'wind; breeze'
level = 'n5'
tags = ['common']
highest_frequency = 252
highest_frequency_source = 'Novels'

[[cards]]
kanji = '雷'
kana = 'かみなり'
english = 'lightning; thunder'
level = 'n3'
tags = ['common']
highest_frequency = 2604
highest_frequency_source = 'Anime'

[[cards]]
kanji = '気温'
kana = 'きおん'
english = 'atmospheric temperature'
level = 'n3'
tags = ['common']
highest_frequency = 3166
highest_frequency_source = 'Wikipedia'

[[cards]]
kanji = '霧'
kana = 'きり'
english = 'fog; mist'
level = 'n3'
tags = ['common']
highest_frequency = 751
highest_frequency_source = 'Anime'

[[cards]]
kanji = '空気'
kana = 'くうき'
english = 'air; atmosphere; mood'
level = 'n4'
tags = ['common']
highest_frequency = 764
highest_frequency_source = 'Novels'

[[cards]]
kanji = '雲'
kana = 'くも'
english = 'cloud'
level = 'n4'
tags = ['common']
highest_frequency = 1156
highest_frequency_source = 'Novels'

[[cards]]
kanji = '曇り'
kana = 'くもり'
english = 'cloudiness; cloudy weather'
level = 'n5'
tags = ['common']

[[cards]]
kanji = '暗い'
kana = 'くらい'
english = 'dark; gloomy; depressed'
level = 'n5'
tags = ['common', 'i-adjective']
highest_frequency = 614
highest_frequency_source = 'Novels'

[[cards]]
kanji = '氷'
kana = 'こおり'
english = 'ice'
level = 'n3'
tags = ['common']
highest_frequency = 2387
highest_frequency_source = 'Novels'

[[cards]]
kanji = '寒い'
kana = 'さむい'
english = 'cold (weather)'
level = 'n5'
tags = ['common', 'i-adjective']
highest_frequency = 1137
highest_frequency_source = 'Anime'

[[cards]]
kanji = '涼しい'
kana = 'すずしい'
english = 'cool (temperature); refreshing'
level = 'n5'
tags = ['common']
highest_frequency = 5291
highest_frequency_source = 'Anime'

[[cards]]
kanji = '空'
kana = 'そら'
english = 'sky'
level = 'n5'
tags = ['common']
highest_frequency = 265
highest_frequency_source = 'Anime'

[[cards]]
kanji = '大気'
kana = 'たいき'
english = 'atmosphere'
source = 'wanikani'
level = 'n3'
tags = ['common', 'noun']
highest_frequency = 3581
highest_frequency_source = 'Wikipedia'

[[cards]]
kanji = '台風'
kana = 'たいふう'
english = 'typhoon; hurricane'
level = 'n4'
tags = ['common']
highest_frequency = 3624
highest_frequency_source = 'Leeds'

[[cards]]
kanji = '露'
kana = 'つゆ'
english = 'dew'
level = 'n1'
tags = ['common']
highest_frequency = 2880
highest_frequency_source = 'Novels'

[[cards]]
kanji = '天気'
kana = 'てんき'
english = 'weather'
level = 'n5'
tags = ['common']
highest_frequency = 1920
highest_frequency_source = 'Anime'

[[cards]]
kanji = '天気予報'
kana = 'てんきよほう'
english = 'weather forecast'
source = 'wiki-n4'
level = 'n4'
tags = ['common', 'noun', 'weather']

[[cards]]
kanji = '晴れ'
kana = 'はれ'
english = 'clear weather; fine weather'
level = 'n5'
tags = ['common']
highest_frequency = 6326
highest_frequency_source = 'Leeds'

[[cards]]
kanji = '吹雪'
kana = 'ふぶき'
english = 'snow storm; blizzard'
level = 'n2'
tags = ['common']
highest_frequency = 2597
highest_frequency_source = 'Anime'

[[cards]]
kanji = '雪'
kana = 'ゆき'
english = 'snow'
level = 'n5'
tags = ['common']
highest_frequency = 368
highest_frequency_source = 'Anime'

