[[cards]]
kanji = '暖かい'
kana = 'あたたかい'
english = 'warm (air temp)'
level = 'n5'
tags = ['common', 'i-adjective', 'temperature', 'weather']
frequency_scores = { anime = 2522, leeds = 3556 }

[[cards]]
kanji = '暑い'
kana = 'あつい'
english = 'hot; warm'
level = 'n5'
tags = ['common', 'i-adjectives', 'weather']
frequency_scores = { anime = 1505, leeds = 1999, novels = 2598 }

[[cards]]
kanji = '雨'
kana = 'あめ'
english = 'rain'
level = 'n5'
tags = ['common', 'weather']
frequency_scores = { anime = 804, leeds = 1120, novels = 844, wikipedia = 2317 }

[[cards]]
kanji = '嵐'
kana = 'あらし'
english = 'storm'
level = 'n3'
tags = ['common']
frequency_scores = { anime = 3677, leeds = 5449, novels = 2866, wikipedia = 4393 }

[[cards]]
kanji = '大雨'
kana = 'おおあめ'
english = 'heavy rain'
source = 'wanikani'
tags = ['common', 'nature', 'noun', 'rain', 'weather']
frequency_scores = { anime = 20915, leeds = 9634 }

[[cards]]
kanji = '傘'
kana = 'かさ'
english = 'umbrella'
level = 'n5'
tags = ['accessories', 'clothing', 'common', 'weather']
frequency_scores = { anime = 2872, leeds = 5746, wikipedia = 7373 }

[[cards]]
kanji = '風'
kana = 'かぜ'
english = 'wind; breeze'
level = 'n5'
tags = ['common']
frequency_scores = { anime = 361, leeds = 683, novels = 252, wikipedia = 732 }

[[cards]]
kanji = '雷'
kana = 'かみなり'
english = 'lightning; thunder'
level = 'n3'
tags = ['common']
frequency_scores = { anime = 2604, leeds = 7882, wikipedia = 3105 }

[[cards]]
kanji = '気温'
kana = 'きおん'
english = 'atmospheric temperature'
level = 'n3'
tags = ['common']
frequency_scores = { anime = 12716, leeds = 3614, wikipedia = 3166 }

[[cards]]
kanji = '霧'
kana = 'きり'
english = 'fog; mist'
level = 'n3'
tags = ['common']
frequency_scores = { anime = 751, leeds = 6415, novels = 1812, wikipedia = 6245 }

[[cards]]
kanji = '空気'
kana = 'くうき'
english = 'air; atmosphere; mood'
level = 'n4'
tags = ['common']
frequency_scores = { anime = 1092, leeds = 1815, novels = 764, wikipedia = 2147 }

[[cards]]
kanji = '雲'
kana = 'くも'
english = 'cloud'
level = 'n4'
tags = ['common']
frequency_scores = { anime = 2684, leeds = 3488, novels = 1156, wikipedia = 2150 }

[[cards]]
kanji = '曇り'
kana = 'くもり'
english = 'cloudiness; cloudy weather'
level = 'n5'
tags = ['common']

[[cards]]
kanji = '暗い'
kana = 'くらい'
english = 'dark; gloomy; depressed'
level = 'n5'
tags = ['common', 'i-adjective']
frequency_scores = { anime = 1213, leeds = 2646, novels = 614, wikipedia = 5997 }

[[cards]]
kanji = '氷'
kana = 'こおり'
english = 'ice'
level = 'n3'
tags = ['common']
frequency_scores = { anime = 3476, leeds = 4874, novels = 2387, wikipedia = 3930 }

[[cards]]
kanji = '寒い'
kana = 'さむい'
english = 'cold (weather)'
level = 'n5'
tags = ['common', 'i-adjective']
frequency_scores = { anime = 1137, leeds = 1752, novels = 1498, wikipedia = 8404 }

[[cards]]
kanji = '涼しい'
kana = 'すずしい'
english = 'cool (temperature); refreshing'
level = 'n5'
tags = ['common']
frequency_scores = { anime = 5291, leeds = 6348 }

[[cards]]
kanji = '空'
kana = 'そら'
english = 'sky'
level = 'n5'
tags = ['common']
frequency_scores = { anime = 265, leeds = 1447, novels = 335, wikipedia = 1024 }

[[cards]]
kanji = '大気'
kana = 'たいき'
english = 'atmosphere'
source = 'wanikani'
level = 'n3'
tags = ['common', 'noun']
frequency_scores = { anime = 10360, leeds = 5801, wikipedia = 3581 }

[[cards]]
kanji = '台風'
kana = 'たいふう'
english = 'typhoon; hurricane'
level = 'n4'
tags = ['common']
frequency_scores = { anime = 9634, leeds = 3624, wikipedia = 4250 }

[[cards]]
kanji = '露'
kana = 'つゆ'
english = 'dew'
level = 'n1'
tags = ['common']
frequency_scores = { anime = 12130, leeds = 5074, novels = 2880, wikipedia = 3095 }

[[cards]]
kanji = '天気'
kana = 'てんき'
english = 'weather'
level = 'n5'
tags = ['common']
frequency_scores = { anime = 1920, leeds = 2253, wikipedia = 5135 }

[[cards]]
kanji = '天気予報'
kana = 'てんきよほう'
english = 'weather forecast'
source = 'wiki-n4'
level = 'n4'
tags = ['common', 'noun', 'weather']

[[cards]]
kanji = '晴れ'
kana = 'はれ'
english = 'clear weather; fine weather'
level = 'n5'
tags = ['common']
frequency_scores = { anime = 7339, leeds = 6326 }

[[cards]]
kanji = '吹雪'
kana = 'ふぶき'
english = 'snow storm; blizzard'
level = 'n2'
tags = ['common']
frequency_scores = { anime = 2597 }

[[cards]]
kanji = '雪'
kana = 'ゆき'
english = 'snow'
level = 'n5'
tags = ['common']
frequency_scores = { anime = 368, leeds = 1645, novels = 932, wikipedia = 1924 }

