[[cards]]
kanji = '経済'
kana = 'けいざい'
english = 'economics; business; finance'
source = 'wanikani'
level = 'n4'
tags = ['common', 'noun', 'suru-verb']
highest_frequency = 279
highest_frequency_source = 'Leeds 15k'

[[cards]]
kanji = '産業'
kana = 'さんぎょう'
english = 'industry'
source = 'n4-wikipedia'
level = 'n4'
tags = ['no-adjective', 'noun']
highest_frequency = 677
highest_frequency_source = 'Wikipedia 10k'

[[cards]]
kanji = '仕事'
kana = 'しごと'
english = 'work; job'
level = 'n5'
tags = []
highest_frequency = 210
highest_frequency_source = 'Anime 45k'

[[cards]]
kanji = '名刺'
kana = 'めいし'
english = 'business card'
level = 'n2'
tags = ['common']
highest_frequency = 6369
highest_frequency_source = 'Leeds 15k'

