[[cards]]
kanji = '経済'
kana = 'けいざい'
english = 'economics; business; finance'
source = 'wanikani'
level = 'n4'
tags = ['common', 'noun', 'suru-verb']
frequency_scores = { anime = 6677, leeds = 279, wikipedia = 288 }

[[cards]]
kanji = '産業'
kana = 'さんぎょう'
english = 'industry'
source = 'n4-wikipedia'
level = 'n4'
tags = ['no-adjective', 'noun']
frequency_scores = { anime = 15700, leeds = 801, wikipedia = 677 }

[[cards]]
kanji = '仕事'
kana = 'しごと'
english = 'work; job'
level = 'n5'
tags = []
frequency_scores = { anime = 210, leeds = 220, novels = 349, wikipedia = 1046 }

[[cards]]
kanji = '名刺'
kana = 'めいし'
english = 'business card'
level = 'n2'
tags = ['common']
frequency_scores = { anime = 11073, leeds = 6369 }

