[[cards]]
kanji = 'あっち'
kana = 'あっち'
english = 'over there; that way'
make_kanji_card = false
level = 'n5'
tags = ['common', 'directions', 'locations', 'places']

[[cards]]
kanji = '彼の'
kana = 'あの'
english = 'that (way over there)'
make_kanji_card = false
level = 'n5'
tags = ['common', 'places', 'locations']

[[cards]]
kanji = '彼'
kana = 'あれ'
english = 'that (way over there)'
make_kanji_card = false
level = 'n5'
tags = ['common', 'locations', 'places', 'kosoado']

